// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/gen.h"

// 11:7f64
void func_11_7f64(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL_ASM(0x7f64, 0x20ef, 0x7f67); /* unported */  // call $20ef
  I(0x7f67, 2); H = 0xcf;  // ld h,$cf
  I(0x7f69, 3); mem_wr(gb, HL, 0x00);  // ld (hl),$00
  I(0x7f6b, 2); A = 0x98;  // ld a,$98
  CALL_ASM(0x7f6d, 0x0510, 0x7f70); /* unported */  // call $0510
  I(0x7f70, 4); HANDOFF(0x1eaf); /* getRelativeAngle@jump1eaf */  // jp $1eaf
}

