// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/gen.h"

// 09:6b9c
void interactionCode59(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x6b9c, checkInteractionState_hook, 0x23fe, 0x6b9f);  // call $23fe
  if (!(F & FZ)) { I(0x6b9f, 3); goto L_6be7; } I(0x6b9f, 2);  // jr nz,$6be7
L_6ba1:
  I(0x6ba1, 2); E = 0x43;  // ld e,$43
  I(0x6ba3, 2); A = mem_rd(gb, DE);  // ld a,(de)
  RST_PUSH(0x6ba4, 0x6ba5);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x6bab: goto L_6bab; case 0x6bbd: goto L_6bbd; case 0x6bd4: goto L_6bd4; default: HANDOFF(HL); }
L_6bab:
  CALL(0x6bab, getThisRoomFlags_hook, 0x197d, 0x6bae);  // call $197d
  I(0x6bae, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if (!(F & FZ)) { I(0x6bb0, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bb0, 3);  // jp nz,$3b05
  I(0x6bb3, 3); SET_HL(0xc72e);  // ld hl,$c72e
  I(0x6bb6, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if (!(F & FZ)) { I(0x6bb8, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bb8, 3);  // jp nz,$3b05
  I(0x6bbb, 3); goto L_6be4;  // jr $6be4
L_6bbd:
  CALL(0x6bbd, getThisRoomFlags_hook, 0x197d, 0x6bc0);  // call $197d
  I(0x6bc0, 3); alu_bit(gb, 5, mem_rd(gb, HL));  // bit 5,(hl)
  if (!(F & FZ)) { I(0x6bc2, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bc2, 3);  // jp nz,$3b05
  I(0x6bc5, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if ((F & FZ)) { I(0x6bc7, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bc7, 3);  // jp z,$3b05
  I(0x6bca, 3); SET_HL(0xc72e);  // ld hl,$c72e
  I(0x6bcd, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if ((F & FZ)) { I(0x6bcf, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bcf, 3);  // jp z,$3b05
  I(0x6bd2, 3); goto L_6be4;  // jr $6be4
L_6bd4:
  I(0x6bd4, 3); SET_HL(0xc77c);  // ld hl,$c77c
  I(0x6bd7, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if ((F & FZ)) { I(0x6bd9, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bd9, 3);  // jp z,$3b05
  CALL(0x6bdc, getThisRoomFlags_hook, 0x197d, 0x6bdf);  // call $197d
  I(0x6bdf, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if (!(F & FZ)) { I(0x6be1, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6be1, 3);  // jp nz,$3b05
L_6be4:
  CALL(0x6be4, interactionCode59__loadScriptAndInitGraphics, 0x6c08, 0x6be7);  // call $6c08
L_6be7:
  CALL(0x6be7, interactionRunScript_hook, 0x2552, 0x6bea);  // call $2552
  if ((F & FC)) { I(0x6bea, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bea, 3);  // jp c,$3b05
  I(0x6bed, 2); E = 0x7e;  // ld e,$7e
  I(0x6bef, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf0, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6bf1); return; } I(0x6bf1, 2);  // ret nz
  I(0x6bf2, 2); E = 0x7f;  // ld e,$7f
  I(0x6bf4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf5, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x6bf6, 4); if (hook_enabled_at(0x26a9)) { npcFaceLinkAndAnimate_hook(gb); return; } HANDOFF(0x26a9); } I(0x6bf6, 3);  // jp z,$26a9
  CALL(0x6bf9, interactionAnimate_hook, 0x261b, 0x6bfc);  // call $261b
  I(0x6bfc, 4); if (hook_enabled_at(0x22e0)) { objectSetPriorityRelativeToLink_withTerrainEffects_hook(gb); return; } HANDOFF(0x22e0);  // jp $22e0
}

// 09:6ba1
void interactionCode59__state0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6ba1:
  I(0x6ba1, 2); E = 0x43;  // ld e,$43
  I(0x6ba3, 2); A = mem_rd(gb, DE);  // ld a,(de)
  RST_PUSH(0x6ba4, 0x6ba5);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x6bab: goto L_6bab; case 0x6bbd: goto L_6bbd; case 0x6bd4: goto L_6bd4; default: HANDOFF(HL); }
L_6bab:
  CALL(0x6bab, getThisRoomFlags_hook, 0x197d, 0x6bae);  // call $197d
  I(0x6bae, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if (!(F & FZ)) { I(0x6bb0, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bb0, 3);  // jp nz,$3b05
  I(0x6bb3, 3); SET_HL(0xc72e);  // ld hl,$c72e
  I(0x6bb6, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if (!(F & FZ)) { I(0x6bb8, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bb8, 3);  // jp nz,$3b05
  I(0x6bbb, 3); goto L_6be4;  // jr $6be4
L_6bbd:
  CALL(0x6bbd, getThisRoomFlags_hook, 0x197d, 0x6bc0);  // call $197d
  I(0x6bc0, 3); alu_bit(gb, 5, mem_rd(gb, HL));  // bit 5,(hl)
  if (!(F & FZ)) { I(0x6bc2, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bc2, 3);  // jp nz,$3b05
  I(0x6bc5, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if ((F & FZ)) { I(0x6bc7, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bc7, 3);  // jp z,$3b05
  I(0x6bca, 3); SET_HL(0xc72e);  // ld hl,$c72e
  I(0x6bcd, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if ((F & FZ)) { I(0x6bcf, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bcf, 3);  // jp z,$3b05
  I(0x6bd2, 3); goto L_6be4;  // jr $6be4
L_6bd4:
  I(0x6bd4, 3); SET_HL(0xc77c);  // ld hl,$c77c
  I(0x6bd7, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if ((F & FZ)) { I(0x6bd9, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bd9, 3);  // jp z,$3b05
  CALL(0x6bdc, getThisRoomFlags_hook, 0x197d, 0x6bdf);  // call $197d
  I(0x6bdf, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if (!(F & FZ)) { I(0x6be1, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6be1, 3);  // jp nz,$3b05
L_6be4:
  CALL(0x6be4, interactionCode59__loadScriptAndInitGraphics, 0x6c08, 0x6be7);  // call $6c08
L_6be7:
  CALL(0x6be7, interactionRunScript_hook, 0x2552, 0x6bea);  // call $2552
  if ((F & FC)) { I(0x6bea, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bea, 3);  // jp c,$3b05
  I(0x6bed, 2); E = 0x7e;  // ld e,$7e
  I(0x6bef, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf0, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6bf1); return; } I(0x6bf1, 2);  // ret nz
  I(0x6bf2, 2); E = 0x7f;  // ld e,$7f
  I(0x6bf4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf5, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x6bf6, 4); if (hook_enabled_at(0x26a9)) { npcFaceLinkAndAnimate_hook(gb); return; } HANDOFF(0x26a9); } I(0x6bf6, 3);  // jp z,$26a9
  CALL(0x6bf9, interactionAnimate_hook, 0x261b, 0x6bfc);  // call $261b
  I(0x6bfc, 4); if (hook_enabled_at(0x22e0)) { objectSetPriorityRelativeToLink_withTerrainEffects_hook(gb); return; } HANDOFF(0x22e0);  // jp $22e0
}

// 09:6bab
void interactionCode59__initSubid00(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6bab:
  CALL(0x6bab, getThisRoomFlags_hook, 0x197d, 0x6bae);  // call $197d
  I(0x6bae, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if (!(F & FZ)) { I(0x6bb0, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bb0, 3);  // jp nz,$3b05
  I(0x6bb3, 3); SET_HL(0xc72e);  // ld hl,$c72e
  I(0x6bb6, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if (!(F & FZ)) { I(0x6bb8, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bb8, 3);  // jp nz,$3b05
  I(0x6bbb, 3); goto L_6be4;  // jr $6be4
L_6be4:
  CALL(0x6be4, interactionCode59__loadScriptAndInitGraphics, 0x6c08, 0x6be7);  // call $6c08
L_6be7:
  CALL(0x6be7, interactionRunScript_hook, 0x2552, 0x6bea);  // call $2552
  if ((F & FC)) { I(0x6bea, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bea, 3);  // jp c,$3b05
  I(0x6bed, 2); E = 0x7e;  // ld e,$7e
  I(0x6bef, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf0, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6bf1); return; } I(0x6bf1, 2);  // ret nz
  I(0x6bf2, 2); E = 0x7f;  // ld e,$7f
  I(0x6bf4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf5, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x6bf6, 4); if (hook_enabled_at(0x26a9)) { npcFaceLinkAndAnimate_hook(gb); return; } HANDOFF(0x26a9); } I(0x6bf6, 3);  // jp z,$26a9
  CALL(0x6bf9, interactionAnimate_hook, 0x261b, 0x6bfc);  // call $261b
  I(0x6bfc, 4); if (hook_enabled_at(0x22e0)) { objectSetPriorityRelativeToLink_withTerrainEffects_hook(gb); return; } HANDOFF(0x22e0);  // jp $22e0
}

// 09:6bbd
void interactionCode59__initSubid02(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6bbd:
  CALL(0x6bbd, getThisRoomFlags_hook, 0x197d, 0x6bc0);  // call $197d
  I(0x6bc0, 3); alu_bit(gb, 5, mem_rd(gb, HL));  // bit 5,(hl)
  if (!(F & FZ)) { I(0x6bc2, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bc2, 3);  // jp nz,$3b05
  I(0x6bc5, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if ((F & FZ)) { I(0x6bc7, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bc7, 3);  // jp z,$3b05
  I(0x6bca, 3); SET_HL(0xc72e);  // ld hl,$c72e
  I(0x6bcd, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if ((F & FZ)) { I(0x6bcf, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bcf, 3);  // jp z,$3b05
  I(0x6bd2, 3); goto L_6be4;  // jr $6be4
L_6be4:
  CALL(0x6be4, interactionCode59__loadScriptAndInitGraphics, 0x6c08, 0x6be7);  // call $6c08
L_6be7:
  CALL(0x6be7, interactionRunScript_hook, 0x2552, 0x6bea);  // call $2552
  if ((F & FC)) { I(0x6bea, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bea, 3);  // jp c,$3b05
  I(0x6bed, 2); E = 0x7e;  // ld e,$7e
  I(0x6bef, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf0, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6bf1); return; } I(0x6bf1, 2);  // ret nz
  I(0x6bf2, 2); E = 0x7f;  // ld e,$7f
  I(0x6bf4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf5, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x6bf6, 4); if (hook_enabled_at(0x26a9)) { npcFaceLinkAndAnimate_hook(gb); return; } HANDOFF(0x26a9); } I(0x6bf6, 3);  // jp z,$26a9
  CALL(0x6bf9, interactionAnimate_hook, 0x261b, 0x6bfc);  // call $261b
  I(0x6bfc, 4); if (hook_enabled_at(0x22e0)) { objectSetPriorityRelativeToLink_withTerrainEffects_hook(gb); return; } HANDOFF(0x22e0);  // jp $22e0
}

// 09:6bd4
void interactionCode59__initSubid01(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6bd4:
  I(0x6bd4, 3); SET_HL(0xc77c);  // ld hl,$c77c
  I(0x6bd7, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if ((F & FZ)) { I(0x6bd9, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bd9, 3);  // jp z,$3b05
  CALL(0x6bdc, getThisRoomFlags_hook, 0x197d, 0x6bdf);  // call $197d
  I(0x6bdf, 3); alu_bit(gb, 6, mem_rd(gb, HL));  // bit 6,(hl)
  if (!(F & FZ)) { I(0x6be1, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6be1, 3);  // jp nz,$3b05
L_6be4:
  CALL(0x6be4, interactionCode59__loadScriptAndInitGraphics, 0x6c08, 0x6be7);  // call $6c08
L_6be7:
  CALL(0x6be7, interactionRunScript_hook, 0x2552, 0x6bea);  // call $2552
  if ((F & FC)) { I(0x6bea, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bea, 3);  // jp c,$3b05
  I(0x6bed, 2); E = 0x7e;  // ld e,$7e
  I(0x6bef, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf0, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6bf1); return; } I(0x6bf1, 2);  // ret nz
  I(0x6bf2, 2); E = 0x7f;  // ld e,$7f
  I(0x6bf4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf5, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x6bf6, 4); if (hook_enabled_at(0x26a9)) { npcFaceLinkAndAnimate_hook(gb); return; } HANDOFF(0x26a9); } I(0x6bf6, 3);  // jp z,$26a9
  CALL(0x6bf9, interactionAnimate_hook, 0x261b, 0x6bfc);  // call $261b
  I(0x6bfc, 4); if (hook_enabled_at(0x22e0)) { objectSetPriorityRelativeToLink_withTerrainEffects_hook(gb); return; } HANDOFF(0x22e0);  // jp $22e0
}

// 09:6be4
void interactionCode59__init(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6be4:
  CALL(0x6be4, interactionCode59__loadScriptAndInitGraphics, 0x6c08, 0x6be7);  // call $6c08
L_6be7:
  CALL(0x6be7, interactionRunScript_hook, 0x2552, 0x6bea);  // call $2552
  if ((F & FC)) { I(0x6bea, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bea, 3);  // jp c,$3b05
  I(0x6bed, 2); E = 0x7e;  // ld e,$7e
  I(0x6bef, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf0, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6bf1); return; } I(0x6bf1, 2);  // ret nz
  I(0x6bf2, 2); E = 0x7f;  // ld e,$7f
  I(0x6bf4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf5, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x6bf6, 4); if (hook_enabled_at(0x26a9)) { npcFaceLinkAndAnimate_hook(gb); return; } HANDOFF(0x26a9); } I(0x6bf6, 3);  // jp z,$26a9
  CALL(0x6bf9, interactionAnimate_hook, 0x261b, 0x6bfc);  // call $261b
  I(0x6bfc, 4); if (hook_enabled_at(0x22e0)) { objectSetPriorityRelativeToLink_withTerrainEffects_hook(gb); return; } HANDOFF(0x22e0);  // jp $22e0
}

// 09:6be7
void interactionCode59__state1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6be7:
  CALL(0x6be7, interactionRunScript_hook, 0x2552, 0x6bea);  // call $2552
  if ((F & FC)) { I(0x6bea, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x6bea, 3);  // jp c,$3b05
  I(0x6bed, 2); E = 0x7e;  // ld e,$7e
  I(0x6bef, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf0, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6bf1); return; } I(0x6bf1, 2);  // ret nz
  I(0x6bf2, 2); E = 0x7f;  // ld e,$7f
  I(0x6bf4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6bf5, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x6bf6, 4); if (hook_enabled_at(0x26a9)) { npcFaceLinkAndAnimate_hook(gb); return; } HANDOFF(0x26a9); } I(0x6bf6, 3);  // jp z,$26a9
  CALL(0x6bf9, interactionAnimate_hook, 0x261b, 0x6bfc);  // call $261b
  I(0x6bfc, 4); if (hook_enabled_at(0x22e0)) { objectSetPriorityRelativeToLink_withTerrainEffects_hook(gb); return; } HANDOFF(0x22e0);  // jp $22e0
}

// 09:6bff
void interactionCode59__unusedFunc_6bff(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6bff:
  CALL(0x6bff, interactionInitGraphics_hook, 0x15fb, 0x6c02);  // call $15fb
  CALL(0x6c02, objectMarkSolidPosition_hook, 0x24f0, 0x6c05);  // call $24f0
  I(0x6c05, 4); if (hook_enabled_at(0x23e0)) { interactionIncState_hook(gb); return; } HANDOFF(0x23e0);  // jp $23e0
}

// 09:6c08
void interactionCode59__loadScriptAndInitGraphics(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6c08:
  CALL(0x6c08, interactionInitGraphics_hook, 0x15fb, 0x6c0b);  // call $15fb
  CALL(0x6c0b, objectMarkSolidPosition_hook, 0x24f0, 0x6c0e);  // call $24f0
  I(0x6c0e, 2); E = 0x42;  // ld e,$42
  I(0x6c10, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6c11, 3); SET_HL(0x6c1e);  // ld hl,$6c1e
  RST_PUSH(0x6c14, 0x6c15);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x6c15, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6c16, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x6c17, 1); L = A;  // ld l,a
  CALL(0x6c18, interactionSetScript_hook, 0x2544, 0x6c1b);  // call $2544
  I(0x6c1b, 4); if (hook_enabled_at(0x23e0)) { interactionIncState_hook(gb); return; } HANDOFF(0x23e0);  // jp $23e0
}

// 09:6c1e
void interactionCode59__scriptTable(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6c1e:
  I(0x6c1e, 2); gb->sp = gb->sp - 1;  // dec sp
  I(0x6c1f, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  if (hook_enabled_at(0x6c20)) { interactionCode5a_hook(gb); return; } HANDOFF(0x6c20);  // fallthrough
}

// 09:7807
void goronSubid03(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x7807, checkInteractionState_hook, 0x23fe, 0x780a);  // call $23fe
  if (!(F & FZ)) { I(0x780a, 3); goto L_7812; } I(0x780a, 2);  // jr nz,$7812
L_780c:
  CALL(0x780c, goron_loadScriptAndInitGraphics_hook, 0x7d78, 0x780f);  // call $7d78
  if (hook_enabled_at(0x780f)) { goronSubid04__afterCall780f_hook(gb); return; } HANDOFF(0x780f);  // fallthrough
L_7812:
  CALL(0x7812, interactionRunScript_hook, 0x2552, 0x7815);  // call $2552
  if ((F & FC)) { I(0x7815, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x7815, 3);  // jp c,$3b05
  I(0x7818, 4); if (hook_enabled_at(0x26db)) { interactionAnimateAsNpc_hook(gb); return; } HANDOFF(0x26db);  // jp $26db
}

// 09:780c
void goronSubid04__state0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_780c:
  CALL(0x780c, goron_loadScriptAndInitGraphics_hook, 0x7d78, 0x780f);  // call $7d78
  if (hook_enabled_at(0x780f)) { goronSubid04__afterCall780f_hook(gb); return; } HANDOFF(0x780f);  // fallthrough
}

// 09:7812
void goronSubid04__state1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_7812:
  CALL(0x7812, interactionRunScript_hook, 0x2552, 0x7815);  // call $2552
  if ((F & FC)) { I(0x7815, 4); if (hook_enabled_at(0x3b05)) { interactionDelete_hook(gb); return; } HANDOFF(0x3b05); } I(0x7815, 3);  // jp c,$3b05
  I(0x7818, 4); if (hook_enabled_at(0x26db)) { interactionAnimateAsNpc_hook(gb); return; } HANDOFF(0x26db);  // jp $26db
}

