// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/gen.h"

// 06:4000
void interactWithTileBeforeLink_b06(GB *gb) {
  I(0x4000, 4); A = mem_rd(gb, 0xcc5a);  // ld a,($cc5a)
  I(0x4003, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x4004); return; } I(0x4004, 2);  // ret nz
  CALL(0x4005, specialObjectGetTileInFront, 0x4373, 0x4008);  // call $4373
  I(0x4008, 1); E = A;  // ld e,a
  I(0x4009, 3); mem_wr(gb, 0xff8b, A);  // ldh ($ff8b),a
  I(0x400b, 1); A = C;  // ld a,c
  I(0x400c, 3); mem_wr(gb, 0xff8d, A);  // ldh ($ff8d),a
  I(0x400e, 3); SET_HL(0x43b2);  // ld hl,$43b2
  CALL(0x4011, lookupCollisionTable_paramE, 0x1e20, 0x4014);  // call $1e20
  if (!(F & FC)) { I(0x4014, 4); resetPushingAgainstTileCounter(gb); return; } I(0x4014, 3);  // jp nc,$420c
  I(0x4017, 1); B = A;  // ld b,a
  I(0x4018, 2); alu_and(gb, 0x0f);  // and $0f
  RST_PUSH(0x401a, 0x401b);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 06:46bb
void linkApplyDamage_b06(GB *gb) {
  I(0x46bb, 1); H = D;  // ld h,d
  I(0x46bc, 2); L = 0x25;  // ld l,$25
  I(0x46be, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x46bf, 3); mem_wr(gb, HL, 0x00);  // ld (hl),$00
  I(0x46c1, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x46c2, 3); goto L_46d3; } I(0x46c2, 2);  // jr z,$46d3
  I(0x46c4, 1); B = A;  // ld b,a
  I(0x46c5, 2); A = 0x3f;  // ld a,$3f
  CALL(0x46c7, cpActiveRing, 0x23b0, 0x46ca);  // call $23b0
  if (!(F & FZ)) { I(0x46ca, 3); goto L_46ce; } I(0x46ca, 2);  // jr nz,$46ce
  I(0x46cc, 2); B = 0xf8;  // ld b,$f8
L_46ce:
  I(0x46ce, 2); L = 0x29;  // ld l,$29
  I(0x46d0, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x46d1, 1); alu_add(gb, B);  // add b
  I(0x46d2, 2); mem_wr(gb, HL, A);  // ld (hl),a
L_46d3:
  I(0x46d3, 2); L = 0x2a;  // ld l,$2a
  I(0x46d5, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x46d6, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x46d7, 3); goto L_46e4; } I(0x46d7, 2);  // jr z,$46e4
  I(0x46d9, 2); A = 0x10;  // ld a,$10
  CALL(0x46db, cpActiveRing, 0x23b0, 0x46de);  // call $23b0
  if (!(F & FZ)) { I(0x46de, 3); goto L_46e4; } I(0x46de, 2);  // jr nz,$46e4
  I(0x46e0, 2); L = 0x2d;  // ld l,$2d
  I(0x46e2, 4); mem_wr(gb, HL, alu_srl(gb, mem_rd(gb, HL)));  // srl (hl)
L_46e4:
  I(0x46e4, 3); SET_HL(0xc6aa);  // ld hl,$c6aa
  I(0x46e7, 2); E = 0x29;  // ld e,$29
  I(0x46e9, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x46ea, 2); alu_bit(gb, 7, A);  // bit 7,a
  if ((F & FZ)) { I(0x46ec, 3); goto L_46f5; } I(0x46ec, 2);  // jr z,$46f5
  I(0x46ee, 2); A = mem_rd(gb, DE);  // ld a,(de)
L_46ef:
  I(0x46ef, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x46f0, 2); alu_add(gb, 0x02);  // add $02
  if (!(F & FC)) { I(0x46f2, 3); goto L_46ef; } I(0x46f2, 2);  // jr nc,$46ef
  I(0x46f4, 2); mem_wr(gb, DE, A);  // ld (de),a
L_46f5:
  I(0x46f5, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x46f6, 1); A = alu_dec8(gb, A);  // dec a
  I(0x46f7, 1); alu_rlca(gb);  // rlca
  if (!(F & FC)) { I(0x46f8, 3); goto L_4725; } I(0x46f8, 2);  // jr nc,$4725
  I(0x46fa, 2); A = 0x2f;  // ld a,$2f
  CALL(0x46fc, checkTreasureObtained, 0x1748, 0x46ff);  // call $1748
  if (!(F & FC)) { I(0x46ff, 3); goto L_4710; } I(0x46ff, 2);  // jr nc,$4710
  I(0x4701, 3); SET_HL(0xc6ab);  // ld hl,$c6ab
  I(0x4704, 2); A = mem_rd(gb, HL); SET_HL(HL - 1);  // ld a,(hl-)
  I(0x4705, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x4706, 2); A = 0x01;  // ld a,$01
  I(0x4708, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4709, 2); A = 0x2f;  // ld a,$2f
  CALL(0x470b, loseTreasure, 0x1733, 0x470e);  // call $1733
  I(0x470e, 3); goto L_4725;  // jr $4725
L_4710:
  I(0x4710, 1); alu_xor(gb, A);  // xor a
  I(0x4711, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4712, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x4713, 4); mem_wr(gb, 0xcc6f, A);  // ld ($cc6f),a
  I(0x4716, 2); E = 0x04;  // ld e,$04
  I(0x4718, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4719, 2); alu_cp(gb, 0x0d);  // cp $0d
  if ((F & FZ)) { I(0x471b, 3); goto L_4725; } I(0x471b, 2);  // jr z,$4725
  I(0x471d, 2); A = 0xff;  // ld a,$ff
  I(0x471f, 4); mem_wr(gb, 0xcdd5, A);  // ld ($cdd5),a
  CALL(0x4722, clearAllParentItems, 0x2c10, 0x4725);  // call $2c10
L_4725:
  I(0x4725, 4); A = mem_rd(gb, 0xcc00);  // ld a,($cc00)
  I(0x4728, 1); alu_rrca(gb);  // rrca
  if (!(F & FC)) { I(0x4729, 3); goto L_4733; } I(0x4729, 2);  // jr nc,$4733
  I(0x472b, 2); E = 0x2e;  // ld e,$2e
  I(0x472d, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x472e, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x472f, 3); goto L_4733; } I(0x472f, 2);  // jr z,$4733
  I(0x4731, 1); A = alu_dec8(gb, A);  // dec a
  I(0x4732, 2); mem_wr(gb, DE, A);  // ld (de),a
L_4733:
  RET(0x4733); return;  // ret
}

// 06:48b3
void checkUseItems_b06(GB *gb) {
  I(0x48b3, 1); alu_xor(gb, A);  // xor a
  I(0x48b4, 4); mem_wr(gb, 0xcc6f, A);  // ld ($cc6f),a
  I(0x48b7, 3); SET_HL(0xcc59);  // ld hl,$cc59
  I(0x48ba, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x48bb, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x48bc, 3); goto L_48bf; } I(0x48bc, 2);  // jr z,$48bf
  I(0x48be, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
L_48bf:
  I(0x48bf, 3); SET_HL(0xcc5f);  // ld hl,$cc5f
  I(0x48c2, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x48c3, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x48c5, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x48c6, 4); A = mem_rd(gb, 0xcc63);  // ld a,($cc63)
  I(0x48c9, 1); alu_rlca(gb);  // rlca
  if ((F & FC)) { I(0x48ca, 3); goto L_493b; } I(0x48ca, 2);  // jr c,$493b
  I(0x48cc, 4); A = mem_rd(gb, 0xccd3);  // ld a,($ccd3)
  I(0x48cf, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x48d0, 4); checkShopInput(gb); return; } I(0x48d0, 3);  // jp nz,$49da
  I(0x48d3, 4); A = mem_rd(gb, 0xcc95);  // ld a,($cc95)
  I(0x48d6, 1); B = A;  // ld b,a
  I(0x48d7, 4); A = mem_rd(gb, 0xcc5c);  // ld a,($cc5c)
  I(0x48da, 1); alu_or(gb, B);  // or b
  I(0x48db, 1); alu_rlca(gb);  // rlca
  if ((F & FC)) { I(0x48dc, 3); goto L_4922; } I(0x48dc, 2);  // jr c,$4922
  I(0x48de, 4); A = mem_rd(gb, 0xccd8);  // ld a,($ccd8)
  I(0x48e1, 1); B = A;  // ld b,a
  I(0x48e2, 4); A = mem_rd(gb, 0xcc5a);  // ld a,($cc5a)
  I(0x48e5, 1); alu_or(gb, B);  // or b
  if (!(F & FZ)) { I(0x48e6, 3); goto L_4922; } I(0x48e6, 2);  // jr nz,$4922
  I(0x48e8, 4); A = mem_rd(gb, 0xcc68);  // ld a,($cc68)
  I(0x48eb, 1); A = alu_inc8(gb, A);  // inc a
  if ((F & FZ)) { I(0x48ec, 3); goto L_4922; } I(0x48ec, 2);  // jr z,$4922
  I(0x48ee, 4); A = mem_rd(gb, 0xcc34);  // ld a,($cc34)
  I(0x48f1, 2); alu_bit(gb, 5, A);  // bit 5,a
  if (!(F & FZ)) { I(0x48f3, 3); goto L_4909; } I(0x48f3, 2);  // jr nz,$4909
  I(0x48f5, 2); alu_bit(gb, 6, A);  // bit 6,a
  if ((F & FZ)) { I(0x48f7, 3); goto L_4901; } I(0x48f7, 2);  // jr z,$4901
L_48f9:
  I(0x48f9, 3); SET_DE(0x0189);  // ld de,$0189
  CALL(0x48fc, checkItemUsed, 0x4954, 0x48ff);  // call $4954
  I(0x48ff, 3); goto L_4922;  // jr $4922
L_4901:
  I(0x4901, 4); A = mem_rd(gb, 0xcc5d);  // ld a,($cc5d)
  I(0x4904, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x4905, 3); goto L_4916; } I(0x4905, 2);  // jr z,$4916
  I(0x4907, 3); goto L_4922;  // jr $4922
L_4909:
  I(0x4909, 4); A = mem_rd(gb, 0xcc5d);  // ld a,($cc5d)
  I(0x490c, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x490d, 3); goto L_4916; } I(0x490d, 2);  // jr z,$4916
  I(0x490f, 3); SET_HL(0xd02f);  // ld hl,$d02f
  I(0x4912, 3); alu_bit(gb, 7, mem_rd(gb, HL));  // bit 7,(hl)
  if ((F & FZ)) { I(0x4914, 3); goto L_491c; } I(0x4914, 2);  // jr z,$491c
L_4916:
  I(0x4916, 3); SET_DE(0x0189);  // ld de,$0189
  CALL(0x4919, checkItemUsed, 0x4954, 0x491c);  // call $4954
L_491c:
  I(0x491c, 3); SET_DE(0x0288);  // ld de,$0288
  CALL(0x491f, checkItemUsed, 0x4954, 0x4922);  // call $4954
L_4922:
  I(0x4922, 3); SET_DE(0xd200);  // ld de,$d200
L_4925:
  I(0x4925, 2); E = 0x00;  // ld e,$00
  I(0x4927, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4928, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { CALL(0x4929, parentItemUpdate, 0x49ef, 0x492c); } else I(0x4929, 3);  // call nz,$49ef
  I(0x492c, 1); D = alu_inc8(gb, D);  // inc d
  I(0x492d, 1); A = D;  // ld a,d
  I(0x492e, 2); alu_cp(gb, 0xd6);  // cp $d6
  if ((F & FC)) { I(0x4930, 3); goto L_4925; } I(0x4930, 2);  // jr c,$4925
  I(0x4932, 1); alu_xor(gb, A);  // xor a
  I(0x4933, 3); mem_wr(gb, 0xffae, A);  // ldh ($ffae),a
  I(0x4935, 2); D = 0xd0;  // ld d,$d0
  I(0x4937, 1); A = D;  // ld a,d
  I(0x4938, 3); mem_wr(gb, 0xffaf, A);  // ldh ($ffaf),a
  RET(0x493a); return;  // ret
L_493b:
  I(0x493b, 2); alu_cp(gb, 0xff);  // cp $ff
  if (!(F & FZ)) { I(0x493d, 3); goto L_4922; } I(0x493d, 2);  // jr nz,$4922
  CALL(0x493f, clearAllParentItems_body, 0x4878, 0x4942);  // call $4878
  I(0x4942, 3); SET_HL(0xd200);  // ld hl,$d200
  I(0x4945, 3); SET_DE(0xff05);  // ld de,$ff05
  I(0x4948, 2); C = 0xf1;  // ld c,$f1
  CALL(0x494a, initializeParentItem, 0x4980, 0x494d);  // call $4980
  I(0x494d, 2); A = 0x80;  // ld a,$80
  I(0x494f, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x4952, 3); goto L_4922;  // jr $4922
}

// 06:6cec
void specialObjectCode_companionCutscene_b06(GB *gb) {
  I(0x6cec, 3); SET_HL(0xd101);  // ld hl,$d101
  I(0x6cef, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x6cf0, 2); alu_sub(gb, 0x0f);  // sub $0f
  RST_PUSH(0x6cf2, 0x6cf3);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 06:70a0
void specialObjectCode_linkInCutscene_b06(GB *gb) {
  I(0x70a0, 2); E = 0x02;  // ld e,$02
  I(0x70a2, 2); A = mem_rd(gb, DE);  // ld a,(de)
  RST_PUSH(0x70a3, 0x70a4);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 06:4734
void tryToBreakTile_body(GB *gb) {
  I(0x4734, 1); A = B;  // ld a,b
  I(0x4735, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x4737, 2); alu_or(gb, 0x08);  // or $08
  I(0x4739, 3); mem_wr(gb, 0xff90, A);  // ldh ($ff90),a
  I(0x473b, 1); A = C;  // ld a,c
  I(0x473c, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x473e, 2); alu_or(gb, 0x08);  // or $08
  I(0x4740, 3); mem_wr(gb, 0xff91, A);  // ldh ($ff91),a
  CALL(0x4742, getTileAtPosition, 0x1447, 0x4745);  // call $1447
  I(0x4745, 3); mem_wr(gb, 0xff92, A);  // ldh ($ff92),a
  I(0x4747, 1); E = A;  // ld e,a
  I(0x4748, 1); A = L;  // ld a,l
  I(0x4749, 3); mem_wr(gb, 0xff93, A);  // ldh ($ff93),a
  I(0x474b, 3); SET_HL(0x7818);  // ld hl,$7818
  CALL(0x474e, lookupCollisionTable_paramE, 0x1e20, 0x4751);  // call $1e20
  if (!(F & FC)) { RET_TAKEN(0x4751); return; } I(0x4751, 2);  // ret nc
  I(0x4752, 1); E = A;  // ld e,a
  I(0x4753, 1); alu_add(gb, A);  // add a
  I(0x4754, 3); SET_HL(0x78dd);  // ld hl,$78dd
  RST_PUSH(0x4757, 0x4758);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x4758, 1); A = E;  // ld a,e
  RST_PUSH(0x4759, 0x475a);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x475a, 3); A = mem_rd(gb, 0xff8f);  // ldh a,($ff8f)
  I(0x475c, 1); E = A;  // ld e,a
  I(0x475d, 2); alu_and(gb, 0x1f);  // and $1f
  CALL(0x475f, checkFlag, 0x0205, 0x4762);  // call $0205
  if ((F & FZ)) { RET_TAKEN(0x4762); return; } I(0x4762, 2);  // ret z
  I(0x4763, 2); E = alu_rl(gb, E);  // rl e
  if ((F & FC)) { RET_TAKEN(0x4765); return; } I(0x4765, 2);  // ret c
  I(0x4766, 2); SET_HL(HL + 1);  // inc hl
  I(0x4767, 2); SET_HL(HL + 1);  // inc hl
  I(0x4768, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4769, 2); A = alu_swap(gb, A);  // swap a
  I(0x476b, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x476d, 3); mem_wr(gb, 0xff8d, A);  // ldh ($ff8d),a
  I(0x476f, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4770, 3); mem_wr(gb, 0xff8e, A);  // ldh ($ff8e),a
  PUSH(0x4772, DE);  // push de
  I(0x4773, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4774, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x4775, 3); goto L_47a2; } I(0x4775, 2);  // jr z,$47a2
  I(0x4777, 3); A = mem_rd(gb, 0xff92);  // ldh a,($ff92)
  I(0x4779, 2); alu_cp(gb, 0xdb);  // cp $db
  if ((F & FZ)) { I(0x477b, 3); goto L_478e; } I(0x477b, 2);  // jr z,$478e
  I(0x477d, 4); A = mem_rd(gb, 0xcc33);  // ld a,($cc33)
  I(0x4780, 2); alu_cp(gb, 0x02);  // cp $02
  if ((F & FZ)) { I(0x4782, 3); goto L_4788; } I(0x4782, 2);  // jr z,$4788
  I(0x4784, 2); alu_cp(gb, 0x01);  // cp $01
  if (!(F & FZ)) { I(0x4786, 3); goto L_4797; } I(0x4786, 2);  // jr nz,$4797
L_4788:
  I(0x4788, 3); A = mem_rd(gb, 0xff92);  // ldh a,($ff92)
  I(0x478a, 2); alu_cp(gb, 0x10);  // cp $10
  if (!(F & FZ)) { I(0x478c, 3); goto L_4797; } I(0x478c, 2);  // jr nz,$4797
L_478e:
  I(0x478e, 3); A = mem_rd(gb, 0xff93);  // ldh a,($ff93)
  PUSH(0x4790, HL);  // push hl
  CALL(0x4791, getTileIndexFromRoomLayoutBuffer, 0x15d7, 0x4794);  // call $15d7
  SET_HL(POP(0x4794));  // pop hl
  if (!(F & FC)) { I(0x4795, 3); goto L_479f; } I(0x4795, 2);  // jr nc,$479f
L_4797:
  I(0x4797, 3); A = mem_rd(gb, 0xff93);  // ldh a,($ff93)
  I(0x4799, 1); C = A;  // ld c,a
  I(0x479a, 2); B = mem_rd(gb, HL);  // ld b,(hl)
  CALL(0x479b, setTileInRoomLayoutBuffer, 0x1426, 0x479e);  // call $1426
  I(0x479e, 2); A = mem_rd(gb, HL);  // ld a,(hl)
L_479f:
  CALL(0x479f, setTile, 0x3a9c, 0x47a2);  // call $3a9c
L_47a2:
  I(0x47a2, 3); A = mem_rd(gb, 0xff92);  // ldh a,($ff92)
  I(0x47a4, 2); alu_cp(gb, 0xda);  // cp $da
  if ((F & FZ)) { I(0x47a6, 3); goto L_47ea; } I(0x47a6, 2);  // jr z,$47ea
  I(0x47a8, 2); alu_cp(gb, 0xf2);  // cp $f2
  I(0x47aa, 3); SET_HL(0xc626);  // ld hl,$c626
  if ((F & FZ)) { CALL(0x47ad, incHlRefWithCap, 0x0245, 0x47b0); } else I(0x47ad, 3);  // call z,$0245
  I(0x47b0, 3); A = mem_rd(gb, 0xff8e);  // ldh a,($ff8e)
  I(0x47b2, 1); alu_rlca(gb);  // rlca
  I(0x47b3, 3); A = mem_rd(gb, 0xff92);  // ldh a,($ff92)
  if ((F & FC)) { CALL(0x47b5, updateRoomFlagsForBrokenTile, 0x1151, 0x47b8); } else I(0x47b5, 3);  // call c,$1151
  I(0x47b8, 3); A = mem_rd(gb, 0xff8e);  // ldh a,($ff8e)
  I(0x47ba, 2); alu_bit(gb, 6, A);  // bit 6,a
  I(0x47bc, 2); A = 0x4d;  // ld a,$4d
  if (!(F & FZ)) { CALL(0x47be, playSound_b00, 0x0c98, 0x47c1); } else I(0x47be, 3);  // call nz,$0c98
  I(0x47c1, 3); SET_HL(0xccaa);  // ld hl,$ccaa
  I(0x47c4, 3); A = mem_rd(gb, 0xff93);  // ldh a,($ff93)
  I(0x47c6, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if (!(F & FZ)) { I(0x47c7, 3); goto L_47cd; } I(0x47c7, 2);  // jr nz,$47cd
  I(0x47c9, 3); mem_wr(gb, HL, 0xff);  // ld (hl),$ff
  I(0x47cb, 3); goto L_47d3;  // jr $47d3
L_47cd:
  I(0x47cd, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x47cf, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { CALL(0x47d0, decideItemDropForBrokenTile, 0x483d, 0x47d3); } else I(0x47d0, 3);  // call nz,$483d
L_47d3:
  I(0x47d3, 3); A = mem_rd(gb, 0xff8f);  // ldh a,($ff8f)
  I(0x47d5, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x47d6, 3); goto L_47e7; } I(0x47d6, 2);  // jr z,$47e7
  I(0x47d8, 2); alu_cp(gb, 0x0c);  // cp $0c
  if ((F & FZ)) { I(0x47da, 3); goto L_47e7; } I(0x47da, 2);  // jr z,$47e7
  I(0x47dc, 2); alu_cp(gb, 0x08);  // cp $08
  if ((F & FZ)) { I(0x47de, 3); goto L_47e7; } I(0x47de, 2);  // jr z,$47e7
  I(0x47e0, 2); alu_cp(gb, 0x12);  // cp $12
  I(0x47e2, 3); A = mem_rd(gb, 0xff8e);  // ldh a,($ff8e)
  if (!(F & FZ)) { CALL(0x47e4, makeInteractionForBreakableTile, 0x4816, 0x47e7); } else I(0x47e4, 3);  // call nz,$4816
L_47e7:
  SET_DE(POP(0x47e7));  // pop de
  I(0x47e8, 1); alu_scf(gb);  // scf
  RET(0x47e9); return;  // ret
L_47ea:
  I(0x47ea, 2); C = 0x18;  // ld c,$18
  CALL(0x47ec, findItemWithID, 0x22b9, 0x47ef);  // call $22b9
  if (!(F & FZ)) { I(0x47ef, 3); goto L_47e7; } I(0x47ef, 2);  // jr nz,$47e7
  CALL_ASM(0x47f1, 0x47fe, 0x47f4); /* unported */  // call $47fe
  CALL(0x47f4, findItemWithID_startingAfterH, 0x22c0, 0x47f7);  // call $22c0
  if (!(F & FZ)) { I(0x47f7, 3); goto L_47e7; } I(0x47f7, 2);  // jr nz,$47e7
  CALL_ASM(0x47f9, 0x47fe, 0x47fc); /* unported */  // call $47fe
  I(0x47fc, 3); goto L_47e7;  // jr $47e7
}

// 06:4809
void itemMakeInteractionForBreakableTile(GB *gb) {
  I(0x4809, 1); H = D;  // ld h,d
  I(0x480a, 2); L = 0x0b;  // ld l,$0b
  I(0x480c, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x480d, 3); mem_wr(gb, 0xff90, A);  // ldh ($ff90),a
  I(0x480f, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4810, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4811, 3); mem_wr(gb, 0xff91, A);  // ldh ($ff91),a
  I(0x4813, 2); L = 0x03;  // ld l,$03
  I(0x4815, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  makeInteractionForBreakableTile(gb); return;  // fallthrough
}

// 06:4816
void makeInteractionForBreakableTile(GB *gb) {
  I(0x4816, 2); alu_and(gb, 0x1f);  // and $1f
  I(0x4818, 2); alu_cp(gb, 0x1f);  // cp $1f
  if ((F & FZ)) { RET_TAKEN(0x481a); return; } I(0x481a, 2);  // ret z
  I(0x481b, 1); C = A;  // ld c,a
  CALL(0x481c, getFreeInteractionSlot, 0x3aef, 0x481f);  // call $3aef
  if (!(F & FZ)) { RET_TAKEN(0x481f); return; } I(0x481f, 2);  // ret nz
  I(0x4820, 1); A = C;  // ld a,c
  I(0x4821, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x4823, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x4824, 1); A = C;  // ld a,c
  I(0x4825, 2); alu_and(gb, 0x10);  // and $10
  I(0x4827, 2); A = alu_swap(gb, A);  // swap a
  I(0x4829, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x482a, 4); A = mem_rd(gb, 0xd008);  // ld a,($d008)
  I(0x482d, 2); L = 0x48;  // ld l,$48
  I(0x482f, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x4830, 2); A = alu_swap(gb, A);  // swap a
  I(0x4832, 1); alu_rrca(gb);  // rrca
  I(0x4833, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x4834, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4835, 3); A = mem_rd(gb, 0xff90);  // ldh a,($ff90)
  I(0x4837, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x4838, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4839, 3); A = mem_rd(gb, 0xff91);  // ldh a,($ff91)
  I(0x483b, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  RET(0x483c); return;  // ret
}

// 06:483d
void decideItemDropForBrokenTile(GB *gb) {
  PUSH(0x483d, HL);  // push hl
  CALL(0x483e, decideItemDrop, 0x16eb, 0x4841);  // call $16eb
  if ((F & FZ)) { I(0x4841, 3); goto L_486e; } I(0x4841, 2);  // jr z,$486e
  CALL(0x4843, getFreePartSlot, 0x3e8e, 0x4846);  // call $3e8e
  if (!(F & FZ)) { I(0x4846, 3); goto L_486e; } I(0x4846, 2);  // jr nz,$486e
  I(0x4848, 3); mem_wr(gb, HL, 0x01);  // ld (hl),$01
  I(0x484a, 1); L = alu_inc8(gb, L);  // inc l
  I(0x484b, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x484c, 2); L = 0xcb;  // ld l,$cb
  I(0x484e, 3); A = mem_rd(gb, 0xff90);  // ldh a,($ff90)
  I(0x4850, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x4851, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4852, 3); A = mem_rd(gb, 0xff91);  // ldh a,($ff91)
  I(0x4854, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x4855, 4); A = mem_rd(gb, 0xd008);  // ld a,($d008)
  I(0x4858, 2); A = alu_swap(gb, A);  // swap a
  I(0x485a, 1); alu_rrca(gb);  // rrca
  I(0x485b, 2); L = 0xc9;  // ld l,$c9
  I(0x485d, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x485e, 2); L = 0xc3;  // ld l,$c3
  I(0x4860, 1); A = C;  // ld a,c
  I(0x4861, 2); alu_cp(gb, 0x0f);  // cp $0f
  if (!(F & FZ)) { I(0x4863, 3); goto L_4867; } I(0x4863, 2);  // jr nz,$4867
  I(0x4865, 3); mem_wr(gb, HL, 0x02);  // ld (hl),$02
L_4867:
  I(0x4867, 3); A = mem_rd(gb, 0xff8f);  // ldh a,($ff8f)
  I(0x4869, 2); alu_cp(gb, 0x06);  // cp $06
  if (!(F & FZ)) { I(0x486b, 3); goto L_486e; } I(0x486b, 2);  // jr nz,$486e
  I(0x486d, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
L_486e:
  SET_HL(POP(0x486e));  // pop hl
  RET(0x486f); return;  // ret
}

// 06:402d
void nextToChestTile(GB *gb) {
  CALL(0x402d, checkFacingBottomOfTileAndPressedA, 0x40ef, 0x4030);  // call $40ef
  if ((F & FZ)) { I(0x4030, 3); goto L_403a; } I(0x4030, 2);  // jr z,$403a
  I(0x4032, 3); SET_BC(0x510d);  // ld bc,$510d
  CALL(0x4035, showText, 0x1872, 0x4038);  // call $1872
  I(0x4038, 1); alu_scf(gb);  // scf
  RET(0x4039); return;  // ret
L_403a:
  I(0x403a, 4); A = mem_rd(gb, 0xccd3);  // ld a,($ccd3)
  I(0x403d, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x403e, 3); goto L_404b; } I(0x403e, 2);  // jr z,$404b
  I(0x4040, 4); A = mem_rd(gb, 0xcca1);  // ld a,($cca1)
  I(0x4043, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x4044, 3); goto L_404b; } I(0x4044, 2);  // jr nz,$404b
  I(0x4046, 4); A = mem_rd(gb, 0xcca2);  // ld a,($cca2)
  I(0x4049, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x404a); return; } I(0x404a, 2);  // ret nz
L_404b:
  I(0x404b, 1); A = C;  // ld a,c
  I(0x404c, 4); mem_wr(gb, 0xcca2, A);  // ld ($cca2),a
  I(0x404f, 2); A = 0xf0;  // ld a,$f0
  CALL(0x4051, setTile, 0x3a9c, 0x4054);  // call $3a9c
  I(0x4054, 2); A = 0x6c;  // ld a,$6c
  CALL(0x4056, playSound_b00, 0x0c98, 0x4059);  // call $0c98
  I(0x4059, 4); A = mem_rd(gb, 0xccd3);  // ld a,($ccd3)
  I(0x405c, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x405d); return; } I(0x405d, 2);  // ret nz
  I(0x405e, 4); A = mem_rd(gb, 0xcca1);  // ld a,($cca1)
  I(0x4061, 1); alu_or(gb, A);  // or a
  I(0x4062, 1); alu_scf(gb);  // scf
  if (!(F & FZ)) { RET_TAKEN(0x4063); return; } I(0x4063, 2);  // ret nz
  I(0x4064, 3); SET_HL(0xd040);  // ld hl,$d040
  I(0x4067, 2); B = 0x40;  // ld b,$40
  CALL(0x4069, clearMemory, 0x046f, 0x406c);  // call $046f
  I(0x406c, 4); A = mem_rd(gb, 0xcca3);  // ld a,($cca3)
  I(0x406f, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x4070, 3); goto L_4079; } I(0x4070, 2);  // jr z,$4079
  I(0x4072, 1); B = A;  // ld b,a
  I(0x4073, 4); A = mem_rd(gb, 0xcca4);  // ld a,($cca4)
  I(0x4076, 1); C = A;  // ld c,a
  I(0x4077, 3); goto L_407c;  // jr $407c
L_4079:
  CALL(0x4079, getChestData, 0x10cc, 0x407c);  // call $10cc
L_407c:
  I(0x407c, 1); A = B;  // ld a,b
  I(0x407d, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x407e, 3); goto L_40a6; } I(0x407e, 2);  // jr z,$40a6
  I(0x4080, 2); A = 0x83;  // ld a,$83
  I(0x4082, 4); mem_wr(gb, 0xcc8a, A);  // ld ($cc8a),a
  I(0x4085, 4); mem_wr(gb, 0xcbca, A);  // ld ($cbca),a
  I(0x4088, 3); SET_HL(0xd040);  // ld hl,$d040
  I(0x408b, 2); A = 0x81;  // ld a,$81
  I(0x408d, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x408e, 3); mem_wr(gb, HL, 0x60);  // ld (hl),$60
  I(0x4090, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4091, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x4092, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4093, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x4094, 2); L = 0x4b;  // ld l,$4b
  I(0x4096, 4); A = mem_rd(gb, 0xcca2);  // ld a,($cca2)
  I(0x4099, 1); B = A;  // ld b,a
  I(0x409a, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x409c, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x409d, 1); L = alu_inc8(gb, L);  // inc l
  I(0x409e, 1); A = B;  // ld a,b
  I(0x409f, 2); A = alu_swap(gb, A);  // swap a
  I(0x40a1, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x40a3, 2); alu_or(gb, 0x08);  // or $08
  I(0x40a5, 2); mem_wr(gb, HL, A);  // ld (hl),a
L_40a6:
  CALL(0x40a6, getThisRoomFlags, 0x197d, 0x40a9);  // call $197d
  I(0x40a9, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) | (1 << 5)));  // set 5,(hl)
  I(0x40ab, 1); alu_xor(gb, A);  // xor a
  I(0x40ac, 4); mem_wr(gb, 0xcca3, A);  // ld ($cca3),a
  I(0x40af, 4); mem_wr(gb, 0xcca4, A);  // ld ($cca4),a
  I(0x40b2, 1); alu_scf(gb);  // scf
  RET(0x40b3); return;  // ret
}

// 06:40b4
void nextToSignTile(GB *gb) {
  CALL(0x40b4, checkFacingBottomOfTileAndPressedA, 0x40ef, 0x40b7);  // call $40ef
  I(0x40b7, 3); SET_BC(0x510e);  // ld bc,$510e
  if (!(F & FZ)) { I(0x40ba, 3); goto L_40ea; } I(0x40ba, 2);  // jr nz,$40ea
  I(0x40bc, 4); A = mem_rd(gb, 0xcc2d);  // ld a,($cc2d)
  I(0x40bf, 3); SET_HL(0x7784);  // ld hl,$7784
  RST_PUSH(0x40c2, 0x40c3);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x40c3, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x40c4, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x40c5, 1); L = A;  // ld l,a
  I(0x40c6, 4); A = mem_rd(gb, 0xcc30);  // ld a,($cc30)
  I(0x40c9, 1); B = A;  // ld b,a
  I(0x40ca, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x40cc, 1); C = A;  // ld c,a
L_40cd:
  I(0x40cd, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x40ce, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x40cf, 3); goto L_40e7; } I(0x40cf, 2);  // jr z,$40e7
  I(0x40d1, 1); alu_cp(gb, C);  // cp c
  if ((F & FZ)) { I(0x40d2, 3); goto L_40d8; } I(0x40d2, 2);  // jr z,$40d8
  I(0x40d4, 2); SET_HL(HL + 1);  // inc hl
  I(0x40d5, 2); SET_HL(HL + 1);  // inc hl
  I(0x40d6, 3); goto L_40cd;  // jr $40cd
L_40d8:
  I(0x40d8, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x40d9, 1); alu_cp(gb, B);  // cp b
  if ((F & FZ)) { I(0x40da, 3); goto L_40df; } I(0x40da, 2);  // jr z,$40df
  I(0x40dc, 2); SET_HL(HL + 1);  // inc hl
  I(0x40dd, 3); goto L_40cd;  // jr $40cd
L_40df:
  I(0x40df, 2); C = mem_rd(gb, HL);  // ld c,(hl)
  I(0x40e0, 2); B = 0x2e;  // ld b,$2e
  CALL(0x40e2, showText, 0x1872, 0x40e5);  // call $1872
  I(0x40e5, 1); alu_scf(gb);  // scf
  RET(0x40e6); return;  // ret
L_40e7:
  I(0x40e7, 3); SET_BC(0x0901);  // ld bc,$0901
L_40ea:
  CALL(0x40ea, showText, 0x1872, 0x40ed);  // call $1872
  I(0x40ed, 1); alu_scf(gb);  // scf
  RET(0x40ee); return;  // ret
}

// 06:40ef
void checkFacingBottomOfTileAndPressedA(GB *gb) {
  I(0x40ef, 4); A = mem_rd(gb, 0xcc2a);  // ld a,($cc2a)
  I(0x40f2, 2); alu_and(gb, 0x01);  // and $01
  if ((F & FZ)) { I(0x40f4, 3); goto L_410b; } I(0x40f4, 2);  // jr z,$410b
  checkFacingBottomOfTile(gb); return;  // fallthrough
L_410b:
  SET_AF(POP(0x410b));  // pop af
  I(0x410c, 1); alu_xor(gb, A);  // xor a
  RET(0x410d); return;  // ret
}

// 06:40f6
void checkFacingBottomOfTile(GB *gb) {
  I(0x40f6, 4); A = mem_rd(gb, 0xd008);  // ld a,($d008)
  I(0x40f9, 3); SET_HL(0x4107);  // ld hl,$4107
  RST_PUSH(0x40fc, 0x40fd);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x40fd, 4); A = mem_rd(gb, 0xd033);  // ld a,($d033)
  I(0x4100, 2); alu_and(gb, mem_rd(gb, HL));  // and (hl)
  I(0x4101, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if (!(F & FZ)) { I(0x4102, 3); goto L_410b; } I(0x4102, 2);  // jr nz,$410b
  I(0x4104, 2); alu_cp(gb, 0xc0);  // cp $c0
  RET(0x4106); return;  // ret
L_410b:
  SET_AF(POP(0x410b));  // pop af
  I(0x410c, 1); alu_xor(gb, A);  // xor a
  RET(0x410d); return;  // ret
}

// 06:410e
void nextToPushableBlock(GB *gb) {
  I(0x410e, 4); A = mem_rd(gb, 0xcc34);  // ld a,($cc34)
  I(0x4111, 2); alu_and(gb, 0x40);  // and $40
  if (!(F & FZ)) { RET_TAKEN(0x4113); return; } I(0x4113, 2);  // ret nz
  CALL(0x4114, specialObjectCheckPushingAgainstTile, 0x4329, 0x4117);  // call $4329
  if ((F & FZ)) { I(0x4117, 4); resetPushingAgainstTileCounter(gb); return; } I(0x4117, 3);  // jp z,$420c
  CALL(0x411a, decPushingAgainstTileCounter, 0x4212, 0x411d);  // call $4212
  if (!(F & FZ)) { RET_TAKEN(0x411d); return; } I(0x411d, 2);  // ret nz
  I(0x411e, 2); alu_bit(gb, 6, B);  // bit 6,b
  if ((F & FZ)) { I(0x4120, 3); goto L_412c; } I(0x4120, 2);  // jr z,$412c
  I(0x4122, 2); A = 0x16;  // ld a,$16
  CALL(0x4124, checkTreasureObtained, 0x1748, 0x4127);  // call $1748
  I(0x4127, 2); A = 0x03;  // ld a,$03
  if (!(F & FC)) { I(0x4129, 4); showInfoTextForTile(gb); return; } I(0x4129, 3);  // jp nc,$42fb
L_412c:
  I(0x412c, 2); alu_bit(gb, 7, B);  // bit 7,b
  if (!(F & FZ)) { I(0x412e, 3); goto L_413c; } I(0x412e, 2);  // jr nz,$413c
  I(0x4130, 1); A = B;  // ld a,b
  I(0x4131, 2); A = alu_swap(gb, A);  // swap a
  I(0x4133, 2); alu_and(gb, 0x03);  // and $03
  I(0x4135, 1); L = A;  // ld l,a
  I(0x4136, 4); A = mem_rd(gb, 0xcc65);  // ld a,($cc65)
  I(0x4139, 1); alu_cp(gb, L);  // cp l
  if (!(F & FZ)) { I(0x413a, 3); goto L_417a; } I(0x413a, 2);  // jr nz,$417a
L_413c:
  CALL(0x413c, checkTileAfterNext, 0x4398, 0x413f);  // call $4398
  if (!(F & FC)) { I(0x413f, 3); goto L_417a; } I(0x413f, 2);  // jr nc,$417a
  I(0x4141, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x4143, 2); alu_cp(gb, 0xda);  // cp $da
  if ((F & FZ)) { I(0x4145, 3); goto L_417e; } I(0x4145, 2);  // jr z,$417e
  I(0x4147, 3); SET_HL(0xd140);  // ld hl,$d140
  I(0x414a, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x414b, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x414c, 3); goto L_417a; } I(0x414c, 2);  // jr nz,$417a
  I(0x414e, 3); mem_wr(gb, HL, 0x01);  // ld (hl),$01
  I(0x4150, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4151, 3); mem_wr(gb, HL, 0x14);  // ld (hl),$14
  I(0x4153, 4); A = mem_rd(gb, 0xcc65);  // ld a,($cc65)
  I(0x4156, 2); A = alu_swap(gb, A);  // swap a
  I(0x4158, 1); alu_rrca(gb);  // rrca
  I(0x4159, 2); L = 0x49;  // ld l,$49
  I(0x415b, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x415c, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x415e, 2); L = 0x70;  // ld l,$70
  I(0x4160, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x4161, 2); L = 0x4b;  // ld l,$4b
  CALL(0x4163, setShortPosition, 0x20b8, 0x4166);  // call $20b8
  I(0x4166, 2); L = 0x4b;  // ld l,$4b
  I(0x4168, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x4169, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x416a, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x416c, 2); alu_cp(gb, 0xd9);  // cp $d9
  if (!(F & FZ)) { I(0x416e, 3); goto L_417a; } I(0x416e, 2);  // jr nz,$417a
  I(0x4170, 4); A = mem_rd(gb, 0xcc34);  // ld a,($cc34)
  I(0x4173, 2); alu_and(gb, 0x01);  // and $01
  if ((F & FZ)) { I(0x4175, 3); goto L_417a; } I(0x4175, 2);  // jr z,$417a
  I(0x4177, 4); mem_wr(gb, 0xcc8a, A);  // ld ($cc8a),a
L_417a:
  I(0x417a, 1); alu_xor(gb, A);  // xor a
  I(0x417b, 4); resetPushingAgainstTileCounter(gb); return;  // jp $420c
L_417e:
  I(0x417e, 2); C = 0x18;  // ld c,$18
  CALL(0x4180, findItemWithID, 0x22b9, 0x4183);  // call $22b9
  if (!(F & FZ)) { I(0x4183, 3); goto L_417a; } I(0x4183, 2);  // jr nz,$417a
  I(0x4185, 2); L = 0x2f;  // ld l,$2f
  I(0x4187, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) | (1 << 0)));  // set 0,(hl)
  I(0x4189, 4); A = mem_rd(gb, 0xcc65);  // ld a,($cc65)
  I(0x418c, 2); L = 0x08;  // ld l,$08
  I(0x418e, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x418f, 3); goto L_417a;  // jr $417a
}

// 06:4191
void nextToKeyBlock(GB *gb) {
  CALL(0x4191, specialObjectCheckPushingAgainstTile, 0x4329, 0x4194);  // call $4329
  if ((F & FZ)) { I(0x4194, 4); resetPushingAgainstTileCounter(gb); return; } I(0x4194, 3);  // jp z,$420c
  CALL(0x4197, decPushingAgainstTileCounter, 0x4212, 0x419a);  // call $4212
  if (!(F & FZ)) { RET_TAKEN(0x419a); return; } I(0x419a, 2);  // ret nz
  CALL(0x419b, checkAndDecKeyCount, 0x4350, 0x419e);  // call $4350
  I(0x419e, 2); A = 0x02;  // ld a,$02
  if ((F & FZ)) { I(0x41a0, 4); showInfoTextForTile(gb); return; } I(0x41a0, 3);  // jp z,$42fb
  CALL(0x41a3, createKeySpriteInteraction, 0x4288, 0x41a6);  // call $4288
  I(0x41a6, 2); A = 0xa0;  // ld a,$a0
  CALL(0x41a8, setTile, 0x3a9c, 0x41ab);  // call $3a9c
  I(0x41ab, 2); A = 0x6c;  // ld a,$6c
  CALL(0x41ad, playSound_b00, 0x0c98, 0x41b0);  // call $0c98
  CALL(0x41b0, getThisRoomFlags, 0x197d, 0x41b3);  // call $197d
  I(0x41b3, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) | (1 << 7)));  // set 7,(hl)
  CALL(0x41b5, getFreeInteractionSlot, 0x3aef, 0x41b8);  // call $3aef
  if (!(F & FZ)) { I(0x41b8, 3); goto L_41c3; } I(0x41b8, 2);  // jr nz,$41c3
  I(0x41ba, 3); mem_wr(gb, HL, 0x05);  // ld (hl),$05
  I(0x41bc, 2); L = 0x4b;  // ld l,$4b
  I(0x41be, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  CALL(0x41c0, setShortPosition, 0x20b8, 0x41c3);  // call $20b8
L_41c3:
  I(0x41c3, 1); alu_xor(gb, A);  // xor a
  I(0x41c4, 3); resetPushingAgainstTileCounter(gb); return;  // jr $420c
}

// 06:41c6
void nextToKeyDoor(GB *gb) {
  CALL(0x41c6, specialObjectCheckPushingAgainstTile, 0x4329, 0x41c9);  // call $4329
  if ((F & FZ)) { I(0x41c9, 3); resetPushingAgainstTileCounter(gb); return; } I(0x41c9, 2);  // jr z,$420c
  CALL(0x41cb, decPushingAgainstTileCounter, 0x4212, 0x41ce);  // call $4212
  if ((F & FZ)) { I(0x41ce, 3); goto L_41d2; } I(0x41ce, 2);  // jr z,$41d2
  I(0x41d0, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  if (!(F & FZ)) { RET_TAKEN(0x41d1); return; } I(0x41d1, 2);  // ret nz
L_41d2:
  CALL(0x41d2, checkAndDecKeyCount, 0x4350, 0x41d5);  // call $4350
  if ((F & FZ)) { I(0x41d5, 3); goto L_4200; } I(0x41d5, 2);  // jr z,$4200
  I(0x41d7, 3); SET_HL(0xd040);  // ld hl,$d040
  I(0x41da, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x41db, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x41dc, 3); goto L_41fd; } I(0x41dc, 2);  // jr nz,$41fd
  CALL(0x41de, createKeySpriteInteraction, 0x4288, 0x41e1);  // call $4288
  I(0x41e1, 3); SET_HL(0xd040);  // ld hl,$d040
  I(0x41e4, 3); mem_wr(gb, HL, 0x01);  // ld (hl),$01
  I(0x41e6, 1); L = alu_inc8(gb, L);  // inc l
  I(0x41e7, 3); mem_wr(gb, HL, 0x1e);  // ld (hl),$1e
  I(0x41e9, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x41eb, 2); L = 0x4b;  // ld l,$4b
  I(0x41ed, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x41ee, 2); L = 0x49;  // ld l,$49
  I(0x41f0, 1); A = B;  // ld a,b
  I(0x41f1, 2); A = alu_swap(gb, A);  // swap a
  I(0x41f3, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x41f5, 1); alu_add(gb, A);  // add a
  I(0x41f6, 2); mem_wr(gb, HL, A);  // ld (hl),a
  PUSH(0x41f7, DE);  // push de
  I(0x41f8, 1); alu_add(gb, A);  // add a
  CALL(0x41f9, setRoomFlagsForUnlockedKeyDoor, 0x11fc, 0x41fc);  // call $11fc
  SET_DE(POP(0x41fc));  // pop de
L_41fd:
  I(0x41fd, 1); alu_xor(gb, A);  // xor a
  I(0x41fe, 3); resetPushingAgainstTileCounter(gb); return;  // jr $420c
L_4200:
  I(0x4200, 1); A = B;  // ld a,b
  I(0x4201, 2); alu_cp(gb, 0x40);  // cp $40
  I(0x4203, 2); A = 0x01;  // ld a,$01
  if (!(F & FC)) { I(0x4205, 4); showInfoTextForTile(gb); return; } I(0x4205, 3);  // jp nc,$42fb
  I(0x4208, 1); alu_xor(gb, A);  // xor a
  I(0x4209, 4); showInfoTextForTile(gb); return;  // jp $42fb
}

// 06:420c
void resetPushingAgainstTileCounter(GB *gb) {
  I(0x420c, 2); A = 0x14;  // ld a,$14
  I(0x420e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  RET(0x4211); return;  // ret
}

// 06:4212
void decPushingAgainstTileCounter(GB *gb) {
  I(0x4212, 3); SET_HL(0xcc6a);  // ld hl,$cc6a
  I(0x4215, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  RET(0x4216); return;  // ret
}

// 06:4217
void nextToOverworldKeyhole(GB *gb) {
  CALL(0x4217, getThisRoomFlags, 0x197d, 0x421a);  // call $197d
  I(0x421a, 2); alu_and(gb, 0x80);  // and $80
  if (!(F & FZ)) { RET_TAKEN(0x421c); return; } I(0x421c, 2);  // ret nz
  CALL(0x421d, specialObjectCheckPushingAgainstTile, 0x4329, 0x4220);  // call $4329
  if ((F & FZ)) { I(0x4220, 3); resetPushingAgainstTileCounter(gb); return; } I(0x4220, 2);  // jr z,$420c
  CALL(0x4222, checkFacingBottomOfTile, 0x40f6, 0x4225);  // call $40f6
  if ((F & FZ)) { I(0x4225, 3); goto L_4229; } I(0x4225, 2);  // jr z,$4229
  I(0x4227, 1); alu_xor(gb, A);  // xor a
  RET(0x4228); return;  // ret
L_4229:
  CALL(0x4229, decPushingAgainstTileCounter, 0x4212, 0x422c);  // call $4212
  if ((F & FZ)) { I(0x422c, 3); goto L_4230; } I(0x422c, 2);  // jr z,$4230
  I(0x422e, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  if (!(F & FZ)) { RET_TAKEN(0x422f); return; } I(0x422f, 2);  // ret nz
L_4230:
  I(0x4230, 4); A = mem_rd(gb, 0xcc30);  // ld a,($cc30)
  I(0x4233, 3); SET_HL(0x4267);  // ld hl,$4267
  CALL(0x4236, findRoomSpecificData, 0x1dfe, 0x4239);  // call $1dfe
  I(0x4239, 1); B = A;  // ld b,a
  if (!(F & FC)) { I(0x423a, 3); jumpToShowInfoText(gb); return; } I(0x423a, 2);  // jr nc,$4283
  CALL(0x423c, checkTreasureObtained, 0x1748, 0x423f);  // call $1748
  if (!(F & FC)) { I(0x423f, 3); jumpToShowInfoText(gb); return; } I(0x423f, 2);  // jr nc,$4283
  I(0x4241, 2); A = 0x6c;  // ld a,$6c
  CALL(0x4243, playSound_b00, 0x0c98, 0x4246);  // call $0c98
  CALL(0x4246, getThisRoomFlags, 0x197d, 0x4249);  // call $197d
  I(0x4249, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) | (1 << 7)));  // set 7,(hl)
  I(0x424b, 3); SET_HL(0xcfc0);  // ld hl,$cfc0
  I(0x424e, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) | (1 << 0)));  // set 0,(hl)
  CALL(0x4250, createKeySpriteInteraction, 0x4288, 0x4253);  // call $4288
  I(0x4253, 2); L = 0x41;  // ld l,$41
  I(0x4255, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x4256, 1); A = B;  // ld a,b
  I(0x4257, 2); alu_sub(gb, 0x42);  // sub $42
  I(0x4259, 2); L = 0x42;  // ld l,$42
  I(0x425b, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x425c, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x425d, 2); A = 0x81;  // ld a,$81
  I(0x425f, 4); mem_wr(gb, 0xcc8a, A);  // ld ($cc8a),a
  I(0x4262, 4); mem_wr(gb, 0xcc02, A);  // ld ($cc02),a
  I(0x4265, 1); alu_scf(gb);  // scf
  RET(0x4266); return;  // ret
}

// 06:4283
void jumpToShowInfoText(GB *gb) {
  I(0x4283, 2); A = 0x08;  // ld a,$08
  I(0x4285, 4); showInfoTextForTile(gb); return;  // jp $42fb
}

// 06:4288
void createKeySpriteInteraction(GB *gb) {
  CALL(0x4288, getFreeInteractionSlot, 0x3aef, 0x428b);  // call $3aef
  if (!(F & FZ)) { RET_TAKEN(0x428b); return; } I(0x428b, 2);  // ret nz
  I(0x428c, 3); mem_wr(gb, HL, 0x17);  // ld (hl),$17
  I(0x428e, 1); L = alu_inc8(gb, L);  // inc l
  I(0x428f, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x4291, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x4292, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x4294, 2); L = 0x4b;  // ld l,$4b
  I(0x4296, 4); setShortPosition(gb); return;  // jp $20b8
}

// 06:4299
void nextToSubrosiaKeydoor(GB *gb) {
  I(0x4299, 1); alu_scf(gb);  // scf
  RET(0x429a); return;  // ret
}

// 06:429b
void nextToGhiniSpawner(GB *gb) {
  I(0x429b, 4); A = mem_rd(gb, 0xcdda);  // ld a,($cdda)
  I(0x429e, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x429f); return; } I(0x429f, 2);  // ret nz
  CALL(0x42a0, specialObjectCheckPushingAgainstTile, 0x4329, 0x42a3);  // call $4329
  if ((F & FZ)) { I(0x42a3, 4); resetPushingAgainstTileCounter(gb); return; } I(0x42a3, 3);  // jp z,$420c
  CALL(0x42a6, decPushingAgainstTileCounter, 0x4212, 0x42a9);  // call $4212
  if (!(F & FZ)) { RET_TAKEN(0x42a9); return; } I(0x42a9, 2);  // ret nz
  I(0x42aa, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x42ac, 1); L = A;  // ld l,a
  I(0x42ad, 2); H = 0xcf;  // ld h,$cf
  I(0x42af, 3); mem_wr(gb, HL, 0x00);  // ld (hl),$00
  CALL(0x42b1, convertShortToLongPosition, 0x20cb, 0x42b4);  // call $20cb
  CALL(0x42b4, getFreeEnemySlot, 0x2e27, 0x42b7);  // call $2e27
  if (!(F & FZ)) { RET_TAKEN(0x42b7); return; } I(0x42b7, 2);  // ret nz
  I(0x42b8, 3); mem_wr(gb, HL, 0x17);  // ld (hl),$17
  I(0x42ba, 1); L = alu_inc8(gb, L);  // inc l
  I(0x42bb, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x42bc, 2); L = 0x8b;  // ld l,$8b
  I(0x42be, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x42bf, 2); L = 0x8d;  // ld l,$8d
  I(0x42c1, 2); mem_wr(gb, HL, C);  // ld (hl),c
  RET(0x42c2); return;  // ret
}

// 06:42c3
void nextToTileWithInfoText(GB *gb) {
  CALL(0x42c3, specialObjectCheckPushingAgainstTile, 0x4329, 0x42c6);  // call $4329
  if ((F & FZ)) { I(0x42c6, 4); resetPushingAgainstTileCounter(gb); return; } I(0x42c6, 3);  // jp z,$420c
  CALL(0x42c9, decPushingAgainstTileCounter, 0x4212, 0x42cc);  // call $4212
  if (!(F & FZ)) { RET_TAKEN(0x42cc); return; } I(0x42cc, 2);  // ret nz
  CALL(0x42cd, resetPushingAgainstTileCounter, 0x420c, 0x42d0);  // call $420c
  I(0x42d0, 1); A = B;  // ld a,b
  I(0x42d1, 2); A = alu_swap(gb, A);  // swap a
  I(0x42d3, 2); alu_and(gb, 0x0f);  // and $0f
  RST_PUSH(0x42d5, 0x42d6);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x42e0: goto L_42e0; case 0x42eb: goto L_42eb; case 0x42ef: goto L_42ef; case 0x42f3: goto L_42f3; case 0x42f7: goto L_42f7; default: HANDOFF(HL); }
L_42e0:
  I(0x42e0, 2); A = 0x16;  // ld a,$16
  CALL(0x42e2, checkTreasureObtained, 0x1748, 0x42e5);  // call $1748
  I(0x42e5, 1); alu_ccf(gb);  // ccf
  if (!(F & FC)) { RET_TAKEN(0x42e6); return; } I(0x42e6, 2);  // ret nc
  I(0x42e7, 2); A = 0x03;  // ld a,$03
  I(0x42e9, 3); showInfoTextForTile(gb); return;  // jr $42fb
L_42eb:
  I(0x42eb, 2); A = 0x05;  // ld a,$05
  I(0x42ed, 3); showInfoTextForTile(gb); return;  // jr $42fb
L_42ef:
  I(0x42ef, 2); A = 0x06;  // ld a,$06
  I(0x42f1, 3); showInfoTextForTile(gb); return;  // jr $42fb
L_42f3:
  I(0x42f3, 2); A = 0x07;  // ld a,$07
  I(0x42f5, 3); showInfoTextForTile(gb); return;  // jr $42fb
L_42f7:
  I(0x42f7, 2); A = 0x04;  // ld a,$04
  I(0x42f9, 3); showInfoTextForTile(gb); return;  // jr $42fb
}

// 06:42fb
void showInfoTextForTile(GB *gb) {
  I(0x42fb, 3); SET_HL(0x4315);  // ld hl,$4315
  RST_PUSH(0x42fe, 0x42ff);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x42ff, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4300, 1); B = A;  // ld b,a
  I(0x4301, 2); C = mem_rd(gb, HL);  // ld c,(hl)
  CALL(0x4302, resetPushingAgainstTileCounter, 0x420c, 0x4305);  // call $420c
  I(0x4305, 3); SET_HL(0xccd7);  // ld hl,$ccd7
  I(0x4308, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4309, 1); alu_and(gb, B);  // and b
  if (!(F & FZ)) { RET_TAKEN(0x430a); return; } I(0x430a, 2);  // ret nz
  I(0x430b, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x430c, 1); alu_or(gb, B);  // or b
  I(0x430d, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x430e, 2); B = 0x51;  // ld b,$51
  CALL(0x4310, showText, 0x1872, 0x4313);  // call $1872
  I(0x4313, 1); alu_scf(gb);  // scf
  RET(0x4314); return;  // ret
}

// 06:4329
void specialObjectCheckPushingAgainstTile(GB *gb) {
  I(0x4329, 4); A = mem_rd(gb, 0xcc65);  // ld a,($cc65)
  I(0x432c, 1); alu_rlca(gb);  // rlca
  if ((F & FC)) { I(0x432d, 3); goto L_433d; } I(0x432d, 2);  // jr c,$433d
  I(0x432f, 4); A = mem_rd(gb, 0xcc2b);  // ld a,($cc2b)
  I(0x4332, 2); alu_and(gb, 0x07);  // and $07
  if (!(F & FZ)) { I(0x4334, 3); goto L_433d; } I(0x4334, 2);  // jr nz,$433d
  CALL_ASM(0x4336, 0x433f, 0x4339); /* unported */  // call $433f
  if (!(F & FC)) { I(0x4339, 3); goto L_433d; } I(0x4339, 2);  // jr nc,$433d
  I(0x433b, 1); alu_or(gb, D);  // or d
  RET(0x433c); return;  // ret
L_433d:
  I(0x433d, 1); alu_xor(gb, A);  // xor a
  RET(0x433e); return;  // ret
}

// 06:4350
void checkAndDecKeyCount(GB *gb) {
  I(0x4350, 4); A = mem_rd(gb, 0xcc39);  // ld a,($cc39)
  I(0x4353, 2); alu_cp(gb, 0xff);  // cp $ff
  if ((F & FZ)) { RET_TAKEN(0x4355); return; } I(0x4355, 2);  // ret z
  I(0x4356, 1); A = B;  // ld a,b
  I(0x4357, 2); alu_cp(gb, 0x40);  // cp $40
  I(0x4359, 2); H = 0xc6;  // ld h,$c6
  I(0x435b, 4); A = mem_rd(gb, 0xcc39);  // ld a,($cc39)
  if (!(F & FC)) { I(0x435e, 3); goto L_436e; } I(0x435e, 2);  // jr nc,$436e
  I(0x4360, 2); alu_add(gb, 0x72);  // add $72
  I(0x4362, 1); L = A;  // ld l,a
  I(0x4363, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4364, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { RET_TAKEN(0x4365); return; } I(0x4365, 2);  // ret z
  I(0x4366, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x4367, 3); SET_HL(0xcbe9);  // ld hl,$cbe9
  I(0x436a, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) | (1 << 4)));  // set 4,(hl)
  I(0x436c, 1); alu_or(gb, H);  // or h
  RET(0x436d); return;  // ret
L_436e:
  I(0x436e, 2); L = 0x82;  // ld l,$82
  I(0x4370, 4); checkFlag(gb); return;  // jp $0205
}

// 06:4373
void specialObjectGetTileInFront(GB *gb) {
  I(0x4373, 2); E = 0x08;  // ld e,$08
  I(0x4375, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4376, 3); SET_HL(0x4390);  // ld hl,$4390
  RST_PUSH(0x4379, 0x437a);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  specialObjectGetTileAtOffset(gb); return;  // fallthrough
}

// 06:437a
void specialObjectGetTileAtOffset(GB *gb) {
  I(0x437a, 2); E = 0x0b;  // ld e,$0b
  I(0x437c, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x437d, 2); alu_add(gb, mem_rd(gb, HL));  // add (hl)
  I(0x437e, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x4380, 1); C = A;  // ld c,a
  I(0x4381, 2); SET_HL(HL + 1);  // inc hl
  I(0x4382, 2); E = 0x0d;  // ld e,$0d
  I(0x4384, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4385, 2); alu_add(gb, mem_rd(gb, HL));  // add (hl)
  I(0x4386, 2); A = alu_swap(gb, A);  // swap a
  I(0x4388, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x438a, 1); alu_or(gb, C);  // or c
  I(0x438b, 1); C = A;  // ld c,a
  I(0x438c, 2); B = 0xcf;  // ld b,$cf
  I(0x438e, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  RET(0x438f); return;  // ret
}

// 06:4398
void checkTileAfterNext(GB *gb) {
  I(0x4398, 4); A = mem_rd(gb, 0xcc65);  // ld a,($cc65)
  I(0x439b, 3); SET_HL(0x43aa);  // ld hl,$43aa
  RST_PUSH(0x439e, 0x439f);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  CALL(0x439f, specialObjectGetTileAtOffset, 0x437a, 0x43a2);  // call $437a
  I(0x43a2, 2); B = 0xce;  // ld b,$ce
  I(0x43a4, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x43a5, 2); alu_and(gb, 0x0f);  // and $0f
  if (!(F & FZ)) { RET_TAKEN(0x43a7); return; } I(0x43a7, 2);  // ret nz
  I(0x43a8, 1); alu_scf(gb);  // scf
  RET(0x43a9); return;  // ret
}

// 06:4870
void functionCaller_b06(GB *gb) {
  I(0x4870, 1); A = C;  // ld a,c
  RST_PUSH(0x4871, 0x4872);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 06:4878
void clearAllParentItems_body(GB *gb) {
  PUSH(0x4878, DE);  // push de
  I(0x4879, 2); D = 0xd2;  // ld d,$d2
L_487b:
  CALL(0x487b, clearParentItem, 0x4a42, 0x487e);  // call $4a42
  I(0x487e, 1); D = alu_inc8(gb, D);  // inc d
  I(0x487f, 1); A = D;  // ld a,d
  I(0x4880, 2); alu_cp(gb, 0xd6);  // cp $d6
  if ((F & FC)) { I(0x4882, 3); goto L_487b; } I(0x4882, 2);  // jr c,$487b
  I(0x4884, 1); alu_xor(gb, A);  // xor a
  I(0x4885, 4); mem_wr(gb, 0xcc6f, A);  // ld ($cc6f),a
  I(0x4888, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x488b, 4); mem_wr(gb, 0xcc5e, A);  // ld ($cc5e),a
  SET_DE(POP(0x488e));  // pop de
  RET(0x488f); return;  // ret
}

// 06:4890
void updateParentItemButtonAssignment_body(GB *gb) {
  I(0x4890, 2); H = 0xd2;  // ld h,$d2
L_4892:
  I(0x4892, 2); L = 0x00;  // ld l,$00
  I(0x4894, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4895, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x4896, 3); goto L_48a8; } I(0x4896, 2);  // jr z,$48a8
  I(0x4898, 4); A = mem_rd(gb, 0xc688);  // ld a,($c688)
  I(0x489b, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  I(0x489c, 2); A = 0x02;  // ld a,$02
  if ((F & FZ)) { I(0x489e, 3); goto L_48a9; } I(0x489e, 2);  // jr z,$48a9
  I(0x48a0, 4); A = mem_rd(gb, 0xc689);  // ld a,($c689)
  I(0x48a3, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  I(0x48a4, 2); A = 0x01;  // ld a,$01
  if ((F & FZ)) { I(0x48a6, 3); goto L_48a9; } I(0x48a6, 2);  // jr z,$48a9
L_48a8:
  I(0x48a8, 1); alu_xor(gb, A);  // xor a
L_48a9:
  I(0x48a9, 2); L = 0x03;  // ld l,$03
  I(0x48ab, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x48ac, 1); H = alu_inc8(gb, H);  // inc h
  I(0x48ad, 1); A = H;  // ld a,h
  I(0x48ae, 2); alu_cp(gb, 0xd6);  // cp $d6
  if ((F & FC)) { I(0x48b0, 3); goto L_4892; } I(0x48b0, 2);  // jr c,$4892
  RET(0x48b2); return;  // ret
}

// 06:4954
void checkItemUsed(GB *gb) {
  I(0x4954, 2); H = 0xc6;  // ld h,$c6
  I(0x4956, 1); L = E;  // ld l,e
  I(0x4957, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4958, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x4959, 3); goto L_496c; } I(0x4959, 2);  // jr nz,$496c
  I(0x495b, 4); A = mem_rd(gb, 0xc6cb);  // ld a,($c6cb)
  I(0x495e, 2); alu_cp(gb, 0x0b);  // cp $0b
  if ((F & FZ)) { I(0x4960, 3); goto L_4965; } I(0x4960, 2);  // jr z,$4965
  I(0x4962, 2); alu_cp(gb, 0x3d);  // cp $3d
  if (!(F & FZ)) { RET_TAKEN(0x4964); return; } I(0x4964, 2);  // ret nz
L_4965:
  I(0x4965, 2); L = 0x88;  // ld l,$88
  I(0x4967, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4968, 2); alu_or(gb, mem_rd(gb, HL));  // or (hl)
  if (!(F & FZ)) { RET_TAKEN(0x4969); return; } I(0x4969, 2);  // ret nz
L_496a:
  I(0x496a, 2); A = 0x02;  // ld a,$02
L_496c:
  I(0x496c, 2); alu_cp(gb, 0x20);  // cp $20
  if (!(F & FC)) { RET_TAKEN(0x496e); return; } I(0x496e, 2);  // ret nc
  I(0x496f, 1); E = A;  // ld e,a
  I(0x4970, 3); SET_HL(0x55be);  // ld hl,$55be
  RST_PUSH(0x4973, 0x4974);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x4974, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4975, 1); C = A;  // ld c,a
  I(0x4976, 2); L = mem_rd(gb, HL);  // ld l,(hl)
  I(0x4977, 2); H = 0xcc;  // ld h,$cc
  I(0x4979, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x497a, 1); alu_and(gb, D);  // and d
  if ((F & FZ)) { RET_TAKEN(0x497b); return; } I(0x497b, 2);  // ret z
  CALL(0x497c, chooseParentItemSlot, 0x498c, 0x497f);  // call $498c
  if (!(F & FZ)) { RET_TAKEN(0x497f); return; } I(0x497f, 2);  // ret nz
  initializeParentItem(gb); return;  // fallthrough
}

// 06:4980
void initializeParentItem(GB *gb) {
  I(0x4980, 1); A = C;  // ld a,c
  I(0x4981, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x4983, 1); A = alu_inc8(gb, A);  // inc a
  I(0x4984, 2); L = 0x00;  // ld l,$00
  I(0x4986, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x4987, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x4988, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4989, 1); L = alu_inc8(gb, L);  // inc l
  I(0x498a, 2); mem_wr(gb, HL, D);  // ld (hl),d
  RET(0x498b); return;  // ret
}

// 06:498c
void chooseParentItemSlot(GB *gb) {
  I(0x498c, 1); A = C;  // ld a,c
  I(0x498d, 2); alu_and(gb, 0x0f);  // and $0f
  RST_PUSH(0x498f, 0x4990);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x499c: goto L_499c; case 0x49a1: goto L_49a1; case 0x49ac: goto L_49ac; case 0x49b6: goto L_49b6; case 0x49d2: goto L_49d2; case 0x49d8: goto L_49d8; default: HANDOFF(HL); }
L_499c:
  I(0x499c, 4); A = mem_rd(gb, 0xd200);  // ld a,($d200)
  I(0x499f, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x49a0); return; } I(0x49a0, 2);  // ret nz
L_49a1:
  I(0x49a1, 3); SET_HL(0xd301);  // ld hl,$d301
  I(0x49a4, 1); A = E;  // ld a,e
  I(0x49a5, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if ((F & FZ)) { I(0x49a6, 3); goto L_49d8; } I(0x49a6, 2);  // jr z,$49d8
  I(0x49a8, 1); H = alu_inc8(gb, H);  // inc h
  I(0x49a9, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if ((F & FZ)) { I(0x49aa, 3); goto L_49d8; } I(0x49aa, 2);  // jr z,$49d8
L_49ac:
  I(0x49ac, 3); SET_HL(0xd300);  // ld hl,$d300
  I(0x49af, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x49b0, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { RET_TAKEN(0x49b1); return; } I(0x49b1, 2);  // ret z
  I(0x49b2, 1); H = alu_inc8(gb, H);  // inc h
  I(0x49b3, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x49b4, 1); alu_or(gb, A);  // or a
  RET(0x49b5); return;  // ret
L_49b6:
  I(0x49b6, 3); SET_HL(0xd200);  // ld hl,$d200
  I(0x49b9, 1); A = C;  // ld a,c
  I(0x49ba, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x49bc, 1); A = alu_inc8(gb, A);  // inc a
  I(0x49bd, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if ((F & FC)) { I(0x49be, 3); goto L_49d8; } I(0x49be, 2);  // jr c,$49d8
  PUSH(0x49c0, DE);  // push de
  PUSH(0x49c1, BC);  // push bc
  CALL(0x49c2, clearParentItemH, 0x4a50, 0x49c5);  // call $4a50
  SET_BC(POP(0x49c5));  // pop bc
  SET_DE(POP(0x49c6));  // pop de
  I(0x49c7, 3); SET_HL(0xd200);  // ld hl,$d200
  I(0x49ca, 1); alu_xor(gb, A);  // xor a
  I(0x49cb, 4); mem_wr(gb, 0xcc5e, A);  // ld ($cc5e),a
  I(0x49ce, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  RET(0x49d1); return;  // ret
L_49d2:
  I(0x49d2, 3); SET_HL(0xd500);  // ld hl,$d500
  I(0x49d5, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x49d6, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { RET_TAKEN(0x49d7); return; } I(0x49d7, 2);  // ret z
L_49d8:
  I(0x49d8, 1); alu_or(gb, H);  // or h
  RET(0x49d9); return;  // ret
}

// 06:49da
void checkShopInput(GB *gb) {
  I(0x49da, 4); A = mem_rd(gb, 0xcc5a);  // ld a,($cc5a)
  I(0x49dd, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x49de); return; } I(0x49de, 2);  // ret nz
  I(0x49df, 4); A = mem_rd(gb, 0xcc2a);  // ld a,($cc2a)
  I(0x49e2, 2); alu_and(gb, 0x03);  // and $03
  if ((F & FZ)) { RET_TAKEN(0x49e4); return; } I(0x49e4, 2);  // ret z
  CALL(0x49e5, checkGrabbableObjects, 0x1c97, 0x49e8);  // call $1c97
  if (!(F & FC)) { RET_TAKEN(0x49e8); return; } I(0x49e8, 2);  // ret nc
  I(0x49e9, 2); A = 0x83;  // ld a,$83
  I(0x49eb, 4); mem_wr(gb, 0xcc5a, A);  // ld ($cc5a),a
  RET(0x49ee); return;  // ret
}

// 06:49ef
void parentItemUpdate(GB *gb) {
  I(0x49ef, 1); A = E;  // ld a,e
  I(0x49f0, 3); mem_wr(gb, 0xffae, A);  // ldh ($ffae),a
  I(0x49f2, 1); A = D;  // ld a,d
  I(0x49f3, 3); mem_wr(gb, 0xffaf, A);  // ldh ($ffaf),a
  CALL_ASM(0x49f5, 0x548c, 0x49f8); /* itemIndexToBit */  // call $548c
  I(0x49f8, 3); SET_HL(0xcc95);  // ld hl,$cc95
  I(0x49fb, 1); alu_cpl(gb);  // cpl
  I(0x49fc, 2); alu_and(gb, mem_rd(gb, HL));  // and (hl)
  I(0x49fd, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x49fe, 2); E = 0x01;  // ld e,$01
  I(0x4a00, 2); A = mem_rd(gb, DE);  // ld a,(de)
  RST_PUSH(0x4a01, 0x4a02);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 06:4a42
void clearParentItem(GB *gb) {
  CALL_ASM(0x4a42, 0x5450, 0x4a45); /* clearLinkUsingItem1 */  // call $5450
  CALL_ASM(0x4a45, 0x5479, 0x4a48); /* itemEnableLinkTurning */  // call $5479
  CALL_ASM(0x4a48, 0x5466, 0x4a4b); /* itemEnableLinkMovement */  // call $5466
  I(0x4a4b, 2); E = 0x00;  // ld e,$00
  I(0x4a4d, 4); objectDelete_de(gb); return;  // jp $21e3
}

// 06:4a50
void clearParentItemH(GB *gb) {
  PUSH(0x4a50, DE);  // push de
  I(0x4a51, 1); D = H;  // ld d,h
  CALL(0x4a52, clearParentItem, 0x4a42, 0x4a55);  // call $4a42
  SET_DE(POP(0x4a55));  // pop de
  RET(0x4a56); return;  // ret
}

// 06:441e
void specialObjectAnimate_optimized(GB *gb) {
  I(0x441e, 1); H = D;  // ld h,d
  I(0x441f, 2); L = 0x20;  // ld l,$20
  I(0x4421, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  if (!(F & FZ)) { RET_TAKEN(0x4422); return; } I(0x4422, 2);  // ret nz
  I(0x4423, 2); L = 0x22;  // ld l,$22
  I(0x4425, 3); specialObjectNextAnimationFrame(gb); return;  // jr $4432
}

// 06:4427
void specialObjectSetAnimation_body(GB *gb) {
  I(0x4427, 2); E = 0x01;  // ld e,$01
  I(0x4429, 2); A = mem_rd(gb, DE);  // ld a,(de)
  label_06_032(gb); return;  // fallthrough
}

// 06:442a
void label_06_032(GB *gb) {
  I(0x442a, 3); SET_HL(0x4479);  // ld hl,$4479
  RST_PUSH(0x442d, 0x442e);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x442e, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x442f, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x4430, 1); L = A;  // ld l,a
  I(0x4431, 2); alu_add_hl(gb, BC);  // add hl,bc
  specialObjectNextAnimationFrame(gb); return;  // fallthrough
}

// 06:4432
void specialObjectNextAnimationFrame(GB *gb) {
  I(0x4432, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4433, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x4434, 1); L = A;  // ld l,a
  I(0x4435, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4436, 2); alu_cp(gb, 0xff);  // cp $ff
  if (!(F & FZ)) { I(0x4438, 3); goto L_443e; } I(0x4438, 2);  // jr nz,$443e
  I(0x443a, 2); C = mem_rd(gb, HL);  // ld c,(hl)
  I(0x443b, 1); B = A;  // ld b,a
  I(0x443c, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x443d, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
L_443e:
  I(0x443e, 2); E = 0x20;  // ld e,$20
  I(0x4440, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4441, 1); E = alu_inc8(gb, E);  // inc e
  I(0x4442, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4443, 1); C = A;  // ld c,a
  I(0x4444, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4445, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4446, 1); E = alu_inc8(gb, E);  // inc e
  I(0x4447, 1); A = L;  // ld a,l
  I(0x4448, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4449, 1); E = alu_inc8(gb, E);  // inc e
  I(0x444a, 1); A = H;  // ld a,h
  I(0x444b, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x444c, 2); E = 0x31;  // ld e,$31
  I(0x444e, 1); A = C;  // ld a,c
  I(0x444f, 2); mem_wr(gb, DE, A);  // ld (de),a
  RET(0x4450); return;  // ret
}

// 06:44c9
void loadLinkAndCompanionAnimationFrame_body(GB *gb) {
  I(0x44c9, 2); A = 0xff;  // ld a,$ff
  I(0x44cb, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x44ce, 4); A = mem_rd(gb, 0xd01a);  // ld a,($d01a)
  I(0x44d1, 1); alu_rlca(gb);  // rlca
  if (!(F & FC)) { I(0x44d2, 3); goto L_44eb; } I(0x44d2, 2);  // jr nc,$44eb
  CALL_ASM(0x44d4, 0x4553, 0x44d7); /* func_4553 */  // call $4553
  I(0x44d7, 4); A = mem_rd(gb, 0xd001);  // ld a,($d001)
  I(0x44da, 3); SET_HL(0x450c);  // ld hl,$450c
  RST_PUSH(0x44dd, 0x44de);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x44de, 1); A = B;  // ld a,b
  I(0x44df, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if ((F & FC)) { I(0x44e0, 3); goto L_44e6; } I(0x44e0, 2);  // jr c,$44e6
  I(0x44e2, 4); A = mem_rd(gb, 0xd008);  // ld a,($d008)
  I(0x44e5, 1); alu_add(gb, B);  // add b
L_44e6:
  I(0x44e6, 2); H = 0xd0;  // ld h,$d0
  CALL_ASM(0x44e8, 0x44f4, 0x44eb); /* unported */  // call $44f4
L_44eb:
  I(0x44eb, 3); SET_HL(0xd11a);  // ld hl,$d11a
  I(0x44ee, 3); alu_bit(gb, 7, mem_rd(gb, HL));  // bit 7,(hl)
  if ((F & FZ)) { RET_TAKEN(0x44f0); return; } I(0x44f0, 2);  // ret z
  I(0x44f1, 2); L = 0x31;  // ld l,$31
  I(0x44f3, 2); A = mem_rd(gb, HL);  // ld a,(hl)
L_44f4:
  I(0x44f4, 2); L = 0x32;  // ld l,$32
  I(0x44f6, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if ((F & FZ)) { RET_TAKEN(0x44f7); return; } I(0x44f7, 2);  // ret z
  I(0x44f8, 2); mem_wr(gb, HL, A);  // ld (hl),a
  CALL(0x44f9, getSpecialObjectGraphicsFrame, 0x4516, 0x44fc);  // call $4516
  if ((F & FZ)) { RET_TAKEN(0x44fc); return; } I(0x44fc, 2);  // ret z
  I(0x44fd, 2); E = 0x01;  // ld e,$01
  I(0x44ff, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4500, 2); alu_cp(gb, 0x0a);  // cp $0a
  I(0x4502, 3); SET_DE(0x8701);  // ld de,$8701
  if ((F & FC)) { I(0x4505, 3); goto L_4509; } I(0x4505, 2);  // jr c,$4509
  I(0x4507, 2); D = 0x86;  // ld d,$86
L_4509:
  I(0x4509, 4); queueDmaTransfer(gb); return;  // jp $058a
}

// 06:4516
void getSpecialObjectGraphicsFrame(GB *gb) {
  I(0x4516, 1); C = A;  // ld c,a
  I(0x4517, 2); B = 0x00;  // ld b,$00
  I(0x4519, 1); D = H;  // ld d,h
  I(0x451a, 2); L = 0x01;  // ld l,$01
  I(0x451c, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x451d, 1); E = A;  // ld e,a
  I(0x451e, 3); SET_HL(0x4451);  // ld hl,$4451
  RST_PUSH(0x4521, 0x4522);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x4522, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4523, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x4524, 1); L = A;  // ld l,a
  I(0x4525, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x4526, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x4527, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x4528, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  PUSH(0x4529, HL);  // push hl
  I(0x452a, 1); alu_add(gb, A);  // add a
  I(0x452b, 1); C = A;  // ld c,a
  I(0x452c, 1); A = E;  // ld a,e
  I(0x452d, 3); SET_HL(0x44a1);  // ld hl,$44a1
  RST_PUSH(0x4530, 0x4531);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x4531, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4532, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x4533, 1); L = A;  // ld l,a
  I(0x4534, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x4535, 2); E = 0x1e;  // ld e,$1e
  I(0x4537, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4538, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4539, 1); E = alu_inc8(gb, E);  // inc e
  I(0x453a, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x453b, 2); alu_and(gb, 0x3f);  // and $3f
  I(0x453d, 2); mem_wr(gb, DE, A);  // ld (de),a
  SET_HL(POP(0x453e));  // pop hl
  I(0x453f, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4540, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x4541, 1); L = A;  // ld l,a
  I(0x4542, 1); alu_or(gb, H);  // or h
  if ((F & FZ)) { RET_TAKEN(0x4543); return; } I(0x4543, 2);  // ret z
  I(0x4544, 1); A = L;  // ld a,l
  I(0x4545, 2); alu_and(gb, 0x01);  // and $01
  I(0x4547, 2); alu_add(gb, 0x1a);  // add $1a
  I(0x4549, 1); C = A;  // ld c,a
  I(0x454a, 1); A = L;  // ld a,l
  I(0x454b, 2); alu_and(gb, 0x1e);  // and $1e
  I(0x454d, 1); A = alu_dec8(gb, A);  // dec a
  I(0x454e, 1); B = A;  // ld b,a
  I(0x454f, 2); L = (uint8_t)(L & ~(1 << 4));  // res 4,l
  I(0x4551, 1); alu_or(gb, D);  // or d
  RET(0x4552); return;  // ret
}

// 06:462d
void getTransformedLinkID(GB *gb) {
  I(0x462d, 3); SET_HL(0xcc56);  // ld hl,$cc56
  I(0x4630, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4631, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x4632, 3); goto L_4637; } I(0x4632, 2);  // jr z,$4637
  I(0x4634, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x4635, 3); goto L_465a;  // jr $465a
L_4637:
  I(0x4637, 4); A = mem_rd(gb, 0xcc34);  // ld a,($cc34)
  I(0x463a, 2); alu_and(gb, 0x60);  // and $60
  if (!(F & FZ)) { I(0x463c, 3); goto L_465a; } I(0x463c, 2);  // jr nz,$465a
  I(0x463e, 4); A = mem_rd(gb, 0xcc02);  // ld a,($cc02)
  I(0x4641, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x4642, 3); goto L_465a; } I(0x4642, 2);  // jr nz,$465a
  I(0x4644, 4); A = mem_rd(gb, 0xccd3);  // ld a,($ccd3)
  I(0x4647, 1); B = A;  // ld b,a
  I(0x4648, 4); A = mem_rd(gb, 0xcc5a);  // ld a,($cc5a)
  I(0x464b, 1); alu_or(gb, B);  // or b
  if (!(F & FZ)) { I(0x464c, 3); goto L_465a; } I(0x464c, 2);  // jr nz,$465a
  I(0x464e, 4); A = mem_rd(gb, 0xc6cb);  // ld a,($c6cb)
  I(0x4651, 1); E = A;  // ld e,a
  I(0x4652, 3); SET_HL(0x465d);  // ld hl,$465d
  CALL(0x4655, lookupKey, 0x1e06, 0x4658);  // call $1e06
  I(0x4658, 1); B = A;  // ld b,a
  RET(0x4659); return;  // ret
L_465a:
  I(0x465a, 2); B = 0x00;  // ld b,$00
  RET(0x465c); return;  // ret
}

// 06:4668
void linkUpdateDamageToApplyForRings(GB *gb) {
  I(0x4668, 2); E = 0x25;  // ld e,$25
  I(0x466a, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x466b, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { RET_TAKEN(0x466c); return; } I(0x466c, 2);  // ret z
  I(0x466d, 1); B = A;  // ld b,a
  I(0x466e, 3); SET_HL(0x46ae);  // ld hl,$46ae
  I(0x4671, 4); A = mem_rd(gb, 0xc6cb);  // ld a,($c6cb)
  I(0x4674, 1); E = A;  // ld e,a
L_4675:
  I(0x4675, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4676, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x4677, 3); goto L_467f; } I(0x4677, 2);  // jr z,$467f
  I(0x4679, 1); alu_cp(gb, E);  // cp e
  if ((F & FZ)) { I(0x467a, 3); goto L_46a2; } I(0x467a, 2);  // jr z,$46a2
  I(0x467c, 2); SET_HL(HL + 1);  // inc hl
  I(0x467d, 3); goto L_4675;  // jr $4675
L_467f:
  I(0x467f, 1); A = E;  // ld a,e
  I(0x4680, 2); alu_cp(gb, 0x08);  // cp $08
  if ((F & FZ)) { I(0x4682, 3); goto L_468f; } I(0x4682, 2);  // jr z,$468f
  I(0x4684, 2); alu_cp(gb, 0x09);  // cp $09
  if ((F & FZ)) { I(0x4686, 3); goto L_4694; } I(0x4686, 2);  // jr z,$4694
  I(0x4688, 2); alu_cp(gb, 0x0a);  // cp $0a
  if (!(F & FZ)) { RET_TAKEN(0x468a); return; } I(0x468a, 2);  // ret nz
  I(0x468b, 1); A = B;  // ld a,b
  I(0x468c, 1); alu_add(gb, A);  // add a
  I(0x468d, 3); goto L_46a4;  // jr $46a4
L_468f:
  I(0x468f, 1); A = B;  // ld a,b
  I(0x4690, 2); A = alu_sra(gb, A);  // sra a
  I(0x4692, 3); goto L_46a4;  // jr $46a4
L_4694:
  I(0x4694, 1); A = B;  // ld a,b
  I(0x4695, 1); alu_cpl(gb);  // cpl
  I(0x4696, 1); A = alu_inc8(gb, A);  // inc a
  I(0x4697, 1); alu_add(gb, A);  // add a
  I(0x4698, 1); alu_add(gb, A);  // add a
  I(0x4699, 1); alu_add(gb, B);  // add b
  I(0x469a, 2); A = alu_sra(gb, A);  // sra a
  I(0x469c, 2); A = alu_sra(gb, A);  // sra a
  I(0x469e, 1); alu_cpl(gb);  // cpl
  I(0x469f, 1); A = alu_inc8(gb, A);  // inc a
  I(0x46a0, 3); goto L_46a4;  // jr $46a4
L_46a2:
  I(0x46a2, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x46a3, 1); alu_add(gb, B);  // add b
L_46a4:
  I(0x46a4, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { I(0x46a6, 3); goto L_46aa; } I(0x46a6, 2);  // jr nz,$46aa
  I(0x46a8, 2); A = 0xff;  // ld a,$ff
L_46aa:
  I(0x46aa, 2); E = 0x25;  // ld e,$25
  I(0x46ac, 2); mem_wr(gb, DE, A);  // ld (de),a
  RET(0x46ad); return;  // ret
}

// 06:563e
void specialObjectCode_minecart_b06(GB *gb) {
  CALL_ASM(0x563e, 0x57dd, 0x5641); /* minecartCreateCollisionItem */  // call $57dd
  I(0x5641, 2); E = 0x04;  // ld e,$04
  I(0x5643, 2); A = mem_rd(gb, DE);  // ld a,(de)
  RST_PUSH(0x5644, 0x5645);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x5649: goto L_5649; case 0x5675: goto L_5675; default: HANDOFF(HL); }
L_5649:
  I(0x5649, 2); A = 0x01;  // ld a,$01
  I(0x564b, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x564c, 3); SET_HL(0x41f7);  // ld hl,$41f7
  I(0x564f, 2); E = 0x05;  // ld e,$05
  CALL_ASM(0x5651, 0x008a, 0x5654); /* interBankCall */  // call $008a
  I(0x5654, 1); H = D;  // ld h,d
  I(0x5655, 2); L = 0x10;  // ld l,$10
  I(0x5657, 3); mem_wr(gb, HL, 0x28);  // ld (hl),$28
  I(0x5659, 2); L = 0x08;  // ld l,$08
  I(0x565b, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  CALL(0x565c, specialObjectSetAnimation, 0x2b0a, 0x565f);  // call $2b0a
  I(0x565f, 1); A = D;  // ld a,d
  I(0x5660, 4); mem_wr(gb, 0xcc2c, A);  // ld ($cc2c),a
  CALL(0x5663, setCameraFocusedObjectToLink, 0x12f0, 0x5666);  // call $12f0
  CALL(0x5666, clearVar3fForParentItems, 0x2c72, 0x5669);  // call $2c72
  CALL(0x5669, clearPegasusSeedCounter, 0x2a85, 0x566c);  // call $2a85
  I(0x566c, 3); SET_HL(0xd00e);  // ld hl,$d00e
  I(0x566f, 1); alu_xor(gb, A);  // xor a
  I(0x5670, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x5671, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x5672, 4); objectSetVisiblec2(gb); return;  // jp $1e45
L_5675:
  I(0x5675, 4); A = mem_rd(gb, 0xc4ab);  // ld a,($c4ab)
  I(0x5678, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x5679); return; } I(0x5679, 2);  // ret nz
  CALL(0x567a, retIfTextIsActive, 0x1859, 0x567d);  // call $1859
  I(0x567d, 4); A = mem_rd(gb, 0xcd00);  // ld a,($cd00)
  I(0x5680, 2); alu_and(gb, 0x0e);  // and $0e
  if (!(F & FZ)) { RET_TAKEN(0x5682); return; } I(0x5682, 2);  // ret nz
  I(0x5683, 4); A = mem_rd(gb, 0xcc8a);  // ld a,($cc8a)
  I(0x5686, 2); alu_and(gb, 0x81);  // and $81
  if (!(F & FZ)) { RET_TAKEN(0x5688); return; } I(0x5688, 2);  // ret nz
  I(0x5689, 3); SET_HL(0xd024);  // ld hl,$d024
  I(0x568c, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) & ~(1 << 7)));  // res 7,(hl)
  I(0x568e, 1); alu_xor(gb, A);  // xor a
  I(0x568f, 2); L = 0x2d;  // ld l,$2d
  I(0x5691, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x5692, 1); H = D;  // ld h,d
  I(0x5693, 2); L = 0x0b;  // ld l,$0b
  I(0x5695, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5696, 1); B = A;  // ld b,a
  I(0x5697, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x5699, 2); alu_cp(gb, 0x08);  // cp $08
  if (!(F & FZ)) { I(0x569b, 3); goto L_56ba; } I(0x569b, 2);  // jr nz,$56ba
  I(0x569d, 1); L = alu_inc8(gb, L);  // inc l
  I(0x569e, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x569f, 1); C = A;  // ld c,a
  I(0x56a0, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x56a2, 2); alu_cp(gb, 0x08);  // cp $08
  if (!(F & FZ)) { I(0x56a4, 3); goto L_56ba; } I(0x56a4, 2);  // jr nz,$56ba
  CALL_ASM(0x56a6, 0x570c, 0x56a9); /* minecartCheckCollisions */  // call $570c
  if ((F & FC)) { I(0x56a9, 3); goto L_56cf; } I(0x56a9, 2);  // jr c,$56cf
  I(0x56ab, 1); H = D;  // ld h,d
  I(0x56ac, 2); L = 0x08;  // ld l,$08
  I(0x56ae, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x56af, 2); A = alu_swap(gb, A);  // swap a
  I(0x56b1, 1); alu_rrca(gb);  // rrca
  I(0x56b2, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if ((F & FZ)) { I(0x56b3, 3); goto L_56ba; } I(0x56b3, 2);  // jr z,$56ba
  I(0x56b5, 2); mem_wr(gb, HL, A); SET_HL(HL - 1);  // ld (hl-),a
  I(0x56b6, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  CALL(0x56b7, specialObjectSetAnimation, 0x2b0a, 0x56ba);  // call $2b0a
L_56ba:
  I(0x56ba, 1); H = D;  // ld h,d
  I(0x56bb, 2); L = 0x35;  // ld l,$35
  I(0x56bd, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x56be, 3); alu_bit(gb, 7, mem_rd(gb, HL));  // bit 7,(hl)
  if ((F & FZ)) { I(0x56c0, 3); goto L_56c9; } I(0x56c0, 2);  // jr z,$56c9
  I(0x56c2, 3); mem_wr(gb, HL, 0x1a);  // ld (hl),$1a
  I(0x56c4, 2); A = 0x80;  // ld a,$80
  CALL(0x56c6, playSound_b00, 0x0c98, 0x56c9);  // call $0c98
L_56c9:
  CALL(0x56c9, objectApplySpeed, 0x201d, 0x56cc);  // call $201d
  I(0x56cc, 4); specialObjectAnimate(gb); return;  // jp $2aef
L_56cf:
  I(0x56cf, 2); E = 0x04;  // ld e,$04
  I(0x56d1, 2); A = 0x02;  // ld a,$02
  I(0x56d3, 2); mem_wr(gb, DE, A);  // ld (de),a
  CALL(0x56d4, clearVar3fForParentItems, 0x2c72, 0x56d7);  // call $2c72
  I(0x56d7, 2); A = 0x81;  // ld a,$81
  I(0x56d9, 4); mem_wr(gb, 0xcc5c, A);  // ld ($cc5c),a
  I(0x56dc, 3); SET_HL(0xd009);  // ld hl,$d009
  I(0x56df, 2); E = 0x09;  // ld e,$09
  I(0x56e1, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x56e2, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x56e3, 2); L = 0x0b;  // ld l,$0b
  I(0x56e5, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x56e6, 2); alu_add(gb, 0x06);  // add $06
  I(0x56e8, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x56e9, 2); L = 0x0f;  // ld l,$0f
  I(0x56eb, 3); mem_wr(gb, HL, 0xfa);  // ld (hl),$fa
  I(0x56ed, 2); L = 0x10;  // ld l,$10
  I(0x56ef, 3); mem_wr(gb, HL, 0x14);  // ld (hl),$14
  I(0x56f1, 2); L = 0x14;  // ld l,$14
  I(0x56f3, 3); mem_wr(gb, HL, 0x40);  // ld (hl),$40
  I(0x56f5, 1); L = alu_inc8(gb, L);  // inc l
  I(0x56f6, 3); mem_wr(gb, HL, 0xfe);  // ld (hl),$fe
  I(0x56f8, 2); L = 0x1a;  // ld l,$1a
  I(0x56fa, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) | (1 << 6)));  // set 6,(hl)
  I(0x56fc, 2); A = 0xd0;  // ld a,$d0
  I(0x56fe, 4); mem_wr(gb, 0xcc2c, A);  // ld ($cc2c),a
  CALL(0x5701, setCameraFocusedObjectToLink, 0x12f0, 0x5704);  // call $12f0
  I(0x5704, 2); B = 0x16;  // ld b,$16
  CALL(0x5706, objectCreateInteractionWithSubid00, 0x24c3, 0x5709);  // call $24c3
  I(0x5709, 4); objectDelete_useActiveObjectType(gb); return;  // jp $21e0
}

// 06:57ef
void specialObjectCode_raft_b06(GB *gb) {
  I(0x57ef, 1); A = D;  // ld a,d
  I(0x57f0, 4); mem_wr(gb, 0xcc96, A);  // ld ($cc96),a
  I(0x57f3, 2); E = 0x04;  // ld e,$04
  I(0x57f5, 2); A = mem_rd(gb, DE);  // ld a,(de)
  RST_PUSH(0x57f6, 0x57f7);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x57ff: goto L_57ff; case 0x5826: goto L_5826; case 0x5917: goto L_5917; case 0x592e: goto L_592e; default: HANDOFF(HL); }
L_57ff:
  I(0x57ff, 3); SET_HL(0x41f7);  // ld hl,$41f7
  I(0x5802, 2); E = 0x05;  // ld e,$05
  CALL_ASM(0x5804, 0x008a, 0x5807); /* interBankCall */  // call $008a
  I(0x5807, 1); alu_xor(gb, A);  // xor a
  CALL(0x5808, specialObjectSetAnimation, 0x2b0a, 0x580b);  // call $2b0a
  CALL(0x580b, itemIncState, 0x23ea, 0x580e);  // call $23ea
  I(0x580e, 2); L = 0x24;  // ld l,$24
  I(0x5810, 2); A = 0x80;  // ld a,$80
  I(0x5812, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x5813, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5814, 2); A = 0x06;  // ld a,$06
  I(0x5816, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x5817, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x5818, 2); L = 0x06;  // ld l,$06
  I(0x581a, 3); mem_wr(gb, HL, 0x0c);  // ld (hl),$0c
  I(0x581c, 1); A = D;  // ld a,d
  I(0x581d, 4); mem_wr(gb, 0xcc2c, A);  // ld ($cc2c),a
  CALL(0x5820, setCameraFocusedObjectToLink, 0x12f0, 0x5823);  // call $12f0
  I(0x5823, 4); goto L_593e;  // jp $593e
L_5826:
  I(0x5826, 4); A = mem_rd(gb, 0xc4ab);  // ld a,($c4ab)
  I(0x5829, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x582a); return; } I(0x582a, 2);  // ret nz
  CALL(0x582b, retIfTextIsActive, 0x1859, 0x582e);  // call $1859
  I(0x582e, 4); A = mem_rd(gb, 0xcd00);  // ld a,($cd00)
  I(0x5831, 2); alu_and(gb, 0x0e);  // and $0e
  if (!(F & FZ)) { RET_TAKEN(0x5833); return; } I(0x5833, 2);  // ret nz
  I(0x5834, 4); A = mem_rd(gb, 0xcc8a);  // ld a,($cc8a)
  I(0x5837, 2); alu_and(gb, 0x81);  // and $81
  if (!(F & FZ)) { RET_TAKEN(0x5839); return; } I(0x5839, 2);  // ret nz
  I(0x583a, 4); A = mem_rd(gb, 0xcc4f);  // ld a,($cc4f)
  I(0x583d, 2); alu_cp(gb, 0x02);  // cp $02
  if ((F & FZ)) { I(0x583f, 3); goto L_5848; } I(0x583f, 2);  // jr z,$5848
  I(0x5841, 4); A = mem_rd(gb, 0xd004);  // ld a,($d004)
  I(0x5844, 2); alu_cp(gb, 0x02);  // cp $02
  if (!(F & FZ)) { I(0x5846, 3); goto L_5856; } I(0x5846, 2);  // jr nz,$5856
L_5848:
  I(0x5848, 3); SET_HL(0xcc21);  // ld hl,$cc21
  I(0x584b, 2); E = 0x0b;  // ld e,$0b
  I(0x584d, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x584e, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x584f, 2); E = 0x0d;  // ld e,$0d
  I(0x5851, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5852, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x5853, 4); objectSetInvisible(gb); return;  // jp $1e7b
L_5856:
  CALL(0x5856, updateCompanionDirectionFromAngle, 0x2b5d, 0x5859);  // call $2b5d
  if ((F & FC)) { I(0x5859, 3); goto L_5860; } I(0x5859, 2);  // jr c,$5860
  CALL(0x585b, specialObjectAnimate, 0x2aef, 0x585e);  // call $2aef
  I(0x585e, 3); goto L_5863;  // jr $5863
L_5860:
  CALL(0x5860, specialObjectSetAnimation, 0x2b0a, 0x5863);  // call $2b0a
L_5863:
  CALL_ASM(0x5863, 0x5952, 0x5866); /* unported */  // call $5952
  CALL_ASM(0x5866, 0x5990, 0x5869); /* unported */  // call $5990
  I(0x5869, 3); SET_HL(0xd02d);  // ld hl,$d02d
  I(0x586c, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x586d, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x586e, 3); goto L_5884; } I(0x586e, 2);  // jr z,$5884
  I(0x5870, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x5871, 1); L = alu_dec8(gb, L);  // dec l
  I(0x5872, 2); C = mem_rd(gb, HL);  // ld c,(hl)
  I(0x5873, 2); B = 0x28;  // ld b,$28
  I(0x5875, 3); SET_HL(0x5d9f);  // ld hl,$5d9f
  I(0x5878, 2); E = 0x05;  // ld e,$05
  CALL_ASM(0x587a, 0x008a, 0x587d); /* interBankCall */  // call $008a
  I(0x587d, 2); A = 0x88;  // ld a,$88
  I(0x587f, 4); mem_wr(gb, 0xcc92, A);  // ld ($cc92),a
  I(0x5882, 3); goto L_58aa;  // jr $58aa
L_5884:
  I(0x5884, 2); E = 0x10;  // ld e,$10
  I(0x5886, 2); A = 0x23;  // ld a,$23
  I(0x5888, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x5889, 2); E = 0x09;  // ld e,$09
  I(0x588b, 4); A = mem_rd(gb, 0xcc2b);  // ld a,($cc2b)
  I(0x588e, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x588f, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { I(0x5891, 3); goto L_58aa; } I(0x5891, 2);  // jr nz,$58aa
  I(0x5893, 4); A = mem_rd(gb, 0xcc61);  // ld a,($cc61)
  I(0x5896, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x5897, 3); goto L_58aa; } I(0x5897, 2);  // jr nz,$58aa
  I(0x5899, 3); SET_HL(0x5d97);  // ld hl,$5d97
  I(0x589c, 2); E = 0x05;  // ld e,$05
  CALL_ASM(0x589e, 0x008a, 0x58a1); /* interBankCall */  // call $008a
  I(0x58a1, 1); A = C;  // ld a,c
  I(0x58a2, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x58a3, 3); goto L_58b3; } I(0x58a3, 2);  // jr z,$58b3
  I(0x58a5, 2); A = 0x08;  // ld a,$08
  I(0x58a7, 4); mem_wr(gb, 0xcc92, A);  // ld ($cc92),a
L_58aa:
  I(0x58aa, 1); H = D;  // ld h,d
  I(0x58ab, 2); L = 0x3e;  // ld l,$3e
  I(0x58ad, 2); A = 0xff;  // ld a,$ff
  I(0x58af, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x58b0, 3); mem_wr(gb, HL, 0x04);  // ld (hl),$04
  RET(0x58b2); return;  // ret
L_58b3:
  I(0x58b3, 1); H = D;  // ld h,d
  I(0x58b4, 2); E = 0x09;  // ld e,$09
  I(0x58b6, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x58b7, 2); L = 0x3e;  // ld l,$3e
  I(0x58b9, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  I(0x58ba, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  if (!(F & FZ)) { RET_TAKEN(0x58bb); return; } I(0x58bb, 2);  // ret nz
  I(0x58bc, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  if (!(F & FZ)) { RET_TAKEN(0x58bd); return; } I(0x58bd, 2);  // ret nz
  I(0x58be, 1); E = alu_dec8(gb, E);  // dec e
  I(0x58bf, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x58c0, 3); SET_HL(0x590f);  // ld hl,$590f
  RST_PUSH(0x58c3, 0x58c4);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x58c4, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x58c5, 2); C = mem_rd(gb, HL);  // ld c,(hl)
  I(0x58c6, 1); H = D;  // ld h,d
  I(0x58c7, 2); L = 0x0b;  // ld l,$0b
  I(0x58c9, 2); alu_add(gb, mem_rd(gb, HL));  // add (hl)
  I(0x58ca, 1); B = A;  // ld b,a
  I(0x58cb, 2); L = 0x0d;  // ld l,$0d
  I(0x58cd, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x58ce, 1); alu_add(gb, C);  // add c
  I(0x58cf, 1); C = A;  // ld c,a
  CALL(0x58d0, getTileAtPosition, 0x1447, 0x58d3);  // call $1447
  I(0x58d3, 2); H = 0xce;  // ld h,$ce
  I(0x58d5, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x58d6, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x58d7, 3); goto L_58dd; } I(0x58d7, 2);  // jr z,$58dd
  I(0x58d9, 2); alu_cp(gb, 0x18);  // cp $18
  if (!(F & FZ)) { I(0x58db, 3); goto L_58aa; } I(0x58db, 2);  // jr nz,$58aa
L_58dd:
  I(0x58dd, 3); SET_HL(0x5ea3);  // ld hl,$5ea3
  I(0x58e0, 2); E = 0x05;  // ld e,$05
  CALL_ASM(0x58e2, 0x008a, 0x58e5); /* interBankCall */  // call $008a
  I(0x58e5, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x58e7, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x58e8, 3); goto L_58aa; } I(0x58e8, 2);  // jr nz,$58aa
  I(0x58ea, 1); A = alu_inc8(gb, A);  // inc a
  I(0x58eb, 4); mem_wr(gb, 0xcc02, A);  // ld ($cc02),a
  I(0x58ee, 2); A = 0x0b;  // ld a,$0b
  I(0x58f0, 4); mem_wr(gb, 0xcc4f, A);  // ld ($cc4f),a
  I(0x58f3, 2); A = 0x0e;  // ld a,$0e
  I(0x58f5, 4); mem_wr(gb, 0xcc51, A);  // ld ($cc51),a
  CALL(0x58f8, itemUpdateAngle, 0x2cf0, 0x58fb);  // call $2cf0
  I(0x58fb, 1); E = L;  // ld e,l
  I(0x58fc, 2); H = 0xd0;  // ld h,$d0
  I(0x58fe, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x58ff, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x5900, 1); E = alu_inc8(gb, E);  // inc e
  I(0x5901, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x5902, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x5903, 1); A = H;  // ld a,h
  I(0x5904, 4); mem_wr(gb, 0xcc2c, A);  // ld ($cc2c),a
  CALL(0x5907, setCameraFocusedObjectToLink, 0x12f0, 0x590a);  // call $12f0
  CALL(0x590a, itemIncState, 0x23ea, 0x590d);  // call $23ea
  I(0x590d, 3); goto L_593e;  // jr $593e
L_5917:
  I(0x5917, 2); A = 0x80;  // ld a,$80
  I(0x5919, 4); mem_wr(gb, 0xcc92, A);  // ld ($cc92),a
  CALL(0x591c, itemDecCounter1, 0x23d6, 0x591f);  // call $23d6
  if (!(F & FZ)) { RET_TAKEN(0x591f); return; } I(0x591f, 2);  // ret nz
  I(0x5920, 1); alu_xor(gb, A);  // xor a
  I(0x5921, 4); mem_wr(gb, 0xcc02, A);  // ld ($cc02),a
  I(0x5924, 2); E = 0x00;  // ld e,$00
  I(0x5926, 1); A = alu_inc8(gb, A);  // inc a
  I(0x5927, 2); mem_wr(gb, DE, A);  // ld (de),a
  CALL(0x5928, updateLinkLocalRespawnPosition, 0x113a, 0x592b);  // call $113a
  CALL(0x592b, itemIncState, 0x23ea, 0x592e);  // call $23ea
L_592e:
  I(0x592e, 3); SET_BC(0xe602);  // ld bc,$e602
  CALL(0x5931, objectCreateInteraction, 0x24c5, 0x5934);  // call $24c5
  if (!(F & FZ)) { RET_TAKEN(0x5934); return; } I(0x5934, 2);  // ret nz
  I(0x5935, 2); E = 0x08;  // ld e,$08
  I(0x5937, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x5938, 2); L = 0x48;  // ld l,$48
  I(0x593a, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x593b, 4); itemDelete(gb); return;  // jp $2ce2
L_593e:
  I(0x593e, 3); SET_BC(0xc638);  // ld bc,$c638
  I(0x5941, 1); H = D;  // ld h,d
  I(0x5942, 2); L = 0x0b;  // ld l,$0b
  I(0x5944, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5945, 2); mem_wr(gb, BC, A);  // ld (bc),a
  I(0x5946, 1); C = alu_inc8(gb, C);  // inc c
  I(0x5947, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5948, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x5949, 2); mem_wr(gb, BC, A);  // ld (bc),a
  I(0x594a, 3); SET_HL(0x467c);  // ld hl,$467c
  I(0x594d, 2); E = 0x05;  // ld e,$05
  I(0x594f, 4); HANDOFF(0x008a); /* interBankCall */  // jp $008a
}

