// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/gen.h"

// 12:5840
void assignRandomPositionToEnemy__afterCall5840(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5840:
  if ((F & FC)) { RET_TAKEN(0x5840); return; } I(0x5840, 2);  // ret c
  I(0x5841, 4); A = mem_rd(gb, 0xcec2);  // ld a,($cec2)
  I(0x5844, 1); C = A;  // ld c,a
  CALL(0x5845, addPositionToPlacedEnemyPositions_hook, 0x5829, 0x5848);  // call $5829
  I(0x5848, 3); A = mem_rd(gb, 0xff91);  // ldh a,($ff91)
  I(0x584a, 1); H = A;  // ld h,a
  I(0x584b, 2); L = 0x8b;  // ld l,$8b
  CALL(0x584d, setShortPosition_paramC_hook, 0x20b9, 0x5850);  // call $20b9
  I(0x5850, 1); alu_xor(gb, A);  // xor a
  RET(0x5851); return;  // ret
}

// 12:566e
void objectDataOp2__afterCall566e(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_566e:
  CALL(0x566e, getFreeInteractionSlot_hook, 0x3aef, 0x5671);  // call $3aef
  if (!(F & FZ)) { I(0x5671, 3); if (hook_enabled_at(gb, 0x567d)) { skipToOpEnd_4byte_hook(gb); return; } HANDOFF(0x567d); } I(0x5671, 2);  // jr nz,$567d
  CALL(0x5673, read2Bytes_hook, 0x580d, 0x5676);  // call $580d
  I(0x5676, 2); L = 0x4b;  // ld l,$4b
  CALL(0x5678, readCoordinates_hook, 0x5814, 0x567b);  // call $5814
  I(0x567b, 3); if (hook_enabled_at(gb, 0x566b)) { objectDataOp2_hook(gb); return; } HANDOFF(0x566b);  // jr $566b
}

// 12:55c9
void parseObjectData__afterCall55c9(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_55c9:
  CALL(0x55c9, generateRandomBuffer_b00_hook, 0x3215, 0x55cc);  // call $3215
L_55cc:
  I(0x55cc, 3); SET_HL(0x4315);  // ld hl,$4315
  I(0x55cf, 2); E = 0x15;  // ld e,$15
  CALL(0x55d1, interBankCall_hook, 0x008a, 0x55d4);  // call $008a
  if (hook_enabled_at(gb, 0x55d4)) { parseGivenObjectData_b12_hook(gb); return; } HANDOFF(0x55d4);  // fallthrough
}

// 12:55cc
void parseObjectData__afterCall55cc(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_55cc:
  I(0x55cc, 3); SET_HL(0x4315);  // ld hl,$4315
  I(0x55cf, 2); E = 0x15;  // ld e,$15
  CALL(0x55d1, interBankCall_hook, 0x008a, 0x55d4);  // call $008a
  if (hook_enabled_at(gb, 0x55d4)) { parseGivenObjectData_b12_hook(gb); return; } HANDOFF(0x55d4);  // fallthrough
}

// 12:579e
void objectDataOp9__afterCall579e(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_579e:
  CALL(0x579e, objectDataOp9__allocateObjectType, 0x57c3, 0x57a1);  // call $57c3
L_57a1:
  if (!(F & FZ)) { I(0x57a1, 3); goto L_57bc; } I(0x57a1, 2);  // jr nz,$57bc
  I(0x57a3, 2); SET_DE(DE + 1);  // inc de
  I(0x57a4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x57a5, 2); SET_DE(DE + 1);  // inc de
  I(0x57a6, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x57a7, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x57a8, 2); SET_DE(DE + 1);  // inc de
  I(0x57a9, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x57aa, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x57ab, 2); SET_DE(DE + 1);  // inc de
  I(0x57ac, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x57ad, 1); A = L;  // ld a,l
  I(0x57ae, 2); alu_and(gb, 0xc0);  // and $c0
  I(0x57b0, 2); alu_add(gb, 0x0b);  // add $0b
  I(0x57b2, 1); L = A;  // ld l,a
  I(0x57b3, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x57b4, 2); SET_DE(DE + 1);  // inc de
  I(0x57b5, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x57b6, 1); L = alu_inc8(gb, L);  // inc l
  I(0x57b7, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x57b8, 2); SET_DE(DE + 1);  // inc de
  I(0x57b9, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x57ba, 3); if (hook_enabled_at(gb, 0x579b)) { objectDataOp9_hook(gb); return; } HANDOFF(0x579b);  // jr $579b
L_57bc:
  I(0x57bc, 2); A = 0x06;  // ld a,$06
  CALL(0x57be, addAToDe_hook, 0x0068, 0x57c1);  // call $0068
  I(0x57c1, 3); if (hook_enabled_at(gb, 0x579b)) { objectDataOp9_hook(gb); return; } HANDOFF(0x579b);  // jr $579b
}

// 12:57a1
void objectDataOp9__afterCall57a1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_57a1:
  if (!(F & FZ)) { I(0x57a1, 3); goto L_57bc; } I(0x57a1, 2);  // jr nz,$57bc
  I(0x57a3, 2); SET_DE(DE + 1);  // inc de
  I(0x57a4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x57a5, 2); SET_DE(DE + 1);  // inc de
  I(0x57a6, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x57a7, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x57a8, 2); SET_DE(DE + 1);  // inc de
  I(0x57a9, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x57aa, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x57ab, 2); SET_DE(DE + 1);  // inc de
  I(0x57ac, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x57ad, 1); A = L;  // ld a,l
  I(0x57ae, 2); alu_and(gb, 0xc0);  // and $c0
  I(0x57b0, 2); alu_add(gb, 0x0b);  // add $0b
  I(0x57b2, 1); L = A;  // ld l,a
  I(0x57b3, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x57b4, 2); SET_DE(DE + 1);  // inc de
  I(0x57b5, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x57b6, 1); L = alu_inc8(gb, L);  // inc l
  I(0x57b7, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x57b8, 2); SET_DE(DE + 1);  // inc de
  I(0x57b9, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x57ba, 3); if (hook_enabled_at(gb, 0x579b)) { objectDataOp9_hook(gb); return; } HANDOFF(0x579b);  // jr $579b
L_57bc:
  I(0x57bc, 2); A = 0x06;  // ld a,$06
  CALL(0x57be, addAToDe_hook, 0x0068, 0x57c1);  // call $0068
  I(0x57c1, 3); if (hook_enabled_at(gb, 0x579b)) { objectDataOp9_hook(gb); return; } HANDOFF(0x579b);  // jr $579b
}

// 12:57c3
void objectDataOp9__allocateObjectType(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_57c3:
  I(0x57c3, 2); A = mem_rd(gb, DE);  // ld a,(de)
  RST_PUSH(0x57c4, 0x57c5);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 12:5656
void objectDataOp1__afterCall5656(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5656:
  CALL(0x5656, getFreeInteractionSlot_hook, 0x3aef, 0x5659);  // call $3aef
  if (!(F & FZ)) { I(0x5659, 3); if (hook_enabled_at(gb, 0x5660)) { skipToOpEnd_2byte_hook(gb); return; } HANDOFF(0x5660); } I(0x5659, 2);  // jr nz,$5660
  CALL(0x565b, read2Bytes_hook, 0x580d, 0x565e);  // call $580d
  I(0x565e, 3); if (hook_enabled_at(gb, 0x5653)) { objectDataOp1_hook(gb); return; } HANDOFF(0x5653);  // jr $5653
}

// 12:5719
void objectDataOp6__afterCall5719(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_5719;
L_56f4:
  I(0x56f4, 2); A = 0x01;  // ld a,$01
  I(0x56f6, 3); mem_wr(gb, 0xff8d, A);  // ldh ($ff8d),a
  I(0x56f8, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x56fa, 2); alu_and(gb, 0x01);  // and $01
  if (!(F & FZ)) { I(0x56fc, 3); goto L_5703; } I(0x56fc, 2);  // jr nz,$5703
  CALL(0x56fe, checkEnemyKilled_hook, 0x5852, 0x5701);  // call $5852
  if (!(F & FC)) { I(0x5701, 3); goto L_572a; } I(0x5701, 2);  // jr nc,$572a
L_5703:
  CALL(0x5703, getFreeEnemySlot_hook, 0x2e27, 0x5706);  // call $2e27
  if (!(F & FZ)) { I(0x5706, 4); if (hook_enabled_at(gb, 0x55d4)) { parseGivenObjectData_b12_hook(gb); return; } HANDOFF(0x55d4); } I(0x5706, 3);  // jp nz,$55d4
  CALL(0x5709, decEnemyCounterIfApplicable_hook, 0x581c, 0x570c);  // call $581c
  I(0x570c, 3); A = mem_rd(gb, 0xff8f);  // ldh a,($ff8f)
  I(0x570e, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x570f, 3); A = mem_rd(gb, 0xff8e);  // ldh a,($ff8e)
  I(0x5711, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x5712, 1); A = H;  // ld a,h
  I(0x5713, 3); mem_wr(gb, 0xff91, A);  // ldh ($ff91),a
  PUSH(0x5715, DE);  // push de
  CALL(0x5716, assignRandomPositionToEnemy_hook, 0x583d, 0x5719);  // call $583d
L_5719:
  SET_DE(POP(0x5719));  // pop de
  I(0x571a, 3); A = mem_rd(gb, 0xff91);  // ldh a,($ff91)
  I(0x571c, 1); H = A;  // ld h,a
  if (!(F & FC)) { I(0x571d, 3); goto L_5725; } I(0x571d, 2);  // jr nc,$5725
  I(0x571f, 2); L = 0x80;  // ld l,$80
  I(0x5721, 3); mem_wr(gb, HL, 0x00);  // ld (hl),$00
  I(0x5723, 3); goto L_572a;  // jr $572a
L_5725:
  I(0x5725, 2); L = 0x80;  // ld l,$80
  I(0x5727, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x5729, 2); mem_wr(gb, HL, A);  // ld (hl),a
L_572a:
  I(0x572a, 3); A = mem_rd(gb, 0xff8c);  // ldh a,($ff8c)
  I(0x572c, 1); A = alu_dec8(gb, A);  // dec a
  I(0x572d, 3); mem_wr(gb, 0xff8c, A);  // ldh ($ff8c),a
  if (!(F & FZ)) { I(0x572f, 3); goto L_56f4; } I(0x572f, 2);  // jr nz,$56f4
  I(0x5731, 4); if (hook_enabled_at(gb, 0x55d4)) { parseGivenObjectData_b12_hook(gb); return; } HANDOFF(0x55d4);  // jp $55d4
}

