// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/gen.h"

// 11:5e51
void label_11_212__afterCall5e51(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_5e51;
L_5e3d:
  I(0x5e3d, 3); mem_wr(gb, 0xffaf, A);  // ldh ($ffaf),a
  I(0x5e3f, 2); E = 0xc0;  // ld e,$c0
  I(0x5e41, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x5e42, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5e43, 3); goto L_5e51; } I(0x5e43, 2);  // jr z,$5e51
  I(0x5e45, 1); alu_rlca(gb);  // rlca
  if ((F & FC)) { I(0x5e46, 3); goto L_5e4e; } I(0x5e46, 2);  // jr c,$5e4e
  I(0x5e48, 2); E = 0xc4;  // ld e,$c4
  I(0x5e4a, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x5e4b, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x5e4c, 3); goto L_5e51; } I(0x5e4c, 2);  // jr nz,$5e51
L_5e4e:
  CALL(0x5e4e, func_11_5e8a_hook, 0x5e8a, 0x5e51);  // call $5e8a
L_5e51:
  I(0x5e51, 1); D = alu_inc8(gb, D);  // inc d
  I(0x5e52, 1); A = D;  // ld a,d
  I(0x5e53, 2); alu_cp(gb, 0xe0);  // cp $e0
  if ((F & FC)) { I(0x5e55, 3); goto L_5e3d; } I(0x5e55, 2);  // jr c,$5e3d
  RET(0x5e57); return;  // ret
}

// 11:5e7e
void updateParts__afterCall5e7e(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_5e7e;
L_5e73:
  I(0x5e73, 3); mem_wr(gb, 0xffaf, A);  // ldh ($ffaf),a
  I(0x5e75, 2); E = 0xc0;  // ld e,$c0
  I(0x5e77, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x5e78, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5e79, 3); goto L_5e83; } I(0x5e79, 2);  // jr z,$5e83
  CALL(0x5e7b, func_11_5e8a_hook, 0x5e8a, 0x5e7e);  // call $5e8a
L_5e7e:
  I(0x5e7e, 1); H = D;  // ld h,d
  I(0x5e7f, 2); L = 0xea;  // ld l,$ea
  I(0x5e81, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) & ~(1 << 7)));  // res 7,(hl)
L_5e83:
  I(0x5e83, 1); D = alu_inc8(gb, D);  // inc d
  I(0x5e84, 1); A = D;  // ld a,d
  I(0x5e85, 2); alu_cp(gb, 0xe0);  // cp $e0
  if ((F & FC)) { I(0x5e87, 3); goto L_5e73; } I(0x5e87, 2);  // jr c,$5e73
  RET(0x5e89); return;  // ret
}

// 11:4064
void partCommon_standardUpdate__afterCall4064(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4064:
  I(0x4064, 2); E = 0xfe;  // ld e,$fe
  I(0x4066, 2); A = 0x08;  // ld a,$08
  I(0x4068, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4069, 2); C = 0x00;  // ld c,$00
  RET(0x406b); return;  // ret
}

// 11:5e8d
void func_11_5e8a__afterCall5e8d(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5e8d:
  I(0x5e8d, 2); E = 0xc1;  // ld e,$c1
  I(0x5e8f, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x5e90, 1); alu_add(gb, A);  // add a
  I(0x5e91, 2); alu_add(gb, 0x9f);  // add $9f
  I(0x5e93, 1); L = A;  // ld l,a
  I(0x5e94, 2); A = 0x00;  // ld a,$00
  I(0x5e96, 2); alu_adc(gb, 0x5e);  // adc $5e
  I(0x5e98, 1); H = A;  // ld h,a
  I(0x5e99, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5e9a, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x5e9b, 1); L = A;  // ld l,a
  I(0x5e9c, 1); A = C;  // ld a,c
  I(0x5e9d, 1); alu_or(gb, A);  // or a
  I(0x5e9e, 1); HANDOFF(HL);  // jp hl
}

// 11:55a6
void partCode27__func_55a6(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_55a6:
  I(0x55a6, 2); E = 0xe1;  // ld e,$e1
  I(0x55a8, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x55a9, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { CALL_ASM(0x55ab, 0x55e7, 0x55ae); /* partCode27@func_55e7 */ } else I(0x55ab, 3);  // call nz,$55e7
  I(0x55ae, 2); E = 0xe1;  // ld e,$e1
  I(0x55b0, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x55b1, 2); alu_and(gb, 0x0e);  // and $0e
  I(0x55b3, 3); SET_HL(0x55da);  // ld hl,$55da
  RST_PUSH(0x55b6, 0x55b7);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x55b7, 2); E = 0xe6;  // ld e,$e6
  I(0x55b9, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x55ba, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x55bb, 1); E = alu_inc8(gb, E);  // inc e
  I(0x55bc, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x55bd, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x55be, 2); E = 0xe1;  // ld e,$e1
  I(0x55c0, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x55c1, 2); alu_and(gb, 0x70);  // and $70
  I(0x55c3, 2); A = alu_swap(gb, A);  // swap a
  I(0x55c5, 3); SET_HL(0x55e2);  // ld hl,$55e2
  RST_PUSH(0x55c8, 0x55c9);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x55c9, 2); E = 0xcf;  // ld e,$cf
  I(0x55cb, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x55cc, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x55cd, 2); E = 0xe1;  // ld e,$e1
  I(0x55cf, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x55d0, 2); alu_bit(gb, 0, A);  // bit 0,a
  if ((F & FZ)) { RET_TAKEN(0x55d2); return; } I(0x55d2, 2);  // ret z
  I(0x55d3, 1); A = alu_dec8(gb, A);  // dec a
  I(0x55d4, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x55d5, 2); A = 0x06;  // ld a,$06
  I(0x55d7, 4); if (hook_enabled_at(gb, 0x24bb)) { setScreenShakeCounter_hook(gb); return; } HANDOFF(0x24bb);  // jp $24bb
}

// 11:4099
void partCommon_checkOutOfBounds__roundAngleToDiagonal(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4099:
  I(0x4099, 2); L = 0xc9;  // ld l,$c9
  I(0x409b, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x409c, 1); E = A;  // ld e,a
  I(0x409d, 2); alu_and(gb, 0x07);  // and $07
  if ((F & FZ)) { RET_TAKEN(0x409f); return; } I(0x409f, 2);  // ret z
  I(0x40a0, 1); A = E;  // ld a,e
  I(0x40a1, 2); alu_and(gb, 0x18);  // and $18
  I(0x40a3, 2); alu_add(gb, 0x04);  // add $04
  I(0x40a5, 1); E = A;  // ld e,a
  RET(0x40a6); return;  // ret
}

// 11:4122
void partCode01__afterCall4122(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4122:
  I(0x4122, 2); E = 0xc4;  // ld e,$c4
  I(0x4124, 2); A = mem_rd(gb, DE);  // ld a,(de)
  RST_PUSH(0x4125, 0x4126);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x412e: goto L_412e; case 0x417b: goto L_417b; case 0x41b4: goto L_41b4; case 0x41d9: goto L_41d9; default: HANDOFF(HL); }
L_412e:
  I(0x412e, 4); A = mem_rd(gb, 0xcdda);  // ld a,($cdda)
  I(0x4131, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x4132, 4); if (hook_enabled_at(gb, 0x3ea1)) { partDelete_hook(gb); return; } HANDOFF(0x3ea1); } I(0x4132, 3);  // jp nz,$3ea1
  I(0x4135, 2); E = 0xc2;  // ld e,$c2
  I(0x4137, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4138, 2); alu_cp(gb, 0x0f);  // cp $0f
  if (!(F & FZ)) { I(0x413a, 3); goto L_4144; } I(0x413a, 2);  // jr nz,$4144
  CALL(0x413c, getRandomNumber_noPreserveVars_hook, 0x0453, 0x413f);  // call $0453
  I(0x413f, 2); alu_cp(gb, 0xe0);  // cp $e0
  if ((F & FC)) { I(0x4141, 4); if (hook_enabled_at(gb, 0x4309)) { itemDrop_spawnEnemy_hook(gb); return; } HANDOFF(0x4309); } I(0x4141, 3);  // jp c,$4309
L_4144:
  CALL(0x4144, itemDrop_initGfx_hook, 0x428e, 0x4147);  // call $428e
  I(0x4147, 1); H = D;  // ld h,d
  I(0x4148, 2); L = 0xd4;  // ld l,$d4
  I(0x414a, 2); A = 0xa0;  // ld a,$a0
  I(0x414c, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x414d, 3); mem_wr(gb, HL, 0xfe);  // ld (hl),$fe
  I(0x414f, 2); L = 0xc4;  // ld l,$c4
  I(0x4151, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x4152, 4); A = mem_rd(gb, 0xcc34);  // ld a,($cc34)
  I(0x4155, 2); alu_and(gb, 0x20);  // and $20
  if ((F & FZ)) { I(0x4157, 3); goto L_416f; } I(0x4157, 2);  // jr z,$416f
  I(0x4159, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x415a, 2); L = 0xe4;  // ld l,$e4
  I(0x415c, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) | (1 << 7)));  // set 7,(hl)
  I(0x415e, 2); L = 0xc6;  // ld l,$c6
  I(0x4160, 3); mem_wr(gb, HL, 0xf0);  // ld (hl),$f0
  CALL(0x4162, objectCheckIsOnHazard_hook, 0x220d, 0x4165);  // call $220d
  if (!(F & FC)) { I(0x4165, 3); goto L_416f; } I(0x4165, 2);  // jr nc,$416f
  I(0x4167, 1); alu_rrca(gb);  // rrca
  if (!(F & FC)) { I(0x4168, 3); goto L_416f; } I(0x4168, 2);  // jr nc,$416f
  I(0x416a, 2); E = 0xf4;  // ld e,$f4
  I(0x416c, 2); A = 0x01;  // ld a,$01
  I(0x416e, 2); mem_wr(gb, DE, A);  // ld (de),a
L_416f:
  I(0x416f, 2); E = 0xc2;  // ld e,$c2
  I(0x4171, 2); A = mem_rd(gb, DE);  // ld a,(de)
  CALL(0x4172, itemDrop_initSpeed_hook, 0x42e8, 0x4175);  // call $42e8
  I(0x4175, 2); E = 0xc2;  // ld e,$c2
  I(0x4177, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4178, 4); if (hook_enabled_at(gb, 0x2988)) { partSetAnimation_hook(gb); return; } HANDOFF(0x2988);  // jp $2988
L_417b:
  CALL(0x417b, partCommon_getTileCollisionInFront_allowHoles_hook, 0x4030, 0x417e);  // call $4030
  if (!(F & FC)) { CALL(0x417e, itemDrop_updateSpeed_hook, 0x4302, 0x4181); } else I(0x417e, 3);  // call nc,$4302
  I(0x4181, 2); C = 0x20;  // ld c,$20
  CALL(0x4183, objectUpdateSpeedZAndBounce_hook, 0x2370, 0x4186);  // call $2370
  if ((F & FC)) { I(0x4186, 3); goto L_418d; } I(0x4186, 2);  // jr c,$418d
  CALL(0x4188, itemDrop_checkHitGround_hook, 0x4365, 0x418b);  // call $4365
  if (!(F & FC)) { I(0x418b, 3); goto L_4198; } I(0x418b, 2);  // jr nc,$4198
L_418d:
  I(0x418d, 1); H = D;  // ld h,d
  I(0x418e, 2); L = 0xc4;  // ld l,$c4
  I(0x4190, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x4191, 2); L = 0xc6;  // ld l,$c6
  I(0x4193, 3); mem_wr(gb, HL, 0xf0);  // ld (hl),$f0
  CALL(0x4195, objectSetVisiblec3_hook, 0x1e4e, 0x4198);  // call $1e4e
L_4198:
  CALL(0x4198, itemDrop_checkOnHazard_hook, 0x4386, 0x419b);  // call $4386
  if ((F & FC)) { RET_TAKEN(0x419b); return; } I(0x419b, 2);  // ret c
  I(0x419c, 2); E = 0xcf;  // ld e,$cf
  I(0x419e, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x419f, 1); alu_rlca(gb);  // rlca
  if ((F & FC)) { RET_TAKEN(0x41a0); return; } I(0x41a0, 2);  // ret c
  I(0x41a1, 3); SET_BC(0x0500);  // ld bc,$0500
  CALL(0x41a4, objectGetRelativeTile_hook, 0x1435, 0x41a7);  // call $1435
  I(0x41a7, 3); SET_HL(0x442c);  // ld hl,$442c
  CALL(0x41aa, lookupCollisionTable_hook, 0x1e1f, 0x41ad);  // call $1e1f
  if (!(F & FC)) { RET_TAKEN(0x41ad); return; } I(0x41ad, 2);  // ret nc
  I(0x41ae, 1); C = A;  // ld c,a
  I(0x41af, 2); B = 0x14;  // ld b,$14
  I(0x41b1, 4); if (hook_enabled_at(gb, 0x441e)) { itemDrop_applySpeed_hook(gb); return; } HANDOFF(0x441e);  // jp $441e
L_41b4:
  CALL(0x41b4, itemDrop_checkSidescrollingConditions_hook, 0x4332, 0x41b7);  // call $4332
  CALL(0x41b7, itemDrop_moveTowardPoint_hook, 0x4401, 0x41ba);  // call $4401
  if ((F & FC)) { I(0x41ba, 4); goto L_41cc; } I(0x41ba, 3);  // jp c,$41cc
  CALL(0x41bd, itemDrop_countdownToDisappear_hook, 0x42c3, 0x41c0);  // call $42c3
  if ((F & FC)) { I(0x41c0, 4); if (hook_enabled_at(gb, 0x3ea1)) { partDelete_hook(gb); return; } HANDOFF(0x3ea1); } I(0x41c0, 3);  // jp c,$3ea1
  I(0x41c3, 2); E = 0xc2;  // ld e,$c2
  I(0x41c5, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x41c6, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x41c7, 3); goto L_4198; } I(0x41c7, 2);  // jr nz,$4198
  I(0x41c9, 4); if (hook_enabled_at(gb, 0x43bf)) { itemDrop_updateFairyMovement_hook(gb); return; } HANDOFF(0x43bf);  // jp $43bf
L_41cc:
  I(0x41cc, 1); H = D;  // ld h,d
  I(0x41cd, 2); L = 0xf1;  // ld l,$f1
  I(0x41cf, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x41d0, 2); C = mem_rd(gb, HL);  // ld c,(hl)
  I(0x41d1, 2); L = 0xcb;  // ld l,$cb
  I(0x41d3, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x41d4, 1); L = alu_inc8(gb, L);  // inc l
  I(0x41d5, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x41d6, 4); if (hook_enabled_at(gb, 0x3ea1)) { partDelete_hook(gb); return; } HANDOFF(0x3ea1);  // jp $3ea1
L_41d9:
  I(0x41d9, 2); E = 0xc5;  // ld e,$c5
  I(0x41db, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x41dc, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { CALL(0x41dd, partCode01__getRelatedObj1ID_hook, 0x41f9, 0x41e0); } else I(0x41dd, 3);  // call z,$41f9
  CALL(0x41e0, objectCheckCollidedWithLink_ignoreZ_hook, 0x1c6f, 0x41e3);  // call $1c6f
  if ((F & FC)) { I(0x41e3, 4); if (hook_enabled_at(gb, 0x4216)) { partCode01__linkCollectedItem_hook(gb); return; } HANDOFF(0x4216); } I(0x41e3, 3);  // jp c,$4216
  I(0x41e6, 2); A = 0x00;  // ld a,$00
  CALL(0x41e8, objectGetRelatedObject1Var_hook, 0x2160, 0x41eb);  // call $2160
  I(0x41eb, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x41ec, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x41ed, 3); goto L_41f6; } I(0x41ed, 2);  // jr z,$41f6
  I(0x41ef, 2); E = 0xf0;  // ld e,$f0
  I(0x41f1, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x41f2, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if ((F & FZ)) { I(0x41f3, 4); if (hook_enabled_at(gb, 0x2274)) { objectTakePosition_hook(gb); return; } HANDOFF(0x2274); } I(0x41f3, 3);  // jp z,$2274
L_41f6:
  I(0x41f6, 4); if (hook_enabled_at(gb, 0x3ea1)) { partDelete_hook(gb); return; } HANDOFF(0x3ea1);  // jp $3ea1
}

// 11:4470
void partCode02__initialize(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4470:
  I(0x4470, 1); A = alu_inc8(gb, A);  // inc a
  I(0x4471, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4472, 2); E = 0xed;  // ld e,$ed
  I(0x4474, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4475, 1); alu_rlca(gb);  // rlca
  I(0x4476, 2); A = 0x01;  // ld a,$01
  if ((F & FC)) { CALL(0x4478, partSetAnimation_hook, 0x2988, 0x447b); } else I(0x4478, 3);  // call c,$2988
  I(0x447b, 4); if (hook_enabled_at(gb, 0x1e69)) { objectSetVisible82_hook(gb); return; } HANDOFF(0x1e69);  // jp $1e69
}

// 11:447e
void partCode02__decCounter2(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_447e:
  I(0x447e, 2); E = 0xc7;  // ld e,$c7
  I(0x4480, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4481, 1); alu_rrca(gb);  // rrca
  if (!(F & FC)) { RET_TAKEN(0x4482); return; } I(0x4482, 2);  // ret nc
  I(0x4483, 4); if (hook_enabled_at(gb, 0x24b3)) { decNumEnemies_hook(gb); return; } HANDOFF(0x24b3);  // jp $24b3
}

// 11:4527
void partCode05__updateTile(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4527:
  I(0x4527, 2); L = 0xf0;  // ld l,$f0
  I(0x4529, 2); C = mem_rd(gb, HL);  // ld c,(hl)
  I(0x452a, 4); A = mem_rd(gb, 0xcc2d);  // ld a,($cc2d)
  I(0x452d, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x452e, 3); goto L_453f; } I(0x452e, 2);  // jr z,$453f
  I(0x4530, 3); SET_HL(0xcdd3);  // ld hl,$cdd3
  I(0x4533, 2); E = 0xc2;  // ld e,$c2
  I(0x4535, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4536, 2); alu_and(gb, mem_rd(gb, HL));  // and (hl)
  I(0x4537, 2); A = 0x0a;  // ld a,$0a
  if ((F & FZ)) { I(0x4539, 3); goto L_453c; } I(0x4539, 2);  // jr z,$453c
  I(0x453b, 1); A = alu_inc8(gb, A);  // inc a
L_453c:
  I(0x453c, 4); if (hook_enabled_at(gb, 0x3a9c)) { setTile_hook(gb); return; } HANDOFF(0x3a9c);  // jp $3a9c
L_453f:
  I(0x453f, 2); A = 0x9f;  // ld a,$9f
  CALL(0x4541, setTile_hook, 0x3a9c, 0x4544);  // call $3a9c
  I(0x4544, 2); B = 0xcf;  // ld b,$cf
  I(0x4546, 1); alu_xor(gb, A);  // xor a
  I(0x4547, 2); mem_wr(gb, BC, A);  // ld (bc),a
  CALL(0x4548, getThisRoomFlags_hook, 0x197d, 0x454b);  // call $197d
  I(0x454b, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) | (1 << 6)));  // set 6,(hl)
  I(0x454d, 4); if (hook_enabled_at(gb, 0x3ea1)) { partDelete_hook(gb); return; } HANDOFF(0x3ea1);  // jp $3ea1
}

// 11:462a
void partCode06__getTileAtRelatedObjPosition(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_462a:
  I(0x462a, 2); A = 0x0b;  // ld a,$0b
  CALL(0x462c, objectGetRelatedObject2Var_hook, 0x2164, 0x462f);  // call $2164
  I(0x462f, 2); B = mem_rd(gb, HL);  // ld b,(hl)
  I(0x4630, 2); L = 0xcd;  // ld l,$cd
  I(0x4632, 2); C = mem_rd(gb, HL);  // ld c,(hl)
  I(0x4633, 4); if (hook_enabled_at(gb, 0x1447)) { getTileAtPosition_hook(gb); return; } HANDOFF(0x1447);  // jp $1447
}

// 11:469a
void partCode07__initialize(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_469a:
  I(0x469a, 1); A = alu_inc8(gb, A);  // inc a
  I(0x469b, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x469c, 2); A = 0x01;  // ld a,$01
  CALL(0x469e, objectGetRelatedObject1Var_hook, 0x2160, 0x46a1);  // call $2160
  I(0x46a1, 2); E = 0xf0;  // ld e,$f0
  I(0x46a3, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x46a4, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x46a5, 4); if (hook_enabled_at(gb, 0x1e72)) { objectSetVisible83_hook(gb); return; } HANDOFF(0x1e72);  // jp $1e72
}

// 11:4704
void partCode08__state0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4704:
  I(0x4704, 1); A = alu_inc8(gb, A);  // inc a
  I(0x4705, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4706, 2); E = 0xc6;  // ld e,$c6
  I(0x4708, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4709, 1); C = A;  // ld c,a
  I(0x470a, 3); SET_HL(0xcf00);  // ld hl,$cf00
  I(0x470d, 2); B = 0xb0;  // ld b,$b0
L_470f:
  I(0x470f, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4710, 2); alu_cp(gb, 0x08);  // cp $08
  if ((F & FZ)) { CALL_ASM(0x4712, 0x46dc, 0x4715); /* partCode08@spawnLightableTorch */ } else I(0x4712, 3);  // call z,$46dc
  I(0x4715, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4716, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x4717, 3); goto L_470f; } I(0x4717, 2);  // jr nz,$470f
  I(0x4719, 2); E = 0xc6;  // ld e,$c6
  I(0x471b, 1); A = C;  // ld a,c
  I(0x471c, 2); mem_wr(gb, DE, A);  // ld (de),a
  CALL(0x471d, objectGetShortPosition_hook, 0x2096, 0x4720);  // call $2096
  I(0x4720, 2); E = 0xcb;  // ld e,$cb
  I(0x4722, 2); mem_wr(gb, DE, A);  // ld (de),a
  RET(0x4723); return;  // ret
}

// 11:47b7
void partCode09__updateTileBeforeDeletion(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_47b7;
L_4796:
  I(0x4796, 2); E = 0xf0;  // ld e,$f0
  I(0x4798, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4799, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x479a); return; } I(0x479a, 2);  // ret nz
  CALL(0x479b, objectGetShortPosition_hook, 0x2096, 0x479e);  // call $2096
  I(0x479e, 1); C = A;  // ld c,a
  I(0x479f, 2); A = 0x0d;  // ld a,$0d
  CALL(0x47a1, setTile_hook, 0x3a9c, 0x47a4);  // call $3a9c
L_47a4:
  I(0x47a4, 2); E = 0xc3;  // ld e,$c3
  I(0x47a6, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x47a7, 3); SET_HL(0xcca0);  // ld hl,$cca0
  CALL(0x47aa, setFlag_hook, 0x020e, 0x47ad);  // call $020e
  I(0x47ad, 2); E = 0xf0;  // ld e,$f0
  I(0x47af, 2); A = 0x01;  // ld a,$01
  I(0x47b1, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x47b2, 2); A = 0x87;  // ld a,$87
  I(0x47b4, 4); if (hook_enabled_at(gb, 0x0c98)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c98);  // jp $0c98
L_47b7:
  CALL(0x47b7, objectGetShortPosition_hook, 0x2096, 0x47ba);  // call $2096
  I(0x47ba, 1); C = A;  // ld c,a
  I(0x47bb, 2); B = 0x0d;  // ld b,$0d
  CALL(0x47bd, setTileInRoomLayoutBuffer_hook, 0x1426, 0x47c0);  // call $1426
  CALL(0x47c0, objectGetTileAtPosition_hook, 0x1444, 0x47c3);  // call $1444
  I(0x47c3, 2); alu_cp(gb, 0x0c);  // cp $0c
  if ((F & FZ)) { I(0x47c5, 3); goto L_4796; } I(0x47c5, 2);  // jr z,$4796
  I(0x47c7, 3); goto L_47a4;  // jr $47a4
}

// 11:47c9
void partCode09__state0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_47c9:
  I(0x47c9, 1); H = D;  // ld h,d
  I(0x47ca, 1); L = E;  // ld l,e
  I(0x47cb, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x47cc, 2); L = 0xc2;  // ld l,$c2
  I(0x47ce, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x47cf, 2); alu_and(gb, 0x07);  // and $07
  I(0x47d1, 2); mem_wr(gb, HL, A); SET_HL(HL - 1);  // ld (hl-),a
  RET(0x47d2); return;  // ret
}

// 11:480c
void partCode0b__afterCall480c(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_480c:
  I(0x480c, 1); H = D;  // ld h,d
  I(0x480d, 2); L = 0xc3;  // ld l,$c3
  I(0x480f, 2); B = 0x01;  // ld b,$01
  I(0x4811, 4); A = mem_rd(gb, 0xcdd2);  // ld a,($cdd2)
  I(0x4814, 2); alu_and(gb, mem_rd(gb, HL));  // and (hl)
  if ((F & FZ)) { I(0x4815, 3); goto L_4818; } I(0x4815, 2);  // jr z,$4818
  I(0x4817, 1); B = alu_inc8(gb, B);  // inc b
L_4818:
  I(0x4818, 1); A = B;  // ld a,b
  I(0x4819, 2); L = 0xdb;  // ld l,$db
  I(0x481b, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x481c, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x481d, 4); if (hook_enabled_at(gb, 0x1e69)) { objectSetVisible82_hook(gb); return; } HANDOFF(0x1e69);  // jp $1e69
}

// 11:48b0
void partCode0c__state0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_48b0:
  I(0x48b0, 1); H = D;  // ld h,d
  I(0x48b1, 1); L = E;  // ld l,e
  I(0x48b2, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x48b3, 2); L = 0xc6;  // ld l,$c6
  I(0x48b5, 3); mem_wr(gb, HL, 0x08);  // ld (hl),$08
  RET(0x48b7); return;  // ret
}

// 11:490b
void partCode0e__spawnCollisionHelper(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_490b:
  CALL(0x490b, getFreePartSlot_hook, 0x3e8e, 0x490e);  // call $3e8e
  if (!(F & FZ)) { RET_TAKEN(0x490e); return; } I(0x490e, 2);  // ret nz
  I(0x490f, 3); mem_wr(gb, HL, 0x0e);  // ld (hl),$0e
  I(0x4911, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4912, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x4913, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4914, 2); mem_wr(gb, HL, C);  // ld (hl),c
  CALL(0x4915, objectCopyPosition_hook, 0x2242, 0x4918);  // call $2242
  I(0x4918, 2); L = 0xc9;  // ld l,$c9
  I(0x491a, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x491b, 2); L = 0xd6;  // ld l,$d6
  I(0x491d, 1); E = L;  // ld e,l
  I(0x491e, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x491f, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x4920, 1); E = alu_inc8(gb, E);  // inc e
  I(0x4921, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4922, 2); mem_wr(gb, HL, A);  // ld (hl),a
  RET(0x4923); return;  // ret
}

// 11:49ef
void partCode0f__setTileHere(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_49ef:
  PUSH(0x49ef, AF);  // push af
  CALL(0x49f0, objectGetShortPosition_hook, 0x2096, 0x49f3);  // call $2096
  I(0x49f3, 1); C = A;  // ld c,a
  SET_AF(POP(0x49f4));  // pop af
  I(0x49f5, 4); if (hook_enabled_at(gb, 0x3a9c)) { setTile_hook(gb); return; } HANDOFF(0x3a9c);  // jp $3a9c
}

// 11:4a8a
void partCode10__giveSeed(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4a8a:
  I(0x4a8a, 2); E = 0xc2;  // ld e,$c2
  I(0x4a8c, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4a8d, 2); alu_add(gb, 0x20);  // add $20
  I(0x4a8f, 4); if (hook_enabled_at(gb, 0x171c)) { giveTreasure_hook(gb); return; } HANDOFF(0x171c);  // jp $171c
}

// 11:4a97
void partCode10__relatedObj2Something(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4a97:
  I(0x4a97, 2); A = 0x00;  // ld a,$00
  CALL(0x4a99, objectGetRelatedObject2Var_hook, 0x2164, 0x4a9c);  // call $2164
  I(0x4a9c, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4a9d, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x4a9e, 3); goto L_4aa6; } I(0x4a9e, 2);  // jr z,$4aa6
  I(0x4aa0, 1); A = L;  // ld a,l
  I(0x4aa1, 2); alu_add(gb, 0x03);  // add $03
  I(0x4aa3, 1); L = A;  // ld l,a
  I(0x4aa4, 3); mem_wr(gb, HL, 0x01);  // ld (hl),$01
L_4aa6:
  I(0x4aa6, 4); if (hook_enabled_at(gb, 0x3ea1)) { partDelete_hook(gb); return; } HANDOFF(0x3ea1);  // jp $3ea1
}

// 11:4c76
void partCode12__state0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4c76:
  I(0x4c76, 1); H = D;  // ld h,d
  I(0x4c77, 1); L = E;  // ld l,e
  I(0x4c78, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x4c79, 2); L = 0xc6;  // ld l,$c6
  I(0x4c7b, 3); mem_wr(gb, HL, 0x3b);  // ld (hl),$3b
  I(0x4c7d, 2); A = 0x01;  // ld a,$01
  CALL(0x4c7f, objectGetRelatedObject1Var_hook, 0x2160, 0x4c82);  // call $2160
  I(0x4c82, 2); E = 0xf0;  // ld e,$f0
  I(0x4c84, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4c85, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4c86, 2); E = 0xf1;  // ld e,$f1
  I(0x4c88, 2); L = 0xa9;  // ld l,$a9
  I(0x4c8a, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4c8b, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4c8c, 3); mem_wr(gb, HL, 0x01);  // ld (hl),$01
  CALL(0x4c8e, objectTakePosition_hook, 0x2274, 0x4c91);  // call $2274
  I(0x4c91, 4); if (hook_enabled_at(gb, 0x1e57)) { objectSetVisible80_hook(gb); return; } HANDOFF(0x1e57);  // jp $1e57
}

// 11:4e6b
void partCode15__afterCall4e6b(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4e6b:
  I(0x4e6b, 4); if (hook_enabled_at(gb, 0x3ea1)) { partDelete_hook(gb); return; } HANDOFF(0x3ea1);  // jp $3ea1
}

// 11:4ec0
void partCode15__setOamData(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4ec0:
  I(0x4ec0, 2); E = 0xc2;  // ld e,$c2
  I(0x4ec2, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4ec3, 1); C = A;  // ld c,a
  I(0x4ec4, 1); alu_add(gb, A);  // add a
  I(0x4ec5, 1); alu_add(gb, C);  // add c
  I(0x4ec6, 3); SET_HL(0x4ed9);  // ld hl,$4ed9
  RST_PUSH(0x4ec9, 0x4eca);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x4eca, 2); E = 0xdd;  // ld e,$dd
  I(0x4ecc, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4ecd, 2); alu_add(gb, mem_rd(gb, HL));  // add (hl)
  I(0x4ece, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4ecf, 2); SET_HL(HL + 1);  // inc hl
  I(0x4ed0, 1); E = alu_dec8(gb, E);  // dec e
  I(0x4ed1, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4ed2, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4ed3, 1); E = alu_dec8(gb, E);  // dec e
  I(0x4ed4, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x4ed5, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4ed6, 4); if (hook_enabled_at(gb, 0x2988)) { partSetAnimation_hook(gb); return; } HANDOFF(0x2988);  // jp $2988
}

// 11:4f03
void partCode15__setDroppedItemPosition(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4f03:
  I(0x4f03, 1); H = D;  // ld h,d
  I(0x4f04, 2); L = 0xcb;  // ld l,$cb
  I(0x4f06, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4f07, 2); alu_cp(gb, 0xf0);  // cp $f0
  if ((F & FC)) { I(0x4f09, 3); goto L_4f0c; } I(0x4f09, 2);  // jr c,$4f0c
  I(0x4f0b, 1); alu_xor(gb, A);  // xor a
L_4f0c:
  I(0x4f0c, 2); alu_cp(gb, 0x20);  // cp $20
  if (!(F & FC)) { I(0x4f0e, 3); goto L_4f14; } I(0x4f0e, 2);  // jr nc,$4f14
  I(0x4f10, 3); mem_wr(gb, HL, 0x20);  // ld (hl),$20
  I(0x4f12, 3); goto L_4f1a;  // jr $4f1a
L_4f14:
  I(0x4f14, 2); alu_cp(gb, 0x78);  // cp $78
  if ((F & FC)) { I(0x4f16, 3); goto L_4f1a; } I(0x4f16, 2);  // jr c,$4f1a
  I(0x4f18, 3); mem_wr(gb, HL, 0x78);  // ld (hl),$78
L_4f1a:
  I(0x4f1a, 2); L = 0xcd;  // ld l,$cd
  I(0x4f1c, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4f1d, 2); alu_cp(gb, 0xf0);  // cp $f0
  if ((F & FC)) { I(0x4f1f, 3); goto L_4f22; } I(0x4f1f, 2);  // jr c,$4f22
  I(0x4f21, 1); alu_xor(gb, A);  // xor a
L_4f22:
  I(0x4f22, 2); alu_cp(gb, 0x08);  // cp $08
  if (!(F & FC)) { I(0x4f24, 3); goto L_4f29; } I(0x4f24, 2);  // jr nc,$4f29
  I(0x4f26, 3); mem_wr(gb, HL, 0x08);  // ld (hl),$08
  RET(0x4f28); return;  // ret
L_4f29:
  I(0x4f29, 2); alu_cp(gb, 0x98);  // cp $98
  if ((F & FC)) { RET_TAKEN(0x4f2b); return; } I(0x4f2b, 2);  // ret c
  I(0x4f2c, 3); mem_wr(gb, HL, 0x98);  // ld (hl),$98
  RET(0x4f2e); return;  // ret
}

// 11:4f2f
void partCode15__moveToMaple(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4f2f:
  I(0x4f2f, 2); L = 0x0b;  // ld l,$0b
  I(0x4f31, 2); B = mem_rd(gb, HL);  // ld b,(hl)
  I(0x4f32, 2); L = 0x0d;  // ld l,$0d
  I(0x4f34, 2); C = mem_rd(gb, HL);  // ld c,(hl)
  PUSH(0x4f35, BC);  // push bc
  CALL(0x4f36, objectGetRelativeAngle_hook, 0x1ea4, 0x4f39);  // call $1ea4
  I(0x4f39, 2); E = 0xc9;  // ld e,$c9
  I(0x4f3b, 2); mem_wr(gb, DE, A);  // ld (de),a
  CALL(0x4f3c, objectApplySpeed_hook, 0x201d, 0x4f3f);  // call $201d
  SET_BC(POP(0x4f3f));  // pop bc
  I(0x4f40, 1); H = D;  // ld h,d
  I(0x4f41, 2); L = 0xcb;  // ld l,$cb
  I(0x4f43, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4f44, 1); alu_cp(gb, B);  // cp b
  if (!(F & FZ)) { RET_TAKEN(0x4f45); return; } I(0x4f45, 2);  // ret nz
  I(0x4f46, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4f47, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4f48, 1); alu_cp(gb, C);  // cp c
  RET(0x4f49); return;  // ret
}

// 11:4fb2
void partCode17__func_4fb2(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4fb2:
  I(0x4fb2, 2); A = 0x01;  // ld a,$01
  CALL(0x4fb4, objectGetRelatedObject1Var_hook, 0x2160, 0x4fb7);  // call $2160
  I(0x4fb7, 2); E = 0xf0;  // ld e,$f0
  I(0x4fb9, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4fba, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  RET(0x4fbb); return;  // ret
}

// 11:5273
void partCode1d__func_5273(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5273:
  I(0x5273, 2); A = 0x01;  // ld a,$01
  CALL(0x5275, objectGetRelatedObject1Var_hook, 0x2160, 0x5278);  // call $2160
  I(0x5278, 2); E = 0xf0;  // ld e,$f0
  I(0x527a, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x527b, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if (!(F & FZ)) { RET_TAKEN(0x527c); return; } I(0x527c, 2);  // ret nz
  I(0x527d, 2); L = 0xb0;  // ld l,$b0
  I(0x527f, 3); alu_bit(gb, 0, mem_rd(gb, HL));  // bit 0,(hl)
  if (!(F & FZ)) { I(0x5281, 3); goto L_5294; } I(0x5281, 2);  // jr nz,$5294
  I(0x5283, 2); L = 0xa9;  // ld l,$a9
  I(0x5285, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x5286, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5287, 3); goto L_5294; } I(0x5287, 2);  // jr z,$5294
  I(0x5289, 2); L = 0xae;  // ld l,$ae
  I(0x528b, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x528c, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x528d, 3); goto L_5294; } I(0x528d, 2);  // jr nz,$5294
  I(0x528f, 2); L = 0xbf;  // ld l,$bf
  I(0x5291, 3); alu_bit(gb, 1, mem_rd(gb, HL));  // bit 1,(hl)
  if ((F & FZ)) { RET_TAKEN(0x5293); return; } I(0x5293, 2);  // ret z
L_5294:
  I(0x5294, 2); E = 0xe4;  // ld e,$e4
  I(0x5296, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x5297, 2); A = (uint8_t)(A & ~(1 << 7));  // res 7,a
  I(0x5299, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x529a, 1); alu_xor(gb, A);  // xor a
  RET(0x529b); return;  // ret
}

// 11:56b3
void partCode28__afterCall56b3(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_56b3:
  I(0x56b3, 4); if (hook_enabled_at(gb, 0x3ea1)) { partDelete_hook(gb); return; } HANDOFF(0x3ea1);  // jp $3ea1
}

// 11:585c
void spikedBall_chain__afterCall585c(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_585c:
  I(0x585c, 2); L = 0xd7;  // ld l,$d7
  I(0x585e, 2); B = mem_rd(gb, HL);  // ld b,(hl)
  I(0x585f, 4); if (hook_enabled_at(gb, 0x57da)) { spikedBall_updatePosition_hook(gb); return; } HANDOFF(0x57da);  // jp $57da
}

// 11:5d31
void partCode52__func_5d31(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5d31:
  CALL(0x5d31, getFreePartSlot_hook, 0x3e8e, 0x5d34);  // call $3e8e
  if (!(F & FZ)) { RET_TAKEN(0x5d34); return; } I(0x5d34, 2);  // ret nz
  I(0x5d35, 3); mem_wr(gb, HL, 0x52);  // ld (hl),$52
  I(0x5d37, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5d38, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x5d39, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5d3a, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x5d3b, 2); L = 0xc9;  // ld l,$c9
  I(0x5d3d, 1); E = L;  // ld e,l
  I(0x5d3e, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x5d3f, 1); alu_add(gb, B);  // add b
  I(0x5d40, 2); alu_and(gb, 0x1f);  // and $1f
  I(0x5d42, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x5d43, 4); if (hook_enabled_at(gb, 0x2242)) { objectCopyPosition_hook(gb); return; } HANDOFF(0x2242);  // jp $2242
}

// 11:64fd
void partCode33__subid0_state0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_64fd:
  I(0x64fd, 1); C = B;  // ld c,b
  I(0x64fe, 2); C = alu_rlc(gb, C);  // rlc c
  I(0x6500, 2); A = 0x01;  // ld a,$01
  if (!(F & FC)) { I(0x6502, 3); goto L_6506; } I(0x6502, 2);  // jr nc,$6506
  I(0x6504, 2); A = 0xff;  // ld a,$ff
L_6506:
  I(0x6506, 1); H = D;  // ld h,d
  I(0x6507, 2); L = 0xf1;  // ld l,$f1
  I(0x6509, 2); mem_wr(gb, HL, A); SET_HL(HL - 1);  // ld (hl-),a
  I(0x650a, 2); C = alu_rlc(gb, C);  // rlc c
  I(0x650c, 2); A = 0x3c;  // ld a,$3c
  if (!(F & FC)) { I(0x650e, 3); goto L_6511; } I(0x650e, 2);  // jr nc,$6511
  I(0x6510, 1); alu_add(gb, A);  // add a
L_6511:
  I(0x6511, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x6512, 2); L = 0xc6;  // ld l,$c6
  I(0x6514, 2); mem_wr(gb, HL, A);  // ld (hl),a
L_6515:
  I(0x6515, 1); A = B;  // ld a,b
  I(0x6516, 1); alu_rrca(gb);  // rrca
  I(0x6517, 1); alu_rrca(gb);  // rrca
  I(0x6518, 2); alu_and(gb, 0x03);  // and $03
  I(0x651a, 2); E = 0xc8;  // ld e,$c8
  I(0x651c, 2); mem_wr(gb, DE, A);  // ld (de),a
  CALL(0x651d, partCode33__func_6588, 0x6588, 0x6520);  // call $6588
  CALL(0x6520, objectMakeTileSolid_hook, 0x20b2, 0x6523);  // call $20b2
  I(0x6523, 2); H = 0xcf;  // ld h,$cf
  I(0x6525, 3); mem_wr(gb, HL, 0x0a);  // ld (hl),$0a
  CALL(0x6527, objectSetVisible83_hook, 0x1e72, 0x652a);  // call $1e72
  CALL(0x652a, getFreePartSlot_hook, 0x3e8e, 0x652d);  // call $3e8e
  if (!(F & FZ)) { RET_TAKEN(0x652d); return; } I(0x652d, 2);  // ret nz
  I(0x652e, 3); mem_wr(gb, HL, 0x33);  // ld (hl),$33
  I(0x6530, 1); L = alu_inc8(gb, L);  // inc l
  I(0x6531, 3); mem_wr(gb, HL, 0x03);  // ld (hl),$03
  I(0x6533, 2); L = 0xd6;  // ld l,$d6
  I(0x6535, 2); A = 0xc0;  // ld a,$c0
  I(0x6537, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x6538, 2); mem_wr(gb, HL, D);  // ld (hl),d
  I(0x6539, 1); H = D;  // ld h,d
  I(0x653a, 2); L = 0xc4;  // ld l,$c4
  I(0x653c, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  RET(0x653d); return;  // ret
}

// 11:6515
void partCode33__func_6515(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6515:
  I(0x6515, 1); A = B;  // ld a,b
  I(0x6516, 1); alu_rrca(gb);  // rrca
  I(0x6517, 1); alu_rrca(gb);  // rrca
  I(0x6518, 2); alu_and(gb, 0x03);  // and $03
  I(0x651a, 2); E = 0xc8;  // ld e,$c8
  I(0x651c, 2); mem_wr(gb, DE, A);  // ld (de),a
  CALL(0x651d, partCode33__func_6588, 0x6588, 0x6520);  // call $6588
  CALL(0x6520, objectMakeTileSolid_hook, 0x20b2, 0x6523);  // call $20b2
  I(0x6523, 2); H = 0xcf;  // ld h,$cf
  I(0x6525, 3); mem_wr(gb, HL, 0x0a);  // ld (hl),$0a
  CALL(0x6527, objectSetVisible83_hook, 0x1e72, 0x652a);  // call $1e72
  CALL(0x652a, getFreePartSlot_hook, 0x3e8e, 0x652d);  // call $3e8e
  if (!(F & FZ)) { RET_TAKEN(0x652d); return; } I(0x652d, 2);  // ret nz
  I(0x652e, 3); mem_wr(gb, HL, 0x33);  // ld (hl),$33
  I(0x6530, 1); L = alu_inc8(gb, L);  // inc l
  I(0x6531, 3); mem_wr(gb, HL, 0x03);  // ld (hl),$03
  I(0x6533, 2); L = 0xd6;  // ld l,$d6
  I(0x6535, 2); A = 0xc0;  // ld a,$c0
  I(0x6537, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x6538, 2); mem_wr(gb, HL, D);  // ld (hl),d
  I(0x6539, 1); H = D;  // ld h,d
  I(0x653a, 2); L = 0xc4;  // ld l,$c4
  I(0x653c, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  RET(0x653d); return;  // ret
}

// 11:6551
void partCode33__func_6551(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6551:
  I(0x6551, 2); E = 0xc2;  // ld e,$c2
  I(0x6553, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6554, 2); alu_bit(gb, 4, A);  // bit 4,a
  I(0x6556, 3); SET_HL(0xcdd2);  // ld hl,$cdd2
  if ((F & FZ)) { I(0x6559, 3); goto L_655e; } I(0x6559, 2);  // jr z,$655e
  I(0x655b, 3); SET_HL(0xcca0);  // ld hl,$cca0
L_655e:
  I(0x655e, 2); E = 0xd8;  // ld e,$d8
  I(0x6560, 1); A = L;  // ld a,l
  I(0x6561, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6562, 1); E = alu_inc8(gb, E);  // inc e
  I(0x6563, 1); A = H;  // ld a,h
  I(0x6564, 2); mem_wr(gb, DE, A);  // ld (de),a
  RET(0x6565); return;  // ret
}

// 11:6588
void partCode33__func_6588(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6588:
  I(0x6588, 1); B = A;  // ld b,a
  I(0x6589, 3); SET_HL(0x6598);  // ld hl,$6598
  RST_PUSH(0x658c, 0x658d);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x658d, 2); E = 0xe6;  // ld e,$e6
  I(0x658f, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6590, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6591, 1); E = alu_inc8(gb, E);  // inc e
  I(0x6592, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x6593, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6594, 1); A = B;  // ld a,b
  I(0x6595, 4); if (hook_enabled_at(gb, 0x2988)) { partSetAnimation_hook(gb); return; } HANDOFF(0x2988);  // jp $2988
}

// 11:6731
void partCode35__state0func_6731(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6731:
  I(0x6731, 2); A = 0x01;  // ld a,$01
  I(0x6733, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6734, 2); E = 0xcf;  // ld e,$cf
  I(0x6736, 2); A = 0x81;  // ld a,$81
  I(0x6738, 2); mem_wr(gb, DE, A);  // ld (de),a
  RET(0x6739); return;  // ret
}

// 11:68d7
void partCode35__state4func_68d7(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_68d7:
  CALL(0x68d7, func_693b_hook, 0x693b, 0x68da);  // call $693b
  I(0x68da, 1); H = D;  // ld h,d
  I(0x68db, 2); L = 0xcb;  // ld l,$cb
  I(0x68dd, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x68de, 2); L = 0xcd;  // ld l,$cd
  I(0x68e0, 2); mem_wr(gb, HL, C);  // ld (hl),c
  RET(0x68e1); return;  // ret
}

// 11:6b00
void partCode38__func_6b00(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6b00:
  I(0x6b00, 1); alu_scf(gb);  // scf
  PUSH(0x6b01, AF);  // push af
  I(0x6b02, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x6b03, 2); alu_cp(gb, 0x0f);  // cp $0f
  if ((F & FZ)) { I(0x6b05, 3); goto L_6b0a; } I(0x6b05, 2);  // jr z,$6b0a
  SET_AF(POP(0x6b07));  // pop af
  I(0x6b08, 1); alu_ccf(gb);  // ccf
  RET(0x6b09); return;  // ret
L_6b0a:
  SET_AF(POP(0x6b0a));  // pop af
  RET(0x6b0b); return;  // ret
}

// 11:6d22
void partCode3a__func_6d22(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6d22:
  CALL(0x6d22, getFreePartSlot_hook, 0x3e8e, 0x6d25);  // call $3e8e
  I(0x6d25, 3); mem_wr(gb, HL, 0x3a);  // ld (hl),$3a
  I(0x6d27, 1); L = alu_inc8(gb, L);  // inc l
  I(0x6d28, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x6d29, 1); L = alu_inc8(gb, L);  // inc l
  I(0x6d2a, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x6d2b, 2); L = 0xc9;  // ld l,$c9
  I(0x6d2d, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x6d2e, 2); L = 0xd6;  // ld l,$d6
  I(0x6d30, 1); E = L;  // ld e,l
  I(0x6d31, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6d32, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x6d33, 1); E = alu_inc8(gb, E);  // inc e
  I(0x6d34, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6d35, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x6d36, 4); if (hook_enabled_at(gb, 0x2242)) { objectCopyPosition_hook(gb); return; } HANDOFF(0x2242);  // jp $2242
}

// 11:756c
void partCode45__bounceRandomlyDownwards(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_756c:
  I(0x756c, 2); L = 0xd4;  // ld l,$d4
  I(0x756e, 2); A = 0x60;  // ld a,$60
  I(0x7570, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x7571, 3); mem_wr(gb, HL, 0xfe);  // ld (hl),$fe
L_7573:
  CALL(0x7573, getRandomNumber_noPreserveVars_hook, 0x0453, 0x7576);  // call $0453
  I(0x7576, 2); alu_and(gb, 0x07);  // and $07
  I(0x7578, 2); alu_cp(gb, 0x07);  // cp $07
  if (!(F & FC)) { I(0x757a, 3); goto L_7573; } I(0x757a, 2);  // jr nc,$7573
  I(0x757c, 2); alu_sub(gb, 0x03);  // sub $03
  I(0x757e, 2); alu_add(gb, 0x10);  // add $10
  I(0x7580, 2); E = 0xc9;  // ld e,$c9
  I(0x7582, 2); mem_wr(gb, DE, A);  // ld (de),a
  CALL(0x7583, objectSetVisiblec1_hook, 0x1e3c, 0x7586);  // call $1e3c
  I(0x7586, 2); A = 0xb3;  // ld a,$b3
  I(0x7588, 4); if (hook_enabled_at(gb, 0x0c98)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c98);  // jp $0c98
}

// 11:7db7
void partCode57__func_7db7(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_7db7:
  I(0x7db7, 2); E = 0xf0;  // ld e,$f0
  I(0x7db9, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x7dba, 1); C = A;  // ld c,a
  I(0x7dbb, 2); B = 0xcf;  // ld b,$cf
  I(0x7dbd, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x7dbe, 2); alu_sub(gb, 0x02);  // sub $02
  I(0x7dc0, 2); alu_cp(gb, 0x03);  // cp $03
  if ((F & FC)) { RET_TAKEN(0x7dc2); return; } I(0x7dc2, 2);  // ret c
  I(0x7dc3, 1); A = L;  // ld a,l
  I(0x7dc4, 4); if (hook_enabled_at(gb, 0x3a9c)) { setTile_hook(gb); return; } HANDOFF(0x3a9c);  // jp $3a9c
}

// 11:7ef4
void partCode59__afterCall7ef4(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_7ef4:
  I(0x7ef4, 1); H = D;  // ld h,d
  I(0x7ef5, 2); L = 0xc4;  // ld l,$c4
  I(0x7ef7, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x7ef8, 1); A = B;  // ld a,b
  I(0x7ef9, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x7efa, 3); goto L_7f2d; } I(0x7efa, 2);  // jr nz,$7f2d
  I(0x7efc, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x7efd, 2); L = 0xc6;  // ld l,$c6
  I(0x7eff, 3); mem_wr(gb, HL, 0x10);  // ld (hl),$10
  I(0x7f01, 3); goto L_7f2d;  // jr $7f2d
L_7f2d:
  I(0x7f2d, 4); if (hook_enabled_at(gb, 0x2978)) { partAnimate_hook(gb); return; } HANDOFF(0x2978);  // jp $2978
}

// 11:423f
void partCode01__linkCollectedItem__afterCall423f(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_423f:
  I(0x423f, 2); E = 0xc2;  // ld e,$c2
  I(0x4241, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x4242, 2); alu_cp(gb, 0x0e);  // cp $0e
  if (!(F & FZ)) { I(0x4244, 3); goto L_424b; } I(0x4244, 2);  // jr nz,$424b
  CALL(0x4246, getThisRoomFlags_hook, 0x197d, 0x4249);  // call $197d
  I(0x4249, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) | (1 << 5)));  // set 5,(hl)
L_424b:
  I(0x424b, 4); if (hook_enabled_at(gb, 0x3ea1)) { partDelete_hook(gb); return; } HANDOFF(0x3ea1);  // jp $3ea1
}

// 11:46dc
void partCode08__spawnLightableTorch(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_46dc:
  PUSH(0x46dc, HL);  // push hl
  PUSH(0x46dd, BC);  // push bc
  I(0x46de, 1); C = L;  // ld c,l
  CALL(0x46df, getFreePartSlot_hook, 0x3e8e, 0x46e2);  // call $3e8e
  if (!(F & FZ)) { I(0x46e2, 3); goto L_4700; } I(0x46e2, 2);  // jr nz,$4700
  I(0x46e4, 3); mem_wr(gb, HL, 0x06);  // ld (hl),$06
  I(0x46e6, 1); L = alu_inc8(gb, L);  // inc l
  I(0x46e7, 1); E = L;  // ld e,l
  I(0x46e8, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x46e9, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x46ea, 2); E = 0xcb;  // ld e,$cb
  I(0x46ec, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x46ed, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x46ef, 1); L = A;  // ld l,a
  I(0x46f0, 2); E = 0xcd;  // ld e,$cd
  I(0x46f2, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x46f3, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x46f5, 2); A = alu_swap(gb, A);  // swap a
  I(0x46f7, 1); alu_or(gb, L);  // or l
  I(0x46f8, 2); L = 0xc7;  // ld l,$c7
  I(0x46fa, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x46fb, 2); L = 0xcb;  // ld l,$cb
  CALL(0x46fd, setShortPosition_paramC_hook, 0x20b9, 0x4700);  // call $20b9
L_4700:
  SET_BC(POP(0x4700));  // pop bc
  SET_HL(POP(0x4701));  // pop hl
  I(0x4702, 1); C = alu_inc8(gb, C);  // inc c
  RET(0x4703); return;  // ret
}

// 11:55e7
void partCode27__func_55e7(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_55e7:
  I(0x55e7, 2); A = (uint8_t)(A & ~(1 << 7));  // res 7,a
  I(0x55e9, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x55ea, 2); alu_and(gb, 0x0e);  // and $0e
  I(0x55ec, 2); alu_sub(gb, 0x02);  // sub $02
  I(0x55ee, 1); B = A;  // ld b,a
  I(0x55ef, 2); E = 0xf0;  // ld e,$f0
  I(0x55f1, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x55f2, 1); alu_add(gb, B);  // add b
  I(0x55f3, 3); SET_HL(0x5603);  // ld hl,$5603
  RST_PUSH(0x55f6, 0x55f7);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x55f7, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x55f8, 2); C = mem_rd(gb, HL);  // ld c,(hl)
  I(0x55f9, 1); B = A;  // ld b,a
  CALL(0x55fa, getFreeInteractionSlot_hook, 0x3aef, 0x55fd);  // call $3aef
  if (!(F & FZ)) { RET_TAKEN(0x55fd); return; } I(0x55fd, 2);  // ret nz
  I(0x55fe, 3); mem_wr(gb, HL, 0x08);  // ld (hl),$08
  I(0x5600, 4); if (hook_enabled_at(gb, 0x225a)) { objectCopyPositionWithOffset_hook(gb); return; } HANDOFF(0x225a);  // jp $225a
}

