#include "game/game.h"
#include "game/gen.h"

#undef CYC
#undef CYCT
#define CYC(from,to) burn_rom(gb,SYMBANK(interactionCodec5),(from),(to),false)
#define CYCT(from,to) burn_rom(gb,SYMBANK(interactionCodec5),(from),(to),true)

static uint16_t harp_jump_table(GB *gb) {
  burn_rom(gb,0,0,1,false); alu_add(gb,A); burn_rom(gb,0,1,2,false); SET_HL(pop_effect(gb)); burn_rom(gb,0,2,3,false); alu_add(gb,L); burn_rom(gb,0,3,4,false); L=A;
  if(F&FC){burn_rom(gb,0,4,6,false);burn_rom(gb,0,6,7,false);H=alu_inc8(gb,H);}else burn_rom(gb,0,4,6,true);
  burn_rom(gb,0,7,8,false);A=mem_rd(gb,HL);SET_HL(HL+1);burn_rom(gb,0,8,9,false);H=mem_rd(gb,HL);burn_rom(gb,0,9,10,false);L=A;burn_rom(gb,0,10,11,false);return HL;
}
static void harp_add_a(GB *gb,uint16_t ra){push_effect(gb,ra);burn_rom(gb,0,0x10,0x11,false);alu_add(gb,L);burn_rom(gb,0,0x11,0x12,false);L=A;if(!(F&FC)){burn_rom(gb,0,0x12,0x13,true);ret_effect(gb);return;}burn_rom(gb,0,0x12,0x13,false);burn_rom(gb,0,0x13,0x14,false);H=alu_inc8(gb,H);burn_rom(gb,0,0x14,0x15,false);ret_effect(gb);}
void interactionCodec5_hook(GB *gb){uint16_t sp0_=gb->sp;CYC(SYM(interactionCodec5),(SYM(interactionCodec5) + 2));E=INTERACTION_BASE+OBJ_STATE;CYC((SYM(interactionCodec5) + 2),(SYM(interactionCodec5) + 3));A=mem_rd(gb,DE);CYC((SYM(interactionCodec5) + 3),(SYM(interactionCodec5) + 4));push_effect(gb,(SYM(interactionCodec5) + 4));do { uint16_t jt_ = (harp_jump_table(gb));
  if (jt_ == SYM(interactionCodec5__state0)) { CALL_C(SYM(interactionCodec5__state0),setLinkForceStateToState08_hook,SYM(setLinkForceStateToState08),(SYM(interactionCodec5__state0) + 3));CYC((SYM(interactionCodec5__state0) + 3),(SYM(interactionCodec5__state0) + 6));SET_HL(w1Link_yh);CALL_C((SYM(interactionCodec5__state0) + 6),objectTakePosition_hook,SYM(objectTakePosition),(SYM(interactionCodec5__state0) + 9));CYC((SYM(interactionCodec5__state0) + 9),(SYM(interactionCodec5__state0) + 11));E=0x46;CYC((SYM(interactionCodec5__state0) + 11),(SYM(interactionCodec5__state0) + 13));A=4;CYC((SYM(interactionCodec5__state0) + 13),(SYM(interactionCodec5__state0) + 14));mem_wr(gb,DE,A);CYC((SYM(interactionCodec5__state0) + 14),SYM(interactionCodec5__state1));interactionIncState_hook(gb);return; }
  else if (jt_ == SYM(interactionCodec5__state1)) { CALL_C(SYM(interactionCodec5__state1),interactionDecCounter1_hook,SYM(interactionDecCounter1),(SYM(interactionCodec5__state1) + 3));if(!(F&FZ)){CYCT((SYM(interactionCodec5__state1) + 3),(SYM(interactionCodec5__state1) + 4));ret_effect(gb);return;}CYC((SYM(interactionCodec5__state1) + 3),(SYM(interactionCodec5__state1) + 4));CYC((SYM(interactionCodec5__state1) + 4),(SYM(interactionCodec5__state1) + 6));mem_wr(gb,HL,52);CYC((SYM(interactionCodec5__state1) + 6),(SYM(interactionCodec5__state1) + 8));A=0x1e;CYC((SYM(interactionCodec5__state1) + 8),(SYM(interactionCodec5__state1) + 11));W8(wcc50)=A;CALL_C((SYM(interactionCodec5__state1) + 11),interactionIncState_hook,SYM(interactionIncState),(SYM(interactionCodec5__state1) + 14));CYC((SYM(interactionCodec5__state1) + 14),(SYM(interactionCodec5__state1) + 16));E=0x42;CYC((SYM(interactionCodec5__state1) + 16),(SYM(interactionCodec5__state1) + 17));A=mem_rd(gb,DE);CYC((SYM(interactionCodec5__state1) + 17),(SYM(interactionCodec5__state1) + 20));SET_HL(SYM(interactionCodec5__sounds));CYC((SYM(interactionCodec5__state1) + 20),(SYM(interactionCodec5__state1) + 21));harp_add_a(gb,(SYM(interactionCodec5__state1) + 21));CYC((SYM(interactionCodec5__state1) + 21),(SYM(interactionCodec5__state1) + 22));A=mem_rd(gb,HL);CYC((SYM(interactionCodec5__state1) + 22),SYM(interactionCodec5__sounds));playSound_b00_hook(gb);return; }
  else if (jt_ == SYM(interactionCodec5__state2) || jt_ == SYM(interactionCodec5__state3)) { {bool right=HL==SYM(interactionCodec5__state3);uint16_t a=right?SYM(interactionCodec5__state3):SYM(interactionCodec5__state2);CYC(a,a+3);A=W8(wFrameCounter);CYC(a+3,a+5);alu_and(gb,0x1f);if(!(F&FZ)){CYCT(a+5,right?SYM(interactionCodec5__stateCommon):(SYM(interactionCodec5__state2) + 7));goto common;}CYC(a+5,right?SYM(interactionCodec5__stateCommon):(SYM(interactionCodec5__state2) + 7));CYC(right?(SYM(interactionCodec5__state3) + 7):(SYM(interactionCodec5__state2) + 7),right?(SYM(interactionCodec5__state3) + 9):(SYM(interactionCodec5__state2) + 8));A=right?1:0;CYC(right?(SYM(interactionCodec5__state3) + 9):(SYM(interactionCodec5__state2) + 8),right?(SYM(interactionCodec5__state3) + 12):(SYM(interactionCodec5__state2) + 11));SET_BC(right?0xf808:0xf8f8);CALL_C(right?(SYM(interactionCodec5__state3) + 12):(SYM(interactionCodec5__state2) + 11),objectCreateFloatingMusicNote_hook,SYM(objectCreateFloatingMusicNote),right?(SYM(interactionCodec5__state3) + 15):SYM(interactionCodec5__stateCommon));if(right)CYC((SYM(interactionCodec5__state3) + 15),SYM(interactionCodec5__stateCommon));common:CYC(SYM(interactionCodec5__stateCommon),(SYM(interactionCodec5__stateCommon) + 1));push_effect(gb,DE);CYC((SYM(interactionCodec5__stateCommon) + 1),(SYM(interactionCodec5__stateCommon) + 4));SET_DE(w1Link);CYC((SYM(interactionCodec5__stateCommon) + 4),(SYM(interactionCodec5__stateCommon) + 7));SET_HL(SYM(specialObjectAnimate));CYC((SYM(interactionCodec5__stateCommon) + 7),(SYM(interactionCodec5__stateCommon) + 9));E=0;CALL_C((SYM(interactionCodec5__stateCommon) + 9),interBankCall_hook,0x008a,(SYM(interactionCodec5__stateCommon) + 12));CYC((SYM(interactionCodec5__stateCommon) + 12),(SYM(interactionCodec5__stateCommon) + 13));SET_DE(pop_effect(gb));CALL_C((SYM(interactionCodec5__stateCommon) + 13),interactionDecCounter1_hook,SYM(interactionDecCounter1),(SYM(interactionCodec5__stateCommon) + 16));if(!(F&FZ)){CYCT((SYM(interactionCodec5__stateCommon) + 16),(SYM(interactionCodec5__stateCommon) + 17));ret_effect(gb);return;}CYC((SYM(interactionCodec5__stateCommon) + 16),(SYM(interactionCodec5__stateCommon) + 17));CYC((SYM(interactionCodec5__stateCommon) + 17),(SYM(interactionCodec5__stateCommon) + 19));mem_wr(gb,HL,52);CYC((SYM(interactionCodec5__stateCommon) + 19),SYM(interactionCodec5__state3));interactionIncState_hook(gb);return;} }
  else if (jt_ == SYM(interactionCodec5__state6)) { CYC(SYM(interactionCodec5__state6),(SYM(interactionCodec5__state6) + 3));SET_HL(wTmpcfc0_genericCutscene_state);CYC((SYM(interactionCodec5__state6) + 3),(SYM(interactionCodec5__state6) + 5));mem_wr(gb,HL,mem_rd(gb,HL)|0x80);CYC((SYM(interactionCodec5__state6) + 5),(SYM(interactionCodec5__state6) + 7));A=0x10;CYC((SYM(interactionCodec5__state6) + 7),(SYM(interactionCodec5__state6) + 10));W8(wcc50)=A;CYC((SYM(interactionCodec5__state6) + 10),SYM(interactionCodec6));interactionDelete_hook(gb);return; }
  else { hook_continue(gb,HL,sp0_);return; }
} while (0);}
