// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/seasons/gen.h"

// 01:4808
void s_applyPaletteFadeTransitionData(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x4808, 2); SET_HL(HL + 1);  // inc hl
  I(0x4809, 2); A = 0x02;  // ld a,$02
  I(0x480b, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x480d, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  PUSH(0x480e, HL);  // push hl
  I(0x480f, 2); A = alu_swap(gb, A);  // swap a
  I(0x4811, 1); alu_rrca(gb);  // rrca
  I(0x4812, 3); SET_HL(0x4845);  // ld hl,$4845
  RST_PUSH(0x4815, 0x4816);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x4816, 4); A = mem_rd(gb, 0xcc4e);  // ld a,($cc4e)
  RST_PUSH(0x4819, 0x481a);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x481a, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x481b, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x481c, 1); L = A;  // ld l,a
  I(0x481d, 3); SET_DE(0xda00);  // ld de,$da00
  CALL(0x4820, extractColorComponents_hook, 0x13d7, 0x4823);  // call $13d7
  SET_HL(POP(0x4823));  // pop hl
  I(0x4824, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4825, 2); A = alu_swap(gb, A);  // swap a
  I(0x4827, 1); alu_rrca(gb);  // rrca
  I(0x4828, 3); SET_HL(0x4845);  // ld hl,$4845
  RST_PUSH(0x482b, 0x482c);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x482c, 4); A = mem_rd(gb, 0xcc4e);  // ld a,($cc4e)
  RST_PUSH(0x482f, 0x4830);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x4830, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4831, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x4832, 1); L = A;  // ld l,a
  I(0x4833, 3); SET_DE(0xdb00);  // ld de,$db00
  CALL(0x4836, extractColorComponents_hook, 0x13d7, 0x4839);  // call $13d7
  I(0x4839, 2); A = 0x00;  // ld a,$00
  I(0x483b, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x483d, 2); A = 0xff;  // ld a,$ff
  I(0x483f, 4); mem_wr(gb, 0xcd29, A);  // ld ($cd29),a
  I(0x4842, 4); if (hook_is(gb, 0x3217, startFadeBetweenTwoPalettes_hook)) { startFadeBetweenTwoPalettes_hook(gb); return; } HANDOFF(0x3217);  // jp $3217
}

// 01:42cf
void s_checkDarkenRoom(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x42cf, 4); A = mem_rd(gb, 0xcc55);  // ld a,($cc55)
  I(0x42d2, 2); alu_cp(gb, 0xff);  // cp $ff
  if ((F & FZ)) { RET_TAKEN(0x42d4); return; } I(0x42d4, 2);  // ret z
  I(0x42d5, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x42d8, 2); alu_cp(gb, 0x04);  // cp $04
  if (!(F & FZ)) { I(0x42da, 3); goto L_42e9; } I(0x42da, 2);  // jr nz,$42e9
  I(0x42dc, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x42df, 2); alu_cp(gb, 0x39);  // cp $39
  if (!(F & FZ)) { I(0x42e1, 3); goto L_42e9; } I(0x42e1, 2);  // jr nz,$42e9
  CALL(0x42e3, getThisRoomFlags_hook, 0x1956, 0x42e6);  // call $1956
  I(0x42e6, 2); alu_and(gb, 0x80);  // and $80
  if (!(F & FZ)) { RET_TAKEN(0x42e8); return; } I(0x42e8, 2);  // ret nz
L_42e9:
  CALL(0x42e9, getThisRoomDungeonProperties_hook, 0x2d2a, 0x42ec);  // call $2d2a
  I(0x42ec, 4); A = mem_rd(gb, 0xcc58);  // ld a,($cc58)
  I(0x42ef, 2); alu_bit(gb, 7, A);  // bit 7,a
  if ((F & FZ)) { RET_TAKEN(0x42f1); return; } I(0x42f1, 2);  // ret z
  I(0x42f2, 4); if (hook_is(gb, 0x31d4, darkenRoom_hook)) { darkenRoom_hook(gb); return; } HANDOFF(0x31d4);  // jp $31d4
}

// 01:6028
void s_checkLinkCloseEnoughToWarpTileCenter__tileSolid(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6028:
  I(0x6028, 2); B = 0x02;  // ld b,$02
L_602a:
  I(0x602a, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x602b, 1); alu_add(gb, B);  // add b
  I(0x602c, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x602e, 2); alu_sub(gb, 0x04);  // sub $04
  I(0x6030, 2); alu_cp(gb, 0x0a);  // cp $0a
  RET(0x6032); return;  // ret
}

// 01:602a
void s_checkLinkCloseEnoughToWarpTileCenter__func_618f(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_602a:
  I(0x602a, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x602b, 1); alu_add(gb, B);  // add b
  I(0x602c, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x602e, 2); alu_sub(gb, 0x04);  // sub $04
  I(0x6030, 2); alu_cp(gb, 0x0a);  // cp $0a
  RET(0x6032); return;  // ret
}

// 01:7dec
void s_checkRoomPack(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x7dec, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x7def, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x7df0, 3); goto L_7df4; } I(0x7df0, 2);  // jr z,$7df4
  I(0x7df2, 1); alu_xor(gb, A);  // xor a
  RET(0x7df3); return;  // ret
L_7df4:
  I(0x7df4, 4); A = mem_rd(gb, 0xcc4d);  // ld a,($cc4d)
  I(0x7df7, 1); C = A;  // ld c,a
  I(0x7df8, 4); A = mem_rd(gb, 0xcc61);  // ld a,($cc61)
  I(0x7dfb, 1); B = A;  // ld b,a
  I(0x7dfc, 4); A = mem_rd(gb, 0xcc4d);  // ld a,($cc4d)
  I(0x7dff, 1); alu_cp(gb, B);  // cp b
  if ((F & FZ)) { RET_TAKEN(0x7e00); return; } I(0x7e00, 2);  // ret z
  I(0x7e01, 1); C = A;  // ld c,a
  I(0x7e02, 1); A = B;  // ld a,b
  I(0x7e03, 4); mem_wr(gb, 0xcc4d, A);  // ld ($cc4d),a
  I(0x7e06, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x7e07, 3); if (hook_is(gb, 0x7e2c, s_setHoronVillageSeason_hook)) { s_setHoronVillageSeason_hook(gb); return; } HANDOFF(0x7e2c); } I(0x7e07, 2);  // jr z,$7e2c
  if (hook_is(gb, 0x7e09, s_determineSeasonForRoomPack_hook)) { s_determineSeasonForRoomPack_hook(gb); return; } HANDOFF(0x7e09);  // fallthrough
}

// 01:6065
void s_checkTileWarps__initiateWarp(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6065:
  I(0x6065, 3); SET_HL(0x4662);  // ld hl,$4662
  I(0x6068, 2); E = 0x04;  // ld e,$04
  CALL(0x606a, interBankCall_hook, 0x008a, 0x606d);  // call $008a
  I(0x606d, 4); if (hook_is(gb, 0x5ffe, initiateWarp_hook)) { initiateWarp_hook(gb); return; } HANDOFF(0x5ffe);  // jp $5ffe
}

// 01:6070
void s_checkTileWarps__chimney(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_6070;
L_6065:
  I(0x6065, 3); SET_HL(0x4662);  // ld hl,$4662
  I(0x6068, 2); E = 0x04;  // ld e,$04
  CALL(0x606a, interBankCall_hook, 0x008a, 0x606d);  // call $008a
  I(0x606d, 4); if (hook_is(gb, 0x5ffe, initiateWarp_hook)) { initiateWarp_hook(gb); return; } HANDOFF(0x5ffe);  // jp $5ffe
L_6070:
  I(0x6070, 3); SET_HL(0xd00f);  // ld hl,$d00f
  I(0x6073, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x6074, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6075); return; } I(0x6075, 2);  // ret nz
  CALL(0x6076, clearAllParentItems_hook, 0x2b57, 0x6079);  // call $2b57
  CALL(0x6079, dropLinkHeldItem_hook, 0x2b8a, 0x607c);  // call $2b8a
  CALL(0x607c, resetLinkInvincibility_hook, 0x2af0, 0x607f);  // call $2af0
  I(0x607f, 3); goto L_6065;  // jr $6065
}

// 01:6081
void s_checkTileWarps__checkAdjacentTileIsWarpTile(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6081:
  I(0x6081, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x6083, 1); A = alu_inc8(gb, A);  // inc a
  CALL(0x6084, s_checkTileWarps__checkAdjacentTileIsWarpTile__checkIsWarpTile, 0x608b, 0x6087);  // call $608b
  if ((F & FC)) { RET_TAKEN(0x6087); return; } I(0x6087, 2);  // ret c
  I(0x6088, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x608a, 1); A = alu_dec8(gb, A);  // dec a
L_608b:
  I(0x608b, 1); C = A;  // ld c,a
  I(0x608c, 2); B = 0xcf;  // ld b,$cf
  I(0x608e, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x608f, 3); if (hook_is(gb, 0x60e2, checkTileIsWarpTile_hook)) { checkTileIsWarpTile_hook(gb); return; } HANDOFF(0x60e2);  // jr $60e2
}

// 01:608b
void s_checkTileWarps__checkAdjacentTileIsWarpTile__checkIsWarpTile(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_608b:
  I(0x608b, 1); C = A;  // ld c,a
  I(0x608c, 2); B = 0xcf;  // ld b,$cf
  I(0x608e, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x608f, 3); if (hook_is(gb, 0x60e2, checkTileIsWarpTile_hook)) { checkTileIsWarpTile_hook(gb); return; } HANDOFF(0x60e2);  // jr $60e2
}

// 01:6091
void s_checkTileWarps__checkLinkCloseEnoughToWarpTileCenter_multiTileDoor(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_6091;
L_6065:
  I(0x6065, 3); SET_HL(0x4662);  // ld hl,$4662
  I(0x6068, 2); E = 0x04;  // ld e,$04
  CALL(0x606a, interBankCall_hook, 0x008a, 0x606d);  // call $008a
  I(0x606d, 4); if (hook_is(gb, 0x5ffe, initiateWarp_hook)) { initiateWarp_hook(gb); return; } HANDOFF(0x5ffe);  // jp $5ffe
L_6091:
  I(0x6091, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x6093, 1); C = A;  // ld c,a
  I(0x6094, 2); B = 0xce;  // ld b,$ce
  I(0x6096, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x6097, 2); alu_cp(gb, 0x0c);  // cp $0c
  I(0x6099, 2); B = 0x02;  // ld b,$02
  if ((F & FZ)) { I(0x609b, 3); goto L_609f; } I(0x609b, 2);  // jr z,$609f
  I(0x609d, 2); B = 0x04;  // ld b,$04
L_609f:
  I(0x609f, 3); SET_HL(0xd00b);  // ld hl,$d00b
  I(0x60a2, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x60a3, 1); alu_add(gb, B);  // add b
  I(0x60a4, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x60a6, 2); alu_sub(gb, 0x04);  // sub $04
  I(0x60a8, 2); alu_cp(gb, 0x0a);  // cp $0a
  if (!(F & FC)) { RET_TAKEN(0x60aa); return; } I(0x60aa, 2);  // ret nc
  I(0x60ab, 3); goto L_6065;  // jr $6065
}

// 01:5953
void s_cutscene00(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x5953, updateStatusBar_hook, 0x1a62, 0x5956);  // call $1a62
L_5956:
  CALL(0x5956, updateAllObjects_hook, 0x3382, 0x5959);  // call $3382
L_5959:
  CALL(0x5959, refreshLoadedTreeGfx_hook, 0x1601, 0x595c);  // call $1601
L_595c:
  I(0x595c, 4); A = mem_rd(gb, 0xcd00);  // ld a,($cd00)
  I(0x595f, 2); alu_cp(gb, 0x01);  // cp $01
  if (!(F & FZ)) { RET_TAKEN(0x5961); return; } I(0x5961, 2);  // ret nz
  CALL(0x5962, setInstrumentsDisabledCounterAndScrollMode_hook, 0x197b, 0x5965);  // call $197b
  I(0x5965, 1); alu_xor(gb, A);  // xor a
  I(0x5966, 4); mem_wr(gb, 0xcbca, A);  // ld ($cbca),a
  CALL(0x5969, clearObjectsWithEnabled2_hook, 0x49a4, 0x596c);  // call $49a4
  CALL(0x596c, refreshObjectGfx_hook, 0x1606, 0x596f);  // call $1606
L_596f:
  CALL(0x596f, setVisitedRoomFlag_hook, 0x2d24, 0x5972);  // call $2d24
  CALL(0x5972, checkUpdateDungeonMinimap_hook, 0x578d, 0x5975);  // call $578d
  I(0x5975, 2); A = 0x01;  // ld a,$01
  I(0x5977, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  CALL(0x597a, playCompassSoundIfKeyInRoom_hook, 0x49e5, 0x597d);  // call $49e5
  I(0x597d, 4); if (hook_is(gb, 0x5cec, updateGrassAnimationModifier_hook)) { updateGrassAnimationModifier_hook(gb); return; } HANDOFF(0x5cec);  // jp $5cec
}

// 01:5956
void s_cutscene00__afterCall5956(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5956:
  CALL(0x5956, updateAllObjects_hook, 0x3382, 0x5959);  // call $3382
L_5959:
  CALL(0x5959, refreshLoadedTreeGfx_hook, 0x1601, 0x595c);  // call $1601
L_595c:
  I(0x595c, 4); A = mem_rd(gb, 0xcd00);  // ld a,($cd00)
  I(0x595f, 2); alu_cp(gb, 0x01);  // cp $01
  if (!(F & FZ)) { RET_TAKEN(0x5961); return; } I(0x5961, 2);  // ret nz
  CALL(0x5962, setInstrumentsDisabledCounterAndScrollMode_hook, 0x197b, 0x5965);  // call $197b
  I(0x5965, 1); alu_xor(gb, A);  // xor a
  I(0x5966, 4); mem_wr(gb, 0xcbca, A);  // ld ($cbca),a
  CALL(0x5969, clearObjectsWithEnabled2_hook, 0x49a4, 0x596c);  // call $49a4
  CALL(0x596c, refreshObjectGfx_hook, 0x1606, 0x596f);  // call $1606
L_596f:
  CALL(0x596f, setVisitedRoomFlag_hook, 0x2d24, 0x5972);  // call $2d24
  CALL(0x5972, checkUpdateDungeonMinimap_hook, 0x578d, 0x5975);  // call $578d
  I(0x5975, 2); A = 0x01;  // ld a,$01
  I(0x5977, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  CALL(0x597a, playCompassSoundIfKeyInRoom_hook, 0x49e5, 0x597d);  // call $49e5
  I(0x597d, 4); if (hook_is(gb, 0x5cec, updateGrassAnimationModifier_hook)) { updateGrassAnimationModifier_hook(gb); return; } HANDOFF(0x5cec);  // jp $5cec
}

// 01:5959
void s_cutscene00__afterCall5959(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5959:
  CALL(0x5959, refreshLoadedTreeGfx_hook, 0x1601, 0x595c);  // call $1601
L_595c:
  I(0x595c, 4); A = mem_rd(gb, 0xcd00);  // ld a,($cd00)
  I(0x595f, 2); alu_cp(gb, 0x01);  // cp $01
  if (!(F & FZ)) { RET_TAKEN(0x5961); return; } I(0x5961, 2);  // ret nz
  CALL(0x5962, setInstrumentsDisabledCounterAndScrollMode_hook, 0x197b, 0x5965);  // call $197b
  I(0x5965, 1); alu_xor(gb, A);  // xor a
  I(0x5966, 4); mem_wr(gb, 0xcbca, A);  // ld ($cbca),a
  CALL(0x5969, clearObjectsWithEnabled2_hook, 0x49a4, 0x596c);  // call $49a4
  CALL(0x596c, refreshObjectGfx_hook, 0x1606, 0x596f);  // call $1606
L_596f:
  CALL(0x596f, setVisitedRoomFlag_hook, 0x2d24, 0x5972);  // call $2d24
  CALL(0x5972, checkUpdateDungeonMinimap_hook, 0x578d, 0x5975);  // call $578d
  I(0x5975, 2); A = 0x01;  // ld a,$01
  I(0x5977, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  CALL(0x597a, playCompassSoundIfKeyInRoom_hook, 0x49e5, 0x597d);  // call $49e5
  I(0x597d, 4); if (hook_is(gb, 0x5cec, updateGrassAnimationModifier_hook)) { updateGrassAnimationModifier_hook(gb); return; } HANDOFF(0x5cec);  // jp $5cec
}

// 01:595c
void s_cutscene00__afterCall595c(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_595c:
  I(0x595c, 4); A = mem_rd(gb, 0xcd00);  // ld a,($cd00)
  I(0x595f, 2); alu_cp(gb, 0x01);  // cp $01
  if (!(F & FZ)) { RET_TAKEN(0x5961); return; } I(0x5961, 2);  // ret nz
  CALL(0x5962, setInstrumentsDisabledCounterAndScrollMode_hook, 0x197b, 0x5965);  // call $197b
  I(0x5965, 1); alu_xor(gb, A);  // xor a
  I(0x5966, 4); mem_wr(gb, 0xcbca, A);  // ld ($cbca),a
  CALL(0x5969, clearObjectsWithEnabled2_hook, 0x49a4, 0x596c);  // call $49a4
  CALL(0x596c, refreshObjectGfx_hook, 0x1606, 0x596f);  // call $1606
L_596f:
  CALL(0x596f, setVisitedRoomFlag_hook, 0x2d24, 0x5972);  // call $2d24
  CALL(0x5972, checkUpdateDungeonMinimap_hook, 0x578d, 0x5975);  // call $578d
  I(0x5975, 2); A = 0x01;  // ld a,$01
  I(0x5977, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  CALL(0x597a, playCompassSoundIfKeyInRoom_hook, 0x49e5, 0x597d);  // call $49e5
  I(0x597d, 4); if (hook_is(gb, 0x5cec, updateGrassAnimationModifier_hook)) { updateGrassAnimationModifier_hook(gb); return; } HANDOFF(0x5cec);  // jp $5cec
}

// 01:596f
void s_cutscene00__afterCall596f(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_596f:
  CALL(0x596f, setVisitedRoomFlag_hook, 0x2d24, 0x5972);  // call $2d24
  CALL(0x5972, checkUpdateDungeonMinimap_hook, 0x578d, 0x5975);  // call $578d
  I(0x5975, 2); A = 0x01;  // ld a,$01
  I(0x5977, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  CALL(0x597a, playCompassSoundIfKeyInRoom_hook, 0x49e5, 0x597d);  // call $49e5
  I(0x597d, 4); if (hook_is(gb, 0x5cec, updateGrassAnimationModifier_hook)) { updateGrassAnimationModifier_hook(gb); return; } HANDOFF(0x5cec);  // jp $5cec
}

// 01:59e6
void s_cutscene02(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  RET(0x59e6); return;  // ret
}

// 01:5a79
void s_cutscene04(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5a79, 4); A = mem_rd(gb, 0xc4ab);  // ld a,($c4ab)
  I(0x5a7c, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x5a7d); return; } I(0x5a7d, 2);  // ret nz
  CALL(0x5a7e, disableLcd_hook, 0x02c1, 0x5a81);  // call $02c1
  I(0x5a81, 4); A = mem_rd(gb, 0xcc63);  // ld a,($cc63)
  I(0x5a84, 2); alu_and(gb, 0x07);  // and $07
  I(0x5a86, 4); mem_wr(gb, 0xcc49, A);  // ld ($cc49),a
  I(0x5a89, 4); A = mem_rd(gb, 0xcc64);  // ld a,($cc64)
  I(0x5a8c, 4); mem_wr(gb, 0xcc4c, A);  // ld ($cc4c),a
  I(0x5a8f, 4); A = mem_rd(gb, 0xcc48);  // ld a,($cc48)
  I(0x5a92, 1); H = A;  // ld h,a
  I(0x5a93, 2); L = 0x0b;  // ld l,$0b
  I(0x5a95, 4); A = mem_rd(gb, 0xcc66);  // ld a,($cc66)
  CALL(0x5a98, setShortPosition_hook, 0x2076, 0x5a9b);  // call $2076
  I(0x5a9b, 3); goto L_5aab;  // jr $5aab
L_5aab:
  CALL(0x5aab, setInteractionsEnabledTo2_hook, 0x497e, 0x5aae);  // call $497e
  CALL(0x5aae, clearObjectsWithEnabled2_hook, 0x49a4, 0x5ab1);  // call $49a4
  CALL(0x5ab1, clearItems_hook, 0x3566, 0x5ab4);  // call $3566
  CALL(0x5ab4, clearEnemies_hook, 0x3578, 0x5ab7);  // call $3578
  CALL(0x5ab7, clearParts_hook, 0x358a, 0x5aba);  // call $358a
  CALL(0x5aba, clearReservedInteraction0_hook, 0x3544, 0x5abd);  // call $3544
  CALL(0x5abd, clearScreenVariables_hook, 0x3528, 0x5ac0);  // call $3528
  CALL(0x5ac0, clearMemoryOnScreenReload_hook, 0x493c, 0x5ac3);  // call $493c
  CALL(0x5ac3, loadScreenMusicAndSetRoomPack_hook, 0x32dc, 0x5ac6);  // call $32dc
  CALL(0x5ac6, loadTilesetData_hook, 0x381a, 0x5ac9);  // call $381a
L_5ac9:
  CALL(0x5ac9, loadTilesetGraphics_hook, 0x3737, 0x5acc);  // call $3737
  CALL(0x5acc, func_131f_hook, 0x12dd, 0x5acf);  // call $12dd
L_5acf:
  I(0x5acf, 3); SET_DE(0xd00b);  // ld de,$d00b
  CALL(0x5ad2, getShortPositionFromDE_hook, 0x2059, 0x5ad5);  // call $2059
  I(0x5ad5, 4); mem_wr(gb, 0xcc66, A);  // ld ($cc66),a
  I(0x5ad8, 4); if (hook_is(gb, 0x5a27, func_5c18_hook)) { func_5c18_hook(gb); return; } HANDOFF(0x5a27);  // jp $5a27
}

// 01:5ac9
void s_cutscene04__afterCall5ac9(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5ac9:
  CALL(0x5ac9, loadTilesetGraphics_hook, 0x3737, 0x5acc);  // call $3737
  CALL(0x5acc, func_131f_hook, 0x12dd, 0x5acf);  // call $12dd
L_5acf:
  I(0x5acf, 3); SET_DE(0xd00b);  // ld de,$d00b
  CALL(0x5ad2, getShortPositionFromDE_hook, 0x2059, 0x5ad5);  // call $2059
  I(0x5ad5, 4); mem_wr(gb, 0xcc66, A);  // ld ($cc66),a
  I(0x5ad8, 4); if (hook_is(gb, 0x5a27, func_5c18_hook)) { func_5c18_hook(gb); return; } HANDOFF(0x5a27);  // jp $5a27
}

// 01:5acf
void s_cutscene04__afterCall5acf(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5acf:
  I(0x5acf, 3); SET_DE(0xd00b);  // ld de,$d00b
  CALL(0x5ad2, getShortPositionFromDE_hook, 0x2059, 0x5ad5);  // call $2059
  I(0x5ad5, 4); mem_wr(gb, 0xcc66, A);  // ld ($cc66),a
  I(0x5ad8, 4); if (hook_is(gb, 0x5a27, func_5c18_hook)) { func_5c18_hook(gb); return; } HANDOFF(0x5a27);  // jp $5a27
}

// 01:5bd2
void s_cutscene06(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5bd2, 2); E = 0x00;  // ld e,$00
  I(0x5bd4, 4); if (hook_is(gb, 0x35b8, s_multiIntroCutsceneCaller_hook)) { s_multiIntroCutsceneCaller_hook(gb); return; } HANDOFF(0x35b8);  // jp $35b8
}

// 01:5bd7
void s_cutscene07(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5bd7, 2); E = 0x01;  // ld e,$01
  CALL(0x5bd9, s_multiIntroCutsceneCaller_hook, 0x35b8, 0x5bdc);  // call $35b8
L_5bdc:
  CALL(0x5bdc, updateInteractionsAndDrawAllSprites_hook, 0x3445, 0x5bdf);  // call $3445
L_5bdf:
  I(0x5bdf, 4); if (hook_is(gb, 0x3276, s_updateAnimationsAfterCutscene_hook)) { s_updateAnimationsAfterCutscene_hook(gb); return; } HANDOFF(0x3276);  // jp $3276
}

// 01:5bdc
void s_cutscene07__afterCall5bdc(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5bdc:
  CALL(0x5bdc, updateInteractionsAndDrawAllSprites_hook, 0x3445, 0x5bdf);  // call $3445
L_5bdf:
  I(0x5bdf, 4); if (hook_is(gb, 0x3276, s_updateAnimationsAfterCutscene_hook)) { s_updateAnimationsAfterCutscene_hook(gb); return; } HANDOFF(0x3276);  // jp $3276
}

// 01:5bdf
void s_cutscene07__afterCall5bdf(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5bdf:
  I(0x5bdf, 4); if (hook_is(gb, 0x3276, s_updateAnimationsAfterCutscene_hook)) { s_updateAnimationsAfterCutscene_hook(gb); return; } HANDOFF(0x3276);  // jp $3276
}

// 01:5be2
void s_cutscene08(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5be2, 2); E = 0x02;  // ld e,$02
  CALL(0x5be4, s_multiIntroCutsceneCaller_hook, 0x35b8, 0x5be7);  // call $35b8
L_5be7:
  I(0x5be7, 4); if (hook_is(gb, 0x3445, updateInteractionsAndDrawAllSprites_hook)) { updateInteractionsAndDrawAllSprites_hook(gb); return; } HANDOFF(0x3445);  // jp $3445
}

// 01:5be7
void s_cutscene08__afterCall5be7(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5be7:
  I(0x5be7, 4); if (hook_is(gb, 0x3445, updateInteractionsAndDrawAllSprites_hook)) { updateInteractionsAndDrawAllSprites_hook(gb); return; } HANDOFF(0x3445);  // jp $3445
}

// 01:5c07
void s_cutscene0b(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5c07, 3); SET_HL(0x6b89);  // ld hl,$6b89
  I(0x5c0a, 2); E = 0x03;  // ld e,$03
  CALL(0x5c0c, interBankCall_hook, 0x008a, 0x5c0f);  // call $008a
L_5c0f:
  I(0x5c0f, 3); if (hook_is(gb, 0x5bb5, func_5d31_hook)) { func_5d31_hook(gb); return; } HANDOFF(0x5bb5);  // jr $5bb5
}

// 01:5c0f
void s_cutscene0b__afterCall5c0f(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5c0f:
  I(0x5c0f, 3); if (hook_is(gb, 0x5bb5, func_5d31_hook)) { func_5d31_hook(gb); return; } HANDOFF(0x5bb5);  // jr $5bb5
}

// 01:5c11
void s_cutscene0c(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5c11, 3); SET_HL(0x66ff);  // ld hl,$66ff
  I(0x5c14, 2); E = 0x03;  // ld e,$03
  CALL(0x5c16, interBankCall_hook, 0x008a, 0x5c19);  // call $008a
L_5c19:
  I(0x5c19, 3); if (hook_is(gb, 0x5bb5, func_5d31_hook)) { func_5d31_hook(gb); return; } HANDOFF(0x5bb5);  // jr $5bb5
}

// 01:5c19
void s_cutscene0c__afterCall5c19(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5c19:
  I(0x5c19, 3); if (hook_is(gb, 0x5bb5, func_5d31_hook)) { func_5d31_hook(gb); return; } HANDOFF(0x5bb5);  // jr $5bb5
}

// 01:5c1b
void s_cutscene0d(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x5c1b, refreshLoadedTreeGfx_hook, 0x1601, 0x5c1e);  // call $1601
L_5c1e:
  I(0x5c1e, 2); E = 0x03;  // ld e,$03
  I(0x5c20, 4); if (hook_is(gb, 0x35b8, s_multiIntroCutsceneCaller_hook)) { s_multiIntroCutsceneCaller_hook(gb); return; } HANDOFF(0x35b8);  // jp $35b8
}

// 01:5c1e
void s_cutscene0d__afterCall5c1e(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5c1e:
  I(0x5c1e, 2); E = 0x03;  // ld e,$03
  I(0x5c20, 4); if (hook_is(gb, 0x35b8, s_multiIntroCutsceneCaller_hook)) { s_multiIntroCutsceneCaller_hook(gb); return; } HANDOFF(0x35b8);  // jp $35b8
}

// 01:5c23
void s_cutscene0e(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5c23, 4); A = mem_rd(gb, 0xcc67);  // ld a,($cc67)
  I(0x5c26, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x5c27, 3); if (hook_is(gb, 0x5c85, applyWarpTransition2_hook)) { applyWarpTransition2_hook(gb); return; } HANDOFF(0x5c85); } I(0x5c27, 2);  // jr nz,$5c85
  I(0x5c29, 2); E = 0x04;  // ld e,$04
  CALL(0x5c2b, s_multiIntroCutsceneCaller_hook, 0x35b8, 0x5c2e);  // call $35b8
L_5c2e:
  I(0x5c2e, 4); if (hook_is(gb, 0x3276, s_updateAnimationsAfterCutscene_hook)) { s_updateAnimationsAfterCutscene_hook(gb); return; } HANDOFF(0x3276);  // jp $3276
}

// 01:5c2e
void s_cutscene0e__afterCall5c2e(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5c2e:
  I(0x5c2e, 4); if (hook_is(gb, 0x3276, s_updateAnimationsAfterCutscene_hook)) { s_updateAnimationsAfterCutscene_hook(gb); return; } HANDOFF(0x3276);  // jp $3276
}

// 01:5c31
void s_cutscene10(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x5c31, s_flameOfDestructionsCutsceneCaller_hook, 0x3346, 0x5c34);  // call $3346
L_5c34:
  I(0x5c34, 4); if (hook_is(gb, 0x5bc5, func_5d41_hook)) { func_5d41_hook(gb); return; } HANDOFF(0x5bc5);  // jp $5bc5
}

// 01:5c34
void s_cutscene10__afterCall5c34(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5c34:
  I(0x5c34, 4); if (hook_is(gb, 0x5bc5, func_5d41_hook)) { func_5d41_hook(gb); return; } HANDOFF(0x5bc5);  // jp $5bc5
}

// 01:5c37
void s_cutscene11(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x5c37, s_zeldaAndVillagersCutsceneCaller_hook, 0x335a, 0x5c3a);  // call $335a
L_5c3a:
  I(0x5c3a, 4); if (hook_is(gb, 0x5bb5, func_5d31_hook)) { func_5d31_hook(gb); return; } HANDOFF(0x5bb5);  // jp $5bb5
}

// 01:5c3a
void s_cutscene11__afterCall5c3a(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5c3a:
  I(0x5c3a, 4); if (hook_is(gb, 0x5bb5, func_5d31_hook)) { func_5d31_hook(gb); return; } HANDOFF(0x5bb5);  // jp $5bb5
}

// 01:5c3d
void s_cutscene12(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x5c3d, s_zeldaKidnappedCutsceneCaller_hook, 0x336e, 0x5c40);  // call $336e
L_5c40:
  I(0x5c40, 4); if (hook_is(gb, 0x5bc5, func_5d41_hook)) { func_5d41_hook(gb); return; } HANDOFF(0x5bc5);  // jp $5bc5
}

// 01:5c40
void s_cutscene12__afterCall5c40(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5c40:
  I(0x5c40, 4); if (hook_is(gb, 0x5bc5, func_5d41_hook)) { func_5d41_hook(gb); return; } HANDOFF(0x5bc5);  // jp $5bc5
}

// 01:5b4e
void s_cutscene13(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5b4e, 4); A = mem_rd(gb, 0xcc03);  // ld a,($cc03)
  RST_PUSH(0x5b51, 0x5b52);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x5b58: goto L_5b58; case 0x5b8a: goto L_5b8a; case 0x5b94: goto L_5b94; default: HANDOFF(HL); }
L_5b58:
  I(0x5b58, 2); A = 0x01;  // ld a,$01
  I(0x5b5a, 4); mem_wr(gb, 0xcc03, A);  // ld ($cc03),a
  I(0x5b5d, 3); SET_HL(0xcfc8);  // ld hl,$cfc8
  I(0x5b60, 2); B = 0x18;  // ld b,$18
  CALL(0x5b62, clearMemory_hook, 0x044b, 0x5b65);  // call $044b
  I(0x5b65, 2); A = 0x07;  // ld a,$07
  I(0x5b67, 4); mem_wr(gb, 0xcc49, A);  // ld ($cc49),a
  I(0x5b6a, 2); A = 0xff;  // ld a,$ff
  I(0x5b6c, 4); mem_wr(gb, 0xcc4c, A);  // ld ($cc4c),a
  I(0x5b6f, 2); A = 0x77;  // ld a,$77
  I(0x5b71, 4); mem_wr(gb, 0xcc56, A);  // ld ($cc56),a
  I(0x5b74, 2); A = 0x28;  // ld a,$28
  I(0x5b76, 4); mem_wr(gb, 0xcc50, A);  // ld ($cc50),a
  I(0x5b79, 2); A = 0x02;  // ld a,$02
  I(0x5b7b, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x5b7d, 3); SET_HL(0xdc3f);  // ld hl,$dc3f
  I(0x5b80, 3); mem_wr(gb, HL, 0xff);  // ld (hl),$ff
  I(0x5b82, 1); alu_xor(gb, A);  // xor a
  I(0x5b83, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x5b85, 2); A = 0x04;  // ld a,$04
  I(0x5b87, 4); if (hook_is(gb, 0x312f, fadeoutToWhiteWithDelay_hook)) { fadeoutToWhiteWithDelay_hook(gb); return; } HANDOFF(0x312f);  // jp $312f
L_5b8a:
  I(0x5b8a, 4); A = mem_rd(gb, 0xc4ab);  // ld a,($c4ab)
  I(0x5b8d, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x5b8e); return; } I(0x5b8e, 2);  // ret nz
  I(0x5b8f, 2); A = 0x02;  // ld a,$02
  I(0x5b91, 4); mem_wr(gb, 0xcc03, A);  // ld ($cc03),a
L_5b94:
  CALL(0x5b94, refreshLoadedTreeGfx_hook, 0x1601, 0x5b97);  // call $1601
L_5b97:
  CALL(0x5b97, updateMenus_hook, 0x1a17, 0x5b9a);  // call $1a17
L_5b9a:
  if (!(F & FZ)) { RET_TAKEN(0x5b9a); return; } I(0x5b9a, 2);  // ret nz
  I(0x5b9b, 4); A = mem_rd(gb, 0xcc67);  // ld a,($cc67)
  I(0x5b9e, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x5b9f, 4); if (hook_is(gb, 0x5c85, applyWarpTransition2_hook)) { applyWarpTransition2_hook(gb); return; } HANDOFF(0x5c85); } I(0x5b9f, 3);  // jp nz,$5c85
  CALL(0x5ba2, s_seasonsFunc_331b_hook, 0x331b, 0x5ba5);  // call $331b
L_5ba5:
  CALL(0x5ba5, s_seasonsFunc_34a0_hook, 0x34a0, 0x5ba8);  // call $34a0
L_5ba8:
  CALL(0x5ba8, updateStatusBar_hook, 0x1a62, 0x5bab);  // call $1a62
L_5bab:
  I(0x5bab, 4); A = mem_rd(gb, 0xcc04);  // ld a,($cc04)
  I(0x5bae, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5baf, 4); if (hook_is(gb, 0x1da5, checkEnemyAndPartCollisionsIfTextInactive_hook)) { checkEnemyAndPartCollisionsIfTextInactive_hook(gb); return; } HANDOFF(0x1da5); } I(0x5baf, 3);  // jp z,$1da5
  I(0x5bb2, 4); if (hook_is(gb, 0x5cb4, setCutsceneIndexIfCutsceneTriggerSet_hook)) { setCutsceneIndexIfCutsceneTriggerSet_hook(gb); return; } HANDOFF(0x5cb4);  // jp $5cb4
}

// 01:5b58
void s_cutscene13__state0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5b58:
  I(0x5b58, 2); A = 0x01;  // ld a,$01
  I(0x5b5a, 4); mem_wr(gb, 0xcc03, A);  // ld ($cc03),a
  I(0x5b5d, 3); SET_HL(0xcfc8);  // ld hl,$cfc8
  I(0x5b60, 2); B = 0x18;  // ld b,$18
  CALL(0x5b62, clearMemory_hook, 0x044b, 0x5b65);  // call $044b
  I(0x5b65, 2); A = 0x07;  // ld a,$07
  I(0x5b67, 4); mem_wr(gb, 0xcc49, A);  // ld ($cc49),a
  I(0x5b6a, 2); A = 0xff;  // ld a,$ff
  I(0x5b6c, 4); mem_wr(gb, 0xcc4c, A);  // ld ($cc4c),a
  I(0x5b6f, 2); A = 0x77;  // ld a,$77
  I(0x5b71, 4); mem_wr(gb, 0xcc56, A);  // ld ($cc56),a
  I(0x5b74, 2); A = 0x28;  // ld a,$28
  I(0x5b76, 4); mem_wr(gb, 0xcc50, A);  // ld ($cc50),a
  I(0x5b79, 2); A = 0x02;  // ld a,$02
  I(0x5b7b, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x5b7d, 3); SET_HL(0xdc3f);  // ld hl,$dc3f
  I(0x5b80, 3); mem_wr(gb, HL, 0xff);  // ld (hl),$ff
  I(0x5b82, 1); alu_xor(gb, A);  // xor a
  I(0x5b83, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x5b85, 2); A = 0x04;  // ld a,$04
  I(0x5b87, 4); if (hook_is(gb, 0x312f, fadeoutToWhiteWithDelay_hook)) { fadeoutToWhiteWithDelay_hook(gb); return; } HANDOFF(0x312f);  // jp $312f
}

// 01:5b8a
void s_cutscene13__state1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5b8a:
  I(0x5b8a, 4); A = mem_rd(gb, 0xc4ab);  // ld a,($c4ab)
  I(0x5b8d, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x5b8e); return; } I(0x5b8e, 2);  // ret nz
  I(0x5b8f, 2); A = 0x02;  // ld a,$02
  I(0x5b91, 4); mem_wr(gb, 0xcc03, A);  // ld ($cc03),a
L_5b94:
  CALL(0x5b94, refreshLoadedTreeGfx_hook, 0x1601, 0x5b97);  // call $1601
L_5b97:
  CALL(0x5b97, updateMenus_hook, 0x1a17, 0x5b9a);  // call $1a17
L_5b9a:
  if (!(F & FZ)) { RET_TAKEN(0x5b9a); return; } I(0x5b9a, 2);  // ret nz
  I(0x5b9b, 4); A = mem_rd(gb, 0xcc67);  // ld a,($cc67)
  I(0x5b9e, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x5b9f, 4); if (hook_is(gb, 0x5c85, applyWarpTransition2_hook)) { applyWarpTransition2_hook(gb); return; } HANDOFF(0x5c85); } I(0x5b9f, 3);  // jp nz,$5c85
  CALL(0x5ba2, s_seasonsFunc_331b_hook, 0x331b, 0x5ba5);  // call $331b
L_5ba5:
  CALL(0x5ba5, s_seasonsFunc_34a0_hook, 0x34a0, 0x5ba8);  // call $34a0
L_5ba8:
  CALL(0x5ba8, updateStatusBar_hook, 0x1a62, 0x5bab);  // call $1a62
L_5bab:
  I(0x5bab, 4); A = mem_rd(gb, 0xcc04);  // ld a,($cc04)
  I(0x5bae, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5baf, 4); if (hook_is(gb, 0x1da5, checkEnemyAndPartCollisionsIfTextInactive_hook)) { checkEnemyAndPartCollisionsIfTextInactive_hook(gb); return; } HANDOFF(0x1da5); } I(0x5baf, 3);  // jp z,$1da5
  I(0x5bb2, 4); if (hook_is(gb, 0x5cb4, setCutsceneIndexIfCutsceneTriggerSet_hook)) { setCutsceneIndexIfCutsceneTriggerSet_hook(gb); return; } HANDOFF(0x5cb4);  // jp $5cb4
}

// 01:5b94
void s_cutscene13__state2(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5b94:
  CALL(0x5b94, refreshLoadedTreeGfx_hook, 0x1601, 0x5b97);  // call $1601
L_5b97:
  CALL(0x5b97, updateMenus_hook, 0x1a17, 0x5b9a);  // call $1a17
L_5b9a:
  if (!(F & FZ)) { RET_TAKEN(0x5b9a); return; } I(0x5b9a, 2);  // ret nz
  I(0x5b9b, 4); A = mem_rd(gb, 0xcc67);  // ld a,($cc67)
  I(0x5b9e, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x5b9f, 4); if (hook_is(gb, 0x5c85, applyWarpTransition2_hook)) { applyWarpTransition2_hook(gb); return; } HANDOFF(0x5c85); } I(0x5b9f, 3);  // jp nz,$5c85
  CALL(0x5ba2, s_seasonsFunc_331b_hook, 0x331b, 0x5ba5);  // call $331b
L_5ba5:
  CALL(0x5ba5, s_seasonsFunc_34a0_hook, 0x34a0, 0x5ba8);  // call $34a0
L_5ba8:
  CALL(0x5ba8, updateStatusBar_hook, 0x1a62, 0x5bab);  // call $1a62
L_5bab:
  I(0x5bab, 4); A = mem_rd(gb, 0xcc04);  // ld a,($cc04)
  I(0x5bae, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5baf, 4); if (hook_is(gb, 0x1da5, checkEnemyAndPartCollisionsIfTextInactive_hook)) { checkEnemyAndPartCollisionsIfTextInactive_hook(gb); return; } HANDOFF(0x1da5); } I(0x5baf, 3);  // jp z,$1da5
  I(0x5bb2, 4); if (hook_is(gb, 0x5cb4, setCutsceneIndexIfCutsceneTriggerSet_hook)) { setCutsceneIndexIfCutsceneTriggerSet_hook(gb); return; } HANDOFF(0x5cb4);  // jp $5cb4
}

// 01:5b97
void s_cutscene13__afterCall5b97(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5b97:
  CALL(0x5b97, updateMenus_hook, 0x1a17, 0x5b9a);  // call $1a17
L_5b9a:
  if (!(F & FZ)) { RET_TAKEN(0x5b9a); return; } I(0x5b9a, 2);  // ret nz
  I(0x5b9b, 4); A = mem_rd(gb, 0xcc67);  // ld a,($cc67)
  I(0x5b9e, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x5b9f, 4); if (hook_is(gb, 0x5c85, applyWarpTransition2_hook)) { applyWarpTransition2_hook(gb); return; } HANDOFF(0x5c85); } I(0x5b9f, 3);  // jp nz,$5c85
  CALL(0x5ba2, s_seasonsFunc_331b_hook, 0x331b, 0x5ba5);  // call $331b
L_5ba5:
  CALL(0x5ba5, s_seasonsFunc_34a0_hook, 0x34a0, 0x5ba8);  // call $34a0
L_5ba8:
  CALL(0x5ba8, updateStatusBar_hook, 0x1a62, 0x5bab);  // call $1a62
L_5bab:
  I(0x5bab, 4); A = mem_rd(gb, 0xcc04);  // ld a,($cc04)
  I(0x5bae, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5baf, 4); if (hook_is(gb, 0x1da5, checkEnemyAndPartCollisionsIfTextInactive_hook)) { checkEnemyAndPartCollisionsIfTextInactive_hook(gb); return; } HANDOFF(0x1da5); } I(0x5baf, 3);  // jp z,$1da5
  I(0x5bb2, 4); if (hook_is(gb, 0x5cb4, setCutsceneIndexIfCutsceneTriggerSet_hook)) { setCutsceneIndexIfCutsceneTriggerSet_hook(gb); return; } HANDOFF(0x5cb4);  // jp $5cb4
}

// 01:5b9a
void s_cutscene13__afterCall5b9a(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5b9a:
  if (!(F & FZ)) { RET_TAKEN(0x5b9a); return; } I(0x5b9a, 2);  // ret nz
  I(0x5b9b, 4); A = mem_rd(gb, 0xcc67);  // ld a,($cc67)
  I(0x5b9e, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x5b9f, 4); if (hook_is(gb, 0x5c85, applyWarpTransition2_hook)) { applyWarpTransition2_hook(gb); return; } HANDOFF(0x5c85); } I(0x5b9f, 3);  // jp nz,$5c85
  CALL(0x5ba2, s_seasonsFunc_331b_hook, 0x331b, 0x5ba5);  // call $331b
L_5ba5:
  CALL(0x5ba5, s_seasonsFunc_34a0_hook, 0x34a0, 0x5ba8);  // call $34a0
L_5ba8:
  CALL(0x5ba8, updateStatusBar_hook, 0x1a62, 0x5bab);  // call $1a62
L_5bab:
  I(0x5bab, 4); A = mem_rd(gb, 0xcc04);  // ld a,($cc04)
  I(0x5bae, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5baf, 4); if (hook_is(gb, 0x1da5, checkEnemyAndPartCollisionsIfTextInactive_hook)) { checkEnemyAndPartCollisionsIfTextInactive_hook(gb); return; } HANDOFF(0x1da5); } I(0x5baf, 3);  // jp z,$1da5
  I(0x5bb2, 4); if (hook_is(gb, 0x5cb4, setCutsceneIndexIfCutsceneTriggerSet_hook)) { setCutsceneIndexIfCutsceneTriggerSet_hook(gb); return; } HANDOFF(0x5cb4);  // jp $5cb4
}

// 01:5ba5
void s_cutscene13__afterCall5ba5(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5ba5:
  CALL(0x5ba5, s_seasonsFunc_34a0_hook, 0x34a0, 0x5ba8);  // call $34a0
L_5ba8:
  CALL(0x5ba8, updateStatusBar_hook, 0x1a62, 0x5bab);  // call $1a62
L_5bab:
  I(0x5bab, 4); A = mem_rd(gb, 0xcc04);  // ld a,($cc04)
  I(0x5bae, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5baf, 4); if (hook_is(gb, 0x1da5, checkEnemyAndPartCollisionsIfTextInactive_hook)) { checkEnemyAndPartCollisionsIfTextInactive_hook(gb); return; } HANDOFF(0x1da5); } I(0x5baf, 3);  // jp z,$1da5
  I(0x5bb2, 4); if (hook_is(gb, 0x5cb4, setCutsceneIndexIfCutsceneTriggerSet_hook)) { setCutsceneIndexIfCutsceneTriggerSet_hook(gb); return; } HANDOFF(0x5cb4);  // jp $5cb4
}

// 01:5ba8
void s_cutscene13__afterCall5ba8(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5ba8:
  CALL(0x5ba8, updateStatusBar_hook, 0x1a62, 0x5bab);  // call $1a62
L_5bab:
  I(0x5bab, 4); A = mem_rd(gb, 0xcc04);  // ld a,($cc04)
  I(0x5bae, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5baf, 4); if (hook_is(gb, 0x1da5, checkEnemyAndPartCollisionsIfTextInactive_hook)) { checkEnemyAndPartCollisionsIfTextInactive_hook(gb); return; } HANDOFF(0x1da5); } I(0x5baf, 3);  // jp z,$1da5
  I(0x5bb2, 4); if (hook_is(gb, 0x5cb4, setCutsceneIndexIfCutsceneTriggerSet_hook)) { setCutsceneIndexIfCutsceneTriggerSet_hook(gb); return; } HANDOFF(0x5cb4);  // jp $5cb4
}

// 01:5bab
void s_cutscene13__afterCall5bab(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5bab:
  I(0x5bab, 4); A = mem_rd(gb, 0xcc04);  // ld a,($cc04)
  I(0x5bae, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x5baf, 4); if (hook_is(gb, 0x1da5, checkEnemyAndPartCollisionsIfTextInactive_hook)) { checkEnemyAndPartCollisionsIfTextInactive_hook(gb); return; } HANDOFF(0x1da5); } I(0x5baf, 3);  // jp z,$1da5
  I(0x5bb2, 4); if (hook_is(gb, 0x5cb4, setCutsceneIndexIfCutsceneTriggerSet_hook)) { setCutsceneIndexIfCutsceneTriggerSet_hook(gb); return; } HANDOFF(0x5cb4);  // jp $5cb4
}

// 01:613a
void s_cutscene14(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x613a, s_cutscene14__handleCutscene, 0x6140, 0x613d);  // call $6140
L_613d:
  I(0x613d, 4); if (hook_is(gb, 0x3382, updateAllObjects_hook)) { updateAllObjects_hook(gb); return; } HANDOFF(0x3382);  // jp $3382
}

// 01:613d
void s_cutscene14__afterCall613d(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_613d:
  I(0x613d, 4); if (hook_is(gb, 0x3382, updateAllObjects_hook)) { updateAllObjects_hook(gb); return; } HANDOFF(0x3382);  // jp $3382
}

// 01:6140
void s_cutscene14__handleCutscene(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6140:
  I(0x6140, 4); A = mem_rd(gb, 0xcc03);  // ld a,($cc03)
  RST_PUSH(0x6143, 0x6144);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x614a: goto L_614a; case 0x617f: goto L_617f; case 0x61f8: goto L_61f8; default: HANDOFF(HL); }
L_614a:
  CALL(0x614a, reloadTileMap_hook, 0x12ba, 0x614d);  // call $12ba
  I(0x614d, 2); A = 0x36;  // ld a,$36
  CALL(0x614f, checkTreasureObtained_hook, 0x1717, 0x6152);  // call $1717
  I(0x6152, 2); A = 0x01;  // ld a,$01
  if (!(F & FC)) { I(0x6154, 3); goto L_6157; } I(0x6154, 2);  // jr nc,$6157
  I(0x6156, 1); A = alu_inc8(gb, A);  // inc a
L_6157:
  I(0x6157, 4); mem_wr(gb, 0xcc03, A);  // ld ($cc03),a
  I(0x615a, 1); alu_xor(gb, A);  // xor a
  I(0x615b, 4); mem_wr(gb, 0xcbb3, A);  // ld ($cbb3),a
  I(0x615e, 4); mem_wr(gb, 0xcd00, A);  // ld ($cd00),a
  I(0x6161, 2); A = 0x28;  // ld a,$28
  I(0x6163, 4); mem_wr(gb, 0xcbb4, A);  // ld ($cbb4),a
  RET(0x6166); return;  // ret
L_616f:
  I(0x616f, 3); SET_HL(0xcbb3);  // ld hl,$cbb3
  I(0x6172, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  RET(0x6173); return;  // ret
L_617f:
  I(0x617f, 4); A = mem_rd(gb, 0xcbb3);  // ld a,($cbb3)
  RST_PUSH(0x6182, 0x6183);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x618b: goto L_618b; case 0x61a8: goto L_61a8; case 0x61b7: goto L_61b7; case 0x61bc: goto L_61bc; default: HANDOFF(HL); }
L_618b:
  CALL(0x618b, s_cutscene14__incSubstate, 0x616f, 0x618e);  // call $616f
  I(0x618e, 2); A = 0x10;  // ld a,$10
  I(0x6190, 4); mem_wr(gb, 0xc490, A);  // ld ($c490),a
  I(0x6193, 2); A = 0x02;  // ld a,$02
  I(0x6195, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x6197, 1); alu_xor(gb, A);  // xor a
  I(0x6198, 4); mem_wr(gb, 0xcbb7, A);  // ld ($cbb7),a
  CALL(0x619b, s_cutscene14__initWaveScrollValues_everyOtherLine, 0x627a, 0x619e);  // call $627a
  I(0x619e, 2); A = 0x10;  // ld a,$10
  I(0x61a0, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x61a3, 2); A = 0xb9;  // ld a,$b9
  I(0x61a5, 4); if (hook_is(gb, 0x0c74, playSound_b00_hook)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c74);  // jp $0c74
L_61a8:
  I(0x61a8, 2); A = 0x02;  // ld a,$02
  CALL(0x61aa, loadBigBufferScrollValues_hook, 0x1393, 0x61ad);  // call $1393
  I(0x61ad, 3); SET_HL(0xcbb7);  // ld hl,$cbb7
  I(0x61b0, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x61b1, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x61b2, 4); goto L_627a; } I(0x61b2, 3);  // jp nz,$627a
  I(0x61b5, 3); goto L_616f;  // jr $616f
L_61b7:
  I(0x61b7, 2); A = 0x02;  // ld a,$02
  I(0x61b9, 4); if (hook_is(gb, 0x1393, loadBigBufferScrollValues_hook)) { loadBigBufferScrollValues_hook(gb); return; } HANDOFF(0x1393);  // jp $1393
L_61bc:
  I(0x61bc, 2); A = 0x02;  // ld a,$02
  CALL(0x61be, loadBigBufferScrollValues_hook, 0x1393, 0x61c1);  // call $1393
  I(0x61c1, 4); A = mem_rd(gb, 0xc4ab);  // ld a,($c4ab)
  I(0x61c4, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x61c5); return; } I(0x61c5, 2);  // ret nz
  I(0x61c6, 4); A = mem_rd(gb, 0xd00d);  // ld a,($d00d)
  I(0x61c9, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x61cb, 2); A = alu_swap(gb, A);  // swap a
  I(0x61cd, 2); alu_or(gb, 0x10);  // or $10
  I(0x61cf, 4); mem_wr(gb, 0xcc66, A);  // ld ($cc66),a
  I(0x61d2, 2); A = 0x80;  // ld a,$80
  I(0x61d4, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x61d7, 2); A = 0x33;  // ld a,$33
  I(0x61d9, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x61dc, 2); A = 0x0c;  // ld a,$0c
  I(0x61de, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x61e1, 1); alu_xor(gb, A);  // xor a
  I(0x61e2, 4); mem_wr(gb, 0xcc6b, A);  // ld ($cc6b),a
  I(0x61e5, 2); A = 0x03;  // ld a,$03
  I(0x61e7, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  I(0x61ea, 2); A = 0x03;  // ld a,$03
  I(0x61ec, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x61ee, 2); A = 0x24;  // ld a,$24
  CALL(0x61f0, setGlobalFlag_hook, 0x30cd, 0x61f3);  // call $30cd
  I(0x61f3, 2); A = 0xf1;  // ld a,$f1
  I(0x61f5, 4); if (hook_is(gb, 0x0c74, playSound_b00_hook)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c74);  // jp $0c74
L_61f8:
  I(0x61f8, 4); A = mem_rd(gb, 0xcbb3);  // ld a,($cbb3)
  RST_PUSH(0x61fb, 0x61fc);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x61b7: goto L_61b7; case 0x6204: goto L_6204; case 0x6220: goto L_6220; case 0x624c: goto L_624c; default: HANDOFF(HL); }
L_6204:
  CALL(0x6204, s_cutscene14__state1__substate0, 0x618b, 0x6207);  // call $618b
  I(0x6207, 2); A = 0xab;  // ld a,$ab
  CALL(0x6209, loadPaletteHeader_hook, 0x04e7, 0x620c);  // call $04e7
  CALL(0x620c, resetLinkInvincibility_hook, 0x2af0, 0x620f);  // call $2af0
  I(0x620f, 2); A = 0x0b;  // ld a,$0b
  I(0x6211, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x6214, 2); A = 0x20;  // ld a,$20
  I(0x6216, 4); mem_wr(gb, 0xcc6c, A);  // ld ($cc6c),a
  I(0x6219, 1); alu_xor(gb, A);  // xor a
  I(0x621a, 3); SET_HL(0xd008);  // ld hl,$d008
  I(0x621d, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x621e, 2); mem_wr(gb, HL, A);  // ld (hl),a
  RET(0x621f); return;  // ret
L_6220:
  I(0x6220, 2); A = 0x02;  // ld a,$02
  CALL(0x6222, loadBigBufferScrollValues_hook, 0x1393, 0x6225);  // call $1393
  I(0x6225, 3); SET_HL(0xcbb7);  // ld hl,$cbb7
  I(0x6228, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x6229, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x622a, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x622b, 4); goto L_627a; } I(0x622b, 3);  // jp nz,$627a
  CALL(0x622e, s_cutscene14__incSubstate, 0x616f, 0x6231);  // call $616f
  CALL(0x6231, getFreeInteractionSlot_hook, 0x3ac6, 0x6234);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x6234); return; } I(0x6234, 2);  // ret nz
  I(0x6235, 3); mem_wr(gb, HL, 0xde);  // ld (hl),$de
  RET(0x6237); return;  // ret
L_624c:
  I(0x624c, 2); A = 0x02;  // ld a,$02
  CALL(0x624e, loadBigBufferScrollValues_hook, 0x1393, 0x6251);  // call $1393
  I(0x6251, 3); SET_HL(0xcbb7);  // ld hl,$cbb7
  I(0x6254, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x6255, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x6256, 4); goto L_627a; } I(0x6256, 3);  // jp nz,$627a
  CALL(0x6259, refreshObjectGfx_hook, 0x1606, 0x625c);  // call $1606
  I(0x625c, 2); A = 0x01;  // ld a,$01
  I(0x625e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x6261, 3); SET_HL(0x7e40);  // ld hl,$7e40
  CALL(0x6264, parseGivenObjectData_b00_hook, 0x3048, 0x6267);  // call $3048
  I(0x6267, 2); A = 0x01;  // ld a,$01
  I(0x6269, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  I(0x626c, 2); A = 0x03;  // ld a,$03
  I(0x626e, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x6270, 2); A = 0x01;  // ld a,$01
  I(0x6272, 4); mem_wr(gb, 0xcd00, A);  // ld ($cd00),a
  I(0x6275, 2); A = 0xf1;  // ld a,$f1
  I(0x6277, 4); if (hook_is(gb, 0x0c74, playSound_b00_hook)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c74);  // jp $0c74
L_627a:
  CALL(0x627a, initWaveScrollValues_hook, 0x1372, 0x627d);  // call $1372
  I(0x627d, 2); A = 0x02;  // ld a,$02
  I(0x627f, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6281, 3); SET_HL(0xd800);  // ld hl,$d800
  I(0x6284, 2); B = 0x80;  // ld b,$80
L_6286:
  I(0x6286, 1); alu_xor(gb, A);  // xor a
  I(0x6287, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x6288, 2); SET_HL(HL + 1);  // inc hl
  I(0x6289, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x628a, 3); goto L_6286; } I(0x628a, 2);  // jr nz,$6286
  I(0x628c, 1); alu_xor(gb, A);  // xor a
  I(0x628d, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  RET(0x628f); return;  // ret
}

// 01:614a
void s_cutscene14__state0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_614a:
  CALL(0x614a, reloadTileMap_hook, 0x12ba, 0x614d);  // call $12ba
  I(0x614d, 2); A = 0x36;  // ld a,$36
  CALL(0x614f, checkTreasureObtained_hook, 0x1717, 0x6152);  // call $1717
  I(0x6152, 2); A = 0x01;  // ld a,$01
  if (!(F & FC)) { I(0x6154, 3); goto L_6157; } I(0x6154, 2);  // jr nc,$6157
  I(0x6156, 1); A = alu_inc8(gb, A);  // inc a
L_6157:
  I(0x6157, 4); mem_wr(gb, 0xcc03, A);  // ld ($cc03),a
  I(0x615a, 1); alu_xor(gb, A);  // xor a
  I(0x615b, 4); mem_wr(gb, 0xcbb3, A);  // ld ($cbb3),a
  I(0x615e, 4); mem_wr(gb, 0xcd00, A);  // ld ($cd00),a
  I(0x6161, 2); A = 0x28;  // ld a,$28
  I(0x6163, 4); mem_wr(gb, 0xcbb4, A);  // ld ($cbb4),a
  RET(0x6166); return;  // ret
}

// 01:616f
void s_cutscene14__incSubstate(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_616f:
  I(0x616f, 3); SET_HL(0xcbb3);  // ld hl,$cbb3
  I(0x6172, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  RET(0x6173); return;  // ret
}

// 01:617f
void s_cutscene14__state1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_617f;
L_616f:
  I(0x616f, 3); SET_HL(0xcbb3);  // ld hl,$cbb3
  I(0x6172, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  RET(0x6173); return;  // ret
L_617f:
  I(0x617f, 4); A = mem_rd(gb, 0xcbb3);  // ld a,($cbb3)
  RST_PUSH(0x6182, 0x6183);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x618b: goto L_618b; case 0x61a8: goto L_61a8; case 0x61b7: goto L_61b7; case 0x61bc: goto L_61bc; default: HANDOFF(HL); }
L_618b:
  CALL(0x618b, s_cutscene14__incSubstate, 0x616f, 0x618e);  // call $616f
  I(0x618e, 2); A = 0x10;  // ld a,$10
  I(0x6190, 4); mem_wr(gb, 0xc490, A);  // ld ($c490),a
  I(0x6193, 2); A = 0x02;  // ld a,$02
  I(0x6195, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x6197, 1); alu_xor(gb, A);  // xor a
  I(0x6198, 4); mem_wr(gb, 0xcbb7, A);  // ld ($cbb7),a
  CALL(0x619b, s_cutscene14__initWaveScrollValues_everyOtherLine, 0x627a, 0x619e);  // call $627a
  I(0x619e, 2); A = 0x10;  // ld a,$10
  I(0x61a0, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x61a3, 2); A = 0xb9;  // ld a,$b9
  I(0x61a5, 4); if (hook_is(gb, 0x0c74, playSound_b00_hook)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c74);  // jp $0c74
L_61a8:
  I(0x61a8, 2); A = 0x02;  // ld a,$02
  CALL(0x61aa, loadBigBufferScrollValues_hook, 0x1393, 0x61ad);  // call $1393
  I(0x61ad, 3); SET_HL(0xcbb7);  // ld hl,$cbb7
  I(0x61b0, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x61b1, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x61b2, 4); goto L_627a; } I(0x61b2, 3);  // jp nz,$627a
  I(0x61b5, 3); goto L_616f;  // jr $616f
L_61b7:
  I(0x61b7, 2); A = 0x02;  // ld a,$02
  I(0x61b9, 4); if (hook_is(gb, 0x1393, loadBigBufferScrollValues_hook)) { loadBigBufferScrollValues_hook(gb); return; } HANDOFF(0x1393);  // jp $1393
L_61bc:
  I(0x61bc, 2); A = 0x02;  // ld a,$02
  CALL(0x61be, loadBigBufferScrollValues_hook, 0x1393, 0x61c1);  // call $1393
  I(0x61c1, 4); A = mem_rd(gb, 0xc4ab);  // ld a,($c4ab)
  I(0x61c4, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x61c5); return; } I(0x61c5, 2);  // ret nz
  I(0x61c6, 4); A = mem_rd(gb, 0xd00d);  // ld a,($d00d)
  I(0x61c9, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x61cb, 2); A = alu_swap(gb, A);  // swap a
  I(0x61cd, 2); alu_or(gb, 0x10);  // or $10
  I(0x61cf, 4); mem_wr(gb, 0xcc66, A);  // ld ($cc66),a
  I(0x61d2, 2); A = 0x80;  // ld a,$80
  I(0x61d4, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x61d7, 2); A = 0x33;  // ld a,$33
  I(0x61d9, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x61dc, 2); A = 0x0c;  // ld a,$0c
  I(0x61de, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x61e1, 1); alu_xor(gb, A);  // xor a
  I(0x61e2, 4); mem_wr(gb, 0xcc6b, A);  // ld ($cc6b),a
  I(0x61e5, 2); A = 0x03;  // ld a,$03
  I(0x61e7, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  I(0x61ea, 2); A = 0x03;  // ld a,$03
  I(0x61ec, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x61ee, 2); A = 0x24;  // ld a,$24
  CALL(0x61f0, setGlobalFlag_hook, 0x30cd, 0x61f3);  // call $30cd
  I(0x61f3, 2); A = 0xf1;  // ld a,$f1
  I(0x61f5, 4); if (hook_is(gb, 0x0c74, playSound_b00_hook)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c74);  // jp $0c74
L_627a:
  CALL(0x627a, initWaveScrollValues_hook, 0x1372, 0x627d);  // call $1372
  I(0x627d, 2); A = 0x02;  // ld a,$02
  I(0x627f, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6281, 3); SET_HL(0xd800);  // ld hl,$d800
  I(0x6284, 2); B = 0x80;  // ld b,$80
L_6286:
  I(0x6286, 1); alu_xor(gb, A);  // xor a
  I(0x6287, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x6288, 2); SET_HL(HL + 1);  // inc hl
  I(0x6289, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x628a, 3); goto L_6286; } I(0x628a, 2);  // jr nz,$6286
  I(0x628c, 1); alu_xor(gb, A);  // xor a
  I(0x628d, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  RET(0x628f); return;  // ret
}

// 01:618b
void s_cutscene14__state1__substate0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_618b:
  CALL(0x618b, s_cutscene14__incSubstate, 0x616f, 0x618e);  // call $616f
  I(0x618e, 2); A = 0x10;  // ld a,$10
  I(0x6190, 4); mem_wr(gb, 0xc490, A);  // ld ($c490),a
  I(0x6193, 2); A = 0x02;  // ld a,$02
  I(0x6195, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x6197, 1); alu_xor(gb, A);  // xor a
  I(0x6198, 4); mem_wr(gb, 0xcbb7, A);  // ld ($cbb7),a
  CALL(0x619b, s_cutscene14__initWaveScrollValues_everyOtherLine, 0x627a, 0x619e);  // call $627a
  I(0x619e, 2); A = 0x10;  // ld a,$10
  I(0x61a0, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x61a3, 2); A = 0xb9;  // ld a,$b9
  I(0x61a5, 4); if (hook_is(gb, 0x0c74, playSound_b00_hook)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c74);  // jp $0c74
}

// 01:61a8
void s_cutscene14__state1__substate1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_61a8;
L_616f:
  I(0x616f, 3); SET_HL(0xcbb3);  // ld hl,$cbb3
  I(0x6172, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  RET(0x6173); return;  // ret
L_61a8:
  I(0x61a8, 2); A = 0x02;  // ld a,$02
  CALL(0x61aa, loadBigBufferScrollValues_hook, 0x1393, 0x61ad);  // call $1393
  I(0x61ad, 3); SET_HL(0xcbb7);  // ld hl,$cbb7
  I(0x61b0, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x61b1, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x61b2, 4); goto L_627a; } I(0x61b2, 3);  // jp nz,$627a
  I(0x61b5, 3); goto L_616f;  // jr $616f
L_627a:
  CALL(0x627a, initWaveScrollValues_hook, 0x1372, 0x627d);  // call $1372
  I(0x627d, 2); A = 0x02;  // ld a,$02
  I(0x627f, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6281, 3); SET_HL(0xd800);  // ld hl,$d800
  I(0x6284, 2); B = 0x80;  // ld b,$80
L_6286:
  I(0x6286, 1); alu_xor(gb, A);  // xor a
  I(0x6287, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x6288, 2); SET_HL(HL + 1);  // inc hl
  I(0x6289, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x628a, 3); goto L_6286; } I(0x628a, 2);  // jr nz,$6286
  I(0x628c, 1); alu_xor(gb, A);  // xor a
  I(0x628d, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  RET(0x628f); return;  // ret
}

// 01:61b7
void s_cutscene14__state1__substate2(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_61b7:
  I(0x61b7, 2); A = 0x02;  // ld a,$02
  I(0x61b9, 4); if (hook_is(gb, 0x1393, loadBigBufferScrollValues_hook)) { loadBigBufferScrollValues_hook(gb); return; } HANDOFF(0x1393);  // jp $1393
}

// 01:61bc
void s_cutscene14__state1__substate3(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_61bc:
  I(0x61bc, 2); A = 0x02;  // ld a,$02
  CALL(0x61be, loadBigBufferScrollValues_hook, 0x1393, 0x61c1);  // call $1393
  I(0x61c1, 4); A = mem_rd(gb, 0xc4ab);  // ld a,($c4ab)
  I(0x61c4, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x61c5); return; } I(0x61c5, 2);  // ret nz
  I(0x61c6, 4); A = mem_rd(gb, 0xd00d);  // ld a,($d00d)
  I(0x61c9, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x61cb, 2); A = alu_swap(gb, A);  // swap a
  I(0x61cd, 2); alu_or(gb, 0x10);  // or $10
  I(0x61cf, 4); mem_wr(gb, 0xcc66, A);  // ld ($cc66),a
  I(0x61d2, 2); A = 0x80;  // ld a,$80
  I(0x61d4, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x61d7, 2); A = 0x33;  // ld a,$33
  I(0x61d9, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x61dc, 2); A = 0x0c;  // ld a,$0c
  I(0x61de, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x61e1, 1); alu_xor(gb, A);  // xor a
  I(0x61e2, 4); mem_wr(gb, 0xcc6b, A);  // ld ($cc6b),a
  I(0x61e5, 2); A = 0x03;  // ld a,$03
  I(0x61e7, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  I(0x61ea, 2); A = 0x03;  // ld a,$03
  I(0x61ec, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x61ee, 2); A = 0x24;  // ld a,$24
  CALL(0x61f0, setGlobalFlag_hook, 0x30cd, 0x61f3);  // call $30cd
  I(0x61f3, 2); A = 0xf1;  // ld a,$f1
  I(0x61f5, 4); if (hook_is(gb, 0x0c74, playSound_b00_hook)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c74);  // jp $0c74
}

// 01:61f8
void s_cutscene14__state2(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_61f8;
L_61b7:
  I(0x61b7, 2); A = 0x02;  // ld a,$02
  I(0x61b9, 4); if (hook_is(gb, 0x1393, loadBigBufferScrollValues_hook)) { loadBigBufferScrollValues_hook(gb); return; } HANDOFF(0x1393);  // jp $1393
L_61f8:
  I(0x61f8, 4); A = mem_rd(gb, 0xcbb3);  // ld a,($cbb3)
  RST_PUSH(0x61fb, 0x61fc);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) { case 0x61b7: goto L_61b7; case 0x6204: goto L_6204; case 0x6220: goto L_6220; case 0x624c: goto L_624c; default: HANDOFF(HL); }
L_6204:
  CALL(0x6204, s_cutscene14__state1__substate0, 0x618b, 0x6207);  // call $618b
  I(0x6207, 2); A = 0xab;  // ld a,$ab
  CALL(0x6209, loadPaletteHeader_hook, 0x04e7, 0x620c);  // call $04e7
  CALL(0x620c, resetLinkInvincibility_hook, 0x2af0, 0x620f);  // call $2af0
  I(0x620f, 2); A = 0x0b;  // ld a,$0b
  I(0x6211, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x6214, 2); A = 0x20;  // ld a,$20
  I(0x6216, 4); mem_wr(gb, 0xcc6c, A);  // ld ($cc6c),a
  I(0x6219, 1); alu_xor(gb, A);  // xor a
  I(0x621a, 3); SET_HL(0xd008);  // ld hl,$d008
  I(0x621d, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x621e, 2); mem_wr(gb, HL, A);  // ld (hl),a
  RET(0x621f); return;  // ret
L_6220:
  I(0x6220, 2); A = 0x02;  // ld a,$02
  CALL(0x6222, loadBigBufferScrollValues_hook, 0x1393, 0x6225);  // call $1393
  I(0x6225, 3); SET_HL(0xcbb7);  // ld hl,$cbb7
  I(0x6228, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x6229, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x622a, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x622b, 4); goto L_627a; } I(0x622b, 3);  // jp nz,$627a
  CALL(0x622e, s_cutscene14__incSubstate, 0x616f, 0x6231);  // call $616f
  CALL(0x6231, getFreeInteractionSlot_hook, 0x3ac6, 0x6234);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x6234); return; } I(0x6234, 2);  // ret nz
  I(0x6235, 3); mem_wr(gb, HL, 0xde);  // ld (hl),$de
  RET(0x6237); return;  // ret
L_624c:
  I(0x624c, 2); A = 0x02;  // ld a,$02
  CALL(0x624e, loadBigBufferScrollValues_hook, 0x1393, 0x6251);  // call $1393
  I(0x6251, 3); SET_HL(0xcbb7);  // ld hl,$cbb7
  I(0x6254, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x6255, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x6256, 4); goto L_627a; } I(0x6256, 3);  // jp nz,$627a
  CALL(0x6259, refreshObjectGfx_hook, 0x1606, 0x625c);  // call $1606
  I(0x625c, 2); A = 0x01;  // ld a,$01
  I(0x625e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x6261, 3); SET_HL(0x7e40);  // ld hl,$7e40
  CALL(0x6264, parseGivenObjectData_b00_hook, 0x3048, 0x6267);  // call $3048
  I(0x6267, 2); A = 0x01;  // ld a,$01
  I(0x6269, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  I(0x626c, 2); A = 0x03;  // ld a,$03
  I(0x626e, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x6270, 2); A = 0x01;  // ld a,$01
  I(0x6272, 4); mem_wr(gb, 0xcd00, A);  // ld ($cd00),a
  I(0x6275, 2); A = 0xf1;  // ld a,$f1
  I(0x6277, 4); if (hook_is(gb, 0x0c74, playSound_b00_hook)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c74);  // jp $0c74
L_627a:
  CALL(0x627a, initWaveScrollValues_hook, 0x1372, 0x627d);  // call $1372
  I(0x627d, 2); A = 0x02;  // ld a,$02
  I(0x627f, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6281, 3); SET_HL(0xd800);  // ld hl,$d800
  I(0x6284, 2); B = 0x80;  // ld b,$80
L_6286:
  I(0x6286, 1); alu_xor(gb, A);  // xor a
  I(0x6287, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x6288, 2); SET_HL(HL + 1);  // inc hl
  I(0x6289, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x628a, 3); goto L_6286; } I(0x628a, 2);  // jr nz,$6286
  I(0x628c, 1); alu_xor(gb, A);  // xor a
  I(0x628d, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  RET(0x628f); return;  // ret
}

// 01:6204
void s_cutscene14__state2__substate0(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6204:
  CALL(0x6204, s_cutscene14__state1__substate0, 0x618b, 0x6207);  // call $618b
  I(0x6207, 2); A = 0xab;  // ld a,$ab
  CALL(0x6209, loadPaletteHeader_hook, 0x04e7, 0x620c);  // call $04e7
  CALL(0x620c, resetLinkInvincibility_hook, 0x2af0, 0x620f);  // call $2af0
  I(0x620f, 2); A = 0x0b;  // ld a,$0b
  I(0x6211, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x6214, 2); A = 0x20;  // ld a,$20
  I(0x6216, 4); mem_wr(gb, 0xcc6c, A);  // ld ($cc6c),a
  I(0x6219, 1); alu_xor(gb, A);  // xor a
  I(0x621a, 3); SET_HL(0xd008);  // ld hl,$d008
  I(0x621d, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x621e, 2); mem_wr(gb, HL, A);  // ld (hl),a
  RET(0x621f); return;  // ret
}

// 01:6220
void s_cutscene14__state2__substate1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6220:
  I(0x6220, 2); A = 0x02;  // ld a,$02
  CALL(0x6222, loadBigBufferScrollValues_hook, 0x1393, 0x6225);  // call $1393
  I(0x6225, 3); SET_HL(0xcbb7);  // ld hl,$cbb7
  I(0x6228, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x6229, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x622a, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x622b, 4); goto L_627a; } I(0x622b, 3);  // jp nz,$627a
  CALL(0x622e, s_cutscene14__incSubstate, 0x616f, 0x6231);  // call $616f
  CALL(0x6231, getFreeInteractionSlot_hook, 0x3ac6, 0x6234);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x6234); return; } I(0x6234, 2);  // ret nz
  I(0x6235, 3); mem_wr(gb, HL, 0xde);  // ld (hl),$de
  RET(0x6237); return;  // ret
L_627a:
  CALL(0x627a, initWaveScrollValues_hook, 0x1372, 0x627d);  // call $1372
  I(0x627d, 2); A = 0x02;  // ld a,$02
  I(0x627f, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6281, 3); SET_HL(0xd800);  // ld hl,$d800
  I(0x6284, 2); B = 0x80;  // ld b,$80
L_6286:
  I(0x6286, 1); alu_xor(gb, A);  // xor a
  I(0x6287, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x6288, 2); SET_HL(HL + 1);  // inc hl
  I(0x6289, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x628a, 3); goto L_6286; } I(0x628a, 2);  // jr nz,$6286
  I(0x628c, 1); alu_xor(gb, A);  // xor a
  I(0x628d, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  RET(0x628f); return;  // ret
}

// 01:624c
void s_cutscene14__state2__substate3(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_624c:
  I(0x624c, 2); A = 0x02;  // ld a,$02
  CALL(0x624e, loadBigBufferScrollValues_hook, 0x1393, 0x6251);  // call $1393
  I(0x6251, 3); SET_HL(0xcbb7);  // ld hl,$cbb7
  I(0x6254, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x6255, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x6256, 4); goto L_627a; } I(0x6256, 3);  // jp nz,$627a
  CALL(0x6259, refreshObjectGfx_hook, 0x1606, 0x625c);  // call $1606
  I(0x625c, 2); A = 0x01;  // ld a,$01
  I(0x625e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x6261, 3); SET_HL(0x7e40);  // ld hl,$7e40
  CALL(0x6264, parseGivenObjectData_b00_hook, 0x3048, 0x6267);  // call $3048
  I(0x6267, 2); A = 0x01;  // ld a,$01
  I(0x6269, 4); mem_wr(gb, 0xc2ef, A);  // ld ($c2ef),a
  I(0x626c, 2); A = 0x03;  // ld a,$03
  I(0x626e, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x6270, 2); A = 0x01;  // ld a,$01
  I(0x6272, 4); mem_wr(gb, 0xcd00, A);  // ld ($cd00),a
  I(0x6275, 2); A = 0xf1;  // ld a,$f1
  I(0x6277, 4); if (hook_is(gb, 0x0c74, playSound_b00_hook)) { playSound_b00_hook(gb); return; } HANDOFF(0x0c74);  // jp $0c74
L_627a:
  CALL(0x627a, initWaveScrollValues_hook, 0x1372, 0x627d);  // call $1372
  I(0x627d, 2); A = 0x02;  // ld a,$02
  I(0x627f, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6281, 3); SET_HL(0xd800);  // ld hl,$d800
  I(0x6284, 2); B = 0x80;  // ld b,$80
L_6286:
  I(0x6286, 1); alu_xor(gb, A);  // xor a
  I(0x6287, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x6288, 2); SET_HL(HL + 1);  // inc hl
  I(0x6289, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x628a, 3); goto L_6286; } I(0x628a, 2);  // jr nz,$6286
  I(0x628c, 1); alu_xor(gb, A);  // xor a
  I(0x628d, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  RET(0x628f); return;  // ret
}

// 01:627a
void s_cutscene14__initWaveScrollValues_everyOtherLine(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_627a:
  CALL(0x627a, initWaveScrollValues_hook, 0x1372, 0x627d);  // call $1372
  I(0x627d, 2); A = 0x02;  // ld a,$02
  I(0x627f, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6281, 3); SET_HL(0xd800);  // ld hl,$d800
  I(0x6284, 2); B = 0x80;  // ld b,$80
L_6286:
  I(0x6286, 1); alu_xor(gb, A);  // xor a
  I(0x6287, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x6288, 2); SET_HL(HL + 1);  // inc hl
  I(0x6289, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x628a, 3); goto L_6286; } I(0x628a, 2);  // jr nz,$6286
  I(0x628c, 1); alu_xor(gb, A);  // xor a
  I(0x628d, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  RET(0x628f); return;  // ret
}

// 01:4c0f
void s_cutscene15__state1__substate2(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4c0f:
  CALL(0x4c0f, disableLcd_hook, 0x02c1, 0x4c12);  // call $02c1
  CALL(0x4c12, clearOam_hook, 0x047b, 0x4c15);  // call $047b
  I(0x4c15, 1); alu_xor(gb, A);  // xor a
  I(0x4c16, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x4c18, 3); SET_HL(0xd040);  // ld hl,$d040
  I(0x4c1b, 3); SET_BC(0x0fc0);  // ld bc,$0fc0
  CALL(0x4c1e, clearMemoryBc_hook, 0x0451, 0x4c21);  // call $0451
  CALL(0x4c21, clearScreenVariables_hook, 0x3528, 0x4c24);  // call $3528
  CALL(0x4c24, clearMemoryOnScreenReload_hook, 0x493c, 0x4c27);  // call $493c
  CALL(0x4c27, stopTextThread_hook, 0x1826, 0x4c2a);  // call $1826
  CALL(0x4c2a, applyWarpDest_hook, 0x32be, 0x4c2d);  // call $32be
  CALL(0x4c2d, loadTilesetData_hook, 0x381a, 0x4c30);  // call $381a
  CALL(0x4c30, loadTilesetGraphics_hook, 0x3737, 0x4c33);  // call $3737
  CALL(0x4c33, loadDungeonLayout_hook, 0x2cfd, 0x4c36);  // call $2cfd
  CALL(0x4c36, func_131f_hook, 0x12dd, 0x4c39);  // call $12dd
  CALL(0x4c39, clearEnemiesKilledList_b00_hook, 0x30d9, 0x4c3c);  // call $30d9
  CALL(0x4c3c, func_5c6b_hook, 0x5a58, 0x4c3f);  // call $5a58
  s_cutscene15__state1__substate2__afterCall4ca4(gb); return;  // fallthrough
}

// 01:4c3f
void s_cutscene15__state1__substate2__afterCall4ca4(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x4c3f, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x4c42, 2); alu_cp(gb, 0x03);  // cp $03
  if (!(F & FZ)) { I(0x4c44, 3); goto L_4c58; } I(0x4c44, 2);  // jr nz,$4c58
  I(0x4c46, 1); alu_xor(gb, A);  // xor a
  I(0x4c47, 4); mem_wr(gb, 0xc63a, A);  // ld ($c63a),a
  I(0x4c4a, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x4c4d, 2); alu_cp(gb, 0xab);  // cp $ab
  I(0x4c4f, 2); A = 0xf7;  // ld a,$f7
  if ((F & FZ)) { I(0x4c51, 3); goto L_4c55; } I(0x4c51, 2);  // jr z,$4c55
  I(0x4c53, 2); A = 0x04;  // ld a,$04
L_4c55:
  I(0x4c55, 4); mem_wr(gb, 0xc63b, A);  // ld ($c63b),a
L_4c58:
  CALL(0x4c58, loadCommonGraphics_hook, 0x1a5e, 0x4c5b);  // call $1a5e
L_4c5b:
  I(0x4c5b, 3); SET_HL(0x3b0a);  // ld hl,$3b0a
  I(0x4c5e, 2); E = 0x00;  // ld e,$00
  CALL(0x4c60, interBankCall_hook, 0x008a, 0x4c63);  // call $008a
L_4c63:
  I(0x4c63, 2); A = 0x02;  // ld a,$02
  CALL(0x4c65, loadGfxRegisterStateIndex_hook, 0x02ea, 0x4c68);  // call $02ea
  I(0x4c68, 2); A = 0x10;  // ld a,$10
  I(0x4c6a, 4); mem_wr(gb, 0xc490, A);  // ld ($c490),a
  I(0x4c6d, 2); A = 0xf0;  // ld a,$f0
  I(0x4c6f, 4); mem_wr(gb, 0xc48c, A);  // ld ($c48c),a
  I(0x4c72, 2); A = 0x02;  // ld a,$02
  I(0x4c74, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x4c76, 3); SET_HL(0xcc03);  // ld hl,$cc03
  I(0x4c79, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x4c7a, 1); alu_xor(gb, A);  // xor a
  I(0x4c7b, 4); mem_wr(gb, 0xcbb3, A);  // ld ($cbb3),a
  I(0x4c7e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x4c81, 2); A = 0x08;  // ld a,$08
  I(0x4c83, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x4c86, 2); A = 0x81;  // ld a,$81
  I(0x4c88, 4); mem_wr(gb, 0xcca4, A);  // ld ($cca4),a
  RET(0x4c8b); return;  // ret
}

// 01:4c5b
void s_cutscene15__state1__substate2__afterCall4ca4__afterCall4c5b(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4c5b:
  I(0x4c5b, 3); SET_HL(0x3b0a);  // ld hl,$3b0a
  I(0x4c5e, 2); E = 0x00;  // ld e,$00
  CALL(0x4c60, interBankCall_hook, 0x008a, 0x4c63);  // call $008a
L_4c63:
  I(0x4c63, 2); A = 0x02;  // ld a,$02
  CALL(0x4c65, loadGfxRegisterStateIndex_hook, 0x02ea, 0x4c68);  // call $02ea
  I(0x4c68, 2); A = 0x10;  // ld a,$10
  I(0x4c6a, 4); mem_wr(gb, 0xc490, A);  // ld ($c490),a
  I(0x4c6d, 2); A = 0xf0;  // ld a,$f0
  I(0x4c6f, 4); mem_wr(gb, 0xc48c, A);  // ld ($c48c),a
  I(0x4c72, 2); A = 0x02;  // ld a,$02
  I(0x4c74, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x4c76, 3); SET_HL(0xcc03);  // ld hl,$cc03
  I(0x4c79, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x4c7a, 1); alu_xor(gb, A);  // xor a
  I(0x4c7b, 4); mem_wr(gb, 0xcbb3, A);  // ld ($cbb3),a
  I(0x4c7e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x4c81, 2); A = 0x08;  // ld a,$08
  I(0x4c83, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x4c86, 2); A = 0x81;  // ld a,$81
  I(0x4c88, 4); mem_wr(gb, 0xcca4, A);  // ld ($cca4),a
  RET(0x4c8b); return;  // ret
}

// 01:4c63
void s_cutscene15__state1__substate2__afterCall4ca4__afterCall4c63(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4c63:
  I(0x4c63, 2); A = 0x02;  // ld a,$02
  CALL(0x4c65, loadGfxRegisterStateIndex_hook, 0x02ea, 0x4c68);  // call $02ea
  I(0x4c68, 2); A = 0x10;  // ld a,$10
  I(0x4c6a, 4); mem_wr(gb, 0xc490, A);  // ld ($c490),a
  I(0x4c6d, 2); A = 0xf0;  // ld a,$f0
  I(0x4c6f, 4); mem_wr(gb, 0xc48c, A);  // ld ($c48c),a
  I(0x4c72, 2); A = 0x02;  // ld a,$02
  I(0x4c74, 3); mem_wr(gb, 0xff9b, A);  // ldh ($ff9b),a
  I(0x4c76, 3); SET_HL(0xcc03);  // ld hl,$cc03
  I(0x4c79, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x4c7a, 1); alu_xor(gb, A);  // xor a
  I(0x4c7b, 4); mem_wr(gb, 0xcbb3, A);  // ld ($cbb3),a
  I(0x4c7e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x4c81, 2); A = 0x08;  // ld a,$08
  I(0x4c83, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x4c86, 2); A = 0x81;  // ld a,$81
  I(0x4c88, 4); mem_wr(gb, 0xcca4, A);  // ld ($cca4),a
  RET(0x4c8b); return;  // ret
}

// 01:551f
void s_findActiveRoomInDungeonLayout(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x551f, 1); alu_xor(gb, A);  // xor a
  CALL(0x5520, getFirstDungeonLayoutAddress_hook, 0x553f, 0x5523);  // call $553f
  I(0x5523, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x5526, 2); C = 0x00;  // ld c,$00
L_5528:
  I(0x5528, 2); B = 0x40;  // ld b,$40
L_552a:
  I(0x552a, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if ((F & FZ)) { I(0x552b, 3); goto L_5534; } I(0x552b, 2);  // jr z,$5534
  I(0x552d, 2); SET_HL(HL + 1);  // inc hl
  I(0x552e, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x552f, 3); goto L_552a; } I(0x552f, 2);  // jr nz,$552a
  I(0x5531, 1); C = alu_inc8(gb, C);  // inc c
  I(0x5532, 3); goto L_5528;  // jr $5528
L_5534:
  I(0x5534, 1); A = C;  // ld a,c
  I(0x5535, 4); mem_wr(gb, 0xcc57, A);  // ld ($cc57),a
  I(0x5538, 2); A = 0x40;  // ld a,$40
  I(0x553a, 1); alu_sub(gb, B);  // sub b
  I(0x553b, 4); mem_wr(gb, 0xcc56, A);  // ld ($cc56),a
  RET(0x553e); return;  // ret
}

// 01:47dd
void s_getPaletteFadeTransitionData(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x47dd, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x47e0, 1); B = A;  // ld b,a
  I(0x47e1, 1); alu_rrca(gb);  // rrca
  I(0x47e2, 2); alu_and(gb, 0x7f);  // and $7f
  if (!(F & FZ)) { RET_TAKEN(0x47e4); return; } I(0x47e4, 2);  // ret nz
  I(0x47e5, 1); A = B;  // ld a,b
  I(0x47e6, 3); SET_HL(0x4875);  // ld hl,$4875
  RST_PUSH(0x47e9, 0x47ea);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x47ea, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x47eb, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x47ec, 1); L = A;  // ld l,a
  I(0x47ed, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x47f0, 1); B = A;  // ld b,a
L_47f1:
  I(0x47f1, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x47f2, 1); C = A;  // ld c,a
  I(0x47f3, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x47f4, 2); alu_cp(gb, 0xff);  // cp $ff
  if ((F & FZ)) { RET_TAKEN(0x47f6); return; } I(0x47f6, 2);  // ret z
  I(0x47f7, 4); A = mem_rd(gb, 0xcd02);  // ld a,($cd02)
  I(0x47fa, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if (!(F & FZ)) { I(0x47fb, 3); goto L_4801; } I(0x47fb, 2);  // jr nz,$4801
  I(0x47fd, 1); A = C;  // ld a,c
  I(0x47fe, 1); alu_cp(gb, B);  // cp b
  if ((F & FZ)) { I(0x47ff, 3); goto L_4806; } I(0x47ff, 2);  // jr z,$4806
L_4801:
  I(0x4801, 2); SET_HL(HL + 1);  // inc hl
  I(0x4802, 2); SET_HL(HL + 1);  // inc hl
  I(0x4803, 2); SET_HL(HL + 1);  // inc hl
  I(0x4804, 3); goto L_47f1;  // jr $47f1
L_4806:
  I(0x4806, 1); alu_scf(gb);  // scf
  RET(0x4807); return;  // ret
}

// 01:5f53
void s_initializeSeedTreeRefillData(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5f53, 2); A = 0xfc;  // ld a,$fc
  I(0x5f55, 4); mem_wr(gb, 0xcc69, A);  // ld ($cc69),a
  I(0x5f58, 2); A = 0x03;  // ld a,$03
  I(0x5f5a, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x5f5c, 3); SET_HL(0xdfc0);  // ld hl,$dfc0
  I(0x5f5f, 2); B = 0x40;  // ld b,$40
  CALL(0x5f61, clearMemory_hook, 0x044b, 0x5f64);  // call $044b
  I(0x5f64, 1); alu_xor(gb, A);  // xor a
  I(0x5f65, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  RET(0x5f67); return;  // ret
}

// 01:489d
void s_makeActiveObjectFollowLink_b01(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x489d, 3); SET_HL(0xccfd);  // ld hl,$ccfd
  I(0x48a0, 3); A = mem_rd(gb, 0xffac);  // ldh a,($ffac)
  I(0x48a2, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x48a3, 3); A = mem_rd(gb, 0xffad);  // ldh a,($ffad)
  I(0x48a5, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  if (hook_is(gb, 0x48a6, resetFollowingLinkPath_hook)) { resetFollowingLinkPath_hook(gb); return; } HANDOFF(0x48a6);  // fallthrough
}

// 01:5612
void s_paletteFadeHandler06(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5612, 1); alu_xor(gb, A);  // xor a
  I(0x5613, 3); mem_wr(gb, 0xff8b, A);  // ldh ($ff8b),a
  I(0x5615, 4); A = mem_rd(gb, 0xc4ae);  // ld a,($c4ae)
  I(0x5618, 1); A = alu_inc8(gb, A);  // inc a
  I(0x5619, 1); B = A;  // ld b,a
  I(0x561a, 4); A = mem_rd(gb, 0xc2ff);  // ld a,($c2ff)
  I(0x561d, 1); A = alu_inc8(gb, A);  // inc a
  I(0x561e, 1); alu_cp(gb, B);  // cp b
  if ((F & FZ)) { I(0x561f, 3); if (hook_is(gb, 0x55e8, paletteThread_stop_hook)) { paletteThread_stop_hook(gb); return; } HANDOFF(0x55e8); } I(0x561f, 2);  // jr z,$55e8
  I(0x5621, 4); mem_wr(gb, 0xc2ff, A);  // ld ($c2ff),a
  I(0x5624, 1); C = A;  // ld c,a
  I(0x5625, 4); if (hook_is(gb, 0x5586, updateFadingPalettes_hook)) { updateFadingPalettes_hook(gb); return; } HANDOFF(0x5586);  // jp $5586
}

// 01:5ec2
void s_screenTransitionEyePuzzle__up(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5ec2:
  I(0x5ec2, 4); A = mem_rd(gb, 0xcc53);  // ld a,($cc53)
  I(0x5ec5, 2); alu_cp(gb, 0x06);  // cp $06
  if ((F & FC)) { I(0x5ec7, 3); goto L_5ecc; } I(0x5ec7, 2);  // jr c,$5ecc
  I(0x5ec9, 4); if (hook_is(gb, 0x5da5, screenTransitionStandard_hook)) { screenTransitionStandard_hook(gb); return; } HANDOFF(0x5da5);  // jp $5da5
L_5ecc:
  I(0x5ecc, 1); alu_scf(gb);  // scf
  RET(0x5ecd); return;  // ret
}

// 01:5ecc
void s_screenTransitionEyePuzzle__rightOrLeft(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5ecc:
  I(0x5ecc, 1); alu_scf(gb);  // scf
  RET(0x5ecd); return;  // ret
}

// 01:5d6c
void s_updateActiveRoom__dungeon(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5d6c:
  I(0x5d6c, 4); A = mem_rd(gb, 0xcd02);  // ld a,($cd02)
  I(0x5d6f, 3); SET_HL(0x5d87);  // ld hl,$5d87
  RST_PUSH(0x5d72, 0x5d73);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x5d73, 4); A = mem_rd(gb, 0xcc56);  // ld a,($cc56)
  I(0x5d76, 2); alu_add(gb, mem_rd(gb, HL));  // add (hl)
  I(0x5d77, 4); mem_wr(gb, 0xcc56, A);  // ld ($cc56),a
  CALL(0x5d7a, getActiveRoomFromDungeonMapPosition_hook, 0x2d65, 0x5d7d);  // call $2d65
L_5d7d:
  I(0x5d7d, 4); mem_wr(gb, 0xcc4c, A);  // ld ($cc4c),a
  I(0x5d80, 4); if (hook_is(gb, 0x2d24, setVisitedRoomFlag_hook)) { setVisitedRoomFlag_hook(gb); return; } HANDOFF(0x2d24);  // jp $2d24
}

// 01:5d7d
void s_updateActiveRoom__gotRoom(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5d7d:
  I(0x5d7d, 4); mem_wr(gb, 0xcc4c, A);  // ld ($cc4c),a
  I(0x5d80, 4); if (hook_is(gb, 0x2d24, setVisitedRoomFlag_hook)) { setVisitedRoomFlag_hook(gb); return; } HANDOFF(0x2d24);  // jp $2d24
}

