// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/seasons/gen.h"

// 04:5d94
void s_applyAllTileSubstitutions(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x5d94, s_applySingleTileChanges, 0x5fda, 0x5d97);  // call $5fda
  CALL(0x5d97, applyStandardTileSubstitutions_hook, 0x5de8, 0x5d9a);  // call $5de8
  CALL(0x5d9a, replaceOpenedChest_hook, 0x5f53, 0x5d9d);  // call $5f53
  I(0x5d9d, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x5da0, 2); alu_cp(gb, 0x02);  // cp $02
  if ((F & FZ)) { I(0x5da2, 3); goto L_5db7; } I(0x5da2, 2);  // jr z,$5db7
  I(0x5da4, 2); alu_cp(gb, 0x04);  // cp $04
  if (!(F & FC)) { I(0x5da6, 3); goto L_5dae; } I(0x5da6, 2);  // jr nc,$5dae
  CALL(0x5da8, s_loadSubrosiaObjectGfxHeader, 0x5dbc, 0x5dab);  // call $5dbc
L_5dab:
  I(0x5dab, 4); if (hook_is(gb, 0x60ab, applyRoomSpecificTileChanges_hook)) { applyRoomSpecificTileChanges_hook(gb); return; } HANDOFF(0x60ab);  // jp $60ab
L_5dae:
  CALL(0x5dae, s_replaceShutterForLinkEntering, 0x5ebd, 0x5db1);  // call $5ebd
  CALL(0x5db1, replaceSwitchTiles_hook, 0x5f62, 0x5db4);  // call $5f62
  I(0x5db4, 4); if (hook_is(gb, 0x60ab, applyRoomSpecificTileChanges_hook)) { applyRoomSpecificTileChanges_hook(gb); return; } HANDOFF(0x60ab);  // jp $60ab
L_5db7:
  I(0x5db7, 2); E = 0x03;  // ld e,$03
  I(0x5db9, 4); if (hook_is(gb, 0x1632, loadObjectGfxHeaderToSlot4_hook)) { loadObjectGfxHeaderToSlot4_hook(gb); return; } HANDOFF(0x1632);  // jp $1632
}

// 04:5dab
void s_applyAllTileSubstitutions__afterCall5dab(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5dab:
  I(0x5dab, 4); if (hook_is(gb, 0x60ab, applyRoomSpecificTileChanges_hook)) { applyRoomSpecificTileChanges_hook(gb); return; } HANDOFF(0x60ab);  // jp $60ab
}

// 04:5fda
void s_applySingleTileChanges(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5fda, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x5fdd, 1); B = A;  // ld b,a
  CALL(0x5fde, getThisRoomFlags_hook, 0x1956, 0x5fe1);  // call $1956
  I(0x5fe1, 1); C = A;  // ld c,a
  I(0x5fe2, 2); D = 0xcf;  // ld d,$cf
  I(0x5fe4, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x5fe7, 3); SET_HL(0x6005);  // ld hl,$6005
  RST_PUSH(0x5fea, 0x5feb);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x5feb, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5fec, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x5fed, 1); L = A;  // ld l,a
L_5fee:
  I(0x5fee, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5fef, 1); alu_cp(gb, B);  // cp b
  if (!(F & FZ)) { I(0x5ff0, 3); goto L_5ffd; } I(0x5ff0, 2);  // jr nz,$5ffd
  I(0x5ff2, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x5ff3, 1); alu_and(gb, C);  // and c
  if ((F & FZ)) { I(0x5ff4, 3); goto L_5ffd; } I(0x5ff4, 2);  // jr z,$5ffd
L_5ff6:
  I(0x5ff6, 2); SET_HL(HL + 1);  // inc hl
  I(0x5ff7, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5ff8, 1); E = A;  // ld e,a
  I(0x5ff9, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5ffa, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x5ffb, 3); goto L_5fee;  // jr $5fee
L_5ffd:
  I(0x5ffd, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x5ffe, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { RET_TAKEN(0x5fff); return; } I(0x5fff, 2);  // ret z
  I(0x6000, 2); SET_HL(HL + 1);  // inc hl
  I(0x6001, 2); SET_HL(HL + 1);  // inc hl
  I(0x6002, 2); SET_HL(HL + 1);  // inc hl
  I(0x6003, 3); goto L_5fee;  // jr $5fee
}

// 04:5fee
void s_applySingleTileChanges__next(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5fee:
  I(0x5fee, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5fef, 1); alu_cp(gb, B);  // cp b
  if (!(F & FZ)) { I(0x5ff0, 3); goto L_5ffd; } I(0x5ff0, 2);  // jr nz,$5ffd
  I(0x5ff2, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x5ff3, 1); alu_and(gb, C);  // and c
  if ((F & FZ)) { I(0x5ff4, 3); goto L_5ffd; } I(0x5ff4, 2);  // jr z,$5ffd
L_5ff6:
  I(0x5ff6, 2); SET_HL(HL + 1);  // inc hl
  I(0x5ff7, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5ff8, 1); E = A;  // ld e,a
  I(0x5ff9, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5ffa, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x5ffb, 3); goto L_5fee;  // jr $5fee
L_5ffd:
  I(0x5ffd, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x5ffe, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { RET_TAKEN(0x5fff); return; } I(0x5fff, 2);  // ret z
  I(0x6000, 2); SET_HL(HL + 1);  // inc hl
  I(0x6001, 2); SET_HL(HL + 1);  // inc hl
  I(0x6002, 2); SET_HL(HL + 1);  // inc hl
  I(0x6003, 3); goto L_5fee;  // jr $5fee
}

// 04:5ff6
void s_applySingleTileChanges__match(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_5ff6;
L_5fee:
  I(0x5fee, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5fef, 1); alu_cp(gb, B);  // cp b
  if (!(F & FZ)) { I(0x5ff0, 3); goto L_5ffd; } I(0x5ff0, 2);  // jr nz,$5ffd
  I(0x5ff2, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x5ff3, 1); alu_and(gb, C);  // and c
  if ((F & FZ)) { I(0x5ff4, 3); goto L_5ffd; } I(0x5ff4, 2);  // jr z,$5ffd
L_5ff6:
  I(0x5ff6, 2); SET_HL(HL + 1);  // inc hl
  I(0x5ff7, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5ff8, 1); E = A;  // ld e,a
  I(0x5ff9, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5ffa, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x5ffb, 3); goto L_5fee;  // jr $5fee
L_5ffd:
  I(0x5ffd, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x5ffe, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { RET_TAKEN(0x5fff); return; } I(0x5fff, 2);  // ret z
  I(0x6000, 2); SET_HL(HL + 1);  // inc hl
  I(0x6001, 2); SET_HL(HL + 1);  // inc hl
  I(0x6002, 2); SET_HL(HL + 1);  // inc hl
  I(0x6003, 3); goto L_5fee;  // jr $5fee
}

// 04:5ffd
void s_applySingleTileChanges__notMatch(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_5ffd;
L_5fee:
  I(0x5fee, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5fef, 1); alu_cp(gb, B);  // cp b
  if (!(F & FZ)) { I(0x5ff0, 3); goto L_5ffd; } I(0x5ff0, 2);  // jr nz,$5ffd
  I(0x5ff2, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x5ff3, 1); alu_and(gb, C);  // and c
  if ((F & FZ)) { I(0x5ff4, 3); goto L_5ffd; } I(0x5ff4, 2);  // jr z,$5ffd
L_5ff6:
  I(0x5ff6, 2); SET_HL(HL + 1);  // inc hl
  I(0x5ff7, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5ff8, 1); E = A;  // ld e,a
  I(0x5ff9, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x5ffa, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x5ffb, 3); goto L_5fee;  // jr $5fee
L_5ffd:
  I(0x5ffd, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x5ffe, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { RET_TAKEN(0x5fff); return; } I(0x5fff, 2);  // ret z
  I(0x6000, 2); SET_HL(HL + 1);  // inc hl
  I(0x6001, 2); SET_HL(HL + 1);  // inc hl
  I(0x6002, 2); SET_HL(HL + 1);  // inc hl
  I(0x6003, 3); goto L_5fee;  // jr $5fee
}

// 04:45d0
void s_applyWarpDest_b04(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x45d0, 4); A = mem_rd(gb, 0xcc63);  // ld a,($cc63)
  I(0x45d3, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { I(0x45d5, 3); goto L_460c; } I(0x45d5, 2);  // jr nz,$460c
  I(0x45d7, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x45d9, 2); alu_cp(gb, 0x02);  // cp $02
  if (!(F & FZ)) { I(0x45db, 3); if (hook_is(gb, 0x45ee, label_04_032_hook)) { label_04_032_hook(gb); return; } HANDOFF(0x45ee); } I(0x45db, 2);  // jr nz,$45ee
  I(0x45dd, 3); SET_HL(0x6d4e);  // ld hl,$6d4e
  RST_PUSH(0x45e0, 0x45e1);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x45e1, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x45e2, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x45e3, 1); L = A;  // ld l,a
  I(0x45e4, 4); A = mem_rd(gb, 0xcc64);  // ld a,($cc64)
  I(0x45e7, 1); B = A;  // ld b,a
  I(0x45e8, 4); A = mem_rd(gb, 0xc6df);  // ld a,($c6df)
  I(0x45eb, 1); alu_add(gb, B);  // add b
  I(0x45ec, 3); s_label_04_033(gb); return;  // jr $45f8
L_460c:
  I(0x460c, 2); A = 0x0a;  // ld a,$0a
  I(0x460e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x4611, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x4614, 3); mem_wr(gb, 0xff8b, A);  // ldh ($ff8b),a
  I(0x4616, 4); A = mem_rd(gb, 0xcc63);  // ld a,($cc63)
  I(0x4619, 2); alu_and(gb, 0x07);  // and $07
  I(0x461b, 4); mem_wr(gb, 0xcc49, A);  // ld ($cc49),a
  I(0x461e, 4); A = mem_rd(gb, 0xcc64);  // ld a,($cc64)
  I(0x4621, 4); mem_wr(gb, 0xcc4c, A);  // ld ($cc4c),a
  I(0x4624, 3); SET_HL(0xd000);  // ld hl,$d000
  I(0x4627, 3); mem_wr(gb, HL, 0x03);  // ld (hl),$03
  I(0x4629, 4); A = mem_rd(gb, 0xcc66);  // ld a,($cc66)
  I(0x462c, 1); B = A;  // ld b,a
  I(0x462d, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x462f, 2); alu_or(gb, 0x08);  // or $08
  I(0x4631, 2); L = 0x0b;  // ld l,$0b
  I(0x4633, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x4634, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4635, 1); A = B;  // ld a,b
  I(0x4636, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x4638, 2); A = alu_swap(gb, A);  // swap a
  I(0x463a, 2); alu_or(gb, 0x08);  // or $08
  I(0x463c, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x463d, 4); A = mem_rd(gb, 0xcc63);  // ld a,($cc63)
  I(0x4640, 2); alu_bit(gb, 6, A);  // bit 6,a
  if (!(F & FZ)) { I(0x4642, 3); s_label_04_036(gb); return; } I(0x4642, 2);  // jr nz,$465f
  I(0x4644, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x4647, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x4648, 3); s_label_04_036(gb); return; } I(0x4648, 2);  // jr nz,$465f
  I(0x464a, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x464c, 2); alu_cp(gb, 0x03);  // cp $03
  if ((F & FC)) { I(0x464e, 3); s_label_04_035(gb); return; } I(0x464e, 2);  // jr c,$4659
  if ((F & FZ)) { I(0x4650, 3); s_label_04_036(gb); return; } I(0x4650, 2);  // jr z,$465f
  I(0x4652, 4); A = mem_rd(gb, 0xcc55);  // ld a,($cc55)
  I(0x4655, 2); alu_cp(gb, 0xff);  // cp $ff
  if ((F & FZ)) { I(0x4657, 3); s_label_04_036(gb); return; } I(0x4657, 2);  // jr z,$465f
  s_label_04_035(gb); return;  // fallthrough
}

// 04:6cff
void s_checkIsTempleRemains(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x6cff, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x6d02, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6d03); return; } I(0x6d03, 2);  // ret nz
  I(0x6d04, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x6d07, 2); alu_cp(gb, 0x14);  // cp $14
  if ((F & FC)) { I(0x6d09, 3); goto L_6d15; } I(0x6d09, 2);  // jr c,$6d15
  I(0x6d0b, 2); alu_sub(gb, 0x04);  // sub $04
  I(0x6d0d, 2); alu_cp(gb, 0x30);  // cp $30
  if (!(F & FC)) { RET_TAKEN(0x6d0f); return; } I(0x6d0f, 2);  // ret nc
  I(0x6d10, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x6d12, 2); alu_cp(gb, 0x04);  // cp $04
  RET(0x6d14); return;  // ret
L_6d15:
  I(0x6d15, 1); alu_xor(gb, A);  // xor a
  RET(0x6d16); return;  // ret
}

// 04:6a99
void s_copyRectangleFromTmpGfxBuffer__nextRow(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6a99:
  PUSH(0x6a99, BC);  // push bc
L_6a9a:
  I(0x6a9a, 2); A = 0x02;  // ld a,$02
  I(0x6a9c, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6a9e, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6a9f, 1); B = A;  // ld b,a
  I(0x6aa0, 2); A = 0x03;  // ld a,$03
  I(0x6aa2, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6aa4, 1); A = B;  // ld a,b
  I(0x6aa5, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6aa6, 2); SET_DE(DE + 1);  // inc de
  I(0x6aa7, 1); C = alu_dec8(gb, C);  // dec c
  if (!(F & FZ)) { I(0x6aa8, 3); goto L_6a9a; } I(0x6aa8, 2);  // jr nz,$6a9a
  SET_BC(POP(0x6aaa));  // pop bc
  I(0x6aab, 2); A = 0x20;  // ld a,$20
  I(0x6aad, 1); alu_sub(gb, C);  // sub c
  CALL(0x6aae, addAToDe_hook, 0x0068, 0x6ab1);  // call $0068
  I(0x6ab1, 2); A = 0x20;  // ld a,$20
  I(0x6ab3, 1); alu_sub(gb, C);  // sub c
  RST_PUSH(0x6ab4, 0x6ab5);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x6ab5, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x6ab6, 3); goto L_6a99; } I(0x6ab6, 2);  // jr nz,$6a99
  SET_AF(POP(0x6ab8));  // pop af
  I(0x6ab9, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  RET(0x6abb); return;  // ret
}

// 04:6ac4
void s_copyRectangleToRoomLayoutAndCollisions_paramDe__nextRow(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6ac4:
  PUSH(0x6ac4, BC);  // push bc
L_6ac5:
  I(0x6ac5, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6ac6, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6ac7, 1); D = alu_dec8(gb, D);  // dec d
  I(0x6ac8, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6ac9, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6aca, 1); D = alu_inc8(gb, D);  // inc d
  I(0x6acb, 2); SET_DE(DE + 1);  // inc de
  I(0x6acc, 1); C = alu_dec8(gb, C);  // dec c
  if (!(F & FZ)) { I(0x6acd, 3); goto L_6ac5; } I(0x6acd, 2);  // jr nz,$6ac5
  SET_BC(POP(0x6acf));  // pop bc
  I(0x6ad0, 2); A = 0x10;  // ld a,$10
  I(0x6ad2, 1); alu_sub(gb, C);  // sub c
  CALL(0x6ad3, addAToDe_hook, 0x0068, 0x6ad6);  // call $0068
  I(0x6ad6, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x6ad7, 3); goto L_6ac4; } I(0x6ad7, 2);  // jr nz,$6ac4
  RET(0x6ad9); return;  // ret
}

// 04:6a70
void s_drawRectangleToVramTiles__nextRow(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6a70:
  PUSH(0x6a70, BC);  // push bc
L_6a71:
  I(0x6a71, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6a72, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6a73, 2); D = (uint8_t)(D | (1 << 2));  // set 2,d
  I(0x6a75, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6a76, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6a77, 2); D = (uint8_t)(D & ~(1 << 2));  // res 2,d
  I(0x6a79, 2); SET_DE(DE + 1);  // inc de
  I(0x6a7a, 1); C = alu_dec8(gb, C);  // dec c
  if (!(F & FZ)) { I(0x6a7b, 3); goto L_6a71; } I(0x6a7b, 2);  // jr nz,$6a71
  SET_BC(POP(0x6a7d));  // pop bc
  I(0x6a7e, 2); A = 0x20;  // ld a,$20
  I(0x6a80, 1); alu_sub(gb, C);  // sub c
  CALL(0x6a81, addAToDe_hook, 0x0068, 0x6a84);  // call $0068
  I(0x6a84, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x6a85, 3); goto L_6a70; } I(0x6a85, 2);  // jr nz,$6a70
  SET_AF(POP(0x6a87));  // pop af
  I(0x6a88, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  RET(0x6a8a); return;  // ret
}

// 04:46ca
void s_findScreenEdgeWarpSource__nextWarpSource(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_46ca:
  I(0x46ca, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46cb, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x46cd); return; } I(0x46cd, 2);  // ret nz
  I(0x46ce, 2); alu_bit(gb, 6, A);  // bit 6,a
  if (!(F & FZ)) { I(0x46d0, 3); goto L_46df; } I(0x46d0, 2);  // jr nz,$46df
  I(0x46d2, 1); E = A;  // ld e,a
  I(0x46d3, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46d4, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x46d5, 3); goto L_46db; } I(0x46d5, 2);  // jr nz,$46db
  I(0x46d7, 1); A = E;  // ld a,e
  I(0x46d8, 1); alu_and(gb, B);  // and b
  if (!(F & FZ)) { I(0x46d9, 3); goto L_46e8; } I(0x46d9, 2);  // jr nz,$46e8
L_46db:
  I(0x46db, 2); SET_HL(HL + 1);  // inc hl
  I(0x46dc, 2); SET_HL(HL + 1);  // inc hl
  I(0x46dd, 3); goto L_46ca;  // jr $46ca
L_46df:
  I(0x46df, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46e0, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x46e1, 3); goto L_46db; } I(0x46e1, 2);  // jr nz,$46db
  I(0x46e3, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46e4, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x46e5, 1); L = A;  // ld l,a
  I(0x46e6, 3); goto L_46ca;  // jr $46ca
L_46e8:
  I(0x46e8, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46e9, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x46ec, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46ed, 1); B = A;  // ld b,a
  I(0x46ee, 2); A = alu_swap(gb, A);  // swap a
  I(0x46f0, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46f2, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x46f5, 1); A = B;  // ld a,b
  I(0x46f6, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46f8, 1); B = A;  // ld b,a
  I(0x46f9, 4); A = mem_rd(gb, 0xcd02);  // ld a,($cd02)
  I(0x46fc, 1); alu_rlca(gb);  // rlca
  I(0x46fd, 2); A = alu_swap(gb, A);  // swap a
  I(0x46ff, 2); alu_and(gb, 0x40);  // and $40
  I(0x4701, 1); alu_or(gb, B);  // or b
  I(0x4702, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x4705, 4); A = mem_rd(gb, 0xcc48);  // ld a,($cc48)
  I(0x4708, 2); alu_cp(gb, 0xd0);  // cp $d0
  if (!(F & FZ)) { CALL(0x470a, func_04_4732_hook, 0x4712, 0x470d); } else I(0x470a, 3);  // call nz,$4712
  I(0x470d, 1); alu_xor(gb, A);  // xor a
  I(0x470e, 4); mem_wr(gb, 0xcec0, A);  // ld ($cec0),a
  RET(0x4711); return;  // ret
}

// 04:46db
void s_findScreenEdgeWarpSource__skipRemainingBytes(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_46db;
L_46ca:
  I(0x46ca, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46cb, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x46cd); return; } I(0x46cd, 2);  // ret nz
  I(0x46ce, 2); alu_bit(gb, 6, A);  // bit 6,a
  if (!(F & FZ)) { I(0x46d0, 3); goto L_46df; } I(0x46d0, 2);  // jr nz,$46df
  I(0x46d2, 1); E = A;  // ld e,a
  I(0x46d3, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46d4, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x46d5, 3); goto L_46db; } I(0x46d5, 2);  // jr nz,$46db
  I(0x46d7, 1); A = E;  // ld a,e
  I(0x46d8, 1); alu_and(gb, B);  // and b
  if (!(F & FZ)) { I(0x46d9, 3); goto L_46e8; } I(0x46d9, 2);  // jr nz,$46e8
L_46db:
  I(0x46db, 2); SET_HL(HL + 1);  // inc hl
  I(0x46dc, 2); SET_HL(HL + 1);  // inc hl
  I(0x46dd, 3); goto L_46ca;  // jr $46ca
L_46df:
  I(0x46df, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46e0, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x46e1, 3); goto L_46db; } I(0x46e1, 2);  // jr nz,$46db
  I(0x46e3, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46e4, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x46e5, 1); L = A;  // ld l,a
  I(0x46e6, 3); goto L_46ca;  // jr $46ca
L_46e8:
  I(0x46e8, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46e9, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x46ec, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46ed, 1); B = A;  // ld b,a
  I(0x46ee, 2); A = alu_swap(gb, A);  // swap a
  I(0x46f0, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46f2, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x46f5, 1); A = B;  // ld a,b
  I(0x46f6, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46f8, 1); B = A;  // ld b,a
  I(0x46f9, 4); A = mem_rd(gb, 0xcd02);  // ld a,($cd02)
  I(0x46fc, 1); alu_rlca(gb);  // rlca
  I(0x46fd, 2); A = alu_swap(gb, A);  // swap a
  I(0x46ff, 2); alu_and(gb, 0x40);  // and $40
  I(0x4701, 1); alu_or(gb, B);  // or b
  I(0x4702, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x4705, 4); A = mem_rd(gb, 0xcc48);  // ld a,($cc48)
  I(0x4708, 2); alu_cp(gb, 0xd0);  // cp $d0
  if (!(F & FZ)) { CALL(0x470a, func_04_4732_hook, 0x4712, 0x470d); } else I(0x470a, 3);  // call nz,$4712
  I(0x470d, 1); alu_xor(gb, A);  // xor a
  I(0x470e, 4); mem_wr(gb, 0xcec0, A);  // ld ($cec0),a
  RET(0x4711); return;  // ret
}

// 04:46df
void s_findScreenEdgeWarpSource__pointerWarp(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_46df;
L_46ca:
  I(0x46ca, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46cb, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x46cd); return; } I(0x46cd, 2);  // ret nz
  I(0x46ce, 2); alu_bit(gb, 6, A);  // bit 6,a
  if (!(F & FZ)) { I(0x46d0, 3); goto L_46df; } I(0x46d0, 2);  // jr nz,$46df
  I(0x46d2, 1); E = A;  // ld e,a
  I(0x46d3, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46d4, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x46d5, 3); goto L_46db; } I(0x46d5, 2);  // jr nz,$46db
  I(0x46d7, 1); A = E;  // ld a,e
  I(0x46d8, 1); alu_and(gb, B);  // and b
  if (!(F & FZ)) { I(0x46d9, 3); goto L_46e8; } I(0x46d9, 2);  // jr nz,$46e8
L_46db:
  I(0x46db, 2); SET_HL(HL + 1);  // inc hl
  I(0x46dc, 2); SET_HL(HL + 1);  // inc hl
  I(0x46dd, 3); goto L_46ca;  // jr $46ca
L_46df:
  I(0x46df, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46e0, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x46e1, 3); goto L_46db; } I(0x46e1, 2);  // jr nz,$46db
  I(0x46e3, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46e4, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x46e5, 1); L = A;  // ld l,a
  I(0x46e6, 3); goto L_46ca;  // jr $46ca
L_46e8:
  I(0x46e8, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46e9, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x46ec, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46ed, 1); B = A;  // ld b,a
  I(0x46ee, 2); A = alu_swap(gb, A);  // swap a
  I(0x46f0, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46f2, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x46f5, 1); A = B;  // ld a,b
  I(0x46f6, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46f8, 1); B = A;  // ld b,a
  I(0x46f9, 4); A = mem_rd(gb, 0xcd02);  // ld a,($cd02)
  I(0x46fc, 1); alu_rlca(gb);  // rlca
  I(0x46fd, 2); A = alu_swap(gb, A);  // swap a
  I(0x46ff, 2); alu_and(gb, 0x40);  // and $40
  I(0x4701, 1); alu_or(gb, B);  // or b
  I(0x4702, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x4705, 4); A = mem_rd(gb, 0xcc48);  // ld a,($cc48)
  I(0x4708, 2); alu_cp(gb, 0xd0);  // cp $d0
  if (!(F & FZ)) { CALL(0x470a, func_04_4732_hook, 0x4712, 0x470d); } else I(0x470a, 3);  // call nz,$4712
  I(0x470d, 1); alu_xor(gb, A);  // xor a
  I(0x470e, 4); mem_wr(gb, 0xcec0, A);  // ld ($cec0),a
  RET(0x4711); return;  // ret
}

// 04:46e8
void s_findScreenEdgeWarpSource__foundWarpSource(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_46e8:
  I(0x46e8, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46e9, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x46ec, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x46ed, 1); B = A;  // ld b,a
  I(0x46ee, 2); A = alu_swap(gb, A);  // swap a
  I(0x46f0, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46f2, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x46f5, 1); A = B;  // ld a,b
  I(0x46f6, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46f8, 1); B = A;  // ld b,a
  I(0x46f9, 4); A = mem_rd(gb, 0xcd02);  // ld a,($cd02)
  I(0x46fc, 1); alu_rlca(gb);  // rlca
  I(0x46fd, 2); A = alu_swap(gb, A);  // swap a
  I(0x46ff, 2); alu_and(gb, 0x40);  // and $40
  I(0x4701, 1); alu_or(gb, B);  // or b
  I(0x4702, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x4705, 4); A = mem_rd(gb, 0xcc48);  // ld a,($cc48)
  I(0x4708, 2); alu_cp(gb, 0xd0);  // cp $d0
  if (!(F & FZ)) { CALL(0x470a, func_04_4732_hook, 0x4712, 0x470d); } else I(0x470a, 3);  // call nz,$4712
  I(0x470d, 1); alu_xor(gb, A);  // xor a
  I(0x470e, 4); mem_wr(gb, 0xcec0, A);  // ld ($cec0),a
  RET(0x4711); return;  // ret
}

// 04:4662
void s_findWarpSourceAndDest(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x4662, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x4665, 3); SET_HL(0x7457);  // ld hl,$7457
  RST_PUSH(0x4668, 0x4669);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x4669, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x466a, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x466b, 1); L = A;  // ld l,a
  I(0x466c, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x466f, 1); B = A;  // ld b,a
L_4670:
  I(0x4670, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4671, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { I(0x4673, 3); goto L_4693; } I(0x4673, 2);  // jr nz,$4693
  I(0x4675, 2); alu_bit(gb, 6, A);  // bit 6,a
  if (!(F & FZ)) { I(0x4677, 3); goto L_4686; } I(0x4677, 2);  // jr nz,$4686
  I(0x4679, 2); alu_and(gb, 0x0f);  // and $0f
  if (!(F & FZ)) { I(0x467b, 3); goto L_4681; } I(0x467b, 2);  // jr nz,$4681
  I(0x467d, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x467e, 1); alu_cp(gb, B);  // cp b
  if ((F & FZ)) { I(0x467f, 3); goto L_4693; } I(0x467f, 2);  // jr z,$4693
L_4681:
  I(0x4681, 2); SET_HL(HL + 1);  // inc hl
  I(0x4682, 2); SET_HL(HL + 1);  // inc hl
  I(0x4683, 2); SET_HL(HL + 1);  // inc hl
  I(0x4684, 3); goto L_4670;  // jr $4670
L_4686:
  I(0x4686, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4687, 1); alu_cp(gb, B);  // cp b
  if (!(F & FZ)) { I(0x4688, 3); goto L_4681; } I(0x4688, 2);  // jr nz,$4681
  I(0x468a, 2); SET_HL(HL + 1);  // inc hl
  I(0x468b, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x468c, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x468d, 1); L = A;  // ld l,a
  I(0x468e, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x4690, 1); B = A;  // ld b,a
  I(0x4691, 3); goto L_4670;  // jr $4670
L_4693:
  I(0x4693, 2); SET_HL(HL + 1);  // inc hl
  I(0x4694, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4695, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x4698, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4699, 1); B = A;  // ld b,a
  I(0x469a, 2); A = alu_swap(gb, A);  // swap a
  I(0x469c, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x469e, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x46a1, 1); A = B;  // ld a,b
  I(0x46a2, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46a4, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  RET(0x46a7); return;  // ret
}

// 04:4670
void s_findWarpSourceAndDest__nextWarpSource(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4670:
  I(0x4670, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4671, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { I(0x4673, 3); goto L_4693; } I(0x4673, 2);  // jr nz,$4693
  I(0x4675, 2); alu_bit(gb, 6, A);  // bit 6,a
  if (!(F & FZ)) { I(0x4677, 3); goto L_4686; } I(0x4677, 2);  // jr nz,$4686
  I(0x4679, 2); alu_and(gb, 0x0f);  // and $0f
  if (!(F & FZ)) { I(0x467b, 3); goto L_4681; } I(0x467b, 2);  // jr nz,$4681
  I(0x467d, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x467e, 1); alu_cp(gb, B);  // cp b
  if ((F & FZ)) { I(0x467f, 3); goto L_4693; } I(0x467f, 2);  // jr z,$4693
L_4681:
  I(0x4681, 2); SET_HL(HL + 1);  // inc hl
  I(0x4682, 2); SET_HL(HL + 1);  // inc hl
  I(0x4683, 2); SET_HL(HL + 1);  // inc hl
  I(0x4684, 3); goto L_4670;  // jr $4670
L_4686:
  I(0x4686, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4687, 1); alu_cp(gb, B);  // cp b
  if (!(F & FZ)) { I(0x4688, 3); goto L_4681; } I(0x4688, 2);  // jr nz,$4681
  I(0x468a, 2); SET_HL(HL + 1);  // inc hl
  I(0x468b, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x468c, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x468d, 1); L = A;  // ld l,a
  I(0x468e, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x4690, 1); B = A;  // ld b,a
  I(0x4691, 3); goto L_4670;  // jr $4670
L_4693:
  I(0x4693, 2); SET_HL(HL + 1);  // inc hl
  I(0x4694, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4695, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x4698, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4699, 1); B = A;  // ld b,a
  I(0x469a, 2); A = alu_swap(gb, A);  // swap a
  I(0x469c, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x469e, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x46a1, 1); A = B;  // ld a,b
  I(0x46a2, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46a4, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  RET(0x46a7); return;  // ret
}

// 04:4681
void s_findWarpSourceAndDest__skipRemainingBytes(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_4681;
L_4670:
  I(0x4670, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4671, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { I(0x4673, 3); goto L_4693; } I(0x4673, 2);  // jr nz,$4693
  I(0x4675, 2); alu_bit(gb, 6, A);  // bit 6,a
  if (!(F & FZ)) { I(0x4677, 3); goto L_4686; } I(0x4677, 2);  // jr nz,$4686
  I(0x4679, 2); alu_and(gb, 0x0f);  // and $0f
  if (!(F & FZ)) { I(0x467b, 3); goto L_4681; } I(0x467b, 2);  // jr nz,$4681
  I(0x467d, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x467e, 1); alu_cp(gb, B);  // cp b
  if ((F & FZ)) { I(0x467f, 3); goto L_4693; } I(0x467f, 2);  // jr z,$4693
L_4681:
  I(0x4681, 2); SET_HL(HL + 1);  // inc hl
  I(0x4682, 2); SET_HL(HL + 1);  // inc hl
  I(0x4683, 2); SET_HL(HL + 1);  // inc hl
  I(0x4684, 3); goto L_4670;  // jr $4670
L_4686:
  I(0x4686, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4687, 1); alu_cp(gb, B);  // cp b
  if (!(F & FZ)) { I(0x4688, 3); goto L_4681; } I(0x4688, 2);  // jr nz,$4681
  I(0x468a, 2); SET_HL(HL + 1);  // inc hl
  I(0x468b, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x468c, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x468d, 1); L = A;  // ld l,a
  I(0x468e, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x4690, 1); B = A;  // ld b,a
  I(0x4691, 3); goto L_4670;  // jr $4670
L_4693:
  I(0x4693, 2); SET_HL(HL + 1);  // inc hl
  I(0x4694, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4695, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x4698, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4699, 1); B = A;  // ld b,a
  I(0x469a, 2); A = alu_swap(gb, A);  // swap a
  I(0x469c, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x469e, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x46a1, 1); A = B;  // ld a,b
  I(0x46a2, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46a4, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  RET(0x46a7); return;  // ret
}

// 04:4686
void s_findWarpSourceAndDest__pointerWarp(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_4686;
L_4670:
  I(0x4670, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4671, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { I(0x4673, 3); goto L_4693; } I(0x4673, 2);  // jr nz,$4693
  I(0x4675, 2); alu_bit(gb, 6, A);  // bit 6,a
  if (!(F & FZ)) { I(0x4677, 3); goto L_4686; } I(0x4677, 2);  // jr nz,$4686
  I(0x4679, 2); alu_and(gb, 0x0f);  // and $0f
  if (!(F & FZ)) { I(0x467b, 3); goto L_4681; } I(0x467b, 2);  // jr nz,$4681
  I(0x467d, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x467e, 1); alu_cp(gb, B);  // cp b
  if ((F & FZ)) { I(0x467f, 3); goto L_4693; } I(0x467f, 2);  // jr z,$4693
L_4681:
  I(0x4681, 2); SET_HL(HL + 1);  // inc hl
  I(0x4682, 2); SET_HL(HL + 1);  // inc hl
  I(0x4683, 2); SET_HL(HL + 1);  // inc hl
  I(0x4684, 3); goto L_4670;  // jr $4670
L_4686:
  I(0x4686, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4687, 1); alu_cp(gb, B);  // cp b
  if (!(F & FZ)) { I(0x4688, 3); goto L_4681; } I(0x4688, 2);  // jr nz,$4681
  I(0x468a, 2); SET_HL(HL + 1);  // inc hl
  I(0x468b, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x468c, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x468d, 1); L = A;  // ld l,a
  I(0x468e, 3); A = mem_rd(gb, 0xff8d);  // ldh a,($ff8d)
  I(0x4690, 1); B = A;  // ld b,a
  I(0x4691, 3); goto L_4670;  // jr $4670
L_4693:
  I(0x4693, 2); SET_HL(HL + 1);  // inc hl
  I(0x4694, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4695, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x4698, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4699, 1); B = A;  // ld b,a
  I(0x469a, 2); A = alu_swap(gb, A);  // swap a
  I(0x469c, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x469e, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x46a1, 1); A = B;  // ld a,b
  I(0x46a2, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46a4, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  RET(0x46a7); return;  // ret
}

// 04:4693
void s_findWarpSourceAndDest__foundWarpSource(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4693:
  I(0x4693, 2); SET_HL(HL + 1);  // inc hl
  I(0x4694, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4695, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x4698, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4699, 1); B = A;  // ld b,a
  I(0x469a, 2); A = alu_swap(gb, A);  // swap a
  I(0x469c, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x469e, 4); mem_wr(gb, 0xcc63, A);  // ld ($cc63),a
  I(0x46a1, 1); A = B;  // ld a,b
  I(0x46a2, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x46a4, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  RET(0x46a7); return;  // ret
}

// 04:4730
void s_getLinkWarpQuadrant__smallRoom(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4730:
  I(0x4730, 2); alu_cp(gb, 0x60);  // cp $60
  I(0x4732, 1); A = B;  // ld a,b
  if ((F & FC)) { RET_TAKEN(0x4733); return; } I(0x4733, 2);  // ret c
  I(0x4734, 1); A = alu_inc8(gb, A);  // inc a
  RET(0x4735); return;  // ret
}

// 04:4736
void s_getLinkWarpQuadrant__largeRoom(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4736:
  I(0x4736, 2); alu_cp(gb, 0x80);  // cp $80
  I(0x4738, 1); A = B;  // ld a,b
  if ((F & FC)) { RET_TAKEN(0x4739); return; } I(0x4739, 2);  // ret c
  I(0x473a, 1); A = alu_inc8(gb, A);  // inc a
  RET(0x473b); return;  // ret
}

// 04:6d36
void s_getMoblinKeepScreenIndex(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x6d36, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x6d39, 2); B = 0x05;  // ld b,$05
  I(0x6d3b, 3); SET_HL(0x6d49);  // ld hl,$6d49
L_6d3e:
  I(0x6d3e, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  if ((F & FZ)) { I(0x6d3f, 3); goto L_6d47; } I(0x6d3f, 2);  // jr z,$6d47
  I(0x6d41, 2); SET_HL(HL + 1);  // inc hl
  I(0x6d42, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x6d43, 3); goto L_6d3e; } I(0x6d43, 2);  // jr nz,$6d3e
  I(0x6d45, 1); alu_xor(gb, A);  // xor a
  RET(0x6d46); return;  // ret
L_6d47:
  I(0x6d47, 1); alu_scf(gb);  // scf
  RET(0x6d48); return;  // ret
}

// 04:6d17
void s_getMoblinKeepSeasonsTilesetData(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_6d17;
L_6cfa:
  I(0x6cfa, 1); alu_xor(gb, A);  // xor a
  I(0x6cfb, 3); mem_wr(gb, 0xff8b, A);  // ldh ($ff8b),a
  I(0x6cfd, 1); alu_scf(gb);  // scf
  RET(0x6cfe); return;  // ret
L_6d17:
  I(0x6d17, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x6d1a, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6d1b); return; } I(0x6d1b, 2);  // ret nz
  CALL(0x6d1c, s_getMoblinKeepScreenIndex, 0x6d36, 0x6d1f);  // call $6d36
  if (!(F & FC)) { RET_TAKEN(0x6d1f); return; } I(0x6d1f, 2);  // ret nc
  I(0x6d20, 2); A = 0x16;  // ld a,$16
  CALL(0x6d22, checkGlobalFlag_hook, 0x30c7, 0x6d25);  // call $30c7
  if ((F & FZ)) { RET_TAKEN(0x6d25); return; } I(0x6d25, 2);  // ret z
  I(0x6d26, 4); A = mem_rd(gb, 0xc610);  // ld a,($c610)
  I(0x6d29, 2); alu_sub(gb, 0x0a);  // sub $0a
  I(0x6d2b, 2); alu_and(gb, 0x03);  // and $03
  CALL(0x6d2d, multiplyABy8_hook, 0x01b7, 0x6d30);  // call $01b7
  I(0x6d30, 3); SET_HL(0x531c);  // ld hl,$531c
  I(0x6d33, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x6d34, 3); goto L_6cfa;  // jr $6cfa
}

// 04:6ce6
void s_getTempleRemainsSeasonsTilesetData(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x6ce6, 2); A = 0x15;  // ld a,$15
  CALL(0x6ce8, checkGlobalFlag_hook, 0x30c7, 0x6ceb);  // call $30c7
  if ((F & FZ)) { RET_TAKEN(0x6ceb); return; } I(0x6ceb, 2);  // ret z
  CALL(0x6cec, s_checkIsTempleRemains, 0x6cff, 0x6cef);  // call $6cff
  if (!(F & FC)) { RET_TAKEN(0x6cef); return; } I(0x6cef, 2);  // ret nc
  I(0x6cf0, 4); A = mem_rd(gb, 0xcc4e);  // ld a,($cc4e)
  CALL(0x6cf3, multiplyABy8_hook, 0x01b7, 0x6cf6);  // call $01b7
  I(0x6cf6, 3); SET_HL(0x52fc);  // ld hl,$52fc
  I(0x6cf9, 2); alu_add_hl(gb, BC);  // add hl,bc
L_6cfa:
  I(0x6cfa, 1); alu_xor(gb, A);  // xor a
  I(0x6cfb, 3); mem_wr(gb, 0xff8b, A);  // ldh ($ff8b),a
  I(0x6cfd, 1); alu_scf(gb);  // scf
  RET(0x6cfe); return;  // ret
}

// 04:6cfa
void s_getTempleRemainsSeasonsTilesetData__returnAlteredData(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6cfa:
  I(0x6cfa, 1); alu_xor(gb, A);  // xor a
  I(0x6cfb, 3); mem_wr(gb, 0xff8b, A);  // ldh ($ff8b),a
  I(0x6cfd, 1); alu_scf(gb);  // scf
  RET(0x6cfe); return;  // ret
}

// 04:574c
void s_initializeAnimations(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x574c, 4); A = mem_rd(gb, 0xcd25);  // ld a,($cd25)
  I(0x574f, 2); alu_cp(gb, 0xff);  // cp $ff
  if ((F & FZ)) { RET_TAKEN(0x5751); return; } I(0x5751, 2);  // ret z
  CALL(0x5752, loadAnimationData_hook, 0x3600, 0x5755);  // call $3600
L_5755:
  CALL(0x5755, updateAnimationData_hook, 0x579a, 0x5758);  // call $579a
L_5758:
  CALL(0x5758, updateAnimationQueue_hook, 0x5773, 0x575b);  // call $5773
  if (!(F & FZ)) { I(0x575b, 3); goto L_5758; } I(0x575b, 2);  // jr nz,$5758
  RET(0x575d); return;  // ret
}

// 04:5755
void s_initializeAnimations__locFunc(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5755:
  CALL(0x5755, updateAnimationData_hook, 0x579a, 0x5758);  // call $579a
L_5758:
  CALL(0x5758, updateAnimationQueue_hook, 0x5773, 0x575b);  // call $5773
  if (!(F & FZ)) { I(0x575b, 3); goto L_5758; } I(0x575b, 2);  // jr nz,$5758
  RET(0x575d); return;  // ret
}

// 04:45f8
void s_label_04_033(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x45f8, 1); C = A;  // ld c,a
  I(0x45f9, 2); B = 0x00;  // ld b,$00
  I(0x45fb, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x45fc, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x45fd, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x45fe, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x45ff, 4); mem_wr(gb, 0xcc64, A);  // ld ($cc64),a
  I(0x4602, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4603, 4); mem_wr(gb, 0xcc66, A);  // ld ($cc66),a
  I(0x4606, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x4607, 2); alu_or(gb, 0x80);  // or $80
  I(0x4609, 4); mem_wr(gb, 0xcc65, A);  // ld ($cc65),a
  I(0x460c, 2); A = 0x0a;  // ld a,$0a
  I(0x460e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x4611, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x4614, 3); mem_wr(gb, 0xff8b, A);  // ldh ($ff8b),a
  I(0x4616, 4); A = mem_rd(gb, 0xcc63);  // ld a,($cc63)
  I(0x4619, 2); alu_and(gb, 0x07);  // and $07
  I(0x461b, 4); mem_wr(gb, 0xcc49, A);  // ld ($cc49),a
  I(0x461e, 4); A = mem_rd(gb, 0xcc64);  // ld a,($cc64)
  I(0x4621, 4); mem_wr(gb, 0xcc4c, A);  // ld ($cc4c),a
  I(0x4624, 3); SET_HL(0xd000);  // ld hl,$d000
  I(0x4627, 3); mem_wr(gb, HL, 0x03);  // ld (hl),$03
  I(0x4629, 4); A = mem_rd(gb, 0xcc66);  // ld a,($cc66)
  I(0x462c, 1); B = A;  // ld b,a
  I(0x462d, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x462f, 2); alu_or(gb, 0x08);  // or $08
  I(0x4631, 2); L = 0x0b;  // ld l,$0b
  I(0x4633, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x4634, 1); L = alu_inc8(gb, L);  // inc l
  I(0x4635, 1); A = B;  // ld a,b
  I(0x4636, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x4638, 2); A = alu_swap(gb, A);  // swap a
  I(0x463a, 2); alu_or(gb, 0x08);  // or $08
  I(0x463c, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x463d, 4); A = mem_rd(gb, 0xcc63);  // ld a,($cc63)
  I(0x4640, 2); alu_bit(gb, 6, A);  // bit 6,a
  if (!(F & FZ)) { I(0x4642, 3); s_label_04_036(gb); return; } I(0x4642, 2);  // jr nz,$465f
  I(0x4644, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x4647, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { I(0x4648, 3); s_label_04_036(gb); return; } I(0x4648, 2);  // jr nz,$465f
  I(0x464a, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x464c, 2); alu_cp(gb, 0x03);  // cp $03
  if ((F & FC)) { I(0x464e, 3); s_label_04_035(gb); return; } I(0x464e, 2);  // jr c,$4659
  if ((F & FZ)) { I(0x4650, 3); s_label_04_036(gb); return; } I(0x4650, 2);  // jr z,$465f
  I(0x4652, 4); A = mem_rd(gb, 0xcc55);  // ld a,($cc55)
  I(0x4655, 2); alu_cp(gb, 0xff);  // cp $ff
  if ((F & FZ)) { I(0x4657, 3); s_label_04_036(gb); return; } I(0x4657, 2);  // jr z,$465f
  s_label_04_035(gb); return;  // fallthrough
}

// 04:4659
void s_label_04_035(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x4659, loadScreenMusicAndSetRoomPack_hook, 0x32dc, 0x465c);  // call $32dc
  I(0x465c, 4); s_checkRoomPackAfterWarp(gb); return;  // jp $3ab2
}

// 04:465f
void s_label_04_036(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x465f, 4); if (hook_is(gb, 0x32dc, loadScreenMusicAndSetRoomPack_hook)) { loadScreenMusicAndSetRoomPack_hook(gb); return; } HANDOFF(0x32dc);  // jp $32dc
}

// 04:6778
void s_label_04_291(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x6778, loadTreeGfx_hook, 0x1646, 0x677b);  // call $1646
L_677b:
  I(0x677b, 3); SET_HL(0x6781);  // ld hl,$6781
  I(0x677e, 4); if (hook_is(gb, 0x6a66, drawRectangleToVramTiles_hook)) { drawRectangleToVramTiles_hook(gb); return; } HANDOFF(0x6a66);  // jp $6a66
}

// 04:677b
void s_label_04_291__afterCall677b(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_677b:
  I(0x677b, 3); SET_HL(0x6781);  // ld hl,$6781
  I(0x677e, 4); if (hook_is(gb, 0x6a66, drawRectangleToVramTiles_hook)) { drawRectangleToVramTiles_hook(gb); return; } HANDOFF(0x6a66);  // jp $6a66
}

// 04:68d1
void s_loadDinsTroupeTileChanges(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x68d1, 2); A = 0x03;  // ld a,$03
  I(0x68d3, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
L_68d5:
  I(0x68d5, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68d6, 1); L = A;  // ld l,a
  I(0x68d7, 2); SET_DE(DE + 1);  // inc de
  I(0x68d8, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68d9, 3); goto L_68f8; } I(0x68d9, 2);  // jr z,$68f8
  I(0x68db, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68dc, 1); H = A;  // ld h,a
  I(0x68dd, 2); SET_DE(DE + 1);  // inc de
L_68de:
  I(0x68de, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68df, 1); B = A;  // ld b,a
  I(0x68e0, 2); SET_DE(DE + 1);  // inc de
  I(0x68e1, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68e2, 3); goto L_68d5; } I(0x68e2, 2);  // jr z,$68d5
  I(0x68e4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68e5, 1); C = A;  // ld c,a
  I(0x68e6, 2); SET_DE(DE + 1);  // inc de
  PUSH(0x68e7, HL);  // push hl
  I(0x68e8, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x68e9, 2); H = (uint8_t)(H | (1 << 2));  // set 2,h
  I(0x68eb, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x68ec, 2); A = 0x20;  // ld a,$20
  RST_PUSH(0x68ee, 0x68ef);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x68ef, 1); B = alu_inc8(gb, B);  // inc b
  I(0x68f0, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x68f1, 2); H = (uint8_t)(H & ~(1 << 2));  // res 2,h
  I(0x68f3, 2); mem_wr(gb, HL, B);  // ld (hl),b
  SET_HL(POP(0x68f4));  // pop hl
  I(0x68f5, 2); SET_HL(HL + 1);  // inc hl
  I(0x68f6, 3); goto L_68de;  // jr $68de
L_68f8:
  I(0x68f8, 1); L = E;  // ld l,e
  I(0x68f9, 1); H = D;  // ld h,d
  I(0x68fa, 2); D = 0xce;  // ld d,$ce
L_68fc:
  I(0x68fc, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x68fd, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68fe, 3); goto L_690e; } I(0x68fe, 2);  // jr z,$690e
  I(0x6900, 1); E = A;  // ld e,a
  I(0x6901, 2); A = 0x0f;  // ld a,$0f
  I(0x6903, 2); alu_bit(gb, 7, E);  // bit 7,e
  if ((F & FZ)) { I(0x6905, 3); goto L_690b; } I(0x6905, 2);  // jr z,$690b
  I(0x6907, 2); E = (uint8_t)(E & ~(1 << 7));  // res 7,e
  I(0x6909, 2); A = 0x05;  // ld a,$05
L_690b:
  I(0x690b, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x690c, 3); goto L_68fc;  // jr $68fc
L_690e:
  SET_BC(POP(0x690e));  // pop bc
  I(0x690f, 1); A = B;  // ld a,b
  I(0x6910, 3); mem_wr(gb, 0xff97, A);  // ldh ($ff97),a
  I(0x6912, 4); mem_wr(gb, 0x2222, A);  // ld ($2222),a
  I(0x6915, 1); A = C;  // ld a,c
  I(0x6916, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6918, 2); A = 0x02;  // ld a,$02
  I(0x691a, 4); if (hook_is(gb, 0x1646, loadTreeGfx_hook)) { loadTreeGfx_hook(gb); return; } HANDOFF(0x1646);  // jp $1646
}

// 04:68d5
void s_loadDinsTroupeTileChanges__getAddress(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_68d5:
  I(0x68d5, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68d6, 1); L = A;  // ld l,a
  I(0x68d7, 2); SET_DE(DE + 1);  // inc de
  I(0x68d8, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68d9, 3); goto L_68f8; } I(0x68d9, 2);  // jr z,$68f8
  I(0x68db, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68dc, 1); H = A;  // ld h,a
  I(0x68dd, 2); SET_DE(DE + 1);  // inc de
L_68de:
  I(0x68de, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68df, 1); B = A;  // ld b,a
  I(0x68e0, 2); SET_DE(DE + 1);  // inc de
  I(0x68e1, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68e2, 3); goto L_68d5; } I(0x68e2, 2);  // jr z,$68d5
  I(0x68e4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68e5, 1); C = A;  // ld c,a
  I(0x68e6, 2); SET_DE(DE + 1);  // inc de
  PUSH(0x68e7, HL);  // push hl
  I(0x68e8, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x68e9, 2); H = (uint8_t)(H | (1 << 2));  // set 2,h
  I(0x68eb, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x68ec, 2); A = 0x20;  // ld a,$20
  RST_PUSH(0x68ee, 0x68ef);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x68ef, 1); B = alu_inc8(gb, B);  // inc b
  I(0x68f0, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x68f1, 2); H = (uint8_t)(H & ~(1 << 2));  // res 2,h
  I(0x68f3, 2); mem_wr(gb, HL, B);  // ld (hl),b
  SET_HL(POP(0x68f4));  // pop hl
  I(0x68f5, 2); SET_HL(HL + 1);  // inc hl
  I(0x68f6, 3); goto L_68de;  // jr $68de
L_68f8:
  I(0x68f8, 1); L = E;  // ld l,e
  I(0x68f9, 1); H = D;  // ld h,d
  I(0x68fa, 2); D = 0xce;  // ld d,$ce
L_68fc:
  I(0x68fc, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x68fd, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68fe, 3); goto L_690e; } I(0x68fe, 2);  // jr z,$690e
  I(0x6900, 1); E = A;  // ld e,a
  I(0x6901, 2); A = 0x0f;  // ld a,$0f
  I(0x6903, 2); alu_bit(gb, 7, E);  // bit 7,e
  if ((F & FZ)) { I(0x6905, 3); goto L_690b; } I(0x6905, 2);  // jr z,$690b
  I(0x6907, 2); E = (uint8_t)(E & ~(1 << 7));  // res 7,e
  I(0x6909, 2); A = 0x05;  // ld a,$05
L_690b:
  I(0x690b, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x690c, 3); goto L_68fc;  // jr $68fc
L_690e:
  SET_BC(POP(0x690e));  // pop bc
  I(0x690f, 1); A = B;  // ld a,b
  I(0x6910, 3); mem_wr(gb, 0xff97, A);  // ldh ($ff97),a
  I(0x6912, 4); mem_wr(gb, 0x2222, A);  // ld ($2222),a
  I(0x6915, 1); A = C;  // ld a,c
  I(0x6916, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6918, 2); A = 0x02;  // ld a,$02
  I(0x691a, 4); if (hook_is(gb, 0x1646, loadTreeGfx_hook)) { loadTreeGfx_hook(gb); return; } HANDOFF(0x1646);  // jp $1646
}

// 04:68de
void s_loadDinsTroupeTileChanges__getTilePair(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_68de;
L_68d5:
  I(0x68d5, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68d6, 1); L = A;  // ld l,a
  I(0x68d7, 2); SET_DE(DE + 1);  // inc de
  I(0x68d8, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68d9, 3); goto L_68f8; } I(0x68d9, 2);  // jr z,$68f8
  I(0x68db, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68dc, 1); H = A;  // ld h,a
  I(0x68dd, 2); SET_DE(DE + 1);  // inc de
L_68de:
  I(0x68de, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68df, 1); B = A;  // ld b,a
  I(0x68e0, 2); SET_DE(DE + 1);  // inc de
  I(0x68e1, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68e2, 3); goto L_68d5; } I(0x68e2, 2);  // jr z,$68d5
  I(0x68e4, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x68e5, 1); C = A;  // ld c,a
  I(0x68e6, 2); SET_DE(DE + 1);  // inc de
  PUSH(0x68e7, HL);  // push hl
  I(0x68e8, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x68e9, 2); H = (uint8_t)(H | (1 << 2));  // set 2,h
  I(0x68eb, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x68ec, 2); A = 0x20;  // ld a,$20
  RST_PUSH(0x68ee, 0x68ef);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x68ef, 1); B = alu_inc8(gb, B);  // inc b
  I(0x68f0, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x68f1, 2); H = (uint8_t)(H & ~(1 << 2));  // res 2,h
  I(0x68f3, 2); mem_wr(gb, HL, B);  // ld (hl),b
  SET_HL(POP(0x68f4));  // pop hl
  I(0x68f5, 2); SET_HL(HL + 1);  // inc hl
  I(0x68f6, 3); goto L_68de;  // jr $68de
L_68f8:
  I(0x68f8, 1); L = E;  // ld l,e
  I(0x68f9, 1); H = D;  // ld h,d
  I(0x68fa, 2); D = 0xce;  // ld d,$ce
L_68fc:
  I(0x68fc, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x68fd, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68fe, 3); goto L_690e; } I(0x68fe, 2);  // jr z,$690e
  I(0x6900, 1); E = A;  // ld e,a
  I(0x6901, 2); A = 0x0f;  // ld a,$0f
  I(0x6903, 2); alu_bit(gb, 7, E);  // bit 7,e
  if ((F & FZ)) { I(0x6905, 3); goto L_690b; } I(0x6905, 2);  // jr z,$690b
  I(0x6907, 2); E = (uint8_t)(E & ~(1 << 7));  // res 7,e
  I(0x6909, 2); A = 0x05;  // ld a,$05
L_690b:
  I(0x690b, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x690c, 3); goto L_68fc;  // jr $68fc
L_690e:
  SET_BC(POP(0x690e));  // pop bc
  I(0x690f, 1); A = B;  // ld a,b
  I(0x6910, 3); mem_wr(gb, 0xff97, A);  // ldh ($ff97),a
  I(0x6912, 4); mem_wr(gb, 0x2222, A);  // ld ($2222),a
  I(0x6915, 1); A = C;  // ld a,c
  I(0x6916, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6918, 2); A = 0x02;  // ld a,$02
  I(0x691a, 4); if (hook_is(gb, 0x1646, loadTreeGfx_hook)) { loadTreeGfx_hook(gb); return; } HANDOFF(0x1646);  // jp $1646
}

// 04:68f8
void s_loadDinsTroupeTileChanges__doneReadingVramTiles(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_68f8:
  I(0x68f8, 1); L = E;  // ld l,e
  I(0x68f9, 1); H = D;  // ld h,d
  I(0x68fa, 2); D = 0xce;  // ld d,$ce
L_68fc:
  I(0x68fc, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x68fd, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68fe, 3); goto L_690e; } I(0x68fe, 2);  // jr z,$690e
  I(0x6900, 1); E = A;  // ld e,a
  I(0x6901, 2); A = 0x0f;  // ld a,$0f
  I(0x6903, 2); alu_bit(gb, 7, E);  // bit 7,e
  if ((F & FZ)) { I(0x6905, 3); goto L_690b; } I(0x6905, 2);  // jr z,$690b
  I(0x6907, 2); E = (uint8_t)(E & ~(1 << 7));  // res 7,e
  I(0x6909, 2); A = 0x05;  // ld a,$05
L_690b:
  I(0x690b, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x690c, 3); goto L_68fc;  // jr $68fc
L_690e:
  SET_BC(POP(0x690e));  // pop bc
  I(0x690f, 1); A = B;  // ld a,b
  I(0x6910, 3); mem_wr(gb, 0xff97, A);  // ldh ($ff97),a
  I(0x6912, 4); mem_wr(gb, 0x2222, A);  // ld ($2222),a
  I(0x6915, 1); A = C;  // ld a,c
  I(0x6916, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6918, 2); A = 0x02;  // ld a,$02
  I(0x691a, 4); if (hook_is(gb, 0x1646, loadTreeGfx_hook)) { loadTreeGfx_hook(gb); return; } HANDOFF(0x1646);  // jp $1646
}

// 04:68fc
void s_loadDinsTroupeTileChanges__nextAddress(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_68fc:
  I(0x68fc, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x68fd, 1); alu_or(gb, A);  // or a
  if ((F & FZ)) { I(0x68fe, 3); goto L_690e; } I(0x68fe, 2);  // jr z,$690e
  I(0x6900, 1); E = A;  // ld e,a
  I(0x6901, 2); A = 0x0f;  // ld a,$0f
  I(0x6903, 2); alu_bit(gb, 7, E);  // bit 7,e
  if ((F & FZ)) { I(0x6905, 3); goto L_690b; } I(0x6905, 2);  // jr z,$690b
  I(0x6907, 2); E = (uint8_t)(E & ~(1 << 7));  // res 7,e
  I(0x6909, 2); A = 0x05;  // ld a,$05
L_690b:
  I(0x690b, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x690c, 3); goto L_68fc;  // jr $68fc
L_690e:
  SET_BC(POP(0x690e));  // pop bc
  I(0x690f, 1); A = B;  // ld a,b
  I(0x6910, 3); mem_wr(gb, 0xff97, A);  // ldh ($ff97),a
  I(0x6912, 4); mem_wr(gb, 0x2222, A);  // ld ($2222),a
  I(0x6915, 1); A = C;  // ld a,c
  I(0x6916, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6918, 2); A = 0x02;  // ld a,$02
  I(0x691a, 4); if (hook_is(gb, 0x1646, loadTreeGfx_hook)) { loadTreeGfx_hook(gb); return; } HANDOFF(0x1646);  // jp $1646
}

// 04:690e
void s_loadDinsTroupeTileChanges__done(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_690e:
  SET_BC(POP(0x690e));  // pop bc
  I(0x690f, 1); A = B;  // ld a,b
  I(0x6910, 3); mem_wr(gb, 0xff97, A);  // ldh ($ff97),a
  I(0x6912, 4); mem_wr(gb, 0x2222, A);  // ld ($2222),a
  I(0x6915, 1); A = C;  // ld a,c
  I(0x6916, 3); mem_wr(gb, 0xff70, A);  // ldh ($ff70),a
  I(0x6918, 2); A = 0x02;  // ld a,$02
  I(0x691a, 4); if (hook_is(gb, 0x1646, loadTreeGfx_hook)) { loadTreeGfx_hook(gb); return; } HANDOFF(0x1646);  // jp $1646
}

// 04:67a4
void s_loadGaleTreeGfx(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x67a4, drawRectangleToVramTiles_hook, 0x6a66, 0x67a7);  // call $6a66
  I(0x67a7, 2); A = 0x09;  // ld a,$09
  I(0x67a9, 4); if (hook_is(gb, 0x1646, loadTreeGfx_hook)) { loadTreeGfx_hook(gb); return; } HANDOFF(0x1646);  // jp $1646
}

// 04:5dbc
void s_loadSubrosiaObjectGfxHeader(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5dbc, 4); A = mem_rd(gb, 0xc63a);  // ld a,($c63a)
  I(0x5dbf, 2); alu_cp(gb, 0x01);  // cp $01
  if (!(F & FZ)) { RET_TAKEN(0x5dc1); return; } I(0x5dc1, 2);  // ret nz
  I(0x5dc2, 2); E = 0x06;  // ld e,$06
  I(0x5dc4, 4); if (hook_is(gb, 0x1632, loadObjectGfxHeaderToSlot4_hook)) { loadObjectGfxHeaderToSlot4_hook(gb); return; } HANDOFF(0x1632);  // jp $1632
}

// 04:6c6d
void s_loadTilesetData_body(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x6c6d, s_getTempleRemainsSeasonsTilesetData, 0x6ce6, 0x6c70);  // call $6ce6
  if ((F & FC)) { I(0x6c70, 3); goto L_6ca3; } I(0x6c70, 2);  // jr c,$6ca3
  CALL(0x6c72, s_getMoblinKeepSeasonsTilesetData, 0x6d17, 0x6c75);  // call $6d17
  if ((F & FC)) { I(0x6c75, 3); goto L_6ca3; } I(0x6c75, 2);  // jr c,$6ca3
  I(0x6c77, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x6c7a, 3); SET_HL(0x533c);  // ld hl,$533c
  RST_PUSH(0x6c7d, 0x6c7e);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x6c7e, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6c7f, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x6c80, 1); L = A;  // ld l,a
  I(0x6c81, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  RST_PUSH(0x6c84, 0x6c85);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x6c85, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x6c86, 2); alu_and(gb, 0x80);  // and $80
  I(0x6c88, 3); mem_wr(gb, 0xff8b, A);  // ldh ($ff8b),a
  I(0x6c8a, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x6c8b, 2); alu_and(gb, 0x7f);  // and $7f
  CALL(0x6c8d, multiplyABy8_hook, 0x01b7, 0x6c90);  // call $01b7
  I(0x6c90, 3); SET_HL(0x4c84);  // ld hl,$4c84
  I(0x6c93, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x6c94, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x6c95, 1); A = alu_inc8(gb, A);  // inc a
  if (!(F & FZ)) { I(0x6c96, 3); goto L_6ca3; } I(0x6c96, 2);  // jr nz,$6ca3
  I(0x6c98, 2); SET_HL(HL + 1);  // inc hl
  I(0x6c99, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6c9a, 2); H = mem_rd(gb, HL);  // ld h,(hl)
  I(0x6c9b, 1); L = A;  // ld l,a
  I(0x6c9c, 4); A = mem_rd(gb, 0xcc4e);  // ld a,($cc4e)
  CALL(0x6c9f, multiplyABy8_hook, 0x01b7, 0x6ca2);  // call $01b7
  I(0x6ca2, 2); alu_add_hl(gb, BC);  // add hl,bc
L_6ca3:
  I(0x6ca3, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6ca4, 1); E = A;  // ld e,a
  I(0x6ca5, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x6ca7, 2); alu_cp(gb, 0x0f);  // cp $0f
  if (!(F & FZ)) { I(0x6ca9, 3); goto L_6cad; } I(0x6ca9, 2);  // jr nz,$6cad
  I(0x6cab, 2); A = 0xff;  // ld a,$ff
L_6cad:
  I(0x6cad, 4); mem_wr(gb, 0xcc55, A);  // ld ($cc55),a
  I(0x6cb0, 1); A = E;  // ld a,e
  I(0x6cb1, 2); A = alu_swap(gb, A);  // swap a
  I(0x6cb3, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x6cb5, 4); mem_wr(gb, 0xcc4f, A);  // ld ($cc4f),a
  I(0x6cb8, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6cb9, 4); mem_wr(gb, 0xcc50, A);  // ld ($cc50),a
  I(0x6cbc, 2); B = 0x06;  // ld b,$06
  I(0x6cbe, 3); SET_DE(0xcd20);  // ld de,$cd20
L_6cc1:
  I(0x6cc1, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6cc2, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6cc3, 1); E = alu_inc8(gb, E);  // inc e
  I(0x6cc4, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x6cc5, 3); goto L_6cc1; } I(0x6cc5, 2);  // jr nz,$6cc1
  I(0x6cc7, 2); E = 0x20;  // ld e,$20
  I(0x6cc9, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6cca, 1); B = A;  // ld b,a
  I(0x6ccb, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x6ccd, 1); alu_or(gb, B);  // or b
  I(0x6cce, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6ccf, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x6cd2, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6cd3); return; } I(0x6cd3, 2);  // ret nz
  I(0x6cd4, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x6cd7, 2); alu_cp(gb, 0x96);  // cp $96
  if (!(F & FZ)) { RET_TAKEN(0x6cd9); return; } I(0x6cd9, 2);  // ret nz
  CALL(0x6cda, getThisRoomFlags_hook, 0x1956, 0x6cdd);  // call $1956
  I(0x6cdd, 2); alu_and(gb, 0x80);  // and $80
  if (!(F & FZ)) { RET_TAKEN(0x6cdf); return; } I(0x6cdf, 2);  // ret nz
  I(0x6ce0, 2); A = 0x20;  // ld a,$20
  I(0x6ce2, 4); mem_wr(gb, 0xcd20, A);  // ld ($cd20),a
  RET(0x6ce5); return;  // ret
}

// 04:6ca3
void s_loadTilesetData_body__gotTilesetData(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6ca3:
  I(0x6ca3, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6ca4, 1); E = A;  // ld e,a
  I(0x6ca5, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x6ca7, 2); alu_cp(gb, 0x0f);  // cp $0f
  if (!(F & FZ)) { I(0x6ca9, 3); goto L_6cad; } I(0x6ca9, 2);  // jr nz,$6cad
  I(0x6cab, 2); A = 0xff;  // ld a,$ff
L_6cad:
  I(0x6cad, 4); mem_wr(gb, 0xcc55, A);  // ld ($cc55),a
  I(0x6cb0, 1); A = E;  // ld a,e
  I(0x6cb1, 2); A = alu_swap(gb, A);  // swap a
  I(0x6cb3, 2); alu_and(gb, 0x0f);  // and $0f
  I(0x6cb5, 4); mem_wr(gb, 0xcc4f, A);  // ld ($cc4f),a
  I(0x6cb8, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6cb9, 4); mem_wr(gb, 0xcc50, A);  // ld ($cc50),a
  I(0x6cbc, 2); B = 0x06;  // ld b,$06
  I(0x6cbe, 3); SET_DE(0xcd20);  // ld de,$cd20
L_6cc1:
  I(0x6cc1, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6cc2, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6cc3, 1); E = alu_inc8(gb, E);  // inc e
  I(0x6cc4, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x6cc5, 3); goto L_6cc1; } I(0x6cc5, 2);  // jr nz,$6cc1
  I(0x6cc7, 2); E = 0x20;  // ld e,$20
  I(0x6cc9, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6cca, 1); B = A;  // ld b,a
  I(0x6ccb, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x6ccd, 1); alu_or(gb, B);  // or b
  I(0x6cce, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6ccf, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x6cd2, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6cd3); return; } I(0x6cd3, 2);  // ret nz
  I(0x6cd4, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x6cd7, 2); alu_cp(gb, 0x96);  // cp $96
  if (!(F & FZ)) { RET_TAKEN(0x6cd9); return; } I(0x6cd9, 2);  // ret nz
  CALL(0x6cda, getThisRoomFlags_hook, 0x1956, 0x6cdd);  // call $1956
  I(0x6cdd, 2); alu_and(gb, 0x80);  // and $80
  if (!(F & FZ)) { RET_TAKEN(0x6cdf); return; } I(0x6cdf, 2);  // ret nz
  I(0x6ce0, 2); A = 0x20;  // ld a,$20
  I(0x6ce2, 4); mem_wr(gb, 0xcd20, A);  // ld ($cd20),a
  RET(0x6ce5); return;  // ret
}

// 04:6cc1
void s_loadTilesetData_body__copyloop(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6cc1:
  I(0x6cc1, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x6cc2, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6cc3, 1); E = alu_inc8(gb, E);  // inc e
  I(0x6cc4, 1); B = alu_dec8(gb, B);  // dec b
  if (!(F & FZ)) { I(0x6cc5, 3); goto L_6cc1; } I(0x6cc5, 2);  // jr nz,$6cc1
  I(0x6cc7, 2); E = 0x20;  // ld e,$20
  I(0x6cc9, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x6cca, 1); B = A;  // ld b,a
  I(0x6ccb, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x6ccd, 1); alu_or(gb, B);  // or b
  I(0x6cce, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x6ccf, 4); A = mem_rd(gb, 0xcc49);  // ld a,($cc49)
  I(0x6cd2, 1); alu_or(gb, A);  // or a
  if (!(F & FZ)) { RET_TAKEN(0x6cd3); return; } I(0x6cd3, 2);  // ret nz
  I(0x6cd4, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  I(0x6cd7, 2); alu_cp(gb, 0x96);  // cp $96
  if (!(F & FZ)) { RET_TAKEN(0x6cd9); return; } I(0x6cd9, 2);  // ret nz
  CALL(0x6cda, getThisRoomFlags_hook, 0x1956, 0x6cdd);  // call $1956
  I(0x6cdd, 2); alu_and(gb, 0x80);  // and $80
  if (!(F & FZ)) { RET_TAKEN(0x6cdf); return; } I(0x6cdf, 2);  // ret nz
  I(0x6ce0, 2); A = 0x20;  // ld a,$20
  I(0x6ce2, 4); mem_wr(gb, 0xcd20, A);  // ld ($cd20),a
  RET(0x6ce5); return;  // ret
}

// 04:5ebd
void s_replaceShutterForLinkEntering(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5ebd, 4); A = mem_rd(gb, 0xcc55);  // ld a,($cc55)
  I(0x5ec0, 1); A = alu_inc8(gb, A);  // inc a
  if ((F & FZ)) { RET_TAKEN(0x5ec1); return; } I(0x5ec1, 2);  // ret z
  I(0x5ec2, 3); SET_BC(0xcfae);  // ld bc,$cfae
L_5ec5:
  I(0x5ec5, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  PUSH(0x5ec6, BC);  // push bc
  I(0x5ec7, 2); alu_sub(gb, 0x78);  // sub $78
  I(0x5ec9, 2); alu_cp(gb, 0x08);  // cp $08
  if ((F & FC)) { CALL(0x5ecb, s_replaceShutterForLinkEntering__temporarilyOpenDoor, 0x5ed3, 0x5ece); } else I(0x5ecb, 3);  // call c,$5ed3
  SET_BC(POP(0x5ece));  // pop bc
  I(0x5ecf, 1); C = alu_dec8(gb, C);  // dec c
  if (!(F & FZ)) { I(0x5ed0, 3); goto L_5ec5; } I(0x5ed0, 2);  // jr nz,$5ec5
  RET(0x5ed2); return;  // ret
}

// 04:5ed3
void s_replaceShutterForLinkEntering__temporarilyOpenDoor(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5ed3:
  I(0x5ed3, 3); SET_DE(0x5f43);  // ld de,$5f43
  CALL(0x5ed6, addDoubleIndexToDe_hook, 0x0072, 0x5ed9);  // call $0072
  I(0x5ed9, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x5eda, 3); mem_wr(gb, 0xff8b, A);  // ldh ($ff8b),a
  I(0x5edc, 2); SET_DE(DE + 1);  // inc de
  I(0x5edd, 2); A = mem_rd(gb, DE);  // ld a,(de)
  I(0x5ede, 1); E = A;  // ld e,a
  I(0x5edf, 4); A = mem_rd(gb, 0xcd00);  // ld a,($cd00)
  I(0x5ee2, 2); alu_and(gb, 0x08);  // and $08
  if ((F & FZ)) { I(0x5ee4, 3); goto L_5f30; } I(0x5ee4, 2);  // jr z,$5f30
  I(0x5ee6, 4); A = mem_rd(gb, 0xcc48);  // ld a,($cc48)
  I(0x5ee9, 1); H = A;  // ld h,a
  I(0x5eea, 4); A = mem_rd(gb, 0xcd02);  // ld a,($cd02)
  I(0x5eed, 2); alu_xor(gb, 0x02);  // xor $02
  I(0x5eef, 1); D = A;  // ld d,a
  I(0x5ef0, 1); A = E;  // ld a,e
  I(0x5ef1, 2); alu_and(gb, 0x03);  // and $03
  I(0x5ef3, 1); alu_cp(gb, D);  // cp d
  if (!(F & FZ)) { RET_TAKEN(0x5ef4); return; } I(0x5ef4, 2);  // ret nz
  I(0x5ef5, 4); A = mem_rd(gb, 0xcd02);  // ld a,($cd02)
  I(0x5ef8, 2); alu_bit(gb, 0, A);  // bit 0,a
  if (!(F & FZ)) { I(0x5efa, 3); goto L_5f11; } I(0x5efa, 2);  // jr nz,$5f11
  I(0x5efc, 2); alu_and(gb, 0x02);  // and $02
  I(0x5efe, 2); L = 0x0d;  // ld l,$0d
  I(0x5f00, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x5f01, 3); goto L_5f0b; } I(0x5f01, 2);  // jr nz,$5f0b
L_5f03:
  I(0x5f03, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5f05, 2); A = alu_swap(gb, A);  // swap a
  I(0x5f07, 2); alu_or(gb, 0xa0);  // or $a0
  I(0x5f09, 3); goto L_5f20;  // jr $5f20
L_5f0b:
  I(0x5f0b, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5f0d, 2); A = alu_swap(gb, A);  // swap a
  I(0x5f0f, 3); goto L_5f20;  // jr $5f20
L_5f11:
  I(0x5f11, 2); alu_and(gb, 0x02);  // and $02
  I(0x5f13, 2); L = 0x0b;  // ld l,$0b
  I(0x5f15, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x5f16, 3); goto L_5f1c; } I(0x5f16, 2);  // jr nz,$5f1c
L_5f18:
  I(0x5f18, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5f1a, 3); goto L_5f20;  // jr $5f20
L_5f1c:
  I(0x5f1c, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5f1e, 2); alu_or(gb, 0x0e);  // or $0e
L_5f20:
  I(0x5f20, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x5f21, 3); goto L_5f30; } I(0x5f21, 2);  // jr nz,$5f30
  PUSH(0x5f23, BC);  // push bc
  I(0x5f24, 1); C = A;  // ld c,a
  I(0x5f25, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x5f26, 2); alu_sub(gb, 0x78);  // sub $78
  I(0x5f28, 2); alu_cp(gb, 0x08);  // cp $08
  if (!(F & FC)) { I(0x5f2a, 3); goto L_5f2f; } I(0x5f2a, 2);  // jr nc,$5f2f
  I(0x5f2c, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x5f2e, 2); mem_wr(gb, BC, A);  // ld (bc),a
L_5f2f:
  SET_BC(POP(0x5f2f));  // pop bc
L_5f30:
  I(0x5f30, 1); A = E;  // ld a,e
  I(0x5f31, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x5f33); return; } I(0x5f33, 2);  // ret nz
  I(0x5f34, 2); alu_and(gb, 0x7f);  // and $7f
  I(0x5f36, 1); E = A;  // ld e,a
  CALL(0x5f37, getFreeInteractionSlot_hook, 0x3ac6, 0x5f3a);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x5f3a); return; } I(0x5f3a, 2);  // ret nz
  I(0x5f3b, 3); mem_wr(gb, HL, 0x1e);  // ld (hl),$1e
  I(0x5f3d, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5f3e, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x5f3f, 2); L = 0x4b;  // ld l,$4b
  I(0x5f41, 2); mem_wr(gb, HL, C);  // ld (hl),c
  RET(0x5f42); return;  // ret
}

// 04:5f03
void s_replaceShutterForLinkEntering__up(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5f03:
  I(0x5f03, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5f05, 2); A = alu_swap(gb, A);  // swap a
  I(0x5f07, 2); alu_or(gb, 0xa0);  // or $a0
  I(0x5f09, 3); goto L_5f20;  // jr $5f20
L_5f20:
  I(0x5f20, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x5f21, 3); goto L_5f30; } I(0x5f21, 2);  // jr nz,$5f30
  PUSH(0x5f23, BC);  // push bc
  I(0x5f24, 1); C = A;  // ld c,a
  I(0x5f25, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x5f26, 2); alu_sub(gb, 0x78);  // sub $78
  I(0x5f28, 2); alu_cp(gb, 0x08);  // cp $08
  if (!(F & FC)) { I(0x5f2a, 3); goto L_5f2f; } I(0x5f2a, 2);  // jr nc,$5f2f
  I(0x5f2c, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x5f2e, 2); mem_wr(gb, BC, A);  // ld (bc),a
L_5f2f:
  SET_BC(POP(0x5f2f));  // pop bc
L_5f30:
  I(0x5f30, 1); A = E;  // ld a,e
  I(0x5f31, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x5f33); return; } I(0x5f33, 2);  // ret nz
  I(0x5f34, 2); alu_and(gb, 0x7f);  // and $7f
  I(0x5f36, 1); E = A;  // ld e,a
  CALL(0x5f37, getFreeInteractionSlot_hook, 0x3ac6, 0x5f3a);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x5f3a); return; } I(0x5f3a, 2);  // ret nz
  I(0x5f3b, 3); mem_wr(gb, HL, 0x1e);  // ld (hl),$1e
  I(0x5f3d, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5f3e, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x5f3f, 2); L = 0x4b;  // ld l,$4b
  I(0x5f41, 2); mem_wr(gb, HL, C);  // ld (hl),c
  RET(0x5f42); return;  // ret
}

// 04:5f0b
void s_replaceShutterForLinkEntering__down(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5f0b:
  I(0x5f0b, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5f0d, 2); A = alu_swap(gb, A);  // swap a
  I(0x5f0f, 3); goto L_5f20;  // jr $5f20
L_5f20:
  I(0x5f20, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x5f21, 3); goto L_5f30; } I(0x5f21, 2);  // jr nz,$5f30
  PUSH(0x5f23, BC);  // push bc
  I(0x5f24, 1); C = A;  // ld c,a
  I(0x5f25, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x5f26, 2); alu_sub(gb, 0x78);  // sub $78
  I(0x5f28, 2); alu_cp(gb, 0x08);  // cp $08
  if (!(F & FC)) { I(0x5f2a, 3); goto L_5f2f; } I(0x5f2a, 2);  // jr nc,$5f2f
  I(0x5f2c, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x5f2e, 2); mem_wr(gb, BC, A);  // ld (bc),a
L_5f2f:
  SET_BC(POP(0x5f2f));  // pop bc
L_5f30:
  I(0x5f30, 1); A = E;  // ld a,e
  I(0x5f31, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x5f33); return; } I(0x5f33, 2);  // ret nz
  I(0x5f34, 2); alu_and(gb, 0x7f);  // and $7f
  I(0x5f36, 1); E = A;  // ld e,a
  CALL(0x5f37, getFreeInteractionSlot_hook, 0x3ac6, 0x5f3a);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x5f3a); return; } I(0x5f3a, 2);  // ret nz
  I(0x5f3b, 3); mem_wr(gb, HL, 0x1e);  // ld (hl),$1e
  I(0x5f3d, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5f3e, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x5f3f, 2); L = 0x4b;  // ld l,$4b
  I(0x5f41, 2); mem_wr(gb, HL, C);  // ld (hl),c
  RET(0x5f42); return;  // ret
}

// 04:5f11
void s_replaceShutterForLinkEntering__horizontal(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5f11:
  I(0x5f11, 2); alu_and(gb, 0x02);  // and $02
  I(0x5f13, 2); L = 0x0b;  // ld l,$0b
  I(0x5f15, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  if (!(F & FZ)) { I(0x5f16, 3); goto L_5f1c; } I(0x5f16, 2);  // jr nz,$5f1c
L_5f18:
  I(0x5f18, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5f1a, 3); goto L_5f20;  // jr $5f20
L_5f1c:
  I(0x5f1c, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5f1e, 2); alu_or(gb, 0x0e);  // or $0e
L_5f20:
  I(0x5f20, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x5f21, 3); goto L_5f30; } I(0x5f21, 2);  // jr nz,$5f30
  PUSH(0x5f23, BC);  // push bc
  I(0x5f24, 1); C = A;  // ld c,a
  I(0x5f25, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x5f26, 2); alu_sub(gb, 0x78);  // sub $78
  I(0x5f28, 2); alu_cp(gb, 0x08);  // cp $08
  if (!(F & FC)) { I(0x5f2a, 3); goto L_5f2f; } I(0x5f2a, 2);  // jr nc,$5f2f
  I(0x5f2c, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x5f2e, 2); mem_wr(gb, BC, A);  // ld (bc),a
L_5f2f:
  SET_BC(POP(0x5f2f));  // pop bc
L_5f30:
  I(0x5f30, 1); A = E;  // ld a,e
  I(0x5f31, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x5f33); return; } I(0x5f33, 2);  // ret nz
  I(0x5f34, 2); alu_and(gb, 0x7f);  // and $7f
  I(0x5f36, 1); E = A;  // ld e,a
  CALL(0x5f37, getFreeInteractionSlot_hook, 0x3ac6, 0x5f3a);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x5f3a); return; } I(0x5f3a, 2);  // ret nz
  I(0x5f3b, 3); mem_wr(gb, HL, 0x1e);  // ld (hl),$1e
  I(0x5f3d, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5f3e, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x5f3f, 2); L = 0x4b;  // ld l,$4b
  I(0x5f41, 2); mem_wr(gb, HL, C);  // ld (hl),c
  RET(0x5f42); return;  // ret
}

// 04:5f18
void s_replaceShutterForLinkEntering__right(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5f18:
  I(0x5f18, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5f1a, 3); goto L_5f20;  // jr $5f20
L_5f20:
  I(0x5f20, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x5f21, 3); goto L_5f30; } I(0x5f21, 2);  // jr nz,$5f30
  PUSH(0x5f23, BC);  // push bc
  I(0x5f24, 1); C = A;  // ld c,a
  I(0x5f25, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x5f26, 2); alu_sub(gb, 0x78);  // sub $78
  I(0x5f28, 2); alu_cp(gb, 0x08);  // cp $08
  if (!(F & FC)) { I(0x5f2a, 3); goto L_5f2f; } I(0x5f2a, 2);  // jr nc,$5f2f
  I(0x5f2c, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x5f2e, 2); mem_wr(gb, BC, A);  // ld (bc),a
L_5f2f:
  SET_BC(POP(0x5f2f));  // pop bc
L_5f30:
  I(0x5f30, 1); A = E;  // ld a,e
  I(0x5f31, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x5f33); return; } I(0x5f33, 2);  // ret nz
  I(0x5f34, 2); alu_and(gb, 0x7f);  // and $7f
  I(0x5f36, 1); E = A;  // ld e,a
  CALL(0x5f37, getFreeInteractionSlot_hook, 0x3ac6, 0x5f3a);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x5f3a); return; } I(0x5f3a, 2);  // ret nz
  I(0x5f3b, 3); mem_wr(gb, HL, 0x1e);  // ld (hl),$1e
  I(0x5f3d, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5f3e, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x5f3f, 2); L = 0x4b;  // ld l,$4b
  I(0x5f41, 2); mem_wr(gb, HL, C);  // ld (hl),c
  RET(0x5f42); return;  // ret
}

// 04:5f1c
void s_replaceShutterForLinkEntering__left(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5f1c:
  I(0x5f1c, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5f1e, 2); alu_or(gb, 0x0e);  // or $0e
L_5f20:
  I(0x5f20, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x5f21, 3); goto L_5f30; } I(0x5f21, 2);  // jr nz,$5f30
  PUSH(0x5f23, BC);  // push bc
  I(0x5f24, 1); C = A;  // ld c,a
  I(0x5f25, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x5f26, 2); alu_sub(gb, 0x78);  // sub $78
  I(0x5f28, 2); alu_cp(gb, 0x08);  // cp $08
  if (!(F & FC)) { I(0x5f2a, 3); goto L_5f2f; } I(0x5f2a, 2);  // jr nc,$5f2f
  I(0x5f2c, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x5f2e, 2); mem_wr(gb, BC, A);  // ld (bc),a
L_5f2f:
  SET_BC(POP(0x5f2f));  // pop bc
L_5f30:
  I(0x5f30, 1); A = E;  // ld a,e
  I(0x5f31, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x5f33); return; } I(0x5f33, 2);  // ret nz
  I(0x5f34, 2); alu_and(gb, 0x7f);  // and $7f
  I(0x5f36, 1); E = A;  // ld e,a
  CALL(0x5f37, getFreeInteractionSlot_hook, 0x3ac6, 0x5f3a);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x5f3a); return; } I(0x5f3a, 2);  // ret nz
  I(0x5f3b, 3); mem_wr(gb, HL, 0x1e);  // ld (hl),$1e
  I(0x5f3d, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5f3e, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x5f3f, 2); L = 0x4b;  // ld l,$4b
  I(0x5f41, 2); mem_wr(gb, HL, C);  // ld (hl),c
  RET(0x5f42); return;  // ret
}

// 04:5f20
void s_replaceShutterForLinkEntering__doReplacement(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5f20:
  I(0x5f20, 1); alu_cp(gb, C);  // cp c
  if (!(F & FZ)) { I(0x5f21, 3); goto L_5f30; } I(0x5f21, 2);  // jr nz,$5f30
  PUSH(0x5f23, BC);  // push bc
  I(0x5f24, 1); C = A;  // ld c,a
  I(0x5f25, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x5f26, 2); alu_sub(gb, 0x78);  // sub $78
  I(0x5f28, 2); alu_cp(gb, 0x08);  // cp $08
  if (!(F & FC)) { I(0x5f2a, 3); goto L_5f2f; } I(0x5f2a, 2);  // jr nc,$5f2f
  I(0x5f2c, 3); A = mem_rd(gb, 0xff8b);  // ldh a,($ff8b)
  I(0x5f2e, 2); mem_wr(gb, BC, A);  // ld (bc),a
L_5f2f:
  SET_BC(POP(0x5f2f));  // pop bc
L_5f30:
  I(0x5f30, 1); A = E;  // ld a,e
  I(0x5f31, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x5f33); return; } I(0x5f33, 2);  // ret nz
  I(0x5f34, 2); alu_and(gb, 0x7f);  // and $7f
  I(0x5f36, 1); E = A;  // ld e,a
  CALL(0x5f37, getFreeInteractionSlot_hook, 0x3ac6, 0x5f3a);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x5f3a); return; } I(0x5f3a, 2);  // ret nz
  I(0x5f3b, 3); mem_wr(gb, HL, 0x1e);  // ld (hl),$1e
  I(0x5f3d, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5f3e, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x5f3f, 2); L = 0x4b;  // ld l,$4b
  I(0x5f41, 2); mem_wr(gb, HL, C);  // ld (hl),c
  RET(0x5f42); return;  // ret
}

// 04:5f30
void s_replaceShutterForLinkEntering__doneReplacement(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5f30:
  I(0x5f30, 1); A = E;  // ld a,e
  I(0x5f31, 2); alu_bit(gb, 7, A);  // bit 7,a
  if (!(F & FZ)) { RET_TAKEN(0x5f33); return; } I(0x5f33, 2);  // ret nz
  I(0x5f34, 2); alu_and(gb, 0x7f);  // and $7f
  I(0x5f36, 1); E = A;  // ld e,a
  CALL(0x5f37, getFreeInteractionSlot_hook, 0x3ac6, 0x5f3a);  // call $3ac6
  if (!(F & FZ)) { RET_TAKEN(0x5f3a); return; } I(0x5f3a, 2);  // ret nz
  I(0x5f3b, 3); mem_wr(gb, HL, 0x1e);  // ld (hl),$1e
  I(0x5f3d, 1); L = alu_inc8(gb, L);  // inc l
  I(0x5f3e, 2); mem_wr(gb, HL, E);  // ld (hl),e
  I(0x5f3f, 2); L = 0x4b;  // ld l,$4b
  I(0x5f41, 2); mem_wr(gb, HL, C);  // ld (hl),c
  RET(0x5f42); return;  // ret
}

// 04:6810
void s_roomTileChangesAfterLoad00(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x6810, 2); A = 0x17;  // ld a,$17
  CALL(0x6812, checkGlobalFlag_hook, 0x30c7, 0x6815);  // call $30c7
  if ((F & FZ)) { RET_TAKEN(0x6815); return; } I(0x6815, 2);  // ret z
  I(0x6816, 2); E = 0x00;  // ld e,$00
  CALL(0x6818, loadObjectGfxHeaderToSlot4_hook, 0x1632, 0x681b);  // call $1632
L_681b:
  I(0x681b, 2); A = 0x55;  // ld a,$55
  CALL(0x681d, loadGfxHeader_hook, 0x0602, 0x6820);  // call $0602
  I(0x6820, 3); SET_HL(0x6832);  // ld hl,$6832
  CALL(0x6823, copyRectangleFromTmpGfxBuffer_hook, 0x6a8b, 0x6826);  // call $6a8b
  I(0x6826, 3); SET_HL(0x6838);  // ld hl,$6838
  CALL(0x6829, copyRectangleFromTmpGfxBuffer_hook, 0x6a8b, 0x682c);  // call $6a8b
  I(0x682c, 3); SET_HL(0x683e);  // ld hl,$683e
  I(0x682f, 4); if (hook_is(gb, 0x6abc, copyRectangleToRoomLayoutAndCollisions_hook)) { copyRectangleToRoomLayoutAndCollisions_hook(gb); return; } HANDOFF(0x6abc);  // jp $6abc
}

// 04:681b
void s_roomTileChangesAfterLoad00__afterCall681b(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_681b:
  I(0x681b, 2); A = 0x55;  // ld a,$55
  CALL(0x681d, loadGfxHeader_hook, 0x0602, 0x6820);  // call $0602
  I(0x6820, 3); SET_HL(0x6832);  // ld hl,$6832
  CALL(0x6823, copyRectangleFromTmpGfxBuffer_hook, 0x6a8b, 0x6826);  // call $6a8b
  I(0x6826, 3); SET_HL(0x6838);  // ld hl,$6838
  CALL(0x6829, copyRectangleFromTmpGfxBuffer_hook, 0x6a8b, 0x682c);  // call $6a8b
  I(0x682c, 3); SET_HL(0x683e);  // ld hl,$683e
  I(0x682f, 4); if (hook_is(gb, 0x6abc, copyRectangleToRoomLayoutAndCollisions_hook)) { copyRectangleToRoomLayoutAndCollisions_hook(gb); return; } HANDOFF(0x6abc);  // jp $6abc
}

// 04:6874
void s_roomTileChangesAfterLoad01(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x6874, 2); A = 0x17;  // ld a,$17
  CALL(0x6876, checkGlobalFlag_hook, 0x30c7, 0x6879);  // call $30c7
  if ((F & FZ)) { RET_TAKEN(0x6879); return; } I(0x6879, 2);  // ret z
  I(0x687a, 2); E = 0x00;  // ld e,$00
  CALL(0x687c, loadObjectGfxHeaderToSlot4_hook, 0x1632, 0x687f);  // call $1632
L_687f:
  I(0x687f, 2); A = 0x56;  // ld a,$56
  CALL(0x6881, loadGfxHeader_hook, 0x0602, 0x6884);  // call $0602
  I(0x6884, 3); SET_HL(0x6896);  // ld hl,$6896
  CALL(0x6887, copyRectangleFromTmpGfxBuffer_hook, 0x6a8b, 0x688a);  // call $6a8b
  I(0x688a, 3); SET_HL(0x689c);  // ld hl,$689c
  CALL(0x688d, copyRectangleFromTmpGfxBuffer_hook, 0x6a8b, 0x6890);  // call $6a8b
  I(0x6890, 3); SET_HL(0x68a2);  // ld hl,$68a2
  I(0x6893, 4); if (hook_is(gb, 0x6abc, copyRectangleToRoomLayoutAndCollisions_hook)) { copyRectangleToRoomLayoutAndCollisions_hook(gb); return; } HANDOFF(0x6abc);  // jp $6abc
}

// 04:687f
void s_roomTileChangesAfterLoad01__afterCall687f(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_687f:
  I(0x687f, 2); A = 0x56;  // ld a,$56
  CALL(0x6881, loadGfxHeader_hook, 0x0602, 0x6884);  // call $0602
  I(0x6884, 3); SET_HL(0x6896);  // ld hl,$6896
  CALL(0x6887, copyRectangleFromTmpGfxBuffer_hook, 0x6a8b, 0x688a);  // call $6a8b
  I(0x688a, 3); SET_HL(0x689c);  // ld hl,$689c
  CALL(0x688d, copyRectangleFromTmpGfxBuffer_hook, 0x6a8b, 0x6890);  // call $6a8b
  I(0x6890, 3); SET_HL(0x68a2);  // ld hl,$68a2
  I(0x6893, 4); if (hook_is(gb, 0x6abc, copyRectangleToRoomLayoutAndCollisions_hook)) { copyRectangleToRoomLayoutAndCollisions_hook(gb); return; } HANDOFF(0x6abc);  // jp $6abc
}

// 04:68ba
void s_roomTileChangesAfterLoad03(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  CALL(0x68ba, getThisRoomFlags_hook, 0x1956, 0x68bd);  // call $1956
  I(0x68bd, 2); alu_and(gb, 0x40);  // and $40
  if (!(F & FZ)) { RET_TAKEN(0x68bf); return; } I(0x68bf, 2);  // ret nz
  I(0x68c0, 1); alu_xor(gb, A);  // xor a
  I(0x68c1, 4); mem_wr(gb, 0xcf14, A);  // ld ($cf14),a
  I(0x68c4, 4); mem_wr(gb, 0xcf24, A);  // ld ($cf24),a
  I(0x68c7, 3); A = mem_rd(gb, 0xff70);  // ldh a,($ff70)
  I(0x68c9, 1); C = A;  // ld c,a
  I(0x68ca, 3); A = mem_rd(gb, 0xff97);  // ldh a,($ff97)
  I(0x68cc, 1); B = A;  // ld b,a
  PUSH(0x68cd, BC);  // push bc
  I(0x68ce, 3); SET_DE(0x691d);  // ld de,$691d
  s_loadDinsTroupeTileChanges(gb); return;  // fallthrough
}

// 04:6991
void s_roomTileChangesAfterLoad05(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x6991, 2); A = 0x16;  // ld a,$16
  CALL(0x6993, checkGlobalFlag_hook, 0x30c7, 0x6996);  // call $30c7
  if ((F & FZ)) { RET_TAKEN(0x6996); return; } I(0x6996, 2);  // ret z
  I(0x6997, 2); E = 0x08;  // ld e,$08
  CALL(0x6999, loadObjectGfxHeaderToSlot4_hook, 0x1632, 0x699c);  // call $1632
L_699c:
  I(0x699c, 3); SET_HL(0x69a2);  // ld hl,$69a2
  I(0x699f, 4); if (hook_is(gb, 0x6a66, drawRectangleToVramTiles_hook)) { drawRectangleToVramTiles_hook(gb); return; } HANDOFF(0x6a66);  // jp $6a66
}

// 04:699c
void s_roomTileChangesAfterLoad05__afterCall699c(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_699c:
  I(0x699c, 3); SET_HL(0x69a2);  // ld hl,$69a2
  I(0x699f, 4); if (hook_is(gb, 0x6a66, drawRectangleToVramTiles_hook)) { drawRectangleToVramTiles_hook(gb); return; } HANDOFF(0x6a66);  // jp $6a66
}

// 04:69d6
void s_roomTileChangesAfterLoad06(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x69d6, 2); A = 0x01;  // ld a,$01
  CALL(0x69d8, loadTreeGfx_hook, 0x1646, 0x69db);  // call $1646
L_69db:
  I(0x69db, 3); SET_HL(0x69e1);  // ld hl,$69e1
  I(0x69de, 4); if (hook_is(gb, 0x6a66, drawRectangleToVramTiles_hook)) { drawRectangleToVramTiles_hook(gb); return; } HANDOFF(0x6a66);  // jp $6a66
}

// 04:69db
void s_roomTileChangesAfterLoad06__afterCall69db(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_69db:
  I(0x69db, 3); SET_HL(0x69e1);  // ld hl,$69e1
  I(0x69de, 4); if (hook_is(gb, 0x6a66, drawRectangleToVramTiles_hook)) { drawRectangleToVramTiles_hook(gb); return; } HANDOFF(0x6a66);  // jp $6a66
}

// 04:69fd
void s_roomTileChangesAfterLoad07(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x69fd, 2); A = 0x01;  // ld a,$01
  CALL(0x69ff, loadTreeGfx_hook, 0x1646, 0x6a02);  // call $1646
L_6a02:
  I(0x6a02, 3); SET_HL(0x6a0e);  // ld hl,$6a0e
  CALL(0x6a05, drawRectangleToVramTiles_hook, 0x6a66, 0x6a08);  // call $6a66
  if (hook_is(gb, 0x6a08, s_roomTileChangesAfterLoad0f_hook)) { s_roomTileChangesAfterLoad0f_hook(gb); return; } HANDOFF(0x6a08);  // fallthrough
}

// 04:6a02
void s_roomTileChangesAfterLoad07__afterCall6a02(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_6a02:
  I(0x6a02, 3); SET_HL(0x6a0e);  // ld hl,$6a0e
  CALL(0x6a05, drawRectangleToVramTiles_hook, 0x6a66, 0x6a08);  // call $6a66
  if (hook_is(gb, 0x6a08, s_roomTileChangesAfterLoad0f_hook)) { s_roomTileChangesAfterLoad0f_hook(gb); return; } HANDOFF(0x6a08);  // fallthrough
}

// 04:6a1a
void s_roomTileChangesAfterLoad08(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x6a1a, 4); A = mem_rd(gb, 0xcc4c);  // ld a,($cc4c)
  CALL(0x6a1d, getIndexOfGashaSpotInRoom_body_hook, 0x66cc, 0x6a20);  // call $66cc
  if ((F & FZ)) { RET_TAKEN(0x6a20); return; } I(0x6a20, 2);  // ret z
  I(0x6a21, 2); A = 0xe0;  // ld a,$e0
  CALL(0x6a23, findTileInRoom_hook, 0x15ba, 0x6a26);  // call $15ba
  if (!(F & FZ)) { RET_TAKEN(0x6a26); return; } I(0x6a26, 2);  // ret nz
  I(0x6a27, 1); E = L;  // ld e,l
  I(0x6a28, 2); D = 0xcf;  // ld d,$cf
  I(0x6a2a, 1); A = C;  // ld a,c
  I(0x6a2b, 3); SET_HL(0xc64c);  // ld hl,$c64c
  RST_PUSH(0x6a2e, 0x6a2f);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x6a2f, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x6a30, 2); alu_cp(gb, 0x14);  // cp $14
  if ((F & FC)) { I(0x6a32, 3); goto L_6a3d; } I(0x6a32, 2);  // jr c,$6a3d
  I(0x6a34, 1); A = E;  // ld a,e
  I(0x6a35, 2); alu_sub(gb, 0x10);  // sub $10
  I(0x6a37, 1); E = A;  // ld e,a
  I(0x6a38, 3); SET_HL(0x6a4a);  // ld hl,$6a4a
  I(0x6a3b, 3); goto L_6a40;  // jr $6a40
L_6a3d:
  I(0x6a3d, 3); SET_HL(0x6a46);  // ld hl,$6a46
L_6a40:
  CALL(0x6a40, copyRectangleToRoomLayoutAndCollisions_paramDe_hook, 0x6ac0, 0x6a43);  // call $6ac0
  I(0x6a43, 4); if (hook_is(gb, 0x6ae4, generateW3VramTilesAndAttributes_hook)) { generateW3VramTilesAndAttributes_hook(gb); return; } HANDOFF(0x6ae4);  // jp $6ae4
}

// 04:6776
void s_roomTileChangesAfterLoad09(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x6776, 2); A = 0x07;  // ld a,$07
  s_label_04_291(gb); return;  // fallthrough
}

// 04:679d
void s_roomTileChangesAfterLoad0a(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x679d, 2); A = 0x08;  // ld a,$08
  I(0x679f, 3); s_label_04_291(gb); return;  // jr $6778
}

// 04:67a1
void s_roomTileChangesAfterLoad0b(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x67a1, 3); SET_HL(0x67ac);  // ld hl,$67ac
  s_loadGaleTreeGfx(gb); return;  // fallthrough
}

// 04:67c8
void s_roomTileChangesAfterLoad0c(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x67c8, 3); SET_HL(0x67cd);  // ld hl,$67cd
  I(0x67cb, 3); s_loadGaleTreeGfx(gb); return;  // jr $67a4
}

// 04:67e9
void s_roomTileChangesAfterLoad0d(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x67e9, 2); A = 0x0a;  // ld a,$0a
  CALL(0x67eb, loadTreeGfx_hook, 0x1646, 0x67ee);  // call $1646
L_67ee:
  I(0x67ee, 3); SET_HL(0x67f4);  // ld hl,$67f4
  I(0x67f1, 4); if (hook_is(gb, 0x6a66, drawRectangleToVramTiles_hook)) { drawRectangleToVramTiles_hook(gb); return; } HANDOFF(0x6a66);  // jp $6a66
}

// 04:67ee
void s_roomTileChangesAfterLoad0d__afterCall67ee(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_67ee:
  I(0x67ee, 3); SET_HL(0x67f4);  // ld hl,$67f4
  I(0x67f1, 4); if (hook_is(gb, 0x6a66, drawRectangleToVramTiles_hook)) { drawRectangleToVramTiles_hook(gb); return; } HANDOFF(0x6a66);  // jp $6a66
}

// 04:63f2
void s_tileReplacement_group0Map54(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x63f2, 4); A = mem_rd(gb, 0xc643);  // ld a,($c643)
  I(0x63f5, 2); alu_bit(gb, 6, A);  // bit 6,a
  if ((F & FZ)) { RET_TAKEN(0x63f7); return; } I(0x63f7, 2);  // ret z
  I(0x63f8, 3); SET_HL(0xcf34);  // ld hl,$cf34
  I(0x63fb, 3); mem_wr(gb, HL, 0xf2);  // ld (hl),$f2
  RET(0x63fd); return;  // ret
}

// 04:6449
void s_tileReplacement_group0Map61(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x6449, 2); A = 0x81;  // ld a,$81
  CALL(0x644b, getARoomFlags_hook, 0x1959, 0x644e);  // call $1959
  I(0x644e, 3); alu_bit(gb, 7, mem_rd(gb, HL));  // bit 7,(hl)
  if (!(F & FZ)) { RET_TAKEN(0x6450); return; } I(0x6450, 2);  // ret nz
  I(0x6451, 3); SET_HL(0x6457);  // ld hl,$6457
  I(0x6454, 4); if (hook_is(gb, 0x669d, fillRectInRoomLayout_hook)) { fillRectInRoomLayout_hook(gb); return; } HANDOFF(0x669d);  // jp $669d
}

