// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/seasons/gen.h"

// 31:4619
void s_flg_titlescreen(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x4619, 2); B = mem_rd(gb, HL);  // ld b,(hl)
  I(0x461a, 3); SET_BC(0x1100);  // ld bc,$1100
  I(0x461d, 3); SET_HL(0x0021);  // ld hl,$0021
  I(0x4620, 1);  // nop
  I(0x4621, 2); SET_BC(BC - 1);  // dec bc
  I(0x4622, 1); alu_rra(gb);  // rra
  I(0x4623, 2); H = 0x07;  // ld h,$07
  CALL_ASM_RST(0x4625, 0x0030, 0x4626);  // rst $30
  I(0x4626, 1); alu_add(gb, B);  // add b
  I(0x4627, 1); alu_rra(gb);  // rra
  I(0x4628, 1); alu_rla(gb);  // rla
  I(0x4629, 1); A = D;  // ld a,d
  I(0x462a, 2); alu_xor(gb, 0x07);  // xor $07
  I(0x462c, 1); alu_rra(gb);  // rra
  I(0x462d, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x462e, 2); SET_DE(DE - 1);  // dec de
  I(0x462f, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x4630, 1); alu_add(gb, B);  // add b
  I(0x4631, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x4632, 1); alu_rlca(gb);  // rlca
  I(0x4633, 1); alu_rlca(gb);  // rlca
  I(0x4634, 3); gb->sp = 0x1c1f; gb->sp_loads++; HANDOFF_UP(0x4637);  // ld sp,$1c1f
L_4637:
  I(0x4637, 1);  // nop
  I(0x4638, 1); alu_rra(gb);  // rra
L_4639:
  I(0x4639, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x463a, 1); alu_rlca(gb);  // rlca
  I(0x463b, 1); alu_rra(gb);  // rra
  I(0x463c, 2); C = 0xf2;  // ld c,$f2
  I(0x463e, 1); alu_rrca(gb);  // rrca
  I(0x463f, 2); C = 0x1f;  // ld c,$1f
  I(0x4641, 3); SET_HL(0x0f1e);  // ld hl,$0f1e
  if (!(F & FZ)) { I(0x4644, 3); goto L_464d; } I(0x4644, 2);  // jr nz,$464d
  I(0x4646, 3); SET_BC(0x141f);  // ld bc,$141f
  I(0x4649, 2); SET_BC(BC + 1);  // inc bc
  CALL_ASM_RST(0x464a, 0x0038, 0x464b);  // rst $38
  I(0x464b, 1); B = B;  // ld b,b
  I(0x464c, 1); H = L;  // ld h,l
L_464d:
  I(0x464d, 2); L = 0x1f;  // ld l,$1f
  I(0x464f, 1); alu_rrca(gb);  // rrca
  if (!(F & FZ)) { I(0x4650, 3); goto L_46a4; } I(0x4650, 2);  // jr nz,$46a4
  I(0x4652, 1); B = B;  // ld b,b
  I(0x4653, 2); gb->sp = gb->sp - 1;  // dec sp
  I(0x4654, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x4655, 1);  // nop
  I(0x4656, 1); A = E;  // ld a,e
  I(0x4657, 1); H = B;  // ld h,b
  I(0x4658, 1); alu_rra(gb);  // rra
  I(0x4659, 1); alu_rrca(gb);  // rrca
  I(0x465a, 3); SET_BC(0x0407);  // ld bc,$0407
  I(0x465d, 3); mem_wr(gb, 0xff29, A);  // ldh ($ff29),a
  I(0x465f, 2); B = 0x05;  // ld b,$05
  I(0x4661, 1); alu_rra(gb);  // rra
  I(0x4662, 1); D = alu_dec8(gb, D);  // dec d
  I(0x4663, 2); B = 0x1f;  // ld b,$1f
  I(0x4665, 2); E = 0x01;  // ld e,$01
  I(0x4667, 1); alu_rlca(gb);  // rlca
  I(0x4668, 1); H = B;  // ld h,b
  I(0x4669, 1); alu_cpl(gb);  // cpl
  I(0x466a, 1); alu_daa(gb);  // daa
  I(0x466b, 1); alu_daa(gb);  // daa
  I(0x466c, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x466d, 1); alu_rlca(gb);  // rlca
  I(0x466e, 2); alu_adc(gb, mem_rd(gb, HL));  // adc (hl)
  I(0x466f, 1); alu_rra(gb);  // rra
  I(0x4670, 3); SET_DE(0x0f00);  // ld de,$0f00
  I(0x4673, 1); alu_rra(gb);  // rra
  I(0x4674, 3); gb->sp = 0x0a5b; gb->sp_loads++; HANDOFF_UP(0x4677);  // ld sp,$0a5b
L_4677:
  I(0x4677, 1); alu_and(gb, B);  // and b
  I(0x4678, 2); mem_wr(gb, BC, A);  // ld (bc),a
  if (!(F & FZ)) { I(0x4679, 3); goto L_469a; } I(0x4679, 2);  // jr nz,$469a
  I(0x467b, 2); D = 0x09;  // ld d,$09
  I(0x467d, 1);  // nop
  I(0x467e, 1); C = alu_inc8(gb, C);  // inc c
  I(0x467f, 1); alu_rra(gb);  // rra
  I(0x4680, 2); C = 0x40;  // ld c,$40
  CALL_ASM_RST(0x4682, 0x0038, 0x4683);  // rst $38
  I(0x4683, 1);  // nop
  I(0x4684, 2); SET_DE(DE + 1);  // inc de
  I(0x4685, 2); alu_cp(gb, 0xff);  // cp $ff
  I(0x4687, 1); E = alu_inc8(gb, E);  // inc e
  I(0x4688, 3); mem_wr(gb, 0xffc7, A);  // ldh ($ffc7),a
  I(0x468a, 3); alu_ld_hl_sp(gb, 0xd1);  // ld hl,sp+$d1
  I(0x468c, 1); H = alu_dec8(gb, H);  // dec h
  if (!(F & FZ)) { I(0x468d, 3); goto L_4639; } I(0x468d, 2);  // jr nz,$4639
  I(0x468f, 1); alu_adc(gb, A);  // adc a
  I(0x4690, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4691, 3); A = mem_rd(gb, 0xff00);  // ldh a,($ff00)
  I(0x4693, 1); B = B;  // ld b,b
  I(0x4694, 1); B = alu_dec8(gb, B);  // dec b
  I(0x4695, 1); alu_rrca(gb);  // rrca
  I(0x4696, 3); A = mem_rd(gb, 0xffd4);  // ldh a,($ffd4)
  CALL_ASM_RST(0x4698, 0x0038, 0x4699);  // rst $38
  I(0x4699, 1);  // nop
L_469a:
  I(0x469a, 1); alu_adc(gb, A);  // adc a
  I(0x469b, 3); SET_BC(0x926e);  // ld bc,$926e
  I(0x469e, 1); B = B;  // ld b,b
  I(0x469f, 1); A = A;  // ld a,a
  I(0x46a0, 1); alu_add(gb, B);  // add b
  I(0x46a1, 1); alu_xor(gb, A);  // xor a
  I(0x46a2, 3); mem_wr(gb, 0xff1f, A);  // ldh ($ff1f),a
L_46a4:
  I(0x46a4, 1); L = L;  // ld l,l
  I(0x46a5, 1); alu_ccf(gb);  // ccf
  I(0x46a6, 1); A = alu_inc8(gb, A);  // inc a
  I(0x46a7, 1);  // nop
  if (!(F & FZ)) { RET_TAKEN(0x46a8); return; } I(0x46a8, 2);  // ret nz
  I(0x46a9, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x46aa, 1); C = L;  // ld c,l
  I(0x46ab, 2); SET_HL(HL + 1);  // inc hl
  I(0x46ac, 1); B = C;  // ld b,c
  I(0x46ad, 1);  // nop
  I(0x46ae, 1); alu_rlca(gb);  // rlca
  if (!(F & FC)) { I(0x46af, 3); goto L_46b1; } I(0x46af, 2);  // jr nc,$46b1
L_46b1:
  PUSH(0x46b1, BC);  // push bc
  I(0x46b2, 1); C = L;  // ld c,l
  I(0x46b3, 1); alu_xor(gb, A);  // xor a
  I(0x46b4, 1); D = L;  // ld d,l
  CALL_ASM_RST(0x46b5, 0x0038, 0x46b6);  // rst $38
  I(0x46b6, 1); C = alu_inc8(gb, C);  // inc c
  I(0x46b7, 2); SET_BC(BC + 1);  // inc bc
  I(0x46b8, 1); L = L;  // ld l,l
  I(0x46b9, 1); alu_rrca(gb);  // rrca
  RETI(0x46ba); return;  // reti
}

// 31:4637
void s_flg_titlescreen__afterSp4637(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4637:
  I(0x4637, 1);  // nop
  I(0x4638, 1); alu_rra(gb);  // rra
L_4639:
  I(0x4639, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x463a, 1); alu_rlca(gb);  // rlca
  I(0x463b, 1); alu_rra(gb);  // rra
  I(0x463c, 2); C = 0xf2;  // ld c,$f2
  I(0x463e, 1); alu_rrca(gb);  // rrca
  I(0x463f, 2); C = 0x1f;  // ld c,$1f
  I(0x4641, 3); SET_HL(0x0f1e);  // ld hl,$0f1e
  if (!(F & FZ)) { I(0x4644, 3); goto L_464d; } I(0x4644, 2);  // jr nz,$464d
  I(0x4646, 3); SET_BC(0x141f);  // ld bc,$141f
  I(0x4649, 2); SET_BC(BC + 1);  // inc bc
  CALL_ASM_RST(0x464a, 0x0038, 0x464b);  // rst $38
  I(0x464b, 1); B = B;  // ld b,b
  I(0x464c, 1); H = L;  // ld h,l
L_464d:
  I(0x464d, 2); L = 0x1f;  // ld l,$1f
  I(0x464f, 1); alu_rrca(gb);  // rrca
  if (!(F & FZ)) { I(0x4650, 3); goto L_46a4; } I(0x4650, 2);  // jr nz,$46a4
  I(0x4652, 1); B = B;  // ld b,b
  I(0x4653, 2); gb->sp = gb->sp - 1;  // dec sp
  I(0x4654, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x4655, 1);  // nop
  I(0x4656, 1); A = E;  // ld a,e
  I(0x4657, 1); H = B;  // ld h,b
  I(0x4658, 1); alu_rra(gb);  // rra
  I(0x4659, 1); alu_rrca(gb);  // rrca
  I(0x465a, 3); SET_BC(0x0407);  // ld bc,$0407
  I(0x465d, 3); mem_wr(gb, 0xff29, A);  // ldh ($ff29),a
  I(0x465f, 2); B = 0x05;  // ld b,$05
  I(0x4661, 1); alu_rra(gb);  // rra
  I(0x4662, 1); D = alu_dec8(gb, D);  // dec d
  I(0x4663, 2); B = 0x1f;  // ld b,$1f
  I(0x4665, 2); E = 0x01;  // ld e,$01
  I(0x4667, 1); alu_rlca(gb);  // rlca
  I(0x4668, 1); H = B;  // ld h,b
  I(0x4669, 1); alu_cpl(gb);  // cpl
  I(0x466a, 1); alu_daa(gb);  // daa
  I(0x466b, 1); alu_daa(gb);  // daa
  I(0x466c, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x466d, 1); alu_rlca(gb);  // rlca
  I(0x466e, 2); alu_adc(gb, mem_rd(gb, HL));  // adc (hl)
  I(0x466f, 1); alu_rra(gb);  // rra
  I(0x4670, 3); SET_DE(0x0f00);  // ld de,$0f00
  I(0x4673, 1); alu_rra(gb);  // rra
  I(0x4674, 3); gb->sp = 0x0a5b; gb->sp_loads++; HANDOFF_UP(0x4677);  // ld sp,$0a5b
L_4677:
  I(0x4677, 1); alu_and(gb, B);  // and b
  I(0x4678, 2); mem_wr(gb, BC, A);  // ld (bc),a
  if (!(F & FZ)) { I(0x4679, 3); goto L_469a; } I(0x4679, 2);  // jr nz,$469a
  I(0x467b, 2); D = 0x09;  // ld d,$09
  I(0x467d, 1);  // nop
  I(0x467e, 1); C = alu_inc8(gb, C);  // inc c
  I(0x467f, 1); alu_rra(gb);  // rra
  I(0x4680, 2); C = 0x40;  // ld c,$40
  CALL_ASM_RST(0x4682, 0x0038, 0x4683);  // rst $38
  I(0x4683, 1);  // nop
  I(0x4684, 2); SET_DE(DE + 1);  // inc de
  I(0x4685, 2); alu_cp(gb, 0xff);  // cp $ff
  I(0x4687, 1); E = alu_inc8(gb, E);  // inc e
  I(0x4688, 3); mem_wr(gb, 0xffc7, A);  // ldh ($ffc7),a
  I(0x468a, 3); alu_ld_hl_sp(gb, 0xd1);  // ld hl,sp+$d1
  I(0x468c, 1); H = alu_dec8(gb, H);  // dec h
  if (!(F & FZ)) { I(0x468d, 3); goto L_4639; } I(0x468d, 2);  // jr nz,$4639
  I(0x468f, 1); alu_adc(gb, A);  // adc a
  I(0x4690, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4691, 3); A = mem_rd(gb, 0xff00);  // ldh a,($ff00)
  I(0x4693, 1); B = B;  // ld b,b
  I(0x4694, 1); B = alu_dec8(gb, B);  // dec b
  I(0x4695, 1); alu_rrca(gb);  // rrca
  I(0x4696, 3); A = mem_rd(gb, 0xffd4);  // ldh a,($ffd4)
  CALL_ASM_RST(0x4698, 0x0038, 0x4699);  // rst $38
  I(0x4699, 1);  // nop
L_469a:
  I(0x469a, 1); alu_adc(gb, A);  // adc a
  I(0x469b, 3); SET_BC(0x926e);  // ld bc,$926e
  I(0x469e, 1); B = B;  // ld b,b
  I(0x469f, 1); A = A;  // ld a,a
  I(0x46a0, 1); alu_add(gb, B);  // add b
  I(0x46a1, 1); alu_xor(gb, A);  // xor a
  I(0x46a2, 3); mem_wr(gb, 0xff1f, A);  // ldh ($ff1f),a
L_46a4:
  I(0x46a4, 1); L = L;  // ld l,l
  I(0x46a5, 1); alu_ccf(gb);  // ccf
  I(0x46a6, 1); A = alu_inc8(gb, A);  // inc a
  I(0x46a7, 1);  // nop
  if (!(F & FZ)) { RET_TAKEN(0x46a8); return; } I(0x46a8, 2);  // ret nz
  I(0x46a9, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x46aa, 1); C = L;  // ld c,l
  I(0x46ab, 2); SET_HL(HL + 1);  // inc hl
  I(0x46ac, 1); B = C;  // ld b,c
  I(0x46ad, 1);  // nop
  I(0x46ae, 1); alu_rlca(gb);  // rlca
  if (!(F & FC)) { I(0x46af, 3); goto L_46b1; } I(0x46af, 2);  // jr nc,$46b1
L_46b1:
  PUSH(0x46b1, BC);  // push bc
  I(0x46b2, 1); C = L;  // ld c,l
  I(0x46b3, 1); alu_xor(gb, A);  // xor a
  I(0x46b4, 1); D = L;  // ld d,l
  CALL_ASM_RST(0x46b5, 0x0038, 0x46b6);  // rst $38
  I(0x46b6, 1); C = alu_inc8(gb, C);  // inc c
  I(0x46b7, 2); SET_BC(BC + 1);  // inc bc
  I(0x46b8, 1); L = L;  // ld l,l
  I(0x46b9, 1); alu_rrca(gb);  // rrca
  RETI(0x46ba); return;  // reti
}

// 31:4677
void s_flg_titlescreen__afterSp4677(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_4677;
L_4639:
  I(0x4639, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x463a, 1); alu_rlca(gb);  // rlca
  I(0x463b, 1); alu_rra(gb);  // rra
  I(0x463c, 2); C = 0xf2;  // ld c,$f2
  I(0x463e, 1); alu_rrca(gb);  // rrca
  I(0x463f, 2); C = 0x1f;  // ld c,$1f
  I(0x4641, 3); SET_HL(0x0f1e);  // ld hl,$0f1e
  if (!(F & FZ)) { I(0x4644, 3); goto L_464d; } I(0x4644, 2);  // jr nz,$464d
  I(0x4646, 3); SET_BC(0x141f);  // ld bc,$141f
  I(0x4649, 2); SET_BC(BC + 1);  // inc bc
  CALL_ASM_RST(0x464a, 0x0038, 0x464b);  // rst $38
  I(0x464b, 1); B = B;  // ld b,b
  I(0x464c, 1); H = L;  // ld h,l
L_464d:
  I(0x464d, 2); L = 0x1f;  // ld l,$1f
  I(0x464f, 1); alu_rrca(gb);  // rrca
  if (!(F & FZ)) { I(0x4650, 3); goto L_46a4; } I(0x4650, 2);  // jr nz,$46a4
  I(0x4652, 1); B = B;  // ld b,b
  I(0x4653, 2); gb->sp = gb->sp - 1;  // dec sp
  I(0x4654, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x4655, 1);  // nop
  I(0x4656, 1); A = E;  // ld a,e
  I(0x4657, 1); H = B;  // ld h,b
  I(0x4658, 1); alu_rra(gb);  // rra
  I(0x4659, 1); alu_rrca(gb);  // rrca
  I(0x465a, 3); SET_BC(0x0407);  // ld bc,$0407
  I(0x465d, 3); mem_wr(gb, 0xff29, A);  // ldh ($ff29),a
  I(0x465f, 2); B = 0x05;  // ld b,$05
  I(0x4661, 1); alu_rra(gb);  // rra
  I(0x4662, 1); D = alu_dec8(gb, D);  // dec d
  I(0x4663, 2); B = 0x1f;  // ld b,$1f
  I(0x4665, 2); E = 0x01;  // ld e,$01
  I(0x4667, 1); alu_rlca(gb);  // rlca
  I(0x4668, 1); H = B;  // ld h,b
  I(0x4669, 1); alu_cpl(gb);  // cpl
  I(0x466a, 1); alu_daa(gb);  // daa
  I(0x466b, 1); alu_daa(gb);  // daa
  I(0x466c, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x466d, 1); alu_rlca(gb);  // rlca
  I(0x466e, 2); alu_adc(gb, mem_rd(gb, HL));  // adc (hl)
  I(0x466f, 1); alu_rra(gb);  // rra
  I(0x4670, 3); SET_DE(0x0f00);  // ld de,$0f00
  I(0x4673, 1); alu_rra(gb);  // rra
  I(0x4674, 3); gb->sp = 0x0a5b; gb->sp_loads++; HANDOFF_UP(0x4677);  // ld sp,$0a5b
L_4677:
  I(0x4677, 1); alu_and(gb, B);  // and b
  I(0x4678, 2); mem_wr(gb, BC, A);  // ld (bc),a
  if (!(F & FZ)) { I(0x4679, 3); goto L_469a; } I(0x4679, 2);  // jr nz,$469a
  I(0x467b, 2); D = 0x09;  // ld d,$09
  I(0x467d, 1);  // nop
  I(0x467e, 1); C = alu_inc8(gb, C);  // inc c
  I(0x467f, 1); alu_rra(gb);  // rra
  I(0x4680, 2); C = 0x40;  // ld c,$40
  CALL_ASM_RST(0x4682, 0x0038, 0x4683);  // rst $38
  I(0x4683, 1);  // nop
  I(0x4684, 2); SET_DE(DE + 1);  // inc de
  I(0x4685, 2); alu_cp(gb, 0xff);  // cp $ff
  I(0x4687, 1); E = alu_inc8(gb, E);  // inc e
  I(0x4688, 3); mem_wr(gb, 0xffc7, A);  // ldh ($ffc7),a
  I(0x468a, 3); alu_ld_hl_sp(gb, 0xd1);  // ld hl,sp+$d1
  I(0x468c, 1); H = alu_dec8(gb, H);  // dec h
  if (!(F & FZ)) { I(0x468d, 3); goto L_4639; } I(0x468d, 2);  // jr nz,$4639
  I(0x468f, 1); alu_adc(gb, A);  // adc a
  I(0x4690, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4691, 3); A = mem_rd(gb, 0xff00);  // ldh a,($ff00)
  I(0x4693, 1); B = B;  // ld b,b
  I(0x4694, 1); B = alu_dec8(gb, B);  // dec b
  I(0x4695, 1); alu_rrca(gb);  // rrca
  I(0x4696, 3); A = mem_rd(gb, 0xffd4);  // ldh a,($ffd4)
  CALL_ASM_RST(0x4698, 0x0038, 0x4699);  // rst $38
  I(0x4699, 1);  // nop
L_469a:
  I(0x469a, 1); alu_adc(gb, A);  // adc a
  I(0x469b, 3); SET_BC(0x926e);  // ld bc,$926e
  I(0x469e, 1); B = B;  // ld b,b
  I(0x469f, 1); A = A;  // ld a,a
  I(0x46a0, 1); alu_add(gb, B);  // add b
  I(0x46a1, 1); alu_xor(gb, A);  // xor a
  I(0x46a2, 3); mem_wr(gb, 0xff1f, A);  // ldh ($ff1f),a
L_46a4:
  I(0x46a4, 1); L = L;  // ld l,l
  I(0x46a5, 1); alu_ccf(gb);  // ccf
  I(0x46a6, 1); A = alu_inc8(gb, A);  // inc a
  I(0x46a7, 1);  // nop
  if (!(F & FZ)) { RET_TAKEN(0x46a8); return; } I(0x46a8, 2);  // ret nz
  I(0x46a9, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x46aa, 1); C = L;  // ld c,l
  I(0x46ab, 2); SET_HL(HL + 1);  // inc hl
  I(0x46ac, 1); B = C;  // ld b,c
  I(0x46ad, 1);  // nop
  I(0x46ae, 1); alu_rlca(gb);  // rlca
  if (!(F & FC)) { I(0x46af, 3); goto L_46b1; } I(0x46af, 2);  // jr nc,$46b1
L_46b1:
  PUSH(0x46b1, BC);  // push bc
  I(0x46b2, 1); C = L;  // ld c,l
  I(0x46b3, 1); alu_xor(gb, A);  // xor a
  I(0x46b4, 1); D = L;  // ld d,l
  CALL_ASM_RST(0x46b5, 0x0038, 0x46b6);  // rst $38
  I(0x46b6, 1); C = alu_inc8(gb, C);  // inc c
  I(0x46b7, 2); SET_BC(BC + 1);  // inc bc
  I(0x46b8, 1); L = L;  // ld l,l
  I(0x46b9, 1); alu_rrca(gb);  // rrca
  RETI(0x46ba); return;  // reti
}

// 31:4681
void s_gfx_intro_link_riding_horse_1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_4681;
L_4639:
  I(0x4639, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x463a, 1); alu_rlca(gb);  // rlca
  I(0x463b, 1); alu_rra(gb);  // rra
  I(0x463c, 2); C = 0xf2;  // ld c,$f2
  I(0x463e, 1); alu_rrca(gb);  // rrca
  I(0x463f, 2); C = 0x1f;  // ld c,$1f
  I(0x4641, 3); SET_HL(0x0f1e);  // ld hl,$0f1e
  if (!(F & FZ)) { I(0x4644, 3); goto L_464d; } I(0x4644, 2);  // jr nz,$464d
  I(0x4646, 3); SET_BC(0x141f);  // ld bc,$141f
  I(0x4649, 2); SET_BC(BC + 1);  // inc bc
  CALL_ASM_RST(0x464a, 0x0038, 0x464b);  // rst $38
  I(0x464b, 1); B = B;  // ld b,b
  I(0x464c, 1); H = L;  // ld h,l
L_464d:
  I(0x464d, 2); L = 0x1f;  // ld l,$1f
  I(0x464f, 1); alu_rrca(gb);  // rrca
  if (!(F & FZ)) { I(0x4650, 3); goto L_46a4; } I(0x4650, 2);  // jr nz,$46a4
  I(0x4652, 1); B = B;  // ld b,b
  I(0x4653, 2); gb->sp = gb->sp - 1;  // dec sp
  I(0x4654, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x4655, 1);  // nop
  I(0x4656, 1); A = E;  // ld a,e
  I(0x4657, 1); H = B;  // ld h,b
  I(0x4658, 1); alu_rra(gb);  // rra
  I(0x4659, 1); alu_rrca(gb);  // rrca
  I(0x465a, 3); SET_BC(0x0407);  // ld bc,$0407
  I(0x465d, 3); mem_wr(gb, 0xff29, A);  // ldh ($ff29),a
  I(0x465f, 2); B = 0x05;  // ld b,$05
  I(0x4661, 1); alu_rra(gb);  // rra
  I(0x4662, 1); D = alu_dec8(gb, D);  // dec d
  I(0x4663, 2); B = 0x1f;  // ld b,$1f
  I(0x4665, 2); E = 0x01;  // ld e,$01
  I(0x4667, 1); alu_rlca(gb);  // rlca
  I(0x4668, 1); H = B;  // ld h,b
  I(0x4669, 1); alu_cpl(gb);  // cpl
  I(0x466a, 1); alu_daa(gb);  // daa
  I(0x466b, 1); alu_daa(gb);  // daa
  I(0x466c, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x466d, 1); alu_rlca(gb);  // rlca
  I(0x466e, 2); alu_adc(gb, mem_rd(gb, HL));  // adc (hl)
  I(0x466f, 1); alu_rra(gb);  // rra
  I(0x4670, 3); SET_DE(0x0f00);  // ld de,$0f00
  I(0x4673, 1); alu_rra(gb);  // rra
  I(0x4674, 3); gb->sp = 0x0a5b; gb->sp_loads++; HANDOFF_UP(0x4677);  // ld sp,$0a5b
L_4677:
  I(0x4677, 1); alu_and(gb, B);  // and b
  I(0x4678, 2); mem_wr(gb, BC, A);  // ld (bc),a
  if (!(F & FZ)) { I(0x4679, 3); goto L_469a; } I(0x4679, 2);  // jr nz,$469a
  I(0x467b, 2); D = 0x09;  // ld d,$09
  I(0x467d, 1);  // nop
  I(0x467e, 1); C = alu_inc8(gb, C);  // inc c
  I(0x467f, 1); alu_rra(gb);  // rra
  I(0x4680, 2); C = 0x40;  // ld c,$40
L_4681:
  I(0x4681, 1); B = B;  // ld b,b
  CALL_ASM_RST(0x4682, 0x0038, 0x4683);  // rst $38
  I(0x4683, 1);  // nop
  I(0x4684, 2); SET_DE(DE + 1);  // inc de
  I(0x4685, 2); alu_cp(gb, 0xff);  // cp $ff
  I(0x4687, 1); E = alu_inc8(gb, E);  // inc e
  I(0x4688, 3); mem_wr(gb, 0xffc7, A);  // ldh ($ffc7),a
  I(0x468a, 3); alu_ld_hl_sp(gb, 0xd1);  // ld hl,sp+$d1
  I(0x468c, 1); H = alu_dec8(gb, H);  // dec h
  if (!(F & FZ)) { I(0x468d, 3); goto L_4639; } I(0x468d, 2);  // jr nz,$4639
  I(0x468f, 1); alu_adc(gb, A);  // adc a
  I(0x4690, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4691, 3); A = mem_rd(gb, 0xff00);  // ldh a,($ff00)
  I(0x4693, 1); B = B;  // ld b,b
  I(0x4694, 1); B = alu_dec8(gb, B);  // dec b
  I(0x4695, 1); alu_rrca(gb);  // rrca
  I(0x4696, 3); A = mem_rd(gb, 0xffd4);  // ldh a,($ffd4)
  CALL_ASM_RST(0x4698, 0x0038, 0x4699);  // rst $38
  I(0x4699, 1);  // nop
L_469a:
  I(0x469a, 1); alu_adc(gb, A);  // adc a
  I(0x469b, 3); SET_BC(0x926e);  // ld bc,$926e
  I(0x469e, 1); B = B;  // ld b,b
  I(0x469f, 1); A = A;  // ld a,a
  I(0x46a0, 1); alu_add(gb, B);  // add b
  I(0x46a1, 1); alu_xor(gb, A);  // xor a
  I(0x46a2, 3); mem_wr(gb, 0xff1f, A);  // ldh ($ff1f),a
L_46a4:
  I(0x46a4, 1); L = L;  // ld l,l
  I(0x46a5, 1); alu_ccf(gb);  // ccf
  I(0x46a6, 1); A = alu_inc8(gb, A);  // inc a
  I(0x46a7, 1);  // nop
  if (!(F & FZ)) { RET_TAKEN(0x46a8); return; } I(0x46a8, 2);  // ret nz
  I(0x46a9, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x46aa, 1); C = L;  // ld c,l
  I(0x46ab, 2); SET_HL(HL + 1);  // inc hl
  I(0x46ac, 1); B = C;  // ld b,c
  I(0x46ad, 1);  // nop
  I(0x46ae, 1); alu_rlca(gb);  // rlca
  if (!(F & FC)) { I(0x46af, 3); goto L_46b1; } I(0x46af, 2);  // jr nc,$46b1
L_46b1:
  PUSH(0x46b1, BC);  // push bc
  I(0x46b2, 1); C = L;  // ld c,l
  I(0x46b3, 1); alu_xor(gb, A);  // xor a
  I(0x46b4, 1); D = L;  // ld d,l
  CALL_ASM_RST(0x46b5, 0x0038, 0x46b6);  // rst $38
  I(0x46b6, 1); C = alu_inc8(gb, C);  // inc c
  I(0x46b7, 2); SET_BC(BC + 1);  // inc bc
  I(0x46b8, 1); L = L;  // ld l,l
  I(0x46b9, 1); alu_rrca(gb);  // rrca
  RETI(0x46ba); return;  // reti
}

// 31:43a2
void s_gfx_titlescreen_3(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x43a2, 2); gb->sp = gb->sp + 1;  // inc sp
  if ((F & FZ)) { CALL_ASM(0x43a3, 0xff81, 0x43a6); /* unported */ } else I(0x43a3, 3);  // call z,$ff81
  CALL_ASM_RST(0x43a6, 0x0038, 0x43a7);  // rst $38
  CALL_ASM_RST(0x43a7, 0x0020, 0x43a8);  // rst $20
  CALL_ASM_RST(0x43a8, 0x0020, 0x43a9);  // rst $20
  I(0x43a9, 1); alu_sbc(gb, C);  // sbc c
  I(0x43aa, 1); alu_sbc(gb, C);  // sbc c
  CALL_ASM_RST(0x43ab, 0x0038, 0x43ac);  // rst $38
  CALL_ASM_RST(0x43ac, 0x0038, 0x43ad);  // rst $38
  I(0x43ad, 1); E = A;  // ld e,a
  CALL_ASM_RST(0x43ae, 0x0038, 0x43af);  // rst $38
  CALL_ASM_RST(0x43af, 0x0038, 0x43b0);  // rst $38
  I(0x43b0, 3); mem_wr(gb, 0xfffe, A);  // ldh ($fffe),a
  I(0x43b2, 1); B = alu_dec8(gb, B);  // dec b
  CALL_ASM_RST(0x43b3, 0x0038, 0x43b4);  // rst $38
  CALL_ASM_RST(0x43b4, 0x0038, 0x43b5);  // rst $38
  I(0x43b5, 1);  // nop
  I(0x43b6, 1); alu_add(gb, E);  // add e
  I(0x43b7, 1);  // nop
  I(0x43b8, 3); A = mem_rd(gb, 0xffc0);  // ldh a,($ffc0)
  I(0x43ba, 3); alu_ld_hl_sp(gb, 0x05);  // ld hl,sp+$05
  I(0x43bc, 3); mem_wr(gb, 0xffff, A);  // ldh ($ffff),a
  I(0x43be, 1);  // nop
  if (!(F & FZ)) { I(0x43bf, 3); goto L_43c1; } I(0x43bf, 2);  // jr nz,$43c1
L_43c1:
  I(0x43c1, 1); alu_rlca(gb);  // rlca
  I(0x43c2, 1);  // nop
  I(0x43c3, 2); SET_BC(BC + 1);  // inc bc
  I(0x43c4, 3); alu_ld_hl_sp(gb, 0xf8);  // ld hl,sp+$f8
  RST_PUSH(0x43c6, 0x43c7);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 31:4470
void s_gfx_titlescreen_6(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x4470, 2); mem_wr(gb, BC, A);  // ld (bc),a
  CALL_ASM_RST(0x4471, 0x0038, 0x4472);  // rst $38
  if ((F & FC)) { I(0x4472, 3); goto L_44f1; } I(0x4472, 2);  // jr c,$44f1
  RST_PUSH(0x4474, 0x4475);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
L_44f1:
  RST_PUSH(0x44f1, 0x44f2);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  if ((F & FC)) { RET_TAKEN(0x44f2); return; } I(0x44f2, 2);  // ret c
  RETI(0x44f3); return;  // reti
}

// 31:4e1a
void s_map_intro_link_riding_horse_1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x4e1a, 1); B = B;  // ld b,b
  I(0x4e1b, 1); alu_add(gb, B);  // add b
  I(0x4e1c, 1);  // nop
  I(0x4e1d, 1); alu_add(gb, B);  // add b
  I(0x4e1e, 1); alu_add(gb, C);  // add c
  I(0x4e1f, 1); alu_add(gb, D);  // add d
  I(0x4e20, 1); alu_add(gb, E);  // add e
  I(0x4e21, 1); alu_add(gb, H);  // add h
  I(0x4e22, 1); alu_add(gb, L);  // add l
  I(0x4e23, 2); alu_add(gb, mem_rd(gb, HL));  // add (hl)
  I(0x4e24, 1);  // nop
  I(0x4e25, 1); alu_add(gb, A);  // add a
  I(0x4e26, 1); alu_adc(gb, B);  // adc b
  I(0x4e27, 1); alu_adc(gb, C);  // adc c
  I(0x4e28, 1); alu_adc(gb, D);  // adc d
  I(0x4e29, 1); alu_adc(gb, E);  // adc e
  I(0x4e2a, 1); alu_adc(gb, H);  // adc h
  I(0x4e2b, 1); alu_adc(gb, L);  // adc l
  I(0x4e2c, 2); alu_adc(gb, mem_rd(gb, HL));  // adc (hl)
  I(0x4e2d, 1); B = alu_inc8(gb, B);  // inc b
  I(0x4e2e, 1); alu_adc(gb, A);  // adc a
  I(0x4e2f, 2); gb->sp = HL; gb->sp_loads++; HANDOFF_UP(0x4e30);  // ld sp,hl
L_4e30:
  I(0x4e30, 2); gb->sp = HL; gb->sp_loads++; HANDOFF_UP(0x4e31);  // ld sp,hl
L_4e31:
  I(0x4e31, 4); A = mem_rd(gb, 0x1efa);  // ld a,($1efa)
  I(0x4e34, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4e35, 1); alu_sub(gb, B);  // sub b
  I(0x4e36, 1); alu_sub(gb, C);  // sub c
  I(0x4e37, 1);  // nop
  I(0x4e38, 1); alu_sub(gb, D);  // sub d
  I(0x4e39, 1); alu_sub(gb, E);  // sub e
  I(0x4e3a, 1); alu_sub(gb, H);  // sub h
  I(0x4e3b, 1); alu_sub(gb, L);  // sub l
  I(0x4e3c, 2); alu_sub(gb, mem_rd(gb, HL));  // sub (hl)
  I(0x4e3d, 1); alu_sub(gb, A);  // sub a
  I(0x4e3e, 1); alu_sbc(gb, B);  // sbc b
  I(0x4e3f, 1); alu_sbc(gb, C);  // sbc c
  I(0x4e40, 1);  // nop
  I(0x4e41, 1); alu_sbc(gb, D);  // sbc d
  I(0x4e42, 1); alu_sbc(gb, E);  // sbc e
  I(0x4e43, 1); alu_sbc(gb, H);  // sbc h
  I(0x4e44, 1); alu_sbc(gb, L);  // sbc l
  I(0x4e45, 2); alu_sbc(gb, mem_rd(gb, HL));  // sbc (hl)
  I(0x4e46, 1); alu_sbc(gb, A);  // sbc a
  if (!(F & FC)) { I(0x4e47, 3); goto L_4e7a; } I(0x4e47, 2);  // jr nc,$4e7a
  if (!(F & FZ)) { I(0x4e49, 3); goto L_4e7d; } I(0x4e49, 2);  // jr nz,$4e7d
  I(0x4e4b, 2); gb->sp = gb->sp + 1;  // inc sp
  I(0x4e4c, 1); alu_rra(gb);  // rra
  I(0x4e4d, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4e4e, 1); alu_and(gb, B);  // and b
  I(0x4e4f, 1); alu_and(gb, C);  // and c
  I(0x4e50, 1); alu_and(gb, D);  // and d
  I(0x4e51, 1); alu_and(gb, E);  // and e
  I(0x4e52, 1); alu_and(gb, H);  // and h
  I(0x4e53, 1);  // nop
  I(0x4e54, 1); alu_and(gb, L);  // and l
  I(0x4e55, 2); alu_and(gb, mem_rd(gb, HL));  // and (hl)
  I(0x4e56, 1); alu_and(gb, A);  // and a
  I(0x4e57, 1); alu_xor(gb, B);  // xor b
  I(0x4e58, 1); alu_xor(gb, C);  // xor c
  I(0x4e59, 1); alu_xor(gb, D);  // xor d
  I(0x4e5a, 1); alu_xor(gb, E);  // xor e
  I(0x4e5b, 1); alu_xor(gb, H);  // xor h
  I(0x4e5c, 3); SET_BC(0xaead);  // ld bc,$aead
  I(0x4e5f, 1); alu_xor(gb, A);  // xor a
  I(0x4e60, 1); B = B;  // ld b,b
  I(0x4e61, 1); B = C;  // ld b,c
  I(0x4e62, 1); B = D;  // ld b,d
  I(0x4e63, 1); B = E;  // ld b,e
  I(0x4e64, 1); alu_rra(gb);  // rra
  I(0x4e65, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4e66, 1);  // nop
  I(0x4e67, 1); alu_or(gb, B);  // or b
  I(0x4e68, 1); alu_or(gb, C);  // or c
  I(0x4e69, 1); alu_or(gb, D);  // or d
  I(0x4e6a, 1); alu_or(gb, E);  // or e
  I(0x4e6b, 1); alu_or(gb, H);  // or h
  I(0x4e6c, 1); alu_or(gb, L);  // or l
  I(0x4e6d, 2); alu_or(gb, mem_rd(gb, HL));  // or (hl)
  I(0x4e6e, 1); alu_or(gb, A);  // or a
  I(0x4e6f, 1);  // nop
  I(0x4e70, 1); alu_cp(gb, B);  // cp b
  I(0x4e71, 1); alu_cp(gb, C);  // cp c
  I(0x4e72, 1); alu_cp(gb, D);  // cp d
  I(0x4e73, 1); alu_cp(gb, E);  // cp e
  I(0x4e74, 1); alu_cp(gb, H);  // cp h
  I(0x4e75, 1); alu_cp(gb, L);  // cp l
  I(0x4e76, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  I(0x4e77, 1); alu_cp(gb, A);  // cp a
  I(0x4e78, 4); mem_wr(gb, 0x3f2f, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0x3f30, gb->sp >> 8);  // ld ($3f2f),sp
L_4e7a:
  I(0x4e7a, 1); alu_ccf(gb);  // ccf
  I(0x4e7b, 1); alu_ccf(gb);  // ccf
  I(0x4e7c, 1); alu_cpl(gb);  // cpl
L_4e7d:
  I(0x4e7d, 1); alu_rra(gb);  // rra
  I(0x4e7e, 1); C = alu_inc8(gb, C);  // inc c
  if (!(F & FZ)) { RET_TAKEN(0x4e7f); return; } I(0x4e7f, 2);  // ret nz
  SET_BC(POP(0x4e80));  // pop bc
  if (!(F & FZ)) { I(0x4e81, 4); HANDOFF(0xc300); /* unported */ } I(0x4e81, 3);  // jp nz,$c300
  if (!(F & FZ)) { CALL_ASM(0x4e84, 0xc6c5, 0x4e87); /* unported */ } else I(0x4e84, 3);  // call nz,$c6c5
  RST_PUSH(0x4e87, 0x4e88);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 31:4e30
void s_map_intro_link_riding_horse_1__afterSp4e30(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4e30:
  I(0x4e30, 2); gb->sp = HL; gb->sp_loads++; HANDOFF_UP(0x4e31);  // ld sp,hl
L_4e31:
  I(0x4e31, 4); A = mem_rd(gb, 0x1efa);  // ld a,($1efa)
  I(0x4e34, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4e35, 1); alu_sub(gb, B);  // sub b
  I(0x4e36, 1); alu_sub(gb, C);  // sub c
  I(0x4e37, 1);  // nop
  I(0x4e38, 1); alu_sub(gb, D);  // sub d
  I(0x4e39, 1); alu_sub(gb, E);  // sub e
  I(0x4e3a, 1); alu_sub(gb, H);  // sub h
  I(0x4e3b, 1); alu_sub(gb, L);  // sub l
  I(0x4e3c, 2); alu_sub(gb, mem_rd(gb, HL));  // sub (hl)
  I(0x4e3d, 1); alu_sub(gb, A);  // sub a
  I(0x4e3e, 1); alu_sbc(gb, B);  // sbc b
  I(0x4e3f, 1); alu_sbc(gb, C);  // sbc c
  I(0x4e40, 1);  // nop
  I(0x4e41, 1); alu_sbc(gb, D);  // sbc d
  I(0x4e42, 1); alu_sbc(gb, E);  // sbc e
  I(0x4e43, 1); alu_sbc(gb, H);  // sbc h
  I(0x4e44, 1); alu_sbc(gb, L);  // sbc l
  I(0x4e45, 2); alu_sbc(gb, mem_rd(gb, HL));  // sbc (hl)
  I(0x4e46, 1); alu_sbc(gb, A);  // sbc a
  if (!(F & FC)) { I(0x4e47, 3); goto L_4e7a; } I(0x4e47, 2);  // jr nc,$4e7a
  if (!(F & FZ)) { I(0x4e49, 3); goto L_4e7d; } I(0x4e49, 2);  // jr nz,$4e7d
  I(0x4e4b, 2); gb->sp = gb->sp + 1;  // inc sp
  I(0x4e4c, 1); alu_rra(gb);  // rra
  I(0x4e4d, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4e4e, 1); alu_and(gb, B);  // and b
  I(0x4e4f, 1); alu_and(gb, C);  // and c
  I(0x4e50, 1); alu_and(gb, D);  // and d
  I(0x4e51, 1); alu_and(gb, E);  // and e
  I(0x4e52, 1); alu_and(gb, H);  // and h
  I(0x4e53, 1);  // nop
  I(0x4e54, 1); alu_and(gb, L);  // and l
  I(0x4e55, 2); alu_and(gb, mem_rd(gb, HL));  // and (hl)
  I(0x4e56, 1); alu_and(gb, A);  // and a
  I(0x4e57, 1); alu_xor(gb, B);  // xor b
  I(0x4e58, 1); alu_xor(gb, C);  // xor c
  I(0x4e59, 1); alu_xor(gb, D);  // xor d
  I(0x4e5a, 1); alu_xor(gb, E);  // xor e
  I(0x4e5b, 1); alu_xor(gb, H);  // xor h
  I(0x4e5c, 3); SET_BC(0xaead);  // ld bc,$aead
  I(0x4e5f, 1); alu_xor(gb, A);  // xor a
  I(0x4e60, 1); B = B;  // ld b,b
  I(0x4e61, 1); B = C;  // ld b,c
  I(0x4e62, 1); B = D;  // ld b,d
  I(0x4e63, 1); B = E;  // ld b,e
  I(0x4e64, 1); alu_rra(gb);  // rra
  I(0x4e65, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4e66, 1);  // nop
  I(0x4e67, 1); alu_or(gb, B);  // or b
  I(0x4e68, 1); alu_or(gb, C);  // or c
  I(0x4e69, 1); alu_or(gb, D);  // or d
  I(0x4e6a, 1); alu_or(gb, E);  // or e
  I(0x4e6b, 1); alu_or(gb, H);  // or h
  I(0x4e6c, 1); alu_or(gb, L);  // or l
  I(0x4e6d, 2); alu_or(gb, mem_rd(gb, HL));  // or (hl)
  I(0x4e6e, 1); alu_or(gb, A);  // or a
  I(0x4e6f, 1);  // nop
  I(0x4e70, 1); alu_cp(gb, B);  // cp b
  I(0x4e71, 1); alu_cp(gb, C);  // cp c
  I(0x4e72, 1); alu_cp(gb, D);  // cp d
  I(0x4e73, 1); alu_cp(gb, E);  // cp e
  I(0x4e74, 1); alu_cp(gb, H);  // cp h
  I(0x4e75, 1); alu_cp(gb, L);  // cp l
  I(0x4e76, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  I(0x4e77, 1); alu_cp(gb, A);  // cp a
  I(0x4e78, 4); mem_wr(gb, 0x3f2f, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0x3f30, gb->sp >> 8);  // ld ($3f2f),sp
L_4e7a:
  I(0x4e7a, 1); alu_ccf(gb);  // ccf
  I(0x4e7b, 1); alu_ccf(gb);  // ccf
  I(0x4e7c, 1); alu_cpl(gb);  // cpl
L_4e7d:
  I(0x4e7d, 1); alu_rra(gb);  // rra
  I(0x4e7e, 1); C = alu_inc8(gb, C);  // inc c
  if (!(F & FZ)) { RET_TAKEN(0x4e7f); return; } I(0x4e7f, 2);  // ret nz
  SET_BC(POP(0x4e80));  // pop bc
  if (!(F & FZ)) { I(0x4e81, 4); HANDOFF(0xc300); /* unported */ } I(0x4e81, 3);  // jp nz,$c300
  if (!(F & FZ)) { CALL_ASM(0x4e84, 0xc6c5, 0x4e87); /* unported */ } else I(0x4e84, 3);  // call nz,$c6c5
  RST_PUSH(0x4e87, 0x4e88);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 31:4e31
void s_map_intro_link_riding_horse_1__afterSp4e31(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4e31:
  I(0x4e31, 4); A = mem_rd(gb, 0x1efa);  // ld a,($1efa)
  I(0x4e34, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4e35, 1); alu_sub(gb, B);  // sub b
  I(0x4e36, 1); alu_sub(gb, C);  // sub c
  I(0x4e37, 1);  // nop
  I(0x4e38, 1); alu_sub(gb, D);  // sub d
  I(0x4e39, 1); alu_sub(gb, E);  // sub e
  I(0x4e3a, 1); alu_sub(gb, H);  // sub h
  I(0x4e3b, 1); alu_sub(gb, L);  // sub l
  I(0x4e3c, 2); alu_sub(gb, mem_rd(gb, HL));  // sub (hl)
  I(0x4e3d, 1); alu_sub(gb, A);  // sub a
  I(0x4e3e, 1); alu_sbc(gb, B);  // sbc b
  I(0x4e3f, 1); alu_sbc(gb, C);  // sbc c
  I(0x4e40, 1);  // nop
  I(0x4e41, 1); alu_sbc(gb, D);  // sbc d
  I(0x4e42, 1); alu_sbc(gb, E);  // sbc e
  I(0x4e43, 1); alu_sbc(gb, H);  // sbc h
  I(0x4e44, 1); alu_sbc(gb, L);  // sbc l
  I(0x4e45, 2); alu_sbc(gb, mem_rd(gb, HL));  // sbc (hl)
  I(0x4e46, 1); alu_sbc(gb, A);  // sbc a
  if (!(F & FC)) { I(0x4e47, 3); goto L_4e7a; } I(0x4e47, 2);  // jr nc,$4e7a
  if (!(F & FZ)) { I(0x4e49, 3); goto L_4e7d; } I(0x4e49, 2);  // jr nz,$4e7d
  I(0x4e4b, 2); gb->sp = gb->sp + 1;  // inc sp
  I(0x4e4c, 1); alu_rra(gb);  // rra
  I(0x4e4d, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4e4e, 1); alu_and(gb, B);  // and b
  I(0x4e4f, 1); alu_and(gb, C);  // and c
  I(0x4e50, 1); alu_and(gb, D);  // and d
  I(0x4e51, 1); alu_and(gb, E);  // and e
  I(0x4e52, 1); alu_and(gb, H);  // and h
  I(0x4e53, 1);  // nop
  I(0x4e54, 1); alu_and(gb, L);  // and l
  I(0x4e55, 2); alu_and(gb, mem_rd(gb, HL));  // and (hl)
  I(0x4e56, 1); alu_and(gb, A);  // and a
  I(0x4e57, 1); alu_xor(gb, B);  // xor b
  I(0x4e58, 1); alu_xor(gb, C);  // xor c
  I(0x4e59, 1); alu_xor(gb, D);  // xor d
  I(0x4e5a, 1); alu_xor(gb, E);  // xor e
  I(0x4e5b, 1); alu_xor(gb, H);  // xor h
  I(0x4e5c, 3); SET_BC(0xaead);  // ld bc,$aead
  I(0x4e5f, 1); alu_xor(gb, A);  // xor a
  I(0x4e60, 1); B = B;  // ld b,b
  I(0x4e61, 1); B = C;  // ld b,c
  I(0x4e62, 1); B = D;  // ld b,d
  I(0x4e63, 1); B = E;  // ld b,e
  I(0x4e64, 1); alu_rra(gb);  // rra
  I(0x4e65, 1); C = alu_inc8(gb, C);  // inc c
  I(0x4e66, 1);  // nop
  I(0x4e67, 1); alu_or(gb, B);  // or b
  I(0x4e68, 1); alu_or(gb, C);  // or c
  I(0x4e69, 1); alu_or(gb, D);  // or d
  I(0x4e6a, 1); alu_or(gb, E);  // or e
  I(0x4e6b, 1); alu_or(gb, H);  // or h
  I(0x4e6c, 1); alu_or(gb, L);  // or l
  I(0x4e6d, 2); alu_or(gb, mem_rd(gb, HL));  // or (hl)
  I(0x4e6e, 1); alu_or(gb, A);  // or a
  I(0x4e6f, 1);  // nop
  I(0x4e70, 1); alu_cp(gb, B);  // cp b
  I(0x4e71, 1); alu_cp(gb, C);  // cp c
  I(0x4e72, 1); alu_cp(gb, D);  // cp d
  I(0x4e73, 1); alu_cp(gb, E);  // cp e
  I(0x4e74, 1); alu_cp(gb, H);  // cp h
  I(0x4e75, 1); alu_cp(gb, L);  // cp l
  I(0x4e76, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  I(0x4e77, 1); alu_cp(gb, A);  // cp a
  I(0x4e78, 4); mem_wr(gb, 0x3f2f, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0x3f30, gb->sp >> 8);  // ld ($3f2f),sp
L_4e7a:
  I(0x4e7a, 1); alu_ccf(gb);  // ccf
  I(0x4e7b, 1); alu_ccf(gb);  // ccf
  I(0x4e7c, 1); alu_cpl(gb);  // cpl
L_4e7d:
  I(0x4e7d, 1); alu_rra(gb);  // rra
  I(0x4e7e, 1); C = alu_inc8(gb, C);  // inc c
  if (!(F & FZ)) { RET_TAKEN(0x4e7f); return; } I(0x4e7f, 2);  // ret nz
  SET_BC(POP(0x4e80));  // pop bc
  if (!(F & FZ)) { I(0x4e81, 4); HANDOFF(0xc300); /* unported */ } I(0x4e81, 3);  // jp nz,$c300
  if (!(F & FZ)) { CALL_ASM(0x4e84, 0xc6c5, 0x4e87); /* unported */ } else I(0x4e84, 3);  // call nz,$c6c5
  RST_PUSH(0x4e87, 0x4e88);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 31:4f7d
void s_spr_link_on_horse_closeup(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x4f7d, 3); SET_DE(0x0001);  // ld de,$0001
L_4f7e:
  I(0x4f7e, 3); SET_BC(0x0300);  // ld bc,$0300
  I(0x4f80, 2); SET_BC(BC + 1);  // inc bc
  I(0x4f81, 3); SET_BC(0x0708);  // ld bc,$0708
  I(0x4f84, 1);  // nop
  I(0x4f85, 1); alu_rrca(gb);  // rrca
  I(0x4f86, 3); SET_BC(0x5108);  // ld bc,$5108
  I(0x4f89, 1); alu_rra(gb);  // rra
  I(0x4f8a, 3); SET_BC(0x3f08);  // ld bc,$3f08
  I(0x4f8d, 3); SET_BC(0x7f18);  // ld bc,$7f18
  I(0x4f90, 1);  // nop
  I(0x4f91, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x4f92, 3); SET_BC(0x1518);  // ld bc,$1518
  I(0x4f95, 1); A = H;  // ld a,h
  I(0x4f96, 1);  // nop
  I(0x4f97, 3); alu_ld_hl_sp(gb, 0x01);  // ld hl,sp+$01
  I(0x4f99, 4); mem_wr(gb, 0x01f0, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0x01f1, gb->sp >> 8);  // ld ($01f0),sp
  I(0x4f9c, 3); goto L_4f7e;  // jr $4f7e
}

