// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/seasons/gen.h"

// 32:5567
void s_flg_intro_bar(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5567, 1); E = E;  // ld e,e
  I(0x5568, 1); alu_adc(gb, A);  // adc a
  I(0x5569, 1);  // nop
  I(0x556a, 2); SET_DE(DE + 1);  // inc de
  I(0x556b, 3); goto L_556d;  // jr $556d
L_556d:
  I(0x556d, 2); SET_BC(BC - 1);  // dec bc
  I(0x556e, 1); alu_rra(gb);  // rra
  I(0x556f, 1); B = B;  // ld b,b
  I(0x5570, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x5571, 1);  // nop
  I(0x5572, 2); SET_DE(DE + 1);  // inc de
  I(0x5573, 1); alu_rra(gb);  // rra
  I(0x5574, 1); L = alu_inc8(gb, L);  // inc l
  HANDOFF(0x5575);  // fallthrough to map_intro_outside_castle
}

// 32:5549
void s_map_intro_bar(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5549, 1); E = B;  // ld e,b
  RETI(0x554a); return;  // reti
}

// 32:540a
void s_map_intro_link_riding_horse_2(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x540a, 1); E = B;  // ld e,b
  RETI(0x540b); return;  // reti
}

// 32:432a
void s_map_titlescreen_scroll_2__afterSp432a(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_432a:
  PUSH(0x432a, DE);  // push de
  I(0x432b, 2); alu_sub(gb, 0x00);  // sub $00
  RST_PUSH(0x432d, 0x432e);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  if ((F & FC)) { RET_TAKEN(0x432e); return; } I(0x432e, 2);  // ret c
  RETI(0x432f); return;  // reti
}

// 32:68c0
void s_spr_intro_link_close_frame_5(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x68c0, 1); B = B;  // ld b,b
  I(0x68c1, 1);  // nop
  I(0x68c2, 1);  // nop
  I(0x68c3, 1); alu_rrca(gb);  // rrca
  I(0x68c4, 3); SET_BC(0x0200);  // ld bc,$0200
L_68c5:
  I(0x68c5, 1);  // nop
  I(0x68c6, 2); mem_wr(gb, BC, A);  // ld (bc),a
  I(0x68c7, 3); SET_BC(0x0503);  // ld bc,$0503
  I(0x68ca, 2); alu_add_hl(gb, DE);  // add hl,de
  I(0x68cb, 1); B = alu_dec8(gb, B);  // dec b
  I(0x68cc, 2); SET_BC(BC + 1);  // inc bc
  I(0x68cd, 1); alu_rlca(gb);  // rlca
  SET_BC(POP(0x68ce));  // pop bc
  I(0x68cf, 3); gb->sp = 0x0002; gb->sp_loads++; HANDOFF_UP(0x68d2);  // ld sp,$0002
L_68d2:
  I(0x68d2, 1); H = alu_inc8(gb, H);  // inc h
  I(0x68d3, 1); B = B;  // ld b,b
  I(0x68d4, 2); SET_BC(BC + 1);  // inc bc
  I(0x68d5, 2); gb->sp = gb->sp + 1;  // inc sp
  I(0x68d6, 3); SET_BC(0x001f);  // ld bc,$001f
  I(0x68d9, 1); L = A;  // ld l,a
  I(0x68da, 1); alu_rra(gb);  // rra
  I(0x68db, 1); alu_cp(gb, A);  // cp a
  I(0x68dc, 1); D = alu_inc8(gb, D);  // inc d
  I(0x68dd, 1); A = A;  // ld a,a
  I(0x68de, 1); A = A;  // ld a,a
  CALL_ASM_RST(0x68df, 0x0038, 0x68e0);  // rst $38
  I(0x68e0, 1); alu_and(gb, B);  // and b
  CALL_ASM_RST(0x68e1, 0x0030, 0x68e2);  // rst $30
  I(0x68e2, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  CALL_ASM_RST(0x68e3, 0x0028, 0x68e4);  // rst $28
  CALL_ASM_RST(0x68e4, 0x0028, 0x68e5);  // rst $28
  I(0x68e5, 3); goto L_68c5;  // jr $68c5
}

// 32:68d2
void s_spr_intro_link_close_frame_5__afterSp68d2(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_68d2;
L_68c5:
  I(0x68c5, 1);  // nop
  I(0x68c6, 2); mem_wr(gb, BC, A);  // ld (bc),a
  I(0x68c7, 3); SET_BC(0x0503);  // ld bc,$0503
  I(0x68ca, 2); alu_add_hl(gb, DE);  // add hl,de
  I(0x68cb, 1); B = alu_dec8(gb, B);  // dec b
  I(0x68cc, 2); SET_BC(BC + 1);  // inc bc
  I(0x68cd, 1); alu_rlca(gb);  // rlca
  SET_BC(POP(0x68ce));  // pop bc
  I(0x68cf, 3); gb->sp = 0x0002; gb->sp_loads++; HANDOFF_UP(0x68d2);  // ld sp,$0002
L_68d2:
  I(0x68d2, 1); H = alu_inc8(gb, H);  // inc h
  I(0x68d3, 1); B = B;  // ld b,b
  I(0x68d4, 2); SET_BC(BC + 1);  // inc bc
  I(0x68d5, 2); gb->sp = gb->sp + 1;  // inc sp
  I(0x68d6, 3); SET_BC(0x001f);  // ld bc,$001f
  I(0x68d9, 1); L = A;  // ld l,a
  I(0x68da, 1); alu_rra(gb);  // rra
  I(0x68db, 1); alu_cp(gb, A);  // cp a
  I(0x68dc, 1); D = alu_inc8(gb, D);  // inc d
  I(0x68dd, 1); A = A;  // ld a,a
  I(0x68de, 1); A = A;  // ld a,a
  CALL_ASM_RST(0x68df, 0x0038, 0x68e0);  // rst $38
  I(0x68e0, 1); alu_and(gb, B);  // and b
  CALL_ASM_RST(0x68e1, 0x0030, 0x68e2);  // rst $30
  I(0x68e2, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  CALL_ASM_RST(0x68e3, 0x0028, 0x68e4);  // rst $28
  CALL_ASM_RST(0x68e4, 0x0028, 0x68e5);  // rst $28
  I(0x68e5, 3); goto L_68c5;  // jr $68c5
}

