// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/seasons/gen.h"

// 05:7529
void s_dimitriUpdateMovement__checkHazards(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_7529:
  CALL(0x7529, companionCheckHazards_hook, 0x459f, 0x752c);  // call $459f
  I(0x752c, 1); H = D;  // ld h,d
  if (!(F & FC)) { I(0x752d, 3); goto L_753d; } I(0x752d, 2);  // jr nc,$753d
  I(0x752f, 2); alu_cp(gb, 0x02);  // cp $02
  if ((F & FZ)) { RET_TAKEN(0x7531); return; } I(0x7531, 2);  // ret z
  I(0x7532, 2); L = 0x04;  // ld l,$04
  I(0x7534, 3); mem_wr(gb, HL, 0x05);  // ld (hl),$05
  CALL(0x7536, dimitriAddWaterfallResistance_hook, 0x7703, 0x7539);  // call $7703
  I(0x7539, 2); B = 0x04;  // ld b,$04
  I(0x753b, 3); goto L_753f;  // jr $753f
L_753d:
  I(0x753d, 2); B = 0x00;  // ld b,$00
L_753f:
  I(0x753f, 2); L = 0x38;  // ld l,$38
  I(0x7541, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x7542, 1); alu_cp(gb, B);  // cp b
  I(0x7543, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x7544, 2); C = 0x00;  // ld c,$00
  if (!(F & FZ)) { I(0x7546, 4); if (hook_is(gb, 0x453d, companionUpdateDirectionAndSetAnimation_hook)) { companionUpdateDirectionAndSetAnimation_hook(gb); return; } HANDOFF(0x453d); } I(0x7546, 3);  // jp nz,$453d
  if (hook_is(gb, 0x7549, dimitriState9_hook)) { dimitriState9_hook(gb); return; } HANDOFF(0x7549);  // fallthrough
}

// 05:753d
void s_dimitriUpdateMovement__setNotInWater(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_753d:
  I(0x753d, 2); B = 0x00;  // ld b,$00
L_753f:
  I(0x753f, 2); L = 0x38;  // ld l,$38
  I(0x7541, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x7542, 1); alu_cp(gb, B);  // cp b
  I(0x7543, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x7544, 2); C = 0x00;  // ld c,$00
  if (!(F & FZ)) { I(0x7546, 4); if (hook_is(gb, 0x453d, companionUpdateDirectionAndSetAnimation_hook)) { companionUpdateDirectionAndSetAnimation_hook(gb); return; } HANDOFF(0x453d); } I(0x7546, 3);  // jp nz,$453d
  if (hook_is(gb, 0x7549, dimitriState9_hook)) { dimitriState9_hook(gb); return; } HANDOFF(0x7549);  // fallthrough
}

// 05:753f
void s_dimitriUpdateMovement__setWaterStatus(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_753f:
  I(0x753f, 2); L = 0x38;  // ld l,$38
  I(0x7541, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x7542, 1); alu_cp(gb, B);  // cp b
  I(0x7543, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x7544, 2); C = 0x00;  // ld c,$00
  if (!(F & FZ)) { I(0x7546, 4); if (hook_is(gb, 0x453d, companionUpdateDirectionAndSetAnimation_hook)) { companionUpdateDirectionAndSetAnimation_hook(gb); return; } HANDOFF(0x453d); } I(0x7546, 3);  // jp nz,$453d
  if (hook_is(gb, 0x7549, dimitriState9_hook)) { dimitriState9_hook(gb); return; } HANDOFF(0x7549);  // fallthrough
}

// 05:5656
void s_overworldSwimmingState1__drown(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5656:
  I(0x5656, 2); C = 0x88;  // ld c,$88
  I(0x5658, 3); goto L_565c;  // jr $565c
L_565c:
  I(0x565c, 2); A = 0x02;  // ld a,$02
  I(0x565e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x5661, 2); A = 0x04;  // ld a,$04
  I(0x5663, 4); mem_wr(gb, 0xcc6c, A);  // ld ($cc6c),a
  I(0x5666, 2); A = 0x80;  // ld a,$80
  I(0x5668, 4); mem_wr(gb, 0xccac, A);  // ld ($ccac),a
  I(0x566b, 1); H = D;  // ld h,d
  I(0x566c, 2); L = 0x2b;  // ld l,$2b
  I(0x566e, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x566f, 2); L = 0x24;  // ld l,$24
  I(0x5671, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) & ~(1 << 7)));  // res 7,(hl)
  I(0x5673, 2); A = 0x5f;  // ld a,$5f
  CALL(0x5675, playSound_b00_hook, 0x0c74, 0x5678);  // call $0c74
  I(0x5678, 2); B = 0x0a;  // ld b,$0a
L_567a:
  I(0x567a, 3); SET_HL(0xcc78);  // ld hl,$cc78
  I(0x567d, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x567e, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5680, 2); alu_or(gb, 0x02);  // or $02
  I(0x5682, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x5683, 1); A = B;  // ld a,b
  CALL(0x5684, specialObjectSetAnimation_hook, 0x2a51, 0x5687);  // call $2a51
  I(0x5687, 4); if (hook_is(gb, 0x2bc5, linkCreateSplash_hook)) { linkCreateSplash_hook(gb); return; } HANDOFF(0x2bc5);  // jp $2bc5
}

// 05:565a
void s_overworldSwimmingState1__drownWithLessInvincibility(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_565a:
  I(0x565a, 2); C = 0x78;  // ld c,$78
  I(0x565c, 2); A = 0x02;  // ld a,$02
  I(0x565e, 4); mem_wr(gb, 0xcc6a, A);  // ld ($cc6a),a
  I(0x5661, 2); A = 0x04;  // ld a,$04
  I(0x5663, 4); mem_wr(gb, 0xcc6c, A);  // ld ($cc6c),a
  I(0x5666, 2); A = 0x80;  // ld a,$80
  I(0x5668, 4); mem_wr(gb, 0xccac, A);  // ld ($ccac),a
  I(0x566b, 1); H = D;  // ld h,d
  I(0x566c, 2); L = 0x2b;  // ld l,$2b
  I(0x566e, 2); mem_wr(gb, HL, C);  // ld (hl),c
  I(0x566f, 2); L = 0x24;  // ld l,$24
  I(0x5671, 4); mem_wr(gb, HL, (uint8_t)(mem_rd(gb, HL) & ~(1 << 7)));  // res 7,(hl)
  I(0x5673, 2); A = 0x5f;  // ld a,$5f
  CALL(0x5675, playSound_b00_hook, 0x0c74, 0x5678);  // call $0c74
  I(0x5678, 2); B = 0x0a;  // ld b,$0a
L_567a:
  I(0x567a, 3); SET_HL(0xcc78);  // ld hl,$cc78
  I(0x567d, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x567e, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5680, 2); alu_or(gb, 0x02);  // or $02
  I(0x5682, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x5683, 1); A = B;  // ld a,b
  CALL(0x5684, specialObjectSetAnimation_hook, 0x2a51, 0x5687);  // call $2a51
  I(0x5687, 4); if (hook_is(gb, 0x2bc5, linkCreateSplash_hook)) { linkCreateSplash_hook(gb); return; } HANDOFF(0x2bc5);  // jp $2bc5
}

// 05:567a
void s_overworldSwimmingState1__splashAndSetAnimation(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_567a:
  I(0x567a, 3); SET_HL(0xcc78);  // ld hl,$cc78
  I(0x567d, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x567e, 2); alu_and(gb, 0xf0);  // and $f0
  I(0x5680, 2); alu_or(gb, 0x02);  // or $02
  I(0x5682, 2); mem_wr(gb, HL, A);  // ld (hl),a
  I(0x5683, 1); A = B;  // ld a,b
  CALL(0x5684, specialObjectSetAnimation_hook, 0x2a51, 0x5687);  // call $2a51
  I(0x5687, 4); if (hook_is(gb, 0x2bc5, linkCreateSplash_hook)) { linkCreateSplash_hook(gb); return; } HANDOFF(0x2bc5);  // jp $2bc5
}

