// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/seasons/gen.h"

// 39:478c
void s_getChannelVolume__affectedByMusicVolume(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_478c:
  I(0x478c, 4); A = mem_rd(gb, 0xc022);  // ld a,($c022)
  I(0x478f, 2); alu_cp(gb, 0x00);  // cp $00
  if ((F & FZ)) { I(0x4791, 3); goto L_47c5; } I(0x4791, 2);  // jr z,$47c5
  I(0x4793, 2); alu_cp(gb, 0x01);  // cp $01
  if ((F & FZ)) { I(0x4795, 3); goto L_47b5; } I(0x4795, 2);  // jr z,$47b5
  I(0x4797, 2); alu_cp(gb, 0x02);  // cp $02
  if ((F & FZ)) { I(0x4799, 3); goto L_47a7; } I(0x4799, 2);  // jr z,$47a7
L_479b:
  I(0x479b, 3); SET_HL(0xc07d);  // ld hl,$c07d
  I(0x479e, 4); A = mem_rd(gb, 0xc01a);  // ld a,($c01a)
  I(0x47a1, 1); E = A;  // ld e,a
  I(0x47a2, 2); D = 0x00;  // ld d,$00
  I(0x47a4, 2); alu_add_hl(gb, DE);  // add hl,de
  I(0x47a5, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  RET(0x47a6); return;  // ret
L_47a7:
  I(0x47a7, 3); SET_HL(0xc07d);  // ld hl,$c07d
  I(0x47aa, 4); A = mem_rd(gb, 0xc01a);  // ld a,($c01a)
  I(0x47ad, 1); E = A;  // ld e,a
  I(0x47ae, 2); D = 0x00;  // ld d,$00
  I(0x47b0, 2); alu_add_hl(gb, DE);  // add hl,de
  I(0x47b1, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x47b2, 2); A = alu_srl(gb, A);  // srl a
  RET(0x47b4); return;  // ret
L_47b5:
  I(0x47b5, 3); SET_HL(0xc07d);  // ld hl,$c07d
  I(0x47b8, 4); A = mem_rd(gb, 0xc01a);  // ld a,($c01a)
  I(0x47bb, 1); E = A;  // ld e,a
  I(0x47bc, 2); D = 0x00;  // ld d,$00
  I(0x47be, 2); alu_add_hl(gb, DE);  // add hl,de
  I(0x47bf, 2); A = mem_rd(gb, HL);  // ld a,(hl)
  I(0x47c0, 2); A = alu_srl(gb, A);  // srl a
  I(0x47c2, 2); A = alu_srl(gb, A);  // srl a
  RET(0x47c4); return;  // ret
L_47c5:
  I(0x47c5, 2); A = 0x00;  // ld a,$00
  RET(0x47c7); return;  // ret
}

