// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/seasons/gen.h"

// 08:4fe7
void s_createInteraction(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_4fe7:
  I(0x4fe7, 4); if (hook_is(gb, 0x24b1, objectCreateInteraction_hook)) { objectCreateInteraction_hook(gb); return; } HANDOFF(0x24b1);  // jp $24b1
}

