// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/seasons/gen.h"

// 29:52be
void s_spr_bipsom_1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x52be, 3); SET_BC(0x0000);  // ld bc,$0000
  I(0x52c1, 1); alu_rlca(gb);  // rlca
  I(0x52c2, 1);  // nop
  I(0x52c3, 1); alu_rra(gb);  // rra
  I(0x52c4, 1);  // nop
  I(0x52c5, 1); alu_ccf(gb);  // ccf
  I(0x52c6, 3); SET_BC(0x0008);  // ld bc,$0008
L_52c8:
  I(0x52c8, 1);  // nop
  I(0x52c9, 1); L = A;  // ld l,a
  I(0x52ca, 3); SET_BC(0x044f);  // ld bc,$044f
  I(0x52cd, 1); alu_rra(gb);  // rra
  I(0x52ce, 1); B = alu_dec8(gb, B);  // dec b
  I(0x52cf, 1); alu_rra(gb);  // rra
  I(0x52d0, 1); C = alu_dec8(gb, C);  // dec c
  I(0x52d1, 1);  // nop
  I(0x52d2, 1); alu_rrca(gb);  // rrca
  I(0x52d3, 1); alu_rlca(gb);  // rlca
  I(0x52d4, 1); alu_rlca(gb);  // rlca
  I(0x52d5, 1);  // nop
  I(0x52d6, 1); alu_rrca(gb);  // rrca
  I(0x52d7, 2); B = 0x0f;  // ld b,$0f
  I(0x52d9, 2); B = 0x00;  // ld b,$00
  I(0x52db, 1); alu_rlca(gb);  // rlca
  I(0x52dc, 1);  // nop
  I(0x52dd, 2); SET_BC(BC + 1);  // inc bc
  I(0x52de, 3); SET_BC(0x0007);  // ld bc,$0007
  I(0x52e1, 1);  // nop
  I(0x52e2, 1);  // nop
  I(0x52e3, 1); B = alu_inc8(gb, B);  // inc b
  if (!(F & FZ)) { RET_TAKEN(0x52e4); return; } I(0x52e4, 2);  // ret nz
  I(0x52e5, 1);  // nop
  I(0x52e6, 3); A = mem_rd(gb, 0xff00);  // ldh a,($ff00)
  I(0x52e8, 3); alu_ld_hl_sp(gb, 0x01);  // ld hl,sp+$01
  I(0x52ea, 3); goto L_52c8;  // jr $52c8
}

// 29:41b1
void s_spr_pedestal_ice(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x41b1, 1); B = B;  // ld b,b
  I(0x41b2, 1);  // nop
  I(0x41b3, 1);  // nop
  I(0x41b4, 1); alu_rla(gb);  // rla
  I(0x41b5, 1); alu_ccf(gb);  // ccf
  I(0x41b6, 1); alu_ccf(gb);  // ccf
  I(0x41b7, 1); E = A;  // ld e,a
  I(0x41b8, 1); H = B;  // ld h,b
  I(0x41b9, 1); E = A;  // ld e,a
  I(0x41ba, 1); H = C;  // ld h,c
  I(0x41bb, 1);  // nop
  RST_PUSH(0x41bc, 0x41bd);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  CALL_ASM_RST(0x41bd, 0x0020, 0x41be);  // rst $20
  I(0x41be, 3); SET_BC(0x0301);  // ld bc,$0301
  I(0x41c1, 2); SET_BC(BC + 1);  // inc bc
  I(0x41c2, 1); alu_rlca(gb);  // rlca
  I(0x41c3, 1); alu_rlca(gb);  // rlca
  I(0x41c4, 1); D = H;  // ld d,h
  I(0x41c5, 1); alu_rrca(gb);  // rrca
  I(0x41c6, 1); B = B;  // ld b,b
  I(0x41c7, 1); alu_rra(gb);  // rra
  I(0x41c8, 1); alu_add(gb, B);  // add b
  I(0x41c9, 2); E = 0x41;  // ld e,$41
  I(0x41cb, 1); E = alu_inc8(gb, E);  // inc e
  I(0x41cc, 1); alu_rra(gb);  // rra
  I(0x41cd, 1);  // nop
  I(0x41ce, 1); E = alu_dec8(gb, E);  // dec e
  I(0x41cf, 1); alu_rra(gb);  // rra
  I(0x41d0, 2); alu_add_hl(gb, DE);  // add hl,de
  I(0x41d1, 1); alu_rra(gb);  // rra
  I(0x41d2, 2); SET_DE(DE + 1);  // inc de
  I(0x41d3, 1); alu_rra(gb);  // rra
  I(0x41d4, 2); SET_DE(DE - 1);  // dec de
  I(0x41d5, 1); alu_rra(gb);  // rra
  I(0x41d6, 1); alu_add(gb, B);  // add b
  I(0x41d7, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x41d8, 1); E = A;  // ld e,a
  SET_HL(POP(0x41d9));  // pop hl
  RST_PUSH(0x41da, 0x41db);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x41db, 1); H = B;  // ld h,b
  if (!(F & FZ)) { RET_TAKEN(0x41dc); return; } I(0x41dc, 2);  // ret nz
  I(0x41dd, 1); A = A;  // ld a,a
  CALL_ASM_RST(0x41de, 0x0038, 0x41df);  // rst $38
  I(0x41df, 2); mem_wr(gb, BC, A);  // ld (bc),a
  I(0x41e0, 1); A = A;  // ld a,a
  I(0x41e1, 1); alu_cp(gb, A);  // cp a
  I(0x41e2, 1); A = A;  // ld a,a
  I(0x41e3, 1); A = A;  // ld a,a
  I(0x41e4, 1); alu_add(gb, B);  // add b
  CALL_ASM_RST(0x41e5, 0x0038, 0x41e6);  // rst $38
  I(0x41e6, 2); H = 0xff;  // ld h,$ff
  I(0x41e8, 1);  // nop
  I(0x41e9, 1); H = B;  // ld h,b
  CALL_ASM_RST(0x41ea, 0x0038, 0x41eb);  // rst $38
  SET_BC(POP(0x41eb));  // pop bc
  CALL_ASM_RST(0x41ec, 0x0038, 0x41ed);  // rst $38
  I(0x41ed, 4); HANDOFF(0xccff); /* unported */  // jp $ccff
}

