// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/seasons/gen.h"

// 01:489d
void s_makeActiveObjectFollowLink_b01(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x489d, 3); SET_HL(0xccfd);  // ld hl,$ccfd
  I(0x48a0, 3); A = mem_rd(gb, 0xffac);  // ldh a,($ffac)
  I(0x48a2, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  I(0x48a3, 3); A = mem_rd(gb, 0xffad);  // ldh a,($ffad)
  I(0x48a5, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  if (hook_is(gb, 0x48a6, resetFollowingLinkPath_hook)) { resetFollowingLinkPath_hook(gb); return; } HANDOFF(0x48a6);  // fallthrough
}

