// generated by tools/transliterate.py; do not edit
#include "game/asm.h"
#include "game/seasons/gen.h"

// 28:5528
void s_flg_dungeon_minimap(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_5528;
L_551f:
  I(0x551f, 1); alu_and(gb, E);  // and e
  I(0x5520, 1); alu_rra(gb);  // rra
  I(0x5521, 1);  // nop
  I(0x5522, 1); alu_cp(gb, B);  // cp b
  RST_PUSH(0x5523, 0x5524);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x5524, 3); A = mem_rd(gb, 0xffff);  // ldh a,($ffff)
  I(0x5526, 1);  // nop
  I(0x5527, 1); alu_and(gb, B);  // and b
L_5528:
  I(0x5528, 1); E = E;  // ld e,e
  I(0x5529, 2); SET_BC(BC + 1);  // inc bc
  if (!(F & FZ)) { RET_TAKEN(0x552a); return; } I(0x552a, 2);  // ret nz
  I(0x552b, 1); B = alu_inc8(gb, B);  // inc b
  I(0x552c, 4); alu_add_sp(gb, 0x20);  // add sp,$20
  I(0x552e, 1); H = alu_inc8(gb, H);  // inc h
  I(0x552f, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x5530, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x5531, 1);  // nop
  I(0x5532, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x5533, 1); alu_or(gb, A);  // or a
  I(0x5534, 1); alu_rra(gb);  // rra
  I(0x5535, 1); A = B;  // ld a,b
  I(0x5536, 1); B = alu_inc8(gb, B);  // inc b
  I(0x5537, 3); mem_wr(gb, 0xff1f, A);  // ldh ($ff1f),a
  RST_PUSH(0x5539, 0x553a);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x553a, 1); B = H;  // ld b,h
  if (!(F & FZ)) { RET_TAKEN(0x553b); return; } I(0x553b, 2);  // ret nz
  I(0x553c, 1); alu_rra(gb);  // rra
  I(0x553d, 3); goto L_551f;  // jr $551f
}

// 28:52af
void s_flg_hud_biggoron_sword(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_52af;
L_527a:
  I(0x527a, 1); B = B;  // ld b,b
  I(0x527b, 3); mem_wr(gb, 0xff04, A);  // ldh ($ff04),a
  I(0x527d, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x527e, 1);  // nop
  I(0x527f, 2); D = 0xa0;  // ld d,$a0
  I(0x5281, 1); B = alu_inc8(gb, B);  // inc b
  I(0x5282, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x5283, 1);  // nop
  I(0x5284, 2); mem_wr(gb, DE, A);  // ld (de),a
  s_map_hud_extra_hearts(gb); return;  // fallthrough
L_52af:
  I(0x52af, 2); SET_DE(DE + 1);  // inc de
  I(0x52b0, 1); alu_add(gb, B);  // add b
  I(0x52b1, 1); alu_add(gb, B);  // add b
  I(0x52b2, 1);  // nop
  I(0x52b3, 1); B = B;  // ld b,b
  I(0x52b4, 1); alu_add(gb, B);  // add b
  I(0x52b5, 1); alu_and(gb, B);  // and b
  I(0x52b6, 1); alu_daa(gb);  // daa
  I(0x52b7, 1);  // nop
  I(0x52b8, 3); goto L_527a;  // jr $527a
}

// 28:5295
void s_flg_hud_extra_hearts(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_5295;
L_527a:
  I(0x527a, 1); B = B;  // ld b,b
  I(0x527b, 3); mem_wr(gb, 0xff04, A);  // ldh ($ff04),a
  I(0x527d, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x527e, 1);  // nop
  I(0x527f, 2); D = 0xa0;  // ld d,$a0
  I(0x5281, 1); B = alu_inc8(gb, B);  // inc b
  I(0x5282, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x5283, 1);  // nop
  I(0x5284, 2); mem_wr(gb, DE, A);  // ld (de),a
  s_map_hud_extra_hearts(gb); return;  // fallthrough
L_5295:
  I(0x5295, 1); D = A;  // ld d,a
  I(0x5296, 1); alu_add(gb, B);  // add b
  I(0x5297, 1); B = B;  // ld b,b
  if (!(F & FZ)) { RET_TAKEN(0x5298); return; } I(0x5298, 2);  // ret nz
  I(0x5299, 1); B = E;  // ld b,e
  I(0x529a, 1); alu_and(gb, B);  // and b
  I(0x529b, 1); L = B;  // ld l,b
  I(0x529c, 1);  // nop
  I(0x529d, 2); SET_DE(DE - 1);  // dec de
  I(0x529e, 1); alu_rra(gb);  // rra
  I(0x529f, 3); goto L_52b7;  // jr $52b7
L_52b7:
  I(0x52b7, 1);  // nop
  I(0x52b8, 3); goto L_527a;  // jr $527a
}

// 28:5278
void s_flg_hud_normal(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5278, 1); E = E;  // ld e,e
  I(0x5279, 1); alu_add(gb, B);  // add b
  I(0x527a, 1); B = B;  // ld b,b
  I(0x527b, 3); mem_wr(gb, 0xff04, A);  // ldh ($ff04),a
  I(0x527d, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x527e, 1);  // nop
  I(0x527f, 2); D = 0xa0;  // ld d,$a0
  I(0x5281, 1); B = alu_inc8(gb, B);  // inc b
  I(0x5282, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x5283, 1);  // nop
  I(0x5284, 2); mem_wr(gb, DE, A);  // ld (de),a
  s_map_hud_extra_hearts(gb); return;  // fallthrough
}

// 28:5215
void s_flg_inventory_screen_1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5215, 1); E = A;  // ld e,a
  I(0x5216, 3); SET_BC(0x2000);  // ld bc,$2000
  I(0x5219, 1); alu_rlca(gb);  // rlca
  I(0x521a, 1);  // nop
  I(0x521b, 3); SET_DE(0x0d12);  // ld de,$0d12
  I(0x521e, 1); alu_rra(gb);  // rra
  I(0x521f, 1);  // nop
  I(0x5220, 1); alu_rra(gb);  // rra
  I(0x5221, 1); B = C;  // ld b,c
  I(0x5222, 1);  // nop
  I(0x5223, 1); alu_rra(gb);  // rra
  s_map_inventory_textbar(gb); return;  // fallthrough
}

// 28:52cf
void s_flg_inventory_screen_2(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x52cf, 1); alu_ccf(gb);  // ccf
  I(0x52d0, 3); SET_BC(0x0007);  // ld bc,$0007
  I(0x52d3, 1); A = B;  // ld a,b
  I(0x52d4, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x52d5, 1); E = B;  // ld e,b
  I(0x52d6, 1); alu_rra(gb);  // rra
  I(0x52d7, 1);  // nop
  SET_HL(POP(0x52d8));  // pop hl
  I(0x52d9, 1);  // nop
  I(0x52da, 3); A = mem_rd(gb, 0xff5f);  // ldh a,($ff5f)
  I(0x52dc, 1);  // nop
  I(0x52dd, 1); E = A;  // ld e,a
  HANDOFF(0x52de);  // fallthrough to map_inventory_screen_3
}

// 28:5259
void s_flg_inventory_textbar(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5259, 2); SET_DE(DE - 1);  // dec de
  I(0x525a, 3); SET_BC(0x0901);  // ld bc,$0901
  I(0x525d, 1);  // nop
  I(0x525e, 1); alu_rrca(gb);  // rrca
  I(0x525f, 3); gb->sp = 0x0007; gb->sp_loads++; HANDOFF_UP(0x5262);  // ld sp,$0007
L_5262:
  I(0x5262, 2); SET_BC(BC - 1);  // dec bc
  I(0x5263, 1); alu_rra(gb);  // rra
  I(0x5264, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  if (!(F & FZ)) { RET_TAKEN(0x5265); return; } I(0x5265, 2);  // ret nz
  I(0x5266, 1);  // nop
  I(0x5267, 2); E = 0x27;  // ld e,$27
  I(0x5269, 1); B = alu_dec8(gb, B);  // dec b
  I(0x526a, 1);  // nop
  if (!(F & FZ)) { I(0x526b, 3); goto L_5273; } I(0x526b, 2);  // jr nz,$5273
  I(0x526d, 4); mem_wr(gb, 0x4364, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0x4365, gb->sp >> 8);  // ld ($4364),sp
  I(0x5270, 1);  // nop
  I(0x5271, 2); SET_DE(DE + 1);  // inc de
  I(0x5272, 1); alu_cp(gb, B);  // cp b
L_5273:
  HALT(0x5273);  // halt
  I(0x5274, 2); B = 0x84;  // ld b,$84
  I(0x5276, 1); alu_rra(gb);  // rra
  I(0x5277, 2); D = 0x5b;  // ld d,$5b
  I(0x5279, 1); alu_add(gb, B);  // add b
  I(0x527a, 1); B = B;  // ld b,b
  I(0x527b, 3); mem_wr(gb, 0xff04, A);  // ldh ($ff04),a
  I(0x527d, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x527e, 1);  // nop
  I(0x527f, 2); D = 0xa0;  // ld d,$a0
  I(0x5281, 1); B = alu_inc8(gb, B);  // inc b
  I(0x5282, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x5283, 1);  // nop
  I(0x5284, 2); mem_wr(gb, DE, A);  // ld (de),a
  s_map_hud_extra_hearts(gb); return;  // fallthrough
}

// 28:5262
void s_flg_inventory_textbar__afterSp5262(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_5262:
  I(0x5262, 2); SET_BC(BC - 1);  // dec bc
  I(0x5263, 1); alu_rra(gb);  // rra
  I(0x5264, 2); mem_wr(gb, HL, A); SET_HL(HL + 1);  // ld (hl+),a
  if (!(F & FZ)) { RET_TAKEN(0x5265); return; } I(0x5265, 2);  // ret nz
  I(0x5266, 1);  // nop
  I(0x5267, 2); E = 0x27;  // ld e,$27
  I(0x5269, 1); B = alu_dec8(gb, B);  // dec b
  I(0x526a, 1);  // nop
  if (!(F & FZ)) { I(0x526b, 3); goto L_5273; } I(0x526b, 2);  // jr nz,$5273
  I(0x526d, 4); mem_wr(gb, 0x4364, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0x4365, gb->sp >> 8);  // ld ($4364),sp
  I(0x5270, 1);  // nop
  I(0x5271, 2); SET_DE(DE + 1);  // inc de
  I(0x5272, 1); alu_cp(gb, B);  // cp b
L_5273:
  HALT(0x5273);  // halt
  I(0x5274, 2); B = 0x84;  // ld b,$84
  I(0x5276, 1); alu_rra(gb);  // rra
  I(0x5277, 2); D = 0x5b;  // ld d,$5b
  I(0x5279, 1); alu_add(gb, B);  // add b
  I(0x527a, 1); B = B;  // ld b,b
  I(0x527b, 3); mem_wr(gb, 0xff04, A);  // ldh ($ff04),a
  I(0x527d, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x527e, 1);  // nop
  I(0x527f, 2); D = 0xa0;  // ld d,$a0
  I(0x5281, 1); B = alu_inc8(gb, B);  // inc b
  I(0x5282, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x5283, 1);  // nop
  I(0x5284, 2); mem_wr(gb, DE, A);  // ld (de),a
  s_map_hud_extra_hearts(gb); return;  // fallthrough
}

// 28:7da2
void s_flg_subrosia_minimap(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x7da2, 1); E = H;  // ld e,h
  I(0x7da3, 1); alu_rrca(gb);  // rrca
  I(0x7da4, 1);  // nop
  I(0x7da5, 3); SET_DE(0x0d2f);  // ld de,$0d2f
  I(0x7da8, 2); C = 0x0e;  // ld c,$0e
  I(0x7daa, 2); C = 0x00;  // ld c,$00
  I(0x7dac, 3); SET_DE(0x6f6f);  // ld de,$6f6f
  I(0x7daf, 1); alu_adc(gb, A);  // adc a
  I(0x7db0, 1); B = H;  // ld b,h
  I(0x7db1, 1); C = A;  // ld c,a
  I(0x7db2, 1); L = A;  // ld l,a
  I(0x7db3, 1); C = A;  // ld c,a
  I(0x7db4, 2); SET_HL(HL + 1);  // inc hl
  if (!(F & FZ)) { RET_TAKEN(0x7db5); return; } I(0x7db5, 2);  // ret nz
  I(0x7db6, 4); mem_wr(gb, 0xa009, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0xa00a, gb->sp >> 8);  // ld ($a009),sp
  I(0x7db9, 1); alu_ccf(gb);  // ccf
  I(0x7dba, 1); alu_cpl(gb);  // cpl
  I(0x7dbb, 1); alu_cpl(gb);  // cpl
  I(0x7dbc, 1); E = A;  // ld e,a
  I(0x7dbd, 1); B = B;  // ld b,b
  I(0x7dbe, 2); alu_add(gb, 0x00);  // add $00
  I(0x7dc0, 3); SET_DE(0x20ff);  // ld de,$20ff
  I(0x7dc3, 1); H = D;  // ld h,d
  I(0x7dc4, 1); C = A;  // ld c,a
  I(0x7dc5, 1); alu_xor(gb, A);  // xor a
  I(0x7dc6, 1); alu_rra(gb);  // rra
  I(0x7dc7, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x7dc8, 1); C = A;  // ld c,a
  I(0x7dc9, 2); SET_BC(BC - 1);  // dec bc
  I(0x7dca, 2); C = 0x60;  // ld c,$60
  I(0x7dcc, 1); C = alu_inc8(gb, C);  // inc c
  I(0x7dcd, 2); alu_cp(gb, mem_rd(gb, HL));  // cp (hl)
  I(0x7dce, 1); B = B;  // ld b,b
  I(0x7dcf, 2); SET_BC(BC - 1);  // dec bc
  I(0x7dd0, 1); D = B;  // ld d,b
  I(0x7dd1, 1); alu_rra(gb);  // rra
  I(0x7dd2, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x7dd3, 2); alu_sbc(gb, mem_rd(gb, HL));  // sbc (hl)
  if (!(F & FZ)) { I(0x7dd4, 3); goto L_7e35; } I(0x7dd4, 2);  // jr nz,$7e35
  I(0x7dd6, 1); C = alu_inc8(gb, C);  // inc c
  if (!(F & FZ)) { RET_TAKEN(0x7dd7); return; } I(0x7dd7, 2);  // ret nz
  I(0x7dd8, 1); E = alu_inc8(gb, E);  // inc e
  I(0x7dd9, 2); C = 0xbf;  // ld c,$bf
  I(0x7ddb, 1); L = A;  // ld l,a
  I(0x7ddc, 1); C = alu_dec8(gb, C);  // dec c
  I(0x7ddd, 2); C = 0x09;  // ld c,$09
  I(0x7ddf, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x7de0, 2); C = 0x02;  // ld c,$02
  I(0x7de2, 1); C = alu_dec8(gb, C);  // dec c
  I(0x7de3, 1); C = alu_dec8(gb, C);  // dec c
  I(0x7de4, 1); C = alu_inc8(gb, C);  // inc c
  I(0x7de5, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x7de6, 1); C = alu_inc8(gb, C);  // inc c
  I(0x7de7, 2); A = mem_rd(gb, BC);  // ld a,(bc)
  I(0x7de8, 1); alu_rra(gb);  // rra
  I(0x7de9, 1); D = alu_inc8(gb, D);  // inc d
  I(0x7dea, 1); C = A;  // ld c,a
  I(0x7deb, 1); alu_sbc(gb, B);  // sbc b
  I(0x7dec, 2); A = mem_rd(gb, HL); SET_HL(HL - 1);  // ld a,(hl-)
  I(0x7ded, 1); C = alu_dec8(gb, C);  // dec c
  I(0x7dee, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x7def, 3); SET_HL(0x0c22);  // ld hl,$0c22
  I(0x7df2, 2); C = 0x0c;  // ld c,$0c
  I(0x7df4, 2); alu_or(gb, mem_rd(gb, HL));  // or (hl)
  I(0x7df5, 1); alu_rra(gb);  // rra
  I(0x7df6, 1); D = alu_inc8(gb, D);  // inc d
  I(0x7df7, 1); alu_rrca(gb);  // rrca
  I(0x7df8, 1); E = D;  // ld e,d
  I(0x7df9, 2); A = 0x0c;  // ld a,$0c
  I(0x7dfb, 1); H = alu_dec8(gb, H);  // dec h
  I(0x7dfc, 2); SET_HL(HL + 1);  // inc hl
  I(0x7dfd, 2); SET_BC(BC - 1);  // dec bc
  I(0x7dfe, 1); alu_and(gb, H);  // and h
  I(0x7dff, 1); alu_rra(gb);  // rra
  I(0x7e00, 1); D = alu_inc8(gb, D);  // inc d
  I(0x7e01, 1); C = A;  // ld c,a
  I(0x7e02, 1); alu_scf(gb);  // scf
  I(0x7e03, 1); C = alu_inc8(gb, C);  // inc c
  I(0x7e04, 1); C = alu_dec8(gb, C);  // dec c
  I(0x7e05, 1); H = B;  // ld h,b
  I(0x7e06, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x7e07, 2); C = 0x5b;  // ld c,$5b
  I(0x7e09, 2); C = 0x1f;  // ld c,$1f
  I(0x7e0b, 2); SET_DE(DE + 1);  // inc de
  I(0x7e0c, 1); alu_cpl(gb);  // cpl
  I(0x7e0d, 1); alu_ccf(gb);  // ccf
  if ((F & FC)) { I(0x7e0e, 3); goto L_7e1b; } I(0x7e0e, 2);  // jr c,$7e1b
  if (!(F & FZ)) { I(0x7e10, 3); goto L_7e35; } I(0x7e10, 2);  // jr nz,$7e35
  if (!(F & FC)) { CALL_ASM(0x7e12, 0x3f3e, 0x7e15); /* unported */ } else I(0x7e12, 3);  // call nc,$3f3e
  I(0x7e15, 1); alu_cpl(gb);  // cpl
  RST_PUSH(0x7e16, 0x7e17);  // rst $10 (addAToHl)
  I(0x0010, 1); alu_add(gb, L); I(0x0011, 1); L = A;
  if (!(F & FC)) { I(0x0012, 5); pop_effect(gb); } else { I(0x0012, 2); I(0x0013, 1); H = alu_inc8(gb, H); I(0x0014, 4); pop_effect(gb); }
  I(0x7e17, 2); SET_BC(BC - 1);  // dec bc
  I(0x7e18, 1); alu_rra(gb);  // rra
  I(0x7e19, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x7e1a, 1); alu_rrca(gb);  // rrca
L_7e1b:
  I(0x7e1b, 1); C = A;  // ld c,a
  I(0x7e1c, 1); alu_ccf(gb);  // ccf
  I(0x7e1d, 1); C = alu_dec8(gb, C);  // dec c
  I(0x7e1e, 1); C = alu_dec8(gb, C);  // dec c
  I(0x7e1f, 1); E = L;  // ld e,l
  I(0x7e20, 1); alu_and(gb, B);  // and b
  I(0x7e21, 1); D = B;  // ld d,b
  I(0x7e22, 1); alu_or(gb, A);  // or a
  I(0x7e23, 1); C = C;  // ld c,c
  I(0x7e24, 1); alu_rra(gb);  // rra
  I(0x7e25, 2); alu_add_hl(gb, BC);  // add hl,bc
  CALL_ASM_RST(0x7e26, 0x0030, 0x7e27);  // rst $30
  if ((F & FZ)) { I(0x7e27, 4); s_checkGivenCollision_disallowHoles__jump1500(gb); return; } I(0x7e27, 3);  // jp z,$1500
  I(0x7e2a, 1); E = A;  // ld e,a
  I(0x7e2b, 3); SET_HL(0xed4f);  // ld hl,$ed4f
  I(0x7e2e, 4); mem_wr(gb, 0x1f09, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0x1f0a, gb->sp >> 8);  // ld ($1f09),sp
  I(0x7e31, 1); C = alu_inc8(gb, C);  // inc c
  I(0x7e32, 1); alu_adc(gb, D);  // adc d
  I(0x7e33, 1);  // nop
  I(0x7e34, 1); E = alu_dec8(gb, E);  // dec e
L_7e35:
  I(0x7e35, 1); L = A;  // ld l,a
  I(0x7e36, 1); L = A;  // ld l,a
  I(0x7e37, 1); C = A;  // ld c,a
  I(0x7e38, 1);  // nop
  I(0x7e39, 1); E = alu_dec8(gb, E);  // dec e
  I(0x7e3a, 1); alu_rrca(gb);  // rrca
  I(0x7e3b, 3); SET_DE(0x6f11);  // ld de,$6f11
  I(0x7e3e, 1); H = B;  // ld h,b
  I(0x7e3f, 1); alu_rrca(gb);  // rrca
  I(0x7e40, 1);  // nop
  I(0x7e41, 1); C = alu_inc8(gb, C);  // inc c
  HANDOFF(0x7e42);  // fallthrough to spr_spinner_trampoline
}

// 28:5425
void s_flg_unappraised_ring_list(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5425, 1); D = L;  // ld d,l
  I(0x5426, 3); SET_BC(0x1f00);  // ld bc,$1f00
  I(0x5429, 1); alu_rlca(gb);  // rlca
  I(0x542a, 1);  // nop
  CALL_ASM_RST(0x542b, 0x0038, 0x542c);  // rst $38
  I(0x542c, 3); SET_BC(0x2000);  // ld bc,$2000
  I(0x542f, 1);  // nop
  I(0x5430, 1);  // nop
  I(0x5431, 3); SET_DE(0x216e);  // ld de,$216e
  I(0x5434, 1); C = alu_inc8(gb, C);  // inc c
  I(0x5435, 1); C = alu_inc8(gb, C);  // inc c
  I(0x5436, 1); alu_rra(gb);  // rra
  I(0x5437, 1); alu_add(gb, C);  // add c
  I(0x5438, 1); B = C;  // ld b,c
  I(0x5439, 1);  // nop
  I(0x543a, 3); SET_DE(0x0d12);  // ld de,$0d12
  HANDOFF(0x543d);  // fallthrough to map_appraised_ring_list
}

// 28:42d7
void s_gfx_blank(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x42d7, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x42d8, 1); H = alu_inc8(gb, H);  // inc h
  I(0x42d9, 1);  // nop
  I(0x42da, 1);  // nop
  I(0x42db, 1);  // nop
  CALL_ASM_RST(0x42dc, 0x0038, 0x42dd);  // rst $38
  HANDOFF(0x42dd);  // fallthrough to gfx_rings
}

// 28:4fa0
void s_gfx_inventory_hud_1(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x4fa0, 1); D = H;  // ld d,h
  I(0x4fa1, 1);  // nop
  I(0x4fa2, 1);  // nop
  I(0x4fa3, 1); alu_rra(gb);  // rra
  CALL_ASM_RST(0x4fa4, 0x0038, 0x4fa5);  // rst $38
  I(0x4fa5, 1);  // nop
  I(0x4fa6, 2); mem_wr(gb, DE, A);  // ld (de),a
  RST_PUSH(0x4fa7, 0x4fa8);  // rst $00 (jump table)
  I(0x0000, 1); alu_add(gb, A); I(0x0001, 3); SET_HL(pop_effect(gb)); I(0x0002, 1); alu_add(gb, L); I(0x0003, 1); L = A;
  if (!(F & FC)) I(0x0004, 3); else { I(0x0004, 2); I(0x0006, 1); H = alu_inc8(gb, H); }
  I(0x0007, 2); A = mem_rd(gb, HL); SET_HL(HL + 1); I(0x0008, 2); H = mem_rd(gb, HL); I(0x0009, 1); L = A; I(0x000a, 1);
  switch (HL) {  default: HANDOFF(HL); }
}

// 28:524b
void s_gfx_save__afterSp524b(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
L_524b:
  I(0x524b, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x524c, 1); alu_scf(gb);  // scf
  I(0x524d, 2); alu_add_hl(gb, gb->sp);  // add hl,sp
  I(0x524e, 2); gb->sp = gb->sp - 1;  // dec sp
  I(0x524f, 1); A = alu_dec8(gb, A);  // dec a
  I(0x5250, 1); alu_ccf(gb);  // ccf
  I(0x5251, 1); alu_rra(gb);  // rra
  I(0x5252, 1); alu_rrca(gb);  // rrca
  I(0x5253, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x5254, 2); alu_and(gb, 0x00);  // and $00
  I(0x5256, 3); SET_DE(0x0d12);  // ld de,$0d12
  s_flg_inventory_textbar(gb); return;  // fallthrough
}

// 28:52a0
void s_map_hud_biggoron_sword(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x52a0, 2); D = 0x00;  // ld d,$00
  I(0x52a2, 1); B = alu_dec8(gb, B);  // dec b
  I(0x52a3, 1);  // nop
  I(0x52a4, 1); H = B;  // ld h,b
  I(0x52a5, 4); mem_wr(gb, 0x0085, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0x0086, gb->sp >> 8);  // ld ($0085),sp
  I(0x52a8, 1); D = alu_inc8(gb, D);  // inc d
  I(0x52a9, 2); B = 0xe0;  // ld b,$e0
  I(0x52ab, 1); B = alu_dec8(gb, B);  // dec b
  I(0x52ac, 2); SET_BC(BC - 1);  // dec bc
  I(0x52ad, 1);  // nop
  I(0x52ae, 2); SET_DE(DE + 1);  // inc de
  s_flg_hud_biggoron_sword(gb); return;  // fallthrough
}

// 28:5285
void s_map_hud_extra_hearts(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5285, 2); SET_HL(HL - 1);  // dec hl
  I(0x5286, 1); B = alu_dec8(gb, B);  // dec b
  I(0x5287, 1);  // nop
  if (!(F & FZ)) { I(0x5288, 3); goto L_5291; } I(0x5288, 2);  // jr nz,$5291
  I(0x528a, 1); B = E;  // ld b,e
  I(0x528b, 4); mem_wr(gb, 0x0043, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0x0044, gb->sp >> 8);  // ld ($0043),sp
  I(0x528e, 1); D = alu_inc8(gb, D);  // inc d
  I(0x528f, 1); A = B;  // ld a,b
  I(0x5290, 2); B = 0xdf;  // ld b,$df
L_5291:
  RST_PUSH(0x5291, 0x5292);  // rst $18 (addDoubleIndexToHl)
  PUSH(0x0018, BC); I(0x0019, 1); C = A; I(0x001a, 2); B = 0x00; I(0x001c, 2); alu_add_hl(gb, BC); I(0x001d, 2); alu_add_hl(gb, BC); SET_BC(POP(0x001e)); I(0x001f, 4); pop_effect(gb);
  I(0x5292, 1); H = A;  // ld h,a
  I(0x5293, 1);  // nop
  I(0x5294, 1); D = alu_inc8(gb, D);  // inc d
  s_flg_hud_extra_hearts(gb); return;  // fallthrough
}

// 28:5268
void s_map_hud_normal(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5268, 1); alu_daa(gb);  // daa
  I(0x5269, 1); B = alu_dec8(gb, B);  // dec b
  I(0x526a, 1);  // nop
  if (!(F & FZ)) { I(0x526b, 3); goto L_5273; } I(0x526b, 2);  // jr nz,$5273
  I(0x526d, 4); mem_wr(gb, 0x4364, (uint8_t)gb->sp); TN(1); mem_wr(gb, 0x4365, gb->sp >> 8);  // ld ($4364),sp
  I(0x5270, 1);  // nop
  I(0x5271, 2); SET_DE(DE + 1);  // inc de
  I(0x5272, 1); alu_cp(gb, B);  // cp b
L_5273:
  HALT(0x5273);  // halt
  I(0x5274, 2); B = 0x84;  // ld b,$84
  I(0x5276, 1); alu_rra(gb);  // rra
  I(0x5277, 2); D = 0x5b;  // ld d,$5b
  I(0x5279, 1); alu_add(gb, B);  // add b
  I(0x527a, 1); B = B;  // ld b,b
  I(0x527b, 3); mem_wr(gb, 0xff04, A);  // ldh ($ff04),a
  I(0x527d, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x527e, 1);  // nop
  I(0x527f, 2); D = 0xa0;  // ld d,$a0
  I(0x5281, 1); B = alu_inc8(gb, B);  // inc b
  I(0x5282, 2); alu_add_hl(gb, BC);  // add hl,bc
  I(0x5283, 1);  // nop
  I(0x5284, 2); mem_wr(gb, DE, A);  // ld (de),a
  s_map_hud_extra_hearts(gb); return;  // fallthrough
}

// 28:52bc
void s_map_inventory_screen_2(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x52bc, 2); gb->sp = gb->sp - 1;  // dec sp
  CALL_ASM_RST(0x52bd, 0x0020, 0x52be);  // rst $20
  I(0x52be, 1);  // nop
  I(0x52bf, 1);  // nop
  I(0x52c0, 1); A = B;  // ld a,b
  I(0x52c1, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x52c2, 1); E = B;  // ld e,b
  I(0x52c3, 1); alu_rra(gb);  // rra
  I(0x52c4, 1);  // nop
  SET_HL(POP(0x52c5));  // pop hl
  I(0x52c6, 2); alu_and(gb, 0x00);  // and $00
  I(0x52c8, 1); A = B;  // ld a,b
  I(0x52c9, 2); mem_wr(gb, DE, A);  // ld (de),a
  I(0x52ca, 1); E = B;  // ld e,b
  if (!(F & FZ)) { RET_TAKEN(0x52cb); return; } I(0x52cb, 2);  // ret nz
  I(0x52cc, 1); E = A;  // ld e,a
  I(0x52cd, 1);  // nop
  I(0x52ce, 1); H = B;  // ld h,b
  s_flg_inventory_screen_2(gb); return;  // fallthrough
}

// 28:5224
void s_map_inventory_textbar(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  I(0x5224, 1);  // nop
  CALL_ASM_RST(0x5225, 0x0020, 0x5226);  // rst $20
  I(0x5226, 2); mem_wr(gb, BC, A);  // ld (bc),a
  if (!(F & FZ)) { I(0x5227, 3); goto L_524b; } I(0x5227, 2);  // jr nz,$524b
  I(0x5229, 1); H = alu_inc8(gb, H);  // inc h
  I(0x522a, 2); H = 0x28;  // ld h,$28
  I(0x522c, 2); A = mem_rd(gb, HL); SET_HL(HL + 1);  // ld a,(hl+)
  I(0x522d, 1);  // nop
  I(0x522e, 1); L = alu_inc8(gb, L);  // inc l
  I(0x522f, 2); L = 0x30;  // ld l,$30
  I(0x5231, 2); mem_wr(gb, HL, A); SET_HL(HL - 1);  // ld (hl-),a
  I(0x5232, 3); mem_wr(gb, HL, alu_inc8(gb, mem_rd(gb, HL)));  // inc (hl)
  I(0x5233, 3); mem_wr(gb, HL, 0x38);  // ld (hl),$38
  I(0x5235, 2); A = mem_rd(gb, HL); SET_HL(HL - 1);  // ld a,(hl-)
  I(0x5236, 2); B = 0x3c;  // ld b,$3c
  I(0x5238, 2); A = 0x02;  // ld a,$02
  CALL_ASM_RST(0x523a, 0x0020, 0x523b);  // rst $20
  I(0x523b, 1);  // nop
  I(0x523c, 1);  // nop
  I(0x523d, 2); SET_BC(BC - 1);  // dec bc
  I(0x523e, 1); alu_ccf(gb);  // ccf
  I(0x523f, 3); SET_HL(0x2300);  // ld hl,$2300
  I(0x5242, 1); H = alu_dec8(gb, H);  // dec h
  I(0x5243, 1); alu_daa(gb);  // daa
  I(0x5244, 2); alu_add_hl(gb, HL);  // add hl,hl
  I(0x5245, 2); SET_HL(HL - 1);  // dec hl
  I(0x5246, 1); L = alu_dec8(gb, L);  // dec l
  I(0x5247, 1); alu_cpl(gb);  // cpl
  I(0x5248, 3); gb->sp = 0x3301; gb->sp_loads++; HANDOFF_UP(0x524b);  // ld sp,$3301
L_524b:
  I(0x524b, 3); mem_wr(gb, HL, alu_dec8(gb, mem_rd(gb, HL)));  // dec (hl)
  I(0x524c, 1); alu_scf(gb);  // scf
  I(0x524d, 2); alu_add_hl(gb, gb->sp);  // add hl,sp
  I(0x524e, 2); gb->sp = gb->sp - 1;  // dec sp
  I(0x524f, 1); A = alu_dec8(gb, A);  // dec a
  I(0x5250, 1); alu_ccf(gb);  // ccf
  I(0x5251, 1); alu_rra(gb);  // rra
  I(0x5252, 1); alu_rrca(gb);  // rrca
  I(0x5253, 2); mem_wr(gb, HL, B);  // ld (hl),b
  I(0x5254, 2); alu_and(gb, 0x00);  // and $00
  I(0x5256, 3); SET_DE(0x0d12);  // ld de,$0d12
  s_flg_inventory_textbar(gb); return;  // fallthrough
}

// 28:4637
void s_spr_item_icons_1_spr(GB *gb) {
  uint16_t sp0_ = gb->sp; (void)sp0_;
  goto L_4637;
L_4631:
  I(0x4631, 1); alu_ccf(gb);  // ccf
  I(0x4632, 1);  // nop
  I(0x4633, 1);  // nop
  I(0x4634, 1); H = alu_inc8(gb, H);  // inc h
  I(0x4635, 1);  // nop
  I(0x4636, 1); L = B;  // ld l,b
L_4637:
  I(0x4637, 1);  // nop
  I(0x4638, 1);  // nop
  I(0x4639, 1);  // nop
  if (!(F & FC)) { I(0x463a, 3); goto L_466c; } I(0x463a, 2);  // jr nc,$466c
  I(0x463c, 2); L = mem_rd(gb, HL);  // ld l,(hl)
  I(0x463d, 2); E = mem_rd(gb, HL);  // ld e,(hl)
  PUSH(0x463e, HL);  // push hl
  I(0x463f, 1); alu_sbc(gb, E);  // sbc e
  I(0x4640, 1);  // nop
  I(0x4641, 1); alu_cp(gb, A);  // cp a
  SET_DE(POP(0x4642));  // pop de
  I(0x4643, 1); E = D;  // ld e,d
  HALT(0x4644);  // halt
  I(0x4645, 1); A = alu_inc8(gb, A);  // inc a
  I(0x4646, 1); A = alu_inc8(gb, A);  // inc a
  I(0x4647, 1); L = D;  // ld l,d
L_4648:
  I(0x4648, 2); E = mem_rd(gb, HL);  // ld e,(hl)
  if (!(F & FZ)) { I(0x4649, 3); goto L_4648; } I(0x4649, 2);  // jr nz,$4648
  I(0x464b, 1); alu_add(gb, E);  // add e
  I(0x464c, 1); H = C;  // ld h,c
  I(0x464d, 1); HANDOFF(HL);  // jp hl
L_466c:
  I(0x466c, 3); goto L_4631;  // jr $4631
}

