#!/usr/bin/env python3
"""Code map: which ROM bytes are instructions the C has replaced, per game, as C range tables.

usage: tools/codemap.py AGES.gbc ages.sym SEASONS.gbc seasons.sym [--out src/assets/codemap.c]

A byte is code when it belongs to an instruction of a hooked routine (every entry of
src/hooks/generated.txt or generated_seasons.txt, followed with transliterate.py's routine_body:
jumps inside the routine, jump-table targets, never calls). Jump-table entries (.dw after
rst_jumpTable) are data and stay. Bytes the game reads as data although they are instructions
(code copied to RAM: the `RAM = ROM` relocations in src/hooks/extra.sym, sized by the RAM
label's _sizeof_) and the ranges listed in src/assets/keep_code.txt are left out. The native
runner zeroes the mapped bytes after building the cycle table; with the map installed on the
GB, bus_read aborts on a data read of a mapped byte, which is how new keep_code entries are found.
"""
import contextlib, io, os, re, sys

def load_game(rom_path, sym_path, hooks_path):
    sys.argv = ['transliterate.py', rom_path, sym_path, 'src/hooks/ported.txt']
    for m in list(sys.modules):
        if m == 'transliterate': del sys.modules[m]
    with contextlib.redirect_stdout(io.StringIO()):
        import transliterate as T
    sizes = {}
    for line in open(sym_path):
        m = re.match(r'([0-9a-f]{8}) _sizeof_(\S+)$', line.strip())
        if m: sizes[m.group(2)] = int(m.group(1), 16)
    code = set()
    entries = 0
    for line in open(hooks_path):
        m = re.match(r'([0-9a-f]{2}):([0-9a-f]{4}) ', line)
        if not m: continue
        b, a = int(m.group(1), 16), int(m.group(2), 16)
        if a >= 0x8000: continue
        entries += 1
        for ia, mn, ln, cy, kind, info in T.routine_body(b, a):
            if ia >= 0x8000: continue
            off = ia if ia < 0x4000 else b * 0x4000 + (ia - 0x4000)
            for i in range(ln): code.add(off + i)
    keep = set()
    for line in open('src/hooks/extra.sym'):
        m = re.match(r'([0-9a-f]{2}):([0-9a-f]{4}) (\S+) = ([0-9a-f]{2}):([0-9a-f]{4})', line.strip())
        if not m: continue
        b, a = int(m.group(4), 16), int(m.group(5), 16)
        n = sizes.get(m.group(3)) or sizes.get(T.by_addr.get((b, a), ''), 0)
        off = a if a < 0x4000 else b * 0x4000 + (a - 0x4000)
        for i in range(n): keep.add(off + i)
    game = os.path.basename(sym_path).split('.')[0]
    def off_of(b, a): return a if a < 0x4000 else b * 0x4000 + (a - 0x4000)
    if os.path.exists('src/assets/keep_code.txt'):
        for line in open('src/assets/keep_code.txt'):
            line = line.split('#')[0].strip()
            if not line: continue
            kind, arg = line.split()
            if kind == 'label':
                if arg not in T.labels: print(f'warning: keep_code label {arg} unknown in {game}', file=sys.stderr); continue
                for (b, a) in T.instances.get(arg, [T.labels[arg]]): keep.update(range(off_of(b, a), off_of(b, a) + sizes.get(arg, 0)))
            elif kind in ('both', game):
                lo, hi = (int(x, 16) for x in arg.split('-'))
                keep.update(range(lo, hi))
    # scriptCmd_loadScript copies 256 bytes from every loadscript target into wBigBuffer, so the
    # instruction bytes that follow a short script land in RAM (and in the state hash): keep them.
    scripts = os.path.join(os.path.dirname(os.path.realpath(sym_path)), 'scripts', game, 'scripts.s')
    nscripts = 0
    for line in open(scripts, errors='replace'):
        m = re.match(r'\s*loadscript\s+(\S+)', line)
        if not m: continue
        arg = m.group(1).split(',')[0]
        name = arg.split('.')[-1]
        insts = T.instances.get(name, [T.labels[name]] if name in T.labels else [])
        if arg.startswith('scriptHelp.'): insts = [i for i in insts if i[0] == 0x15] or insts
        if not insts: print(f'warning: loadscript target {arg} unknown in {game}', file=sys.stderr); continue
        b, a = insts[0]
        keep.update(range(off_of(b, a), off_of(b, a) + 256))
        nscripts += 1
    print(f'{game}: {nscripts} loadscript targets', file=sys.stderr)
    code -= keep
    ranges = []
    for off in sorted(code):
        if ranges and ranges[-1][0] + ranges[-1][1] == off: ranges[-1][1] += 1
        else: ranges.append([off, 1])
    return ranges, entries, len(code), len(keep & set(range(len(T.rom))))

def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    out = 'src/assets/codemap.c'
    if '--out' in sys.argv: out = sys.argv[sys.argv.index('--out') + 1]; args = [a for a in args if a != out]
    ages, seasons = args[0:2], args[2:4]
    parts = ['// generated by tools/codemap.py; do not edit\n#include "assets/assets.h"\n']
    for name, (rom, sym) in (('ages', ages), ('seasons', seasons)):
        ranges, entries, nbytes, nkeep = load_game(rom, sym, 'src/hooks/generated.txt' if name == 'ages' else 'src/hooks/generated_seasons.txt')
        print(f'{name}: {entries} entries, {nbytes} code bytes in {len(ranges)} ranges, {nkeep} instruction bytes kept as data', file=sys.stderr)
        parts.append(f'const CodeRange codemap_{name}[] = {{\n' + ''.join(f'  {{0x{o:06x}, {n}}},\n' for o, n in ranges) + '};\n' + f'const size_t codemap_{name}_n = {len(ranges)};\n')
    open(out, 'w').write('\n'.join(parts))

main()
