#!/usr/bin/env python3
"""Generate src/hooks/table.h from the disassembly symbol file and the list of ported routines.

usage: tools/gen_hooks.py [ref/oracles-disasm/ages.sym] [src/hooks/generated.txt[+more.txt]] [src/hooks/table.h]
ported.txt: one routine name per line, '#' comments allowed.
"""
import re, sys
sym = sys.argv[1] if len(sys.argv) > 1 else 'ref/oracles-disasm/ages.sym'
ported = sys.argv[2] if len(sys.argv) > 2 else 'src/hooks/generated.txt'     # several lists: a+b
out = sys.argv[3] if len(sys.argv) > 3 else 'src/hooks/table.h'
labels = {}
in_labels = False
for line in open(sym):
    line = line.strip()
    if line.startswith('['):
        in_labels = line == '[labels]'
        continue
    if not in_labels or not line:
        continue
    m = re.match(r'([0-9a-f]{2}):([0-9a-f]{4}) (\S+)$', line)
    if m:
        labels.setdefault(m.group(3), (int(m.group(1), 16), int(m.group(2), 16)))
rows = []
import itertools, os
for l in itertools.chain.from_iterable(open(f) for f in ported.split('+') if os.path.exists(f)):
    l = l.split('#')[0].strip()
    if not l: continue
    m = re.match(r'([0-9a-f]{2}):([0-9a-f]{4}) (\S+)(?: (\S+))?$', l)
    if not m: sys.exit(f'bad generated line {l}')
    fl = m.group(4) or '-'
    flags = [f for c, f in (('H', 'HOOK_NOVERIFY'), ('L', 'HOOK_LOCAL')) if c in fl]
    rows.append((int(m.group(2), 16), int(m.group(1), 16), m.group(3), ' | '.join(flags) or '0'))
rows.sort()
with open(out, 'w') as f:
    f.write('// generated by tools/gen_hooks.py from %s; do not edit\n' % sym)
    for addr, bank, n, fl in rows:
        f.write('HOOK(0x%02x, 0x%04x, %s, %s)\n' % (bank, addr, n, fl))
total = sum(1 for n, (b, a) in labels.items() if a < 0x8000 and not n.startswith('@') and '.' not in n)
print('%d routines hooked, %d ROM labels in symbol file' % (len(rows), total))
