#!/usr/bin/env python3
"""Generate src/game/ram.h (named WRAM/HRAM addresses) from the disassembly symbol file.

usage: tools/gen_ram.py [ref/oracles-disasm/ages.sym] [src/hooks/generated.txt] [src/game/ram.h]
Labels that are code (present in generated.txt) are left out so they do not clash with functions.
"""
import re, sys
sym = sys.argv[1] if len(sys.argv) > 1 else 'ref/oracles-disasm/ages.sym'
generated = sys.argv[2] if len(sys.argv) > 2 else 'src/hooks/generated.txt'
out = sys.argv[3] if len(sys.argv) > 3 else 'src/game/ram.h'
code = set()
for l in open(generated):
    p = l.split()
    if len(p) >= 2: code.add(p[1].split('__')[0])
ram = {}
section = None
for line in open(sym):
    line = line.strip()
    if line.startswith('['): section = line; continue
    if section not in ('[labels]', '[definitions]') or not line: continue
    if section == '[labels]':
        m = re.match(r'([0-9a-f]{2}):([0-9a-f]{4}) (\S+)$', line)
        if not m: continue
        bank, addr, name = int(m.group(1), 16), int(m.group(2), 16), m.group(3)
    else:
        m = re.match(r'([0-9a-f]{8}) (\S+)$', line)
        if not m: continue
        addr, name = int(m.group(1), 16), m.group(2)
        mb = re.match(r'w([1-7])[A-Z]', name)
        bank = int(mb.group(1)) if mb else (0 if addr < 0xd000 or addr >= 0xff80 else None)
        if bank is None: continue
    if '@' in name or not re.match(r'[wh][A-Z0-9]', name): continue
    if not (0xc000 <= addr < 0xe000 or 0xff80 <= addr < 0xffff): continue
    cn = name.replace('.', '_')
    if cn.split('_')[0] in code: continue
    ram.setdefault(cn, (bank if addr >= 0xd000 else 0, addr))
with open(out, 'w') as f:
    f.write('// generated by tools/gen_ram.py from %s; do not edit\n#pragma once\n' % sym)
    f.write('#define W8(n) (gb->wram[n##_BANK][(n) & 0xfff])\n')
    f.write('#define WP(n) (&gb->wram[n##_BANK][(n) & 0xfff])\n')
    f.write('#define H8(n) (gb->hram[(n) - 0xff80])\n')
    f.write('#define HP(n) (&gb->hram[(n) - 0xff80])\n')
    for cn, (bank, addr) in sorted(ram.items(), key=lambda kv: (kv[1][1], kv[0])):
        f.write('#define %s 0x%04x\n' % (cn, addr))
        if addr < 0xe000: f.write('#define %s_BANK %d\n' % (cn, bank))
print('%d RAM labels' % len(ram))
